// Pure camera-capture conversion and generated-file formatting for the editor
// Cinematic panel. The browser supplies the capture date and the current
// viewport pose; this module performs no I/O and reads no wall clock.

import { WORLD_SEED } from '../world_seed.mjs';
import type { CinematicCameraPose } from './cinematic_scrub_core';

export const CINEMATIC_CAPTURE_TOOL = 'woc-editor-cinematic-panel-v1' as const;
export const CINEMATIC_CAPTURE_BLOCK_START = '// BEGIN GENERATED CINEMATIC CAMERA CAPTURE';
export const CINEMATIC_CAPTURE_BLOCK_END = '// END GENERATED CINEMATIC CAMERA CAPTURE';

const SCENE_ID_RE = /^[a-z0-9_]{1,100}$/;
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/;
const MAX_ABS_COORDINATE = 100_000;
const MAX_SCENE_SECONDS = 24 * 60 * 60;

export interface CinematicCameraCapture {
  readonly sceneId: string;
  readonly timeSec: number;
  readonly keyframe: {
    readonly camera: CinematicCapturePoint;
    readonly lookAt: {
      readonly kind: 'point';
      readonly point: CinematicCapturePoint;
    };
  };
  readonly provenance: {
    readonly seed: number;
    readonly tool: typeof CINEMATIC_CAPTURE_TOOL;
    readonly capturedAt: string;
  };
}

export interface CinematicCapturePoint {
  readonly x: number;
  readonly z: number;
  readonly height: number;
}

export interface CreateCinematicCaptureInput {
  readonly sceneId: string;
  readonly timeSec: number;
  readonly seed: number;
  readonly capturedAt: string;
  readonly pose: CinematicCameraPose;
  groundY(x: number, z: number): number;
}

export function createCinematicCameraCapture(
  input: CreateCinematicCaptureInput,
): CinematicCameraCapture | null {
  if (input.seed !== WORLD_SEED) return null;
  const camera = capturePoint(input.pose.position, input.groundY);
  const lookAt = capturePoint(input.pose.target, input.groundY);
  const capture: CinematicCameraCapture = {
    sceneId: input.sceneId,
    timeSec: round6(input.timeSec),
    keyframe: {
      camera,
      lookAt: {
        kind: 'point',
        point: lookAt,
      },
    },
    provenance: {
      seed: WORLD_SEED,
      tool: CINEMATIC_CAPTURE_TOOL,
      capturedAt: input.capturedAt,
    },
  };
  return isCinematicCameraCapture(capture) ? capture : null;
}

export function isCinematicCameraCapture(value: unknown): value is CinematicCameraCapture {
  if (!isRecord(value)) return false;
  if (typeof value.sceneId !== 'string' || !SCENE_ID_RE.test(value.sceneId)) return false;
  if (!boundedNumber(value.timeSec, 0, MAX_SCENE_SECONDS)) return false;
  if (!isRecord(value.keyframe) || !capturePointIsValid(value.keyframe.camera)) return false;
  if (!isRecord(value.keyframe.lookAt) || value.keyframe.lookAt.kind !== 'point') return false;
  if (!capturePointIsValid(value.keyframe.lookAt.point)) return false;
  if (!isRecord(value.provenance)) return false;
  return (
    value.provenance.seed === WORLD_SEED &&
    value.provenance.tool === CINEMATIC_CAPTURE_TOOL &&
    typeof value.provenance.capturedAt === 'string' &&
    ISO_DATE_RE.test(value.provenance.capturedAt)
  );
}

export function formatGeneratedCinematicCaptureFile(capture: CinematicCameraCapture): string {
  if (!isCinematicCameraCapture(capture)) throw new Error('invalid cinematic camera capture');
  const camera = capture.keyframe.camera;
  const lookAt = capture.keyframe.lookAt.point;
  return [
    '// Generated by the World Editor Cinematic panel. Do not edit by hand.',
    '',
    'export interface CinematicCameraCapture {',
    '  readonly sceneId: string;',
    '  readonly timeSec: number;',
    '  readonly keyframe: {',
    '    readonly camera: { readonly x: number; readonly z: number; readonly height: number };',
    '    readonly lookAt: {',
    "      readonly kind: 'point';",
    '      readonly point: { readonly x: number; readonly z: number; readonly height: number };',
    '    };',
    '  };',
    '  readonly provenance: {',
    '    readonly seed: number;',
    `    readonly tool: '${CINEMATIC_CAPTURE_TOOL}';`,
    '    readonly capturedAt: string;',
    '  };',
    '}',
    '',
    CINEMATIC_CAPTURE_BLOCK_START,
    'export const LATEST_CINEMATIC_CAMERA_CAPTURE = {',
    `  sceneId: ${tsString(capture.sceneId)},`,
    `  timeSec: ${tsNumber(capture.timeSec)},`,
    '  keyframe: {',
    `    camera: ${formatPoint(camera)},`,
    '    lookAt: {',
    "      kind: 'point',",
    `      point: ${formatPoint(lookAt)},`,
    '    },',
    '  },',
    '  provenance: {',
    `    seed: ${capture.provenance.seed},`,
    `    tool: '${CINEMATIC_CAPTURE_TOOL}',`,
    `    capturedAt: ${tsString(capture.provenance.capturedAt)},`,
    '  },',
    '} as const satisfies CinematicCameraCapture;',
    CINEMATIC_CAPTURE_BLOCK_END,
    '',
    '// Paste-ready static dolly shot fields. Choose the authored duration at the call site.',
    'export const LATEST_CINEMATIC_CAMERA_KEYFRAME = {',
    "  kind: 'dolly',",
    '  points: [LATEST_CINEMATIC_CAMERA_CAPTURE.keyframe.camera],',
    '  lookAt: LATEST_CINEMATIC_CAMERA_CAPTURE.keyframe.lookAt,',
    '} as const;',
    '',
  ].join('\n');
}

function capturePoint(
  point: CinematicCameraPose['position'],
  groundY: (x: number, z: number) => number,
): CinematicCapturePoint {
  return {
    x: round6(point.x),
    z: round6(point.z),
    height: round6(point.y - groundY(point.x, point.z)),
  };
}

function capturePointIsValid(value: unknown): value is CinematicCapturePoint {
  if (!isRecord(value)) return false;
  return (
    boundedNumber(value.x, -MAX_ABS_COORDINATE, MAX_ABS_COORDINATE) &&
    boundedNumber(value.z, -MAX_ABS_COORDINATE, MAX_ABS_COORDINATE) &&
    boundedNumber(value.height, -MAX_ABS_COORDINATE, MAX_ABS_COORDINATE)
  );
}

function formatPoint(point: CinematicCapturePoint): string {
  return `{ x: ${tsNumber(point.x)}, z: ${tsNumber(point.z)}, height: ${tsNumber(point.height)} }`;
}

function tsNumber(value: number): string {
  return String(round6(value));
}

function tsString(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

function round6(value: number): number {
  const rounded = Math.round(value * 1_000_000) / 1_000_000;
  return Object.is(rounded, -0) ? 0 : rounded;
}

function boundedNumber(value: unknown, min: number, max: number): value is number {
  return typeof value === 'number' && Number.isFinite(value) && value >= min && value <= max;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}
