// Generated by the World Editor Cinematic panel. Do not edit by hand.

export interface CinematicCameraCapture {
  readonly sceneId: string;
  readonly timeSec: number;
  readonly keyframe: {
    readonly camera: { readonly x: number; readonly z: number; readonly height: number };
    readonly lookAt: {
      readonly kind: 'point';
      readonly point: { readonly x: number; readonly z: number; readonly height: number };
    };
  };
  readonly provenance: {
    readonly seed: number;
    readonly tool: 'woc-editor-cinematic-panel-v1';
    readonly capturedAt: string;
  };
}

// BEGIN GENERATED CINEMATIC CAMERA CAPTURE
export const LATEST_CINEMATIC_CAMERA_CAPTURE: CinematicCameraCapture | null = null;
// END GENERATED CINEMATIC CAMERA CAPTURE

export const LATEST_CINEMATIC_CAMERA_KEYFRAME = null;
