// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  username: __t.string(),
  usernameKey: __t.string().name("username_key"),
  passwordSalt: __t.string().name("password_salt"),
  passwordHash: __t.string().name("password_hash"),
  createdAt: __t.timestamp().name("created_at"),
  isAdmin: __t.bool().name("is_admin"),
  banned: __t.bool(),
});
