// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey(),
  accountId: __t.u64().name("account_id"),
  realm: __t.string(),
  charactersJson: __t.string().name("characters_json"),
  updatedAt: __t.timestamp().name("updated_at"),
  error: __t.string(),
});
