// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  nameKey: __t.string().name("name_key"),
  className: __t.string().name("class_name"),
  level: __t.u32(),
  realm: __t.string(),
  lifetimeXp: __t.u64().name("lifetime_xp"),
  prestigeRank: __t.u32().name("prestige_rank"),
  online: __t.bool(),
  forceRename: __t.bool().name("force_rename"),
  updatedAt: __t.timestamp().name("updated_at"),
});
