// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  owner: __t.identity(),
  forward: __t.bool(),
  back: __t.bool(),
  turnLeft: __t.bool().name("turn_left"),
  turnRight: __t.bool().name("turn_right"),
  strafeLeft: __t.bool().name("strafe_left"),
  strafeRight: __t.bool().name("strafe_right"),
  jump: __t.bool(),
  facingValid: __t.bool().name("facing_valid"),
  facing: __t.f32(),
  updatedAt: __t.timestamp().name("updated_at"),
});
