// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  accountId: __t.u64().name("account_id"),
  reporterCharacterId: __t.u64().name("reporter_character_id"),
  targetPid: __t.u32().name("target_pid"),
  targetCharacterName: __t.string().name("target_character_name"),
  reason: __t.string(),
  details: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
