// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.u64(),
  forward: __t.bool(),
  back: __t.bool(),
  turnLeft: __t.bool(),
  turnRight: __t.bool(),
  strafeLeft: __t.bool(),
  strafeRight: __t.bool(),
  jump: __t.bool(),
  facingValid: __t.bool(),
  facing: __t.f32(),
};
