// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  id: __t.u64(),
  owner: __t.identity(),
  username: __t.string(),
  usernameKey: __t.string(),
  passwordSalt: __t.string(),
  passwordHash: __t.string(),
  createdAt: __t.timestamp(),
  isAdmin: __t.bool(),
  banned: __t.bool(),
});
export type Account = __Infer<typeof Account>;

export const AuthState = __t.object("AuthState", {
  owner: __t.identity(),
  accountId: __t.u64(),
  username: __t.string(),
  token: __t.string(),
  expiresAt: __t.timestamp(),
  error: __t.string(),
});
export type AuthState = __Infer<typeof AuthState>;

export const BridgeAuth = __t.object("BridgeAuth", {
  id: __t.u64(),
  owner: __t.identity(),
  createdAt: __t.timestamp(),
});
export type BridgeAuth = __Infer<typeof BridgeAuth>;

export const BridgeHeartbeat = __t.object("BridgeHeartbeat", {
  id: __t.u64(),
  owner: __t.identity(),
  online: __t.bool(),
  sessions: __t.u32(),
  tick: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type BridgeHeartbeat = __Infer<typeof BridgeHeartbeat>;

export const Character = __t.object("Character", {
  id: __t.u64(),
  accountId: __t.u64(),
  name: __t.string(),
  nameKey: __t.string(),
  className: __t.string(),
  level: __t.u32(),
  stateJson: __t.string(),
  online: __t.bool(),
  forceRename: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Character = __Infer<typeof Character>;

export const CharacterRoster = __t.object("CharacterRoster", {
  owner: __t.identity(),
  accountId: __t.u64(),
  realm: __t.string(),
  charactersJson: __t.string(),
  updatedAt: __t.timestamp(),
  error: __t.string(),
});
export type CharacterRoster = __Infer<typeof CharacterRoster>;

export const ClientCommand = __t.object("ClientCommand", {
  id: __t.u64(),
  owner: __t.identity(),
  sessionId: __t.u64(),
  kind: __t.string(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
  consumed: __t.bool(),
});
export type ClientCommand = __Infer<typeof ClientCommand>;

export const InputState = __t.object("InputState", {
  sessionId: __t.u64(),
  owner: __t.identity(),
  forward: __t.bool(),
  back: __t.bool(),
  turnLeft: __t.bool(),
  turnRight: __t.bool(),
  strafeLeft: __t.bool(),
  strafeRight: __t.bool(),
  jump: __t.bool(),
  facingValid: __t.bool(),
  facing: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type InputState = __Infer<typeof InputState>;

export const PlayerReport = __t.object("PlayerReport", {
  id: __t.u64(),
  owner: __t.identity(),
  accountId: __t.u64(),
  reporterCharacterId: __t.u64(),
  targetPid: __t.u32(),
  targetCharacterName: __t.string(),
  reason: __t.string(),
  details: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type PlayerReport = __Infer<typeof PlayerReport>;

export const ProjectStats = __t.object("ProjectStats", {
  id: __t.u64(),
  realm: __t.string(),
  accountsCreated: __t.u64(),
  playersOnline: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type ProjectStats = __Infer<typeof ProjectStats>;

export const SocialSnapshot = __t.object("SocialSnapshot", {
  sessionId: __t.u64(),
  owner: __t.identity(),
  payloadJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type SocialSnapshot = __Infer<typeof SocialSnapshot>;

export const WorldEvent = __t.object("WorldEvent", {
  id: __t.u64(),
  owner: __t.identity(),
  sessionId: __t.u64(),
  payloadJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type WorldEvent = __Infer<typeof WorldEvent>;

export const WorldSession = __t.object("WorldSession", {
  id: __t.u64(),
  owner: __t.identity(),
  accountId: __t.u64(),
  characterId: __t.u64(),
  playerId: __t.u32(),
  className: __t.string(),
  characterName: __t.string(),
  active: __t.bool(),
  bridgeAttached: __t.bool(),
  startedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  error: __t.string(),
});
export type WorldSession = __Infer<typeof WorldSession>;

export const WorldSnapshot = __t.object("WorldSnapshot", {
  sessionId: __t.u64(),
  owner: __t.identity(),
  payloadJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type WorldSnapshot = __Infer<typeof WorldSnapshot>;

