// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  accountId: __t.u64().name("account_id"),
  characterId: __t.u64().name("character_id"),
  playerId: __t.u32().name("player_id"),
  className: __t.string().name("class_name"),
  characterName: __t.string().name("character_name"),
  active: __t.bool(),
  bridgeAttached: __t.bool().name("bridge_attached"),
  startedAt: __t.timestamp().name("started_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  error: __t.string(),
});
