// Veth Confederation (levels 20-40): the shadow-and-ice faction realm north of
// Ossara. Veth is not a nation, it is an agreement: city-states connected by
// rivers of black water through ancient forests where light never reaches the
// ground. It keeps no standing army; it keeps money, intelligence networks, and
// the most dangerous assassins' guild on the continent. Nighthollow, the hub on
// the towpath, keeps the ledger; everything in the dark around it keeps score.
//
// Difficulty ramps south to north across the 390-unit band in three thirds:
// 20-27 south of Nighthollow (duskmanes, moths, palewidows, river skulkers),
// 27-34 through the Blackmere, the Wispwood, and the Greyweir toll-house
// (drowned, feral smugglers, guildless cutthroats), and 34-40 past the Silent
// Court into the Frostpine Terraces and the Last Lodge, where Veykar the
// Forsworn keeps his own ledger at the top of the zone.
//
// The hostile mobs here are NOT Veth soldiers (Veth is a player faction): the
// forest itself, feral wisps, drowned things in the black water, renegades the
// guild expelled, and the frost-covered north where the pines turn to ice.
//
// Structure mirrors content/valdris/ossara.ts, the exemplar for every Valdris
// zone module: ZoneDef + roads + mobs + npcs + quests + camps + objects +
// items + props, merged by content/valdris/index.ts.

import type {
  CampDef,
  GroundObjectDef,
  ItemDef,
  MobTemplate,
  NpcDef,
  QuestDef,
  ZoneDef,
  ZonePropsDef,
} from '../../types';

export const VETH_ZONE: ZoneDef = {
  id: 'veth_confederation',
  name: 'Veth Confederation',
  zMin: 1290,
  zMax: 1680,
  levelRange: [20, 40],
  biome: 'shadowwood',
  hub: { x: 0, z: 1410, radius: 20, name: 'Nighthollow' },
  graveyard: { x: 18, z: 1395 },
  lakes: [{ x: -90, z: 1470, radius: 16 }], // the Blackmere
  pois: [
    { x: 0, z: 1410, label: 'Nighthollow' },
    { x: -60, z: 1330, label: 'Duskmane Run' },
    { x: 90, z: 1350, label: 'Palewidow Hollows' },
    { x: 40, z: 1380, label: 'Blackwater Quays' },
    { x: 30, z: 1400, label: 'The Whisper Market' },
    { x: -90, z: 1470, label: 'The Blackmere' },
    { x: 80, z: 1480, label: 'Wispwood' },
    { x: -70, z: 1550, label: 'The Silent Court' },
    { x: 100, z: 1590, label: 'Frostpine Terraces' },
    { x: -40, z: 1640, label: 'The Last Lodge' },
    { x: 55, z: 1308, label: 'Mothfall Verge' },
    { x: 16, z: 1540, label: 'The Greyweir' },
    { x: 30, z: 1640, label: 'The Longwatch' },
  ],
  welcome: 'Veth is not a nation, it is an agreement, and Nighthollow keeps its ledger.',
  welcomeQuestId: 'q_duskmane_hunt',
};

// The towpath: up from the Ossara border pass, through Nighthollow, north to
// the Kael border pass, with spokes to the Blackmere, the Quays, and the
// Frostpine Terraces.
export const VETH_ROADS: { x: number; z: number }[][] = [
  [
    { x: 0, z: 1290 },
    { x: 0, z: 1350 },
    { x: 0, z: 1410 },
  ], // Ossara border pass -> Nighthollow
  [
    { x: 0, z: 1420 },
    { x: 0, z: 1550 },
    { x: 0, z: 1680 },
  ], // Nighthollow -> Kael border pass
  [
    { x: -6, z: 1416 },
    { x: -45, z: 1440 },
    { x: -70, z: 1462 },
  ], // -> the Blackmere shore
  [
    { x: 6, z: 1406 },
    { x: 24, z: 1392 },
    { x: 38, z: 1382 },
  ], // -> Blackwater Quays
  [
    { x: 6, z: 1560 },
    { x: 55, z: 1575 },
    { x: 92, z: 1588 },
  ], // -> Frostpine Terraces
];

// ---------------------------------------------------------------------------
// Mobs
// ---------------------------------------------------------------------------

export const VETH_MOBS: Record<string, MobTemplate> = {
  duskmane_stalker: {
    id: 'duskmane_stalker',
    name: 'Duskmane Stalker',
    minLevel: 20,
    maxLevel: 22,
    family: 'beast',
    hpBase: 82,
    hpPerLevel: 26,
    dmgBase: 15,
    dmgPerLevel: 3.2,
    attackSpeed: 1.9,
    armorPerLevel: 18,
    moveSpeed: 8.2,
    aggroRadius: 11,
    // Duskmane Rake: the packs hunt by ear in the dark and worry what they open.
    bleed: {
      chance: 0.25,
      perTick: 8,
      interval: 3,
      duration: 9,
      name: 'Duskmane Rake',
      school: 'physical',
    },
    loot: [
      { copper: 110, chance: 1 },
      { itemId: 'duskmane_tuft', chance: 0.35 },
      { itemId: 'duskmane_pelt_strip', chance: 0.4, questId: 'q_veth_pelt_lots' },
    ],
    scale: 0.95,
    color: 0x4a4a5e,
  },
  // The oldest stalker on the Run: white as birch bark, and porters swear the
  // towpath goes quiet a full minute before she steps out of it.
  palefang_the_silent: {
    id: 'palefang_the_silent',
    name: 'Palefang the Silent',
    minLevel: 24,
    maxLevel: 24,
    family: 'beast',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 7.2,
    hpBase: 480,
    hpPerLevel: 78,
    dmgBase: 21,
    dmgPerLevel: 4.6,
    attackSpeed: 1.7,
    armorPerLevel: 26,
    moveSpeed: 8.6,
    aggroRadius: 13,
    aoePulse: { min: 24, max: 34, radius: 8, every: 9, name: 'Silent Pounce', school: 'physical' },
    enrage: { belowHpPct: 0.35, dmgMult: 1.4, hasteMult: 1.3 },
    loot: [
      { copper: 330, chance: 1 },
      { itemId: 'palefang_pelt', chance: 1 },
      { itemId: 'palefang_grips', chance: 0.3 },
    ],
    scale: 1.3,
    color: 0xe8e4ec,
  },
  palewidow_weaver: {
    id: 'palewidow_weaver',
    name: 'Palewidow Weaver',
    minLevel: 22,
    maxLevel: 24,
    family: 'spider',
    hpBase: 83,
    hpPerLevel: 26,
    dmgBase: 15,
    dmgPerLevel: 3.2,
    attackSpeed: 2.1,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 10,
    // Palewidow Venom: the hollows' silk trade has a supplier no one thanks.
    venom: {
      chance: 0.3,
      perTick: 8,
      interval: 3,
      duration: 12,
      name: 'Palewidow Venom',
      school: 'nature',
    },
    ensnare: { chance: 0.15, duration: 2.5, name: 'Widow Silk' },
    loot: [
      { copper: 125, chance: 1 },
      { itemId: 'palewidow_silk', chance: 0.6, questId: 'q_palewidow_silk' },
      { itemId: 'palewidow_venom_sac', chance: 0.4, questId: 'q_veth_venom_ledger' },
    ],
    scale: 1.0,
    color: 0xd8d4e0,
  },
  blackriver_skulker: {
    id: 'blackriver_skulker',
    name: 'Blackriver Skulker',
    minLevel: 24,
    maxLevel: 26,
    family: 'mudfin',
    canSwim: true,
    hpBase: 85,
    hpPerLevel: 26,
    dmgBase: 15,
    dmgPerLevel: 3.3,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 11,
    // Blackwater Chill: whatever runs in the black rivers, it is not warm.
    chillOnHit: { chance: 0.3, mult: 0.65, duration: 5, name: 'Blackwater Chill' },
    loot: [
      { copper: 155, chance: 1 },
      { itemId: 'waterlogged_ledger', chance: 0.55, questId: 'q_blackmere_ledgers' },
      { itemId: 'quay_manifest', chance: 0.5, questId: 'q_veth_quay_manifests' },
      { itemId: 'silt_eel', chance: 0.55, questId: 'q_veth_silt_eels' },
    ],
    scale: 0.95,
    color: 0x3d5a66,
  },
  feral_wisp: {
    id: 'feral_wisp',
    name: 'Feral Wisp',
    minLevel: 26,
    maxLevel: 28,
    family: 'elemental',
    hpBase: 86,
    hpPerLevel: 27,
    dmgBase: 16,
    dmgPerLevel: 3.3,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 11,
    // The only light under the Wispwood canopy, and it feeds on what you know.
    manaBurn: { chance: 0.25, amount: 100, name: 'Light Siphon', school: 'arcane' },
    enfeeble: { chance: 0.3, int: 15, duration: 12, name: 'Wisplight Daze', school: 'arcane' },
    loot: [
      { copper: 175, chance: 1 },
      { itemId: 'guttering_wisp_mote', chance: 0.4 },
      { itemId: 'wisplight_essence', chance: 0.4, questId: 'q_veth_wisp_essence' },
      { itemId: 'ferry_lantern_mote', chance: 0.5, questId: 'q_veth_lantern_motes' },
    ],
    scale: 0.9,
    color: 0x9fd4e8,
  },
  guildless_cutthroat: {
    id: 'guildless_cutthroat',
    name: 'Guildless Cutthroat',
    minLevel: 31,
    maxLevel: 33,
    family: 'humanoid',
    hpBase: 88,
    hpPerLevel: 27,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.0,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 11,
    // Expelled from the guild for freelancing; the training, they kept.
    mortalStrike: { chance: 0.25, healReduction: 0.4, duration: 8, name: 'Cutthroat Gash' },
    loot: [
      { copper: 235, chance: 1 },
      { itemId: 'guildless_sigil', chance: 0.55, questId: 'q_guildless_debts' },
      { itemId: 'cutthroat_contract', chance: 0.5, questId: 'q_veth_broken_contracts' },
      { itemId: 'healing_potion', chance: 0.08 },
    ],
    scale: 1.0,
    color: 0x5a5668,
  },
  hollow_revenant: {
    id: 'hollow_revenant',
    name: 'Hollow Revenant',
    minLevel: 33,
    maxLevel: 36,
    family: 'undead',
    hpBase: 90,
    hpPerLevel: 27,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.3,
    armorPerLevel: 24,
    moveSpeed: 6.5,
    aggroRadius: 12,
    // The court that refused the Agreement still holds session, after a fashion.
    soulrot: {
      chance: 0.3,
      perTick: 9,
      interval: 3,
      duration: 12,
      name: 'Hollow Rot',
      school: 'shadow',
    },
    loot: [
      { copper: 270, chance: 1 },
      { itemId: 'silent_court_seal', chance: 0.55, questId: 'q_silent_court' },
      { itemId: 'court_ledger_page', chance: 0.4, questId: 'q_veth_court_records' },
      { itemId: 'hollow_toll_scrip', chance: 0.5, questId: 'q_veth_toll_scrip' },
      { itemId: 'bone_fragments', chance: 0.4 },
    ],
    scale: 1.05,
    color: 0xb8c4d0,
  },
  frostpine_headhunter: {
    id: 'frostpine_headhunter',
    name: 'Frostpine Headhunter',
    minLevel: 34,
    maxLevel: 36,
    family: 'troll',
    hpBase: 92,
    hpPerLevel: 28,
    dmgBase: 17,
    dmgPerLevel: 3.5,
    attackSpeed: 2.2,
    armorPerLevel: 26,
    moveSpeed: 6.8,
    aggroRadius: 12,
    // Frostpine Chill: the terraces' trolls oil their spearheads with rime.
    frostbite: {
      chance: 0.3,
      perTick: 9,
      interval: 3,
      duration: 12,
      name: 'Frostpine Chill',
    },
    loot: [
      { copper: 295, chance: 1 },
      { itemId: 'frostpine_charm', chance: 0.35 },
      { itemId: 'frostpine_war_totem', chance: 0.4, questId: 'q_veth_totem_tally' },
      { itemId: 'frostpine_tallow', chance: 0.55, questId: 'q_veth_tallow_accounts' },
    ],
    scale: 1.1,
    color: 0x6e8a94,
  },
  // The trolls of the terraces sank Grelnok in the ice two winters for eating
  // his own war party. The ice let him back out. They did not argue with it.
  grelnok_the_hoarbound: {
    id: 'grelnok_the_hoarbound',
    name: 'Grelnok the Hoarbound',
    minLevel: 38,
    maxLevel: 38,
    family: 'troll',
    rare: true,
    elite: true,
    canSwim: true,
    ccImmune: true,
    respawnMult: 432,
    hpBase: 620,
    hpPerLevel: 92,
    dmgBase: 27,
    dmgPerLevel: 5.6,
    attackSpeed: 2.3,
    armorPerLevel: 48,
    moveSpeed: 6.8,
    aggroRadius: 13,
    aoePulse: { min: 42, max: 56, radius: 10, every: 9, name: 'Hoarfrost Ring', school: 'frost' },
    stoneskin: { amount: 260, every: 20, duration: 8, name: 'Rimehide' },
    summonAdds: { mobId: 'frostpine_headhunter', count: 2, atHpPct: [0.5] },
    enrage: { belowHpPct: 0.3, dmgMult: 1.45, hasteMult: 1.25 },
    loot: [
      { copper: 1050, chance: 1 },
      { itemId: 'grelnoks_frozen_idol', chance: 1 },
      { itemId: 'hoarbound_bindings', chance: 0.3 },
    ],
    scale: 1.35,
    color: 0x88b4c4,
  },
  // Veykar kept the guild's oldest lodge and broke its oldest rule: he chose
  // his own contracts. The guild will not touch him; he trained half of them.
  veykar_the_forsworn: {
    id: 'veykar_the_forsworn',
    name: 'Veykar the Forsworn',
    minLevel: 40,
    maxLevel: 40,
    family: 'humanoid',
    elite: true,
    boss: true,
    hpBase: 700,
    hpPerLevel: 92,
    dmgBase: 26,
    dmgPerLevel: 5.4,
    attackSpeed: 2.5,
    armorPerLevel: 48,
    moveSpeed: 7,
    aggroRadius: 14,
    aoePulse: {
      min: 46,
      max: 62,
      radius: 10,
      every: 11,
      name: 'Fan of Knives',
      school: 'physical',
    },
    mortalStrike: { chance: 0.25, healReduction: 0.5, duration: 8, name: 'Forsworn Cut' },
    summonAdds: { mobId: 'forsworn_blade', count: 2, atHpPct: [0.55] },
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.2 },
    loot: [
      { copper: 4200, chance: 1 },
      { itemId: 'forsworn_lamellar', chance: 0.3 },
      { itemId: 'forsworn_edge', chance: 0.25 },
    ],
    scale: 1.2,
    color: 0x46425c,
  },
  // Porters and bargefolk the Blackmere kept. The mere pays no wages, and it
  // never lets its staff go.
  blackmere_drowned: {
    id: 'blackmere_drowned',
    name: 'Blackmere Drowned',
    minLevel: 28,
    maxLevel: 30,
    family: 'undead',
    canSwim: true,
    hpBase: 87,
    hpPerLevel: 27,
    dmgBase: 16,
    dmgPerLevel: 3.3,
    attackSpeed: 2.1,
    armorPerLevel: 22,
    moveSpeed: 6.4,
    aggroRadius: 11,
    // Drowning Grip: the mere collects slowly, and it starts with your stride.
    chillOnHit: { chance: 0.3, mult: 0.65, duration: 5, name: 'Drowning Grip' },
    loot: [
      { copper: 200, chance: 1 },
      { itemId: 'drowned_toll_coin', chance: 0.4, questId: 'q_veth_drowned_tolls' },
      { itemId: 'barge_chit', chance: 0.5, questId: 'q_veth_ferry_dues' },
      { itemId: 'sunken_ration_tin', chance: 0.55, questId: 'q_veth_stores_ledger' },
      { itemId: 'bone_fragments', chance: 0.35 },
    ],
    scale: 1.0,
    color: 0x46605a,
  },
  // Down from the high ice when the drifts close; the terraces feed better,
  // and the trolls have learned to leave the white cats the first cut.
  rimeclaw_prowler: {
    id: 'rimeclaw_prowler',
    name: 'Rimeclaw Prowler',
    minLevel: 35,
    maxLevel: 37,
    family: 'beast',
    hpBase: 93,
    hpPerLevel: 28,
    dmgBase: 17,
    dmgPerLevel: 3.5,
    attackSpeed: 1.9,
    armorPerLevel: 24,
    moveSpeed: 8.0,
    aggroRadius: 11,
    // Rimeclaw Rake: frostbitten claws open wounds that will not close warm.
    bleed: {
      chance: 0.25,
      perTick: 10,
      interval: 3,
      duration: 9,
      name: 'Rimeclaw Rake',
      school: 'physical',
    },
    loot: [
      { copper: 315, chance: 1 },
      { itemId: 'rimeclaw_pelt', chance: 0.5, questId: 'q_veth_rimeclaw_pelts' },
      { itemId: 'rimeclaw_haunch', chance: 0.55, questId: 'q_veth_meat_for_the_line' },
    ],
    scale: 1.05,
    color: 0xb9c8d2,
  },
  // Twilight moths: the only things that mistake Nighthollow's lamps for the
  // moon. They shed a dust the guild pays for and never explains.
  twilight_moth: {
    id: 'twilight_moth',
    name: 'Twilight Moth',
    minLevel: 21,
    maxLevel: 23,
    family: 'beast',
    hpBase: 80,
    hpPerLevel: 26,
    dmgBase: 14,
    dmgPerLevel: 3.1,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 7.4,
    aggroRadius: 10,
    // Twilight Dust: a wingbeat of powder that makes you forget your figures.
    enfeeble: { chance: 0.25, int: 10, duration: 10, name: 'Twilight Dust', school: 'arcane' },
    loot: [
      { copper: 260, chance: 1 },
      { itemId: 'mothwing_dust', chance: 0.5, questId: 'q_veth_moth_lamps' },
    ],
    scale: 0.85,
    color: 0xcbbfe4,
  },
  // River smugglers who ran cargo past the weir until the forest kept them.
  // They still pole the banks; the cargo rotted years ago, the habit did not.
  feralrun_smuggler: {
    id: 'feralrun_smuggler',
    name: 'Feralrun Smuggler',
    minLevel: 29,
    maxLevel: 31,
    family: 'humanoid',
    canSwim: true,
    hpBase: 87,
    hpPerLevel: 27,
    dmgBase: 16,
    dmgPerLevel: 3.3,
    attackSpeed: 2.0,
    armorPerLevel: 21,
    moveSpeed: 7.2,
    aggroRadius: 11,
    // Gaff Hook: a boat tool, applied to people with a boatman's economy.
    bleed: {
      chance: 0.25,
      perTick: 9,
      interval: 3,
      duration: 9,
      name: 'Gaff Hook',
      school: 'physical',
    },
    loot: [
      { copper: 360, chance: 1 },
      { itemId: 'smugglers_tally_knot', chance: 0.55, questId: 'q_veth_unlicensed_ferry' },
      { itemId: 'forged_weir_pass', chance: 0.5, questId: 'q_veth_forged_passes' },
      { itemId: 'healing_potion', chance: 0.06 },
    ],
    scale: 1.0,
    color: 0x5e6a52,
  },
  // Vessik sold the guild's secrets to four buyers at once and kept a fifth
  // set for himself. He counts his coin by the weir and pays smugglers to
  // watch the road; the guild pays better for his little book.
  vessik_the_turncoat: {
    id: 'vessik_the_turncoat',
    name: 'Vessik the Turncoat',
    minLevel: 32,
    maxLevel: 32,
    family: 'humanoid',
    rare: true,
    elite: true,
    ccImmune: true,
    respawnMult: 6.5,
    hpBase: 540,
    hpPerLevel: 84,
    dmgBase: 24,
    dmgPerLevel: 5.0,
    attackSpeed: 1.9,
    armorPerLevel: 32,
    moveSpeed: 7.4,
    aggroRadius: 13,
    aoePulse: { min: 34, max: 46, radius: 9, every: 10, name: 'Loose Ends', school: 'physical' },
    mortalStrike: { chance: 0.25, healReduction: 0.4, duration: 8, name: 'Sold Secret' },
    summonAdds: { mobId: 'feralrun_smuggler', count: 2, atHpPct: [0.5] },
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.25 },
    loot: [
      { copper: 1150, chance: 1 },
      { itemId: 'vessiks_little_book', chance: 1 },
    ],
    scale: 1.15,
    color: 0x7a6a8e,
  },
  // The icecallers keep the terraces' weather: they sing the rime down onto
  // the stairs before a raid so the blood freezes tidy.
  frostpine_icecaller: {
    id: 'frostpine_icecaller',
    name: 'Frostpine Icecaller',
    minLevel: 36,
    maxLevel: 38,
    family: 'troll',
    hpBase: 94,
    hpPerLevel: 28,
    dmgBase: 17,
    dmgPerLevel: 3.6,
    attackSpeed: 2.3,
    armorPerLevel: 26,
    moveSpeed: 6.6,
    aggroRadius: 12,
    frostbite: {
      chance: 0.35,
      perTick: 11,
      interval: 3,
      duration: 12,
      name: 'Rimecall',
    },
    chillOnHit: { chance: 0.3, mult: 0.65, duration: 5, name: 'Icecaller Grip' },
    loot: [
      { copper: 445, chance: 1 },
      { itemId: 'rimebound_fetish', chance: 0.5, questId: 'q_veth_rites_on_ice' },
    ],
    scale: 1.1,
    color: 0x8fd0e0,
  },
  // Enforcers who followed Veykar out of the guild. They keep the Last Lodge's
  // perimeter in pairs and its old discipline entire; bring a knife you trust.
  forsworn_blade: {
    id: 'forsworn_blade',
    name: 'Forsworn Blade',
    minLevel: 36,
    maxLevel: 38,
    family: 'humanoid',
    elite: true,
    hpBase: 96,
    hpPerLevel: 28,
    dmgBase: 17,
    dmgPerLevel: 3.6,
    attackSpeed: 2.0,
    armorPerLevel: 28,
    moveSpeed: 7.2,
    aggroRadius: 12,
    mortalStrike: { chance: 0.25, healReduction: 0.4, duration: 8, name: 'Lodge Cut' },
    loot: [
      { copper: 780, chance: 1 },
      { itemId: 'forsworn_oath_knife', chance: 0.5, questId: 'q_veth_oath_knives' },
      { itemId: 'healing_potion', chance: 0.08 },
    ],
    scale: 1.05,
    color: 0x3e3a52,
  },
  // The lodge's ciphers were never written down; they were taught to these.
  // Veykar's clerks of shadow, and the only accountants Veth fears.
  forsworn_shadowcaster: {
    id: 'forsworn_shadowcaster',
    name: 'Forsworn Shadowcaster',
    minLevel: 37,
    maxLevel: 39,
    family: 'humanoid',
    elite: true,
    hpBase: 92,
    hpPerLevel: 27,
    dmgBase: 18,
    dmgPerLevel: 3.7,
    attackSpeed: 2.4,
    armorPerLevel: 24,
    moveSpeed: 6.8,
    aggroRadius: 12,
    soulrot: {
      chance: 0.3,
      perTick: 12,
      interval: 3,
      duration: 12,
      name: 'Ledger of Shadows',
      school: 'shadow',
    },
    manaBurn: { chance: 0.25, amount: 120, name: 'Price of Silence', school: 'shadow' },
    loot: [
      { copper: 810, chance: 1 },
      { itemId: 'shadowbound_cipher', chance: 0.5, questId: 'q_veth_ciphers_in_shadow' },
      { itemId: 'mana_potion', chance: 0.08 },
    ],
    scale: 1.0,
    color: 0x584a72,
  },
};

// ---------------------------------------------------------------------------
// NPCs (Nighthollow hub)
// ---------------------------------------------------------------------------

export const VETH_NPCS: Record<string, NpcDef> = {
  spymaster_vael: {
    id: 'spymaster_vael',
    name: 'Spymaster Vael',
    title: 'Keeper of the Ledger',
    pos: { x: 4, z: 1414 },
    facing: -2.0,
    color: 0x5c4a78,
    questIds: [
      'q_veth_quiet_introductions',
      'q_duskmane_hunt',
      'q_blackmere_ledgers',
      'q_veth_greyweir_posting',
      'q_silent_court',
      'q_forsworn_master',
      'q_veth_totem_tally',
      'q_veth_rimeclaw_pelts',
      'q_veth_terrace_sweep',
      'q_veth_hoarbound_debt',
    ],
    greeting:
      'Nothing in Veth is free, $C, and nothing is wasted. Tell me what you can do, and I will tell you what it is worth.',
  },
  provisioner_maren: {
    id: 'provisioner_maren',
    name: 'Provisioner Maren',
    title: 'Sutler of the Whisper Market',
    pos: { x: -6, z: 1418 },
    facing: 1.4,
    color: 0x7a6a4e,
    questIds: ['q_palewidow_silk', 'q_veth_moth_lamps', 'q_veth_verge_cull', 'q_veth_silt_eels'],
    vendorItems: [
      'nighthollow_black_bread',
      'pinefrost_tea',
      'smoked_blackmere_eel',
      'healing_potion',
      'mana_potion',
      'wispweave_robe',
      'quayguard_hauberk',
      'duskstalker_vest',
      'nightpath_treads',
      'blackriver_legguards',
    ],
    greeting:
      'Bread, tea, and a coat the damp cannot argue with: the Quays run on credit, $C, but you will pay me in coin.',
  },
  isyra_coldwater: {
    id: 'isyra_coldwater',
    name: 'Isyra Coldwater',
    title: 'Dealer in Quiet Steel',
    pos: { x: -2, z: 1422 },
    facing: 2.8,
    color: 0x4e6a7a,
    questIds: [
      'q_guildless_debts',
      'q_veth_broken_contracts',
      'q_veth_knife_tax',
      'q_veth_court_records',
      'q_veth_adjourn_court',
      'q_veth_waystation_letters',
    ],
    vendorItems: ['quays_cutlass', 'wispcaller_staff', 'whispersteel_stiletto'],
    greeting: 'Quiet steel for quiet work. If a blade of mine sings, I will refund the difference.',
  },
  factor_ilvane: {
    id: 'factor_ilvane',
    name: 'Factor Ilvane',
    title: 'Broker of Small Debts',
    pos: { x: 10, z: 1414 },
    facing: -1.2,
    color: 0x6a5a44,
    questIds: [
      'q_veth_pelt_lots',
      'q_veth_venom_ledger',
      'q_veth_quay_manifests',
      'q_veth_palefang_price',
      'q_veth_wake_fees',
    ],
    greeting:
      'Every small debt in Nighthollow crosses this desk before it becomes a large one, $C. Yours can start here.',
  },
  auditor_cress: {
    id: 'auditor_cress',
    name: 'Auditor Cress',
    title: 'Examiner of Closed Accounts',
    pos: { x: -12, z: 1408 },
    facing: 0.8,
    color: 0x4a5a6e,
    questIds: [
      'q_veth_towpath_census',
      'q_veth_wisp_essence',
      'q_veth_wispwood_cull',
      'q_veth_drowned_tolls',
      'q_veth_mere_bottom',
    ],
    greeting: 'I audit what the dark takes, $C, and lately it takes more than it reports.',
  },
  // --- the Greyweir toll-house (sub-hub, mid band 28-34) ---
  tollmaster_hesk: {
    id: 'tollmaster_hesk',
    name: 'Tollmaster Hesk',
    title: 'Keeper of the Greyweir',
    pos: { x: 14, z: 1538 },
    facing: -2.4,
    color: 0x51606e,
    questIds: [
      'q_veth_greyweir_posting',
      'q_veth_unlicensed_ferry',
      'q_veth_forged_passes',
      'q_veth_passage_sold',
      'q_veth_turncoats_price',
    ],
    greeting:
      'The weir takes a toll from everything the river carries, $C. Lately the river carries knives, and knives pay in a different coin.',
  },
  ferrywoman_szel: {
    id: 'ferrywoman_szel',
    name: 'Ferrywoman Szel',
    title: 'Mistress of the Weir Landing',
    pos: { x: 9, z: 1546 },
    facing: 2.2,
    color: 0x4a6a62,
    questIds: [
      'q_veth_ferry_dues',
      'q_veth_lantern_motes',
      'q_veth_weir_nets',
      'q_veth_mere_charter',
    ],
    greeting:
      'I pole the black water twice a day and I am owed for both crossings, $N. The mere disagrees. We are negotiating.',
  },
  toll_clerk_odune: {
    id: 'toll_clerk_odune',
    name: 'Toll Clerk Odune',
    title: 'Purser of the Greyweir',
    pos: { x: 20, z: 1544 },
    facing: -0.8,
    color: 0x6e6250,
    questIds: ['q_veth_stores_ledger', 'q_veth_toll_scrip', 'q_veth_dead_letters'],
    vendorItems: [
      'nighthollow_black_bread',
      'pinefrost_tea',
      'smoked_blackmere_eel',
      'healing_potion',
      'mana_potion',
    ],
    greeting:
      'Bread, tea, and receipts, $C. The first two keep you walking; the third keeps you honest. All three are priced accordingly.',
  },
  // --- the Longwatch waystation (sub-hub, north band 34-40) ---
  waykeeper_dral: {
    id: 'waykeeper_dral',
    name: 'Waykeeper Dral',
    title: 'Warden of the North Road',
    pos: { x: 28, z: 1636 },
    facing: -1.6,
    color: 0x546878,
    questIds: ['q_veth_pine_line', 'q_veth_rites_on_ice', 'q_veth_white_ledger', 'q_veth_high_ice'],
    greeting:
      'Everything north of this fire is trying to close the road, $C: trolls, cats, weather. My job is a road that stays open. Yours can be too.',
  },
  arbiter_senna: {
    id: 'arbiter_senna',
    name: 'Arbiter Senna',
    title: "The Guild's Quiet Word",
    pos: { x: 34, z: 1643 },
    facing: 2.9,
    color: 0x5c4a68,
    questIds: [
      'q_veth_waystation_letters',
      'q_veth_watch_the_lodge',
      'q_veth_oath_knives',
      'q_veth_ciphers_in_shadow',
      'q_veth_closing_the_lodge',
    ],
    greeting:
      'Across that dark stands the Last Lodge, $N, and the guild does not go closer. You are not the guild. That is your entire value; try to keep it.',
  },
  sutler_kevish: {
    id: 'sutler_kevish',
    name: 'Sutler Kevish',
    title: 'Provisioner of the Longwatch',
    pos: { x: 24, z: 1645 },
    facing: 1.1,
    color: 0x74604a,
    questIds: ['q_veth_meat_for_the_line', 'q_veth_tallow_accounts', 'q_veth_road_north'],
    vendorItems: [
      'nighthollow_black_bread',
      'pinefrost_tea',
      'smoked_blackmere_eel',
      'healing_potion',
      'mana_potion',
    ],
    greeting:
      'Last hot meal before the ice, $C, and the first one after it, if there is an after. I extend no credit past the tree line.',
  },
};

// ---------------------------------------------------------------------------
// Quests
// ---------------------------------------------------------------------------

export const VETH_QUESTS: Record<string, QuestDef> = {
  q_duskmane_hunt: {
    id: 'q_duskmane_hunt',
    name: 'The Price of Teeth',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'The duskmane packs have started taking porters off the south towpath, $N. Every body they drag into the dark is a debt the Confederation must settle with someone. Kill twelve; the ledger prefers round numbers.',
    completionText:
      'Twelve, as written. The porters will not thank you; they will never know your name. That is how Veth prefers its debts paid.',
    objectives: [
      { type: 'kill', targetMobId: 'duskmane_stalker', count: 12, label: 'Duskmane Stalker slain' },
    ],
    xpReward: 8200,
    copperReward: 3200,
    itemRewards: {},
    minLevel: 20,
  },
  q_palewidow_silk: {
    id: 'q_palewidow_silk',
    name: 'Silk for the Ledger',
    giverNpcId: 'provisioner_maren',
    turnInNpcId: 'provisioner_maren',
    text: 'Palewidow silk holds a knot better than anything the south sells, and my buyers do not ask where it comes from, $N. Eight skeins, cut from the weavers in the hollows east of the towpath. I pay the fair rate, which is the rate I say is fair.',
    completionText:
      'Fine cuts, barely a strand frayed. Take the treads; call the rest of your fee goodwill, which in Veth is worth more than coin.',
    objectives: [{ type: 'collect', itemId: 'palewidow_silk', count: 8, label: 'Palewidow Silk' }],
    xpReward: 8600,
    copperReward: 3600,
    itemRewards: {
      warrior: 'nightpath_treads',
      mage: 'nightpath_treads',
      rogue: 'nightpath_treads',
    },
    minLevel: 21,
  },
  q_blackmere_ledgers: {
    id: 'q_blackmere_ledgers',
    name: 'The Drowned Accounts',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'A courier barge went down where the black river widens into the Blackmere, $N, and the skulkers have nested in the wreck ever since. The cargo was paper: four ledgers, and Veth remembers what is written even when the water does not. Kill ten of the skulkers and bring the books up dry.',
    completionText:
      'Waterstained but legible. Half the names in these pages owe the Confederation money; the other half will, by morning.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 10,
        label: 'Blackriver Skulker slain',
      },
      { type: 'collect', itemId: 'waterlogged_ledger', count: 4, label: 'Waterlogged Ledger' },
    ],
    xpReward: 9800,
    copperReward: 4000,
    itemRewards: {},
    requiresQuest: 'q_duskmane_hunt',
    minLevel: 23,
  },
  q_guildless_debts: {
    id: 'q_guildless_debts',
    name: 'Debts Called Due',
    giverNpcId: 'isyra_coldwater',
    turnInNpcId: 'isyra_coldwater',
    text: 'Every blade I sell is numbered, $N, and the guild keeps the numbers. The cutthroats working the north road were expelled for freelancing; they kept their sigils, and the guild wants them back. Ten dead, five sigils. The guild does not pay for apologies.',
    completionText:
      'Five sigils, struck from the rolls. You did not hear a guild mentioned, and I did not say the word. We understand each other.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'guildless_cutthroat',
        count: 10,
        label: 'Guildless Cutthroat slain',
      },
      { type: 'collect', itemId: 'guildless_sigil', count: 5, label: 'Guildless Sigil' },
    ],
    xpReward: 15200,
    copperReward: 5400,
    itemRewards: {},
    minLevel: 30,
  },
  q_silent_court: {
    id: 'q_silent_court',
    name: 'The Silent Court',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'The city-state that raised the Silent Court refused the Agreement, $N, and it is no coincidence that nobody remembers its name. Its courtiers still hold session in the ruin, and they have begun collecting tolls on the west bank again. Put twelve of them down and bring me five of their court seals; unpaid history is still a debt.',
    completionText:
      'Seals of a court that no longer exists, for a debt that never expires. The Confederation settles everything eventually, $N. Remember that.',
    objectives: [
      { type: 'kill', targetMobId: 'hollow_revenant', count: 12, label: 'Hollow Revenant slain' },
      { type: 'collect', itemId: 'silent_court_seal', count: 5, label: 'Silent Court Seal' },
    ],
    xpReward: 17400,
    copperReward: 5800,
    itemRewards: {},
    requiresQuest: 'q_blackmere_ledgers',
    minLevel: 32,
  },
  q_forsworn_master: {
    id: 'q_forsworn_master',
    name: 'The Forsworn Master',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'Veykar kept the oldest lodge in the guild and broke its oldest rule: he chose his own contracts. Now he sells Veth secrets out of the Last Lodge and calls it independence. The guild will not touch him; he trained half of them. Take companions, $N, mind the knives when he turns, and close the account.',
    completionText:
      'It is done, then. No song, no statue; his name comes off the rolls tonight, and yours goes into a ledger very few are permitted to read. Consider that the highest payment Veth offers.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'veykar_the_forsworn',
        count: 1,
        label: 'Veykar the Forsworn slain',
      },
    ],
    xpReward: 24000,
    copperReward: 7500,
    itemRewards: {
      warrior: 'forsworn_edge',
      mage: 'wispcaller_staff',
      rogue: 'whispersteel_stiletto',
    },
    requiresQuest: 'q_silent_court',
    suggestedPlayers: 3,
    minLevel: 38,
  },
  // --- chain: Factor Ilvane, "small debts" (27-29) ---
  q_veth_pelt_lots: {
    id: 'q_veth_pelt_lots',
    name: 'Pelts by the Lot',
    giverNpcId: 'factor_ilvane',
    turnInNpcId: 'factor_ilvane',
    text: 'The southern lots trade duskmane pelts at four times what the beasts cost to skin, $N. Thin the packs on the Run, twelve of them, and bring me eight clean pelt strips. The margin is mine; the fee is yours.',
    completionText:
      'Eight strips, uncut, and twelve fewer mouths on the towpath. I will enter it as a profit, which in Veth is the warmest word we have.',
    objectives: [
      { type: 'kill', targetMobId: 'duskmane_stalker', count: 12, label: 'Duskmane Stalker slain' },
      { type: 'collect', itemId: 'duskmane_pelt_strip', count: 8, label: 'Duskmane Pelt Strip' },
    ],
    xpReward: 8400,
    copperReward: 3400,
    itemRewards: {},
    minLevel: 20,
  },
  q_veth_venom_ledger: {
    id: 'q_veth_venom_ledger',
    name: 'The Venom Ledger',
    giverNpcId: 'factor_ilvane',
    turnInNpcId: 'factor_ilvane',
    text: 'Palewidow venom sells south as medicine and north as something else, $N; I do not write down which. Fourteen weavers culled and eight venom sacs, unruptured. Handle them the way you would handle your own accounts: carefully.',
    completionText:
      "Not one sac ruptured. You have a bookkeeper's hands, $N. That is a compliment; in Nighthollow there is no higher one.",
    objectives: [
      { type: 'kill', targetMobId: 'palewidow_weaver', count: 14, label: 'Palewidow Weaver slain' },
      { type: 'collect', itemId: 'palewidow_venom_sac', count: 8, label: 'Palewidow Venom Sac' },
    ],
    xpReward: 8800,
    copperReward: 3600,
    itemRewards: {},
    requiresQuest: 'q_veth_pelt_lots',
    minLevel: 21,
  },
  q_veth_quay_manifests: {
    id: 'q_veth_quay_manifests',
    name: 'Manifests in the Mud',
    giverNpcId: 'factor_ilvane',
    turnInNpcId: 'factor_ilvane',
    text: 'The skulkers have been dragging cargo off the Quays and the manifests with it, $N. Paper is the only proof a debt exists. Fourteen skulkers, eight manifests, and mind the chill in the water; I do not insure against it.',
    completionText:
      'Smeared, but the numbers survive. Numbers usually do. The Quays owe you; I have written it down, which makes it true.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 14,
        label: 'Blackriver Skulker slain',
      },
      { type: 'collect', itemId: 'quay_manifest', count: 8, label: 'Sodden Quay Manifest' },
    ],
    xpReward: 9600,
    copperReward: 3800,
    itemRewards: {},
    requiresQuest: 'q_veth_venom_ledger',
    minLevel: 23,
  },
  q_veth_palefang_price: {
    id: 'q_veth_palefang_price',
    name: 'A Debt of Silence',
    giverNpcId: 'factor_ilvane',
    turnInNpcId: 'factor_ilvane',
    text: 'Palefang has taken three porters and a factor this season, and the Run goes quiet a full minute before she steps out of it, $N. The Confederation has priced that silence and found it too expensive. Bring companions; she has never needed them.',
    completionText:
      'So the Run has sound again. The porters will invent a hero for this, and they will be wrong twice. Your fee is entered; the ledger does not care who is thanked.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'palefang_the_silent',
        count: 1,
        label: 'Palefang the Silent slain',
      },
    ],
    xpReward: 12000,
    copperReward: 4600,
    itemRewards: {},
    requiresQuest: 'q_veth_quay_manifests',
    suggestedPlayers: 3,
    minLevel: 24,
  },
  // --- chain: Auditor Cress, the Blackmere audit (29-31) ---
  q_veth_wisp_essence: {
    id: 'q_veth_wisp_essence',
    name: 'What the Light Eats',
    giverNpcId: 'auditor_cress',
    turnInNpcId: 'auditor_cress',
    text: 'The wisps in the Wispwood feed on what travelers know: names, routes, sums, $N. That is Veth property. Cull twelve and bring me eight of their essences; I intend to bill the forest itself if I can find where it banks.',
    completionText:
      'Warm as a lie and twice as bright. The essences balance against three lost couriers; the forest still owes us two.',
    objectives: [
      { type: 'kill', targetMobId: 'feral_wisp', count: 12, label: 'Feral Wisp slain' },
      { type: 'collect', itemId: 'wisplight_essence', count: 8, label: 'Wisplight Essence' },
    ],
    xpReward: 10600,
    copperReward: 4200,
    itemRewards: {},
    minLevel: 26,
  },
  q_veth_wispwood_cull: {
    id: 'q_veth_wispwood_cull',
    name: 'A Correction in the Wood',
    giverNpcId: 'auditor_cress',
    turnInNpcId: 'auditor_cress',
    text: 'The audit says the Wispwood holds a third more wisps than last season, and the skulkers have begun nesting under its bank, $N. The Confederation calls this drift, and drift gets corrected. Fourteen wisps, ten skulkers; round the account down.',
    completionText:
      'Corrected. The wood will drift again by spring, and someone will be paid to correct it again. This is what stability costs, $N; Veth pays it gladly.',
    objectives: [
      { type: 'kill', targetMobId: 'feral_wisp', count: 14, label: 'Feral Wisp slain' },
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 10,
        label: 'Blackriver Skulker slain',
      },
    ],
    xpReward: 11000,
    copperReward: 4400,
    itemRewards: {},
    requiresQuest: 'q_veth_wisp_essence',
    minLevel: 27,
  },
  q_veth_drowned_tolls: {
    id: 'q_veth_drowned_tolls',
    name: 'Tolls for the Drowned',
    giverNpcId: 'auditor_cress',
    turnInNpcId: 'auditor_cress',
    text: 'The drowned have started collecting tolls at the Blackmere landing: coin, cargo, and twice a porter, $N. A toll requires a charter, and they have none on file. Put fourteen of them down and recover eight of the toll coins they hoard; those are Confederation currency.',
    completionText:
      'Cold coin, but coin. The drowned may keep what they took from older ledgers than ours; these eight are ours, and now they are home.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackmere_drowned',
        count: 14,
        label: 'Blackmere Drowned slain',
      },
      { type: 'collect', itemId: 'drowned_toll_coin', count: 8, label: 'Drowned Toll Coin' },
    ],
    xpReward: 12400,
    copperReward: 4600,
    itemRewards: {},
    requiresQuest: 'q_veth_wispwood_cull',
    minLevel: 28,
  },
  q_veth_mere_bottom: {
    id: 'q_veth_mere_bottom',
    name: 'The Bottom of the Mere',
    giverNpcId: 'auditor_cress',
    turnInNpcId: 'auditor_cress',
    text: 'Whatever charter the drowned think they hold, it was not issued by Veth, $N. Sixteen more of them, and ten of the skulkers ferrying for them. When the Blackmere is quiet, the audit closes.',
    completionText:
      'The Blackmere reports quiet water and no new claims. I am closing the account. Do not mistake that for gratitude; it is better, it is a balance.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackmere_drowned',
        count: 16,
        label: 'Blackmere Drowned slain',
      },
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 10,
        label: 'Blackriver Skulker slain',
      },
    ],
    xpReward: 12800,
    copperReward: 4800,
    itemRewards: {},
    requiresQuest: 'q_veth_drowned_tolls',
    minLevel: 29,
  },
  // --- chain: Isyra Coldwater, guild accounts receivable (30-32) ---
  q_veth_broken_contracts: {
    id: 'q_veth_broken_contracts',
    name: 'Broken Contracts',
    giverNpcId: 'isyra_coldwater',
    turnInNpcId: 'isyra_coldwater',
    text: 'The sigils were the start, $N. The guildless still carry their old contracts, and every page names clients who believe those debts died with the expulsion. The guild disagrees. Fourteen cutthroats, eight contracts, and no copies.',
    completionText:
      'Eight contracts, and every client on them suddenly owes the guild an apology and a fee. You have made several important people poorer, $N. They will never know it was you; that is the service.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'guildless_cutthroat',
        count: 14,
        label: 'Guildless Cutthroat slain',
      },
      { type: 'collect', itemId: 'cutthroat_contract', count: 8, label: 'Cutthroat Contract' },
    ],
    xpReward: 15600,
    copperReward: 5400,
    itemRewards: {},
    requiresQuest: 'q_guildless_debts',
    minLevel: 31,
  },
  q_veth_knife_tax: {
    id: 'q_veth_knife_tax',
    name: 'The Knife Tax',
    giverNpcId: 'isyra_coldwater',
    turnInNpcId: 'isyra_coldwater',
    text: 'The freelancers on the north road have begun taxing porters at knifepoint and calling it a toll, $N. There is one tax collector in Veth, and it is not them. Sixteen, and make it plain.',
    completionText:
      'The road reports no collections this week. Plain enough. The guild thanks you in the only language it is fluent in: coin.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'guildless_cutthroat',
        count: 16,
        label: 'Guildless Cutthroat slain',
      },
    ],
    xpReward: 15000,
    copperReward: 5500,
    itemRewards: {},
    requiresQuest: 'q_veth_broken_contracts',
    minLevel: 31,
  },
  q_veth_court_records: {
    id: 'q_veth_court_records',
    name: 'Records of the Court',
    giverNpcId: 'isyra_coldwater',
    turnInNpcId: 'isyra_coldwater',
    text: 'Before the Agreement, the Silent Court licensed killings the guild now claims as its own history, $N. The revenants still file those pages in the ruin. Fourteen of them put down, eight pages recovered; the guild prefers its history unread.',
    completionText:
      "Pages older than the Agreement, and half the names still legible. They go in the vault, not the fire; the guild's history is a weapon, and weapons are not burned.",
    objectives: [
      { type: 'kill', targetMobId: 'hollow_revenant', count: 14, label: 'Hollow Revenant slain' },
      { type: 'collect', itemId: 'court_ledger_page', count: 8, label: 'Court Ledger Page' },
    ],
    xpReward: 16800,
    copperReward: 5800,
    itemRewards: {},
    requiresQuest: 'q_veth_knife_tax',
    minLevel: 32,
  },
  q_veth_adjourn_court: {
    id: 'q_veth_adjourn_court',
    name: 'Court Adjourned',
    giverNpcId: 'isyra_coldwater',
    turnInNpcId: 'isyra_coldwater',
    text: 'The Court has begun sending its tollmen east of the river, and the guildless sell them passage, $N. Both sides of that trade are unlicensed. Sixteen revenants, ten cutthroats, and the west bank keeps its quiet.',
    completionText:
      'Adjourned, then. A court with no session, a road with no toll, and a ledger with no outstanding lines. This is as close to a holiday as Veth observes.',
    objectives: [
      { type: 'kill', targetMobId: 'hollow_revenant', count: 16, label: 'Hollow Revenant slain' },
      {
        type: 'kill',
        targetMobId: 'guildless_cutthroat',
        count: 10,
        label: 'Guildless Cutthroat slain',
      },
    ],
    xpReward: 18200,
    copperReward: 6000,
    itemRewards: {},
    requiresQuest: 'q_veth_court_records',
    minLevel: 33,
  },
  // --- chain: Spymaster Vael, the north ledger (32-34) ---
  q_veth_totem_tally: {
    id: 'q_veth_totem_tally',
    name: 'A Tally of Totems',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'The Frostpine trolls carve a war totem for every raid they intend to make, $N, which makes their intentions admirably easy to audit. The current count is too high. Fourteen headhunters, and bring me eight totems; each one is a raid that never happens.',
    completionText:
      'Eight raids, cancelled in advance. Cheaper than walls, quieter than war. This is why Veth keeps ledgers instead of armies.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_headhunter',
        count: 14,
        label: 'Frostpine Headhunter slain',
      },
      { type: 'collect', itemId: 'frostpine_war_totem', count: 8, label: 'Frostpine War Totem' },
    ],
    xpReward: 19000,
    copperReward: 6200,
    itemRewards: {},
    minLevel: 34,
  },
  q_veth_rimeclaw_pelts: {
    id: 'q_veth_rimeclaw_pelts',
    name: 'Rimeclaw Futures',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'The rimeclaws have come down from the high ice and the terrace trade in furs has noticed, $N. Twelve prowlers thinned and eight pelts, whole. The Confederation buys low, in the north, in winter, from you.',
    completionText:
      'Whole pelts, winter weight. They will sell south for six times your fee, and you will not resent it, because you knew the rate when you took the work. Veth values that in a contractor.',
    objectives: [
      { type: 'kill', targetMobId: 'rimeclaw_prowler', count: 12, label: 'Rimeclaw Prowler slain' },
      { type: 'collect', itemId: 'rimeclaw_pelt', count: 8, label: 'Rimeclaw Pelt' },
    ],
    xpReward: 19400,
    copperReward: 6400,
    itemRewards: {},
    requiresQuest: 'q_veth_totem_tally',
    minLevel: 35,
  },
  q_veth_terrace_sweep: {
    id: 'q_veth_terrace_sweep',
    name: 'Sweeping the Terraces',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'The northern terraces are the only road to the Kael border, and this season it is held by spears and claws in roughly equal measure, $N. Sixteen headhunters, twelve rimeclaws. The pass stays open; the ledger stays balanced.',
    completionText:
      'The border porters crossed this morning without an escort, which is the only report that matters. The north is passable. What comes down that road next is another account entirely.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_headhunter',
        count: 16,
        label: 'Frostpine Headhunter slain',
      },
      { type: 'kill', targetMobId: 'rimeclaw_prowler', count: 12, label: 'Rimeclaw Prowler slain' },
    ],
    xpReward: 20200,
    copperReward: 6600,
    itemRewards: {},
    requiresQuest: 'q_veth_rimeclaw_pelts',
    minLevel: 36,
  },
  q_veth_hoarbound_debt: {
    id: 'q_veth_hoarbound_debt',
    name: 'The Hoarbound Debt',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'The trolls sank Grelnok in the ice for eating his own war party, and the ice let him back out, $N. He has been collecting the terraces piece by piece since, and Veth does not recognize his claim. Take companions onto the ice. The cold is his; make sure the ledger is ours.',
    completionText:
      'The ice keeps him this time; we paid it more than the trolls did. Take the leggings, $N, and the fee. Your account with the north is closed, and very few people can say that.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'grelnok_the_hoarbound',
        count: 1,
        label: 'Grelnok the Hoarbound slain',
      },
    ],
    xpReward: 23000,
    copperReward: 7200,
    itemRewards: {
      warrior: 'terracewatch_leggings',
      mage: 'terracewatch_leggings',
      rogue: 'terracewatch_leggings',
    },
    requiresQuest: 'q_veth_terrace_sweep',
    suggestedPlayers: 3,
    minLevel: 37,
  },
  // --- south third (20-27): arrivals, the Verge, the south river ---
  q_veth_quiet_introductions: {
    id: 'q_veth_quiet_introductions',
    name: 'Quiet Introductions',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'spymaster_vael',
    text: 'Nighthollow does not give tours, $N; it gives introductions, once. Factor Ilvane brokers the small debts, Isyra Coldwater sells the quiet steel, and Auditor Cress counts what the dark takes. Present yourself to each of them. After that, whatever you become here is on your own account.',
    completionText:
      'So they have seen your face and written it down. Three ledgers now carry your name, $N. Try to make every entry after this one a credit.',
    objectives: [
      { type: 'interact', targetNpcId: 'factor_ilvane', count: 1, label: 'Meet Factor Ilvane' },
      { type: 'interact', targetNpcId: 'isyra_coldwater', count: 1, label: 'Meet Isyra Coldwater' },
      { type: 'interact', targetNpcId: 'auditor_cress', count: 1, label: 'Meet Auditor Cress' },
    ],
    xpReward: 3600,
    copperReward: 1600,
    itemRewards: {},
    minLevel: 20,
  },
  q_veth_moth_lamps: {
    id: 'q_veth_moth_lamps',
    name: 'Dust for the Lamps',
    giverNpcId: 'provisioner_maren',
    turnInNpcId: 'provisioner_maren',
    text: 'The twilight moths come off the Verge at dusk and eat my lamp oil down to the wick, $N, and a dark market stall sells nothing. Thin them, ten or so, and shake eight measures of dust from their wings. There are buyers for the dust; I do not ask what they do with it.',
    completionText:
      'Oil in the lamps and dust in the jars: two trades served by one errand. That is the kind of arithmetic Nighthollow respects, $N.',
    objectives: [
      { type: 'kill', targetMobId: 'twilight_moth', count: 10, label: 'Twilight Moth slain' },
      { type: 'collect', itemId: 'mothwing_dust', count: 8, label: 'Mothwing Dust' },
    ],
    xpReward: 8600,
    copperReward: 3400,
    itemRewards: {},
    minLevel: 21,
  },
  q_veth_verge_cull: {
    id: 'q_veth_verge_cull',
    name: 'Both Sides of the Trade',
    giverNpcId: 'provisioner_maren',
    turnInNpcId: 'provisioner_maren',
    text: 'The moths lay in the palewidow hollows and the widows fatten on the moths, $N; left alone, the Verge exports nothing but appetite. Cut both sides of that trade: twelve moths, ten weavers. The Verge does not need to be safe, it needs to be profitable.',
    completionText:
      'The silk lots report the hollows quieter and my stall keeps its stock. Nobody will call the Verge tame, but it is back to paying its way.',
    objectives: [
      { type: 'kill', targetMobId: 'twilight_moth', count: 12, label: 'Twilight Moth slain' },
      { type: 'kill', targetMobId: 'palewidow_weaver', count: 10, label: 'Palewidow Weaver slain' },
    ],
    xpReward: 8800,
    copperReward: 3500,
    itemRewards: {},
    requiresQuest: 'q_veth_moth_lamps',
    minLevel: 22,
  },
  q_veth_towpath_census: {
    id: 'q_veth_towpath_census',
    name: 'The Towpath Census',
    giverNpcId: 'auditor_cress',
    turnInNpcId: 'auditor_cress',
    text: 'A census, $N: the towpath south of the gate hosts more widows and skulkers than my last count allows, and an uncounted thing is an unbilled thing. Reduce the surplus, ten of each, and the books will match the road again. Veth is only dangerous where it is accurate.',
    completionText:
      'Ten and ten, which is what the margin said. The road now matches its own paperwork, $N. You would be surprised how rarely that is true of anything.',
    objectives: [
      { type: 'kill', targetMobId: 'palewidow_weaver', count: 10, label: 'Palewidow Weaver slain' },
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 10,
        label: 'Blackriver Skulker slain',
      },
    ],
    xpReward: 9400,
    copperReward: 3700,
    itemRewards: {},
    minLevel: 23,
  },
  q_veth_silt_eels: {
    id: 'q_veth_silt_eels',
    name: 'The Eel Accounts',
    giverNpcId: 'provisioner_maren',
    turnInNpcId: 'provisioner_maren',
    text: 'The skulkers net the silt eels I smoke, and lately they keep the catch, $N. Ten skulkers off the banks, and bring me eight eels out of their traps while you are in the water. Mind the chill; I sell the cure for it, which is tea.',
    completionText:
      'Fat eels, barely bruised. They will hang in the smoke by morning and sell by noon. The skulkers can file a complaint with the river.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 10,
        label: 'Blackriver Skulker slain',
      },
      { type: 'collect', itemId: 'silt_eel', count: 8, label: 'Silt Eel' },
    ],
    xpReward: 9800,
    copperReward: 3900,
    itemRewards: {},
    minLevel: 24,
  },
  q_veth_wake_fees: {
    id: 'q_veth_wake_fees',
    name: 'Wake Fees',
    giverNpcId: 'factor_ilvane',
    turnInNpcId: 'factor_ilvane',
    text: 'Every barge that passes the Quays pays a wake fee, $N, and every barge this month has paid it twice more: to skulkers in the shallows and to wisps drifting off the Wispwood bank. Competing tolls are bad for the brand. Twelve skulkers, ten wisps, and the river has one creditor again.',
    completionText:
      'The pilots report clean water and a single, correct invoice. You have simplified the river, $N; I will simplify your fee to match: here it is, in full.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackriver_skulker',
        count: 12,
        label: 'Blackriver Skulker slain',
      },
      { type: 'kill', targetMobId: 'feral_wisp', count: 10, label: 'Feral Wisp slain' },
    ],
    xpReward: 10200,
    copperReward: 4100,
    itemRewards: {},
    minLevel: 25,
  },
  // --- middle third (27-34): the Greyweir toll-house ---
  q_veth_greyweir_posting: {
    id: 'q_veth_greyweir_posting',
    name: 'The Greyweir Posting',
    giverNpcId: 'spymaster_vael',
    turnInNpcId: 'tollmaster_hesk',
    text: 'The Greyweir sits where the black river narrows north of the mere, $N, and its toll-house keeps the middle country honest. Tollmaster Hesk holds the posting and is owed a capable pair of hands. Let Ferrywoman Szel count you aboard on the way; she records everything that crosses, and you are now something that crosses.',
    completionText:
      'Vael sends a knife and calls it a clerk. Good; the weir needs both. You will find the middle river less patient than the south, $N. Wages are posted, and collected in advance by nobody.',
    objectives: [
      {
        type: 'interact',
        targetNpcId: 'ferrywoman_szel',
        count: 1,
        label: 'Be counted by Ferrywoman Szel',
      },
    ],
    xpReward: 4200,
    copperReward: 2000,
    itemRewards: {},
    minLevel: 26,
  },
  q_veth_ferry_dues: {
    id: 'q_veth_ferry_dues',
    name: 'Ferry Dues',
    giverNpcId: 'ferrywoman_szel',
    turnInNpcId: 'ferrywoman_szel',
    text: 'The drowned walk out of the mere and board my ferry like paying passengers, $N, except they pay in old chits the Confederation retired thirty years ago. Put twelve of them back in the water and bring me eight of the chits. Somebody upstream is reissuing dead currency, and I intend to know who.',
    completionText:
      'Retired chits, reissued wet. I will pass these to Hesk, who will pass them to someone whose name neither of us says aloud. Your fare is covered, $N: both directions, once.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackmere_drowned',
        count: 12,
        label: 'Blackmere Drowned slain',
      },
      { type: 'collect', itemId: 'barge_chit', count: 8, label: 'Waterlogged Barge Chit' },
    ],
    xpReward: 12000,
    copperReward: 4400,
    itemRewards: {},
    minLevel: 27,
  },
  q_veth_lantern_motes: {
    id: 'q_veth_lantern_motes',
    name: 'Light for the Crossing',
    giverNpcId: 'ferrywoman_szel',
    turnInNpcId: 'ferrywoman_szel',
    text: 'A ferry runs at night or it does not run, $N, and my lanterns burn wisplight or nothing. The feral wisps off the Wispwood bank carry a steadier mote than any candle. Ten wisps culled and eight motes, unbroken; I pay by the lumen.',
    completionText:
      'Steady light, cold as a fair price. The crossing will run all month on these. The forest can bill me, if it ever learns to write.',
    objectives: [
      { type: 'kill', targetMobId: 'feral_wisp', count: 10, label: 'Feral Wisp slain' },
      { type: 'collect', itemId: 'ferry_lantern_mote', count: 8, label: 'Ferry Lantern Mote' },
    ],
    xpReward: 12200,
    copperReward: 4500,
    itemRewards: {},
    requiresQuest: 'q_veth_ferry_dues',
    minLevel: 28,
  },
  q_veth_weir_nets: {
    id: 'q_veth_weir_nets',
    name: 'What the Nets Owe',
    giverNpcId: 'ferrywoman_szel',
    turnInNpcId: 'ferrywoman_szel',
    text: 'The weir nets catch everything the river owes us, and twice a week I haul them up cut, $N. Smugglers cut from above; the drowned pull from below. Twelve of the one, ten of the other, and my nets come up whole and heavy.',
    completionText:
      'Whole nets, full ledger. The river will find new ways to shortchange the weir, it always does, but this week it pays in full, $N.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'feralrun_smuggler',
        count: 12,
        label: 'Feralrun Smuggler slain',
      },
      {
        type: 'kill',
        targetMobId: 'blackmere_drowned',
        count: 10,
        label: 'Blackmere Drowned slain',
      },
    ],
    xpReward: 13000,
    copperReward: 4700,
    itemRewards: {},
    requiresQuest: 'q_veth_lantern_motes',
    minLevel: 29,
  },
  q_veth_mere_charter: {
    id: 'q_veth_mere_charter',
    name: 'A Charter for the Landing',
    giverNpcId: 'ferrywoman_szel',
    turnInNpcId: 'ferrywoman_szel',
    text: 'The mere believes my landing belongs to it, $N: the drowned take the pilings, the wisps take the lantern posts, and each morning I row out and repossess my own ferry. I have filed for a charter that says the landing is mine. Twelve drowned and ten wisps are the filing fee.',
    completionText:
      'The landing stood empty at dawn for the first time since thaw. Charter granted, then, by the only authority the mere respects. You are a considerable filing fee, $N.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackmere_drowned',
        count: 12,
        label: 'Blackmere Drowned slain',
      },
      { type: 'kill', targetMobId: 'feral_wisp', count: 10, label: 'Feral Wisp slain' },
    ],
    xpReward: 13400,
    copperReward: 4800,
    itemRewards: {},
    requiresQuest: 'q_veth_weir_nets',
    minLevel: 30,
  },
  q_veth_unlicensed_ferry: {
    id: 'q_veth_unlicensed_ferry',
    name: 'The Unlicensed Ferry',
    giverNpcId: 'tollmaster_hesk',
    turnInNpcId: 'tollmaster_hesk',
    text: 'There is one licensed crossing on this river, $N, and I am standing at it. The feralrun gangs pole passengers past the weir at midnight and keep their accounts in knotted cord. Twelve smugglers out of business, eight tally knots for evidence; the Confederation likes its convictions pre-counted.',
    completionText:
      'Knotted cord: crude bookkeeping, but honest, which is more than I can say for the clientele. The midnight trade will resume within a season. So will you, I expect.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'feralrun_smuggler',
        count: 12,
        label: 'Feralrun Smuggler slain',
      },
      { type: 'collect', itemId: 'smugglers_tally_knot', count: 8, label: "Smuggler's Tally Knot" },
    ],
    xpReward: 12600,
    copperReward: 4600,
    itemRewards: {},
    minLevel: 28,
  },
  q_veth_forged_passes: {
    id: 'q_veth_forged_passes',
    name: 'Forged Passes',
    giverNpcId: 'tollmaster_hesk',
    turnInNpcId: 'tollmaster_hesk',
    text: 'Now the survivors sell forged weir passes, $N: my seal, my signature, drawn by someone who has clearly met neither. Flattery, and also a hanging offense. Ten more smugglers, and pull eight forgeries out of circulation before some honest fool pays full price for one.',
    completionText:
      'A fair hand, whoever draws these; I would offer them a clerkship if the position were not a noose. The forgeries go in the fire and your fee comes out of it, $N.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'feralrun_smuggler',
        count: 10,
        label: 'Feralrun Smuggler slain',
      },
      { type: 'collect', itemId: 'forged_weir_pass', count: 8, label: 'Forged Weir Pass' },
    ],
    xpReward: 13000,
    copperReward: 4700,
    itemRewards: {},
    requiresQuest: 'q_veth_unlicensed_ferry',
    minLevel: 29,
  },
  q_veth_passage_sold: {
    id: 'q_veth_passage_sold',
    name: 'Passage, Sold',
    giverNpcId: 'tollmaster_hesk',
    turnInNpcId: 'tollmaster_hesk',
    text: 'The guildless on the north road have gone into partnership with the feralrun gangs, $N: steel above the bank, boats below it. Passage sold past my weir, toll-free, to anyone with coin and no questions. Break the partnership: twelve cutthroats, ten smugglers. Leave the wreckage where their next investors can see it.',
    completionText:
      'The road and the river both report a sudden lack of competitors. The Greyweir thanks you in the only voice it has, $N, which is the sound of tolls being paid.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'guildless_cutthroat',
        count: 12,
        label: 'Guildless Cutthroat slain',
      },
      {
        type: 'kill',
        targetMobId: 'feralrun_smuggler',
        count: 10,
        label: 'Feralrun Smuggler slain',
      },
    ],
    xpReward: 14000,
    copperReward: 4900,
    itemRewards: {},
    requiresQuest: 'q_veth_forged_passes',
    minLevel: 30,
  },
  q_veth_turncoats_price: {
    id: 'q_veth_turncoats_price',
    name: "The Turncoat's Price",
    giverNpcId: 'tollmaster_hesk',
    turnInNpcId: 'tollmaster_hesk',
    text: "Vessik kept the guild's books until he sold them, $N: four buyers, one set of accounts, and a fifth copy for himself. He counts his coin by the weir under paid protection and believes the ledger cannot reach him. Take companions; he taught half this river how to kill, and the other half owes him money.",
    completionText:
      'Then the fifth copy comes home and the account closes at last. The guild will not thank you and neither will the buyers, $N. I will, quietly, once: thank you. That is the last time it is said.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'vessik_the_turncoat',
        count: 1,
        label: 'Vessik the Turncoat slain',
      },
    ],
    xpReward: 17200,
    copperReward: 5600,
    itemRewards: {
      warrior: 'weirwatch_wraps',
      mage: 'weirwatch_wraps',
      rogue: 'weirwatch_wraps',
    },
    requiresQuest: 'q_veth_passage_sold',
    suggestedPlayers: 3,
    minLevel: 31,
  },
  q_veth_stores_ledger: {
    id: 'q_veth_stores_ledger',
    name: 'The Stores Ledger',
    giverNpcId: 'toll_clerk_odune',
    turnInNpcId: 'toll_clerk_odune',
    text: "Every ration tin in the toll-house stores is stamped and counted, $N, and forty of them walked into the mere with the last supply barge. The drowned have no use for supper; they hoard out of habit. Ten of them settled and eight tins recovered, stamps legible, or the quartermaster's office bills ME.",
    completionText:
      'Stamped, dented, and accounted for. The stores balance, the office is denied its little triumph, and you are paid, $N. Everyone gets what they deserve; how rare.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'blackmere_drowned',
        count: 10,
        label: 'Blackmere Drowned slain',
      },
      { type: 'collect', itemId: 'sunken_ration_tin', count: 8, label: 'Sunken Ration Tin' },
    ],
    xpReward: 12800,
    copperReward: 4600,
    itemRewards: {},
    minLevel: 29,
  },
  q_veth_toll_scrip: {
    id: 'q_veth_toll_scrip',
    name: 'A Second Issuer',
    giverNpcId: 'toll_clerk_odune',
    turnInNpcId: 'toll_clerk_odune',
    text: 'The Silent Court has begun issuing its own toll scrip on the west bank, $N: paper from a state that does not exist, honored by travelers too frightened to argue. Fear is a currency the Confederation does not license. Twelve revenants retired, eight scrip withdrawn from circulation.',
    completionText:
      'Paper from a dead court, still holding value through pure menace. I almost admire it. Into the fire it goes regardless, $N; the Greyweir tolerates no second issuer.',
    objectives: [
      { type: 'kill', targetMobId: 'hollow_revenant', count: 12, label: 'Hollow Revenant slain' },
      { type: 'collect', itemId: 'hollow_toll_scrip', count: 8, label: 'Hollow Toll Scrip' },
    ],
    xpReward: 17400,
    copperReward: 5400,
    itemRewards: {},
    requiresQuest: 'q_veth_stores_ledger',
    minLevel: 32,
  },
  q_veth_dead_letters: {
    id: 'q_veth_dead_letters',
    name: 'Dead Letters',
    giverNpcId: 'toll_clerk_odune',
    turnInNpcId: 'toll_clerk_odune',
    text: "The Court's tollmen now carry correspondence, $N: dead letters between the ruin and the guildless camps, arranging what I can only call commerce. The living half of that arrangement buys; the dead half enforces. End twelve revenants and eight of their couriers, and the mail stops.",
    completionText:
      'No further correspondence. Whatever the ruin and the road were arranging, it is now a matter for historians, $N, and Veth employs none. The file closes.',
    objectives: [
      { type: 'kill', targetMobId: 'hollow_revenant', count: 12, label: 'Hollow Revenant slain' },
      {
        type: 'kill',
        targetMobId: 'guildless_cutthroat',
        count: 8,
        label: 'Guildless Cutthroat slain',
      },
    ],
    xpReward: 17800,
    copperReward: 5600,
    itemRewards: {},
    requiresQuest: 'q_veth_toll_scrip',
    minLevel: 33,
  },
  // --- north third (34-40): the Longwatch waystation and the Last Lodge ---
  q_veth_waystation_letters: {
    id: 'q_veth_waystation_letters',
    name: 'Letters for the Longwatch',
    giverNpcId: 'isyra_coldwater',
    turnInNpcId: 'arbiter_senna',
    text: 'A sealed case goes north to Arbiter Senna at the Longwatch, $N: guild letters, and the guild does not use the post. Have Sutler Kevish sign for the freight when you arrive; his countersignature is the only receipt Senna accepts. Do not read the letters. That is not a warning, it is a professional courtesy.',
    completionText:
      'Seals intact, countersigned, and you did not read them; I would know. Isyra chooses her couriers well, $N. The Longwatch can always use hands that carry things and do not open them.',
    objectives: [
      {
        type: 'interact',
        targetNpcId: 'sutler_kevish',
        count: 1,
        label: 'Have Sutler Kevish sign for the case',
      },
    ],
    xpReward: 5000,
    copperReward: 2400,
    itemRewards: {},
    minLevel: 33,
  },
  q_veth_pine_line: {
    id: 'q_veth_pine_line',
    name: 'Holding the Pine Line',
    giverNpcId: 'waykeeper_dral',
    turnInNpcId: 'waykeeper_dral',
    text: 'The Frostpine warbands push the tree line south a spear-length every night, $N, and the rimeclaws hunt the gap they open. My road is in the gap. Twelve headhunters and eight cats, and the line goes back where the map says it is.',
    completionText:
      'The line holds at the map again. The trolls will redraw it, the cats will follow, and I will hire you twice more before the thaw, $N. That is not a complaint; it is a budget.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_headhunter',
        count: 12,
        label: 'Frostpine Headhunter slain',
      },
      { type: 'kill', targetMobId: 'rimeclaw_prowler', count: 8, label: 'Rimeclaw Prowler slain' },
    ],
    xpReward: 18400,
    copperReward: 6000,
    itemRewards: {},
    minLevel: 34,
  },
  q_veth_meat_for_the_line: {
    id: 'q_veth_meat_for_the_line',
    name: 'Meat for the Line',
    giverNpcId: 'sutler_kevish',
    turnInNpcId: 'sutler_kevish',
    text: 'Every guard on this watch eats twice a day or watches badly, $N, and the terraces grow nothing but ice and appetite. Rimeclaw haunch keeps on the cold shelf for a month. Ten cats thinned, eight haunches dressed. The irony that the watch eats what hunts it is not lost on me; it seasons the stew.',
    completionText:
      'Winter weight, well dressed. The line eats for a fortnight and owes you for all of it, $N. I run the only kitchen for forty miles; my gratitude is legal tender.',
    objectives: [
      { type: 'kill', targetMobId: 'rimeclaw_prowler', count: 10, label: 'Rimeclaw Prowler slain' },
      { type: 'collect', itemId: 'rimeclaw_haunch', count: 8, label: 'Rimeclaw Haunch' },
    ],
    xpReward: 18800,
    copperReward: 6200,
    itemRewards: {},
    minLevel: 35,
  },
  q_veth_rites_on_ice: {
    id: 'q_veth_rites_on_ice',
    name: 'Rites on the Ice',
    giverNpcId: 'waykeeper_dral',
    turnInNpcId: 'waykeeper_dral',
    text: 'The icecallers sing the rime down onto the terraces before a raid, $N, so the climb is glass by the time the spears come. Each rite hangs on a carved fetish; no fetish, no weather. Ten icecallers silenced, eight fetishes off their cords.',
    completionText:
      'Honest ice again, the kind that falls without being asked. Eight cancelled winters in eight fetishes, $N. The road thanks you; I speak for it.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_icecaller',
        count: 10,
        label: 'Frostpine Icecaller slain',
      },
      { type: 'collect', itemId: 'rimebound_fetish', count: 8, label: 'Rimebound Fetish' },
    ],
    xpReward: 19400,
    copperReward: 6400,
    itemRewards: {},
    requiresQuest: 'q_veth_pine_line',
    minLevel: 36,
  },
  q_veth_white_ledger: {
    id: 'q_veth_white_ledger',
    name: 'The White Ledger',
    giverNpcId: 'waykeeper_dral',
    turnInNpcId: 'waykeeper_dral',
    text: 'The north keeps its own ledger, $N, and it writes in white: every drift a debit, every thaw a payment deferred. This season the icecallers and the rimeclaws have overdrawn it. Twelve callers, ten cats. Balance the page.',
    completionText:
      'Balanced, for a value of balanced that lasts until the next hard frost. That is the only kind of balanced the north offers, $N, and I have learned to invoice accordingly.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_icecaller',
        count: 12,
        label: 'Frostpine Icecaller slain',
      },
      { type: 'kill', targetMobId: 'rimeclaw_prowler', count: 10, label: 'Rimeclaw Prowler slain' },
    ],
    xpReward: 20000,
    copperReward: 6600,
    itemRewards: {},
    requiresQuest: 'q_veth_rites_on_ice',
    minLevel: 37,
  },
  q_veth_high_ice: {
    id: 'q_veth_high_ice',
    name: 'The High Ice',
    giverNpcId: 'waykeeper_dral',
    turnInNpcId: 'waykeeper_dral',
    text: 'Above the terraces the ice stops pretending to be weather, $N. The high shelves belong to the old cats and the coldest of the callers, and they have begun coming down at dusk with a purpose I do not like. Twelve rimeclaws, ten icecallers, up where the ropes are. Rope in; the ledger does not cover falls.',
    completionText:
      'The dusk raids stop, the shelves go quiet, and the ropes come back with everyone who went up them. In the north that is a triumph, $N; I will file it as one.',
    objectives: [
      { type: 'kill', targetMobId: 'rimeclaw_prowler', count: 12, label: 'Rimeclaw Prowler slain' },
      {
        type: 'kill',
        targetMobId: 'frostpine_icecaller',
        count: 10,
        label: 'Frostpine Icecaller slain',
      },
    ],
    xpReward: 20800,
    copperReward: 6800,
    itemRewards: {},
    requiresQuest: 'q_veth_white_ledger',
    minLevel: 38,
  },
  q_veth_tallow_accounts: {
    id: 'q_veth_tallow_accounts',
    name: 'The Tallow Accounts',
    giverNpcId: 'sutler_kevish',
    turnInNpcId: 'sutler_kevish',
    text: 'Frostpine tallow burns slow and hateful, $N, and it is the only fat that keeps a lamp alive on the high terraces. The trolls render it for their war paint. Ten headhunters, eight jars of tallow, and the Longwatch lamps stay lit through the dark month.',
    completionText:
      'Slow, hateful, and lit: exactly as specified. The dark month can come when it likes now, $N. It will find the watch awake and the stew hot.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_headhunter',
        count: 10,
        label: 'Frostpine Headhunter slain',
      },
      { type: 'collect', itemId: 'frostpine_tallow', count: 8, label: 'Frostpine Tallow' },
    ],
    xpReward: 19400,
    copperReward: 6400,
    itemRewards: {},
    minLevel: 36,
  },
  q_veth_road_north: {
    id: 'q_veth_road_north',
    name: 'The Road North',
    giverNpcId: 'sutler_kevish',
    turnInNpcId: 'sutler_kevish',
    text: 'The Kael border post buys my surplus and sells me flour, $N, and this month the road between us is all rime-song and lodge steel. Commerce does not care whose knives they are. Twelve icecallers and six blades off the north mile, and the wagons roll before the flour riots do.',
    completionText:
      'The wagons crossed at dawn: flour south, tallow north, everyone overcharged, everyone content. That is peace, $N, as the border understands it.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'frostpine_icecaller',
        count: 12,
        label: 'Frostpine Icecaller slain',
      },
      { type: 'kill', targetMobId: 'forsworn_blade', count: 6, label: 'Forsworn Blade slain' },
    ],
    xpReward: 20800,
    copperReward: 6800,
    itemRewards: {},
    minLevel: 38,
  },
  q_veth_watch_the_lodge: {
    id: 'q_veth_watch_the_lodge',
    name: 'Watch the Lodge',
    giverNpcId: 'arbiter_senna',
    turnInNpcId: 'arbiter_senna',
    text: "Across the towpath stands the Last Lodge, $N, and Veykar's blades walk its bounds in pairs, in the old pattern, because he wrote the old pattern. Compare tallies with Waykeeper Dral before you start; his count of the patrols is better than mine, which offends me. Then remove ten blades from the rotation. Bring one knife you trust.",
    completionText:
      'Ten gaps in a pattern the lodge believes is perfect. Veykar will notice, and he will know it was not the guild, and that will bother him more than the losses. Good. Bothered men make errors, $N.',
    objectives: [
      {
        type: 'interact',
        targetNpcId: 'waykeeper_dral',
        count: 1,
        label: 'Compare tallies with Waykeeper Dral',
      },
      { type: 'kill', targetMobId: 'forsworn_blade', count: 10, label: 'Forsworn Blade slain' },
    ],
    xpReward: 19400,
    copperReward: 6400,
    itemRewards: {},
    suggestedPlayers: 2,
    minLevel: 36,
  },
  q_veth_oath_knives: {
    id: 'q_veth_oath_knives',
    name: 'The Oath Knives',
    giverNpcId: 'arbiter_senna',
    turnInNpcId: 'arbiter_senna',
    text: 'Every blade at the lodge still carries the oath knife the guild gave them, $N, which is theft: an oath returned means the knife comes home. Twelve more blades, eight knives recovered. The guild does not care that they are dead; it cares that the cutlery is accounted for.',
    completionText:
      'Eight knives, home to the drawer they swore on. Somewhere in the guild a list gets eight lines shorter, $N, and lists are the only scripture we keep.',
    objectives: [
      { type: 'kill', targetMobId: 'forsworn_blade', count: 12, label: 'Forsworn Blade slain' },
      { type: 'collect', itemId: 'forsworn_oath_knife', count: 8, label: 'Forsworn Oath Knife' },
    ],
    xpReward: 20000,
    copperReward: 6600,
    itemRewards: {},
    requiresQuest: 'q_veth_watch_the_lodge',
    suggestedPlayers: 2,
    minLevel: 37,
  },
  q_veth_ciphers_in_shadow: {
    id: 'q_veth_ciphers_in_shadow',
    name: 'Ciphers in Shadow',
    giverNpcId: 'arbiter_senna',
    turnInNpcId: 'arbiter_senna',
    text: "The lodge's ciphers were never written, $N; they were taught, and the shadowcasters are where they live. Veykar is selling them a syllable at a time to whoever pays. Ten casters, and eight of the cipher-slates they train against. What a man cannot remember alone, he cannot sell.",
    completionText:
      'Slates in the fire, casters in the ground, and a language dies solvent. There are perhaps four people alive who could mourn it, $N. None of them will.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'forsworn_shadowcaster',
        count: 10,
        label: 'Forsworn Shadowcaster slain',
      },
      { type: 'collect', itemId: 'shadowbound_cipher', count: 8, label: 'Shadowbound Cipher' },
    ],
    xpReward: 20800,
    copperReward: 6800,
    itemRewards: {},
    requiresQuest: 'q_veth_oath_knives',
    suggestedPlayers: 2,
    minLevel: 38,
  },
  q_veth_closing_the_lodge: {
    id: 'q_veth_closing_the_lodge',
    name: 'Closing the Lodge',
    giverNpcId: 'arbiter_senna',
    turnInNpcId: 'arbiter_senna',
    text: 'The lodge is guttering, $N: blades short-handed, casters hoarse, and Veykar pretending otherwise at the center of it. Put out the last of the light: ten blades, eight casters. When the perimeter is dark, the old man is just a name on a door, and Vael holds the contract for the door.',
    completionText:
      'Dark, then. The Last Lodge stands empty around one man and his ledger of grudges. What happens next is above my desk, $N, and for once I am glad of it. Take the boots; the towpath home is long.',
    objectives: [
      { type: 'kill', targetMobId: 'forsworn_blade', count: 10, label: 'Forsworn Blade slain' },
      {
        type: 'kill',
        targetMobId: 'forsworn_shadowcaster',
        count: 8,
        label: 'Forsworn Shadowcaster slain',
      },
    ],
    xpReward: 21400,
    copperReward: 7000,
    itemRewards: {
      warrior: 'lodgewalk_boots',
      mage: 'lodgewalk_boots',
      rogue: 'lodgewalk_boots',
    },
    requiresQuest: 'q_veth_ciphers_in_shadow',
    suggestedPlayers: 2,
    minLevel: 39,
  },
};

export const VETH_QUEST_ORDER = [
  // 20-25: Nighthollow and the south third
  'q_veth_quiet_introductions',
  'q_duskmane_hunt',
  'q_veth_pelt_lots',
  'q_veth_moth_lamps',
  'q_palewidow_silk',
  'q_veth_venom_ledger',
  'q_veth_verge_cull',
  'q_veth_towpath_census',
  'q_blackmere_ledgers',
  'q_veth_quay_manifests',
  'q_veth_silt_eels',
  'q_veth_palefang_price',
  'q_veth_wake_fees',
  // 26-31: the Blackmere, the Wispwood, the Greyweir toll-house
  'q_veth_wisp_essence',
  'q_veth_greyweir_posting',
  'q_veth_wispwood_cull',
  'q_veth_ferry_dues',
  'q_veth_drowned_tolls',
  'q_veth_lantern_motes',
  'q_veth_unlicensed_ferry',
  'q_veth_mere_bottom',
  'q_veth_weir_nets',
  'q_veth_forged_passes',
  'q_veth_stores_ledger',
  'q_guildless_debts',
  'q_veth_passage_sold',
  'q_veth_mere_charter',
  'q_veth_broken_contracts',
  'q_veth_knife_tax',
  'q_veth_turncoats_price',
  // 32-35: the Silent Court and the road north
  'q_silent_court',
  'q_veth_court_records',
  'q_veth_toll_scrip',
  'q_veth_adjourn_court',
  'q_veth_dead_letters',
  'q_veth_waystation_letters',
  'q_veth_totem_tally',
  'q_veth_pine_line',
  'q_veth_rimeclaw_pelts',
  'q_veth_meat_for_the_line',
  // 36-40: the Frostpine Terraces, the Longwatch, the Last Lodge
  'q_veth_terrace_sweep',
  'q_veth_rites_on_ice',
  'q_veth_tallow_accounts',
  'q_veth_watch_the_lodge',
  'q_veth_hoarbound_debt',
  'q_veth_white_ledger',
  'q_veth_oath_knives',
  'q_veth_ciphers_in_shadow',
  'q_veth_road_north',
  'q_veth_high_ice',
  'q_veth_closing_the_lodge',
  'q_forsworn_master',
];

// ---------------------------------------------------------------------------
// Camps (spawn tables), merged AFTER every existing camp in data.ts and after
// Ossara's, so world-gen RNG draw order for pre-existing content never shifts.
// Graded south (20) to north (40); existing camps re-leveled and moved IN
// PLACE (same order, same counts), new camps appended at the tail.
// ---------------------------------------------------------------------------

export const VETH_CAMPS: CampDef[] = [
  // Duskmane packs: the Run flanking the towpath south of Nighthollow
  { mobId: 'duskmane_stalker', center: { x: -60, z: 1330 }, radius: 22, count: 7 },
  { mobId: 'duskmane_stalker', center: { x: 45, z: 1340 }, radius: 20, count: 6 },
  { mobId: 'palefang_the_silent', center: { x: -85, z: 1318 }, radius: 5, count: 1 },
  // Palewidows: the hollows east of the towpath
  { mobId: 'palewidow_weaver', center: { x: 90, z: 1350 }, radius: 20, count: 8 },
  { mobId: 'palewidow_weaver', center: { x: 115, z: 1380 }, radius: 16, count: 6 },
  // Skulkers: the Quays wreckline, the mere's south bank, the south river bend
  { mobId: 'blackriver_skulker', center: { x: 55, z: 1385 }, radius: 16, count: 6 },
  { mobId: 'blackriver_skulker', center: { x: -70, z: 1440 }, radius: 16, count: 6 },
  { mobId: 'blackriver_skulker', center: { x: -30, z: 1348 }, radius: 16, count: 6 },
  // Feral wisps: the Wispwood, east of the lake
  { mobId: 'feral_wisp', center: { x: 80, z: 1480 }, radius: 20, count: 8 },
  { mobId: 'feral_wisp', center: { x: 105, z: 1510 }, radius: 16, count: 6 },
  // Guildless cutthroats: roadside ambush camps flanking the Greyweir
  { mobId: 'guildless_cutthroat', center: { x: -30, z: 1520 }, radius: 14, count: 5 },
  { mobId: 'guildless_cutthroat', center: { x: 62, z: 1540 }, radius: 14, count: 5 },
  // Revenants: the Silent Court, west bank
  { mobId: 'hollow_revenant', center: { x: -70, z: 1550 }, radius: 20, count: 8 },
  { mobId: 'hollow_revenant', center: { x: -95, z: 1575 }, radius: 16, count: 6 },
  // Frostpine trolls: the frozen terraces at the north edge
  { mobId: 'frostpine_headhunter', center: { x: 100, z: 1590 }, radius: 20, count: 8 },
  { mobId: 'frostpine_headhunter', center: { x: 130, z: 1620 }, radius: 16, count: 6 },
  { mobId: 'grelnok_the_hoarbound', center: { x: 145, z: 1645 }, radius: 5, count: 1 },
  // Veykar the Forsworn: the Last Lodge, northwest
  { mobId: 'veykar_the_forsworn', center: { x: -40, z: 1640 }, radius: 3, count: 1 },
  // Appended after every pre-existing Veth camp (world-gen RNG draw order):
  // the Blackmere drowned, the landing and the far shore
  { mobId: 'blackmere_drowned', center: { x: -95, z: 1452 }, radius: 16, count: 6 },
  { mobId: 'blackmere_drowned', center: { x: -68, z: 1492 }, radius: 16, count: 6 },
  // rimeclaw prowlers: the high ice above the terraces
  { mobId: 'rimeclaw_prowler', center: { x: 70, z: 1612 }, radius: 18, count: 6 },
  { mobId: 'rimeclaw_prowler', center: { x: 118, z: 1652 }, radius: 16, count: 6 },
  // --- 20-40 re-band camps, appended at the tail (world-gen RNG draw order) ---
  // twilight moths: Mothfall Verge, both sides of the south towpath
  { mobId: 'twilight_moth', center: { x: 58, z: 1318 }, radius: 18, count: 6 },
  { mobId: 'twilight_moth', center: { x: -35, z: 1312 }, radius: 16, count: 6 },
  // feralrun smugglers: the black waterway between the mere and the Greyweir
  { mobId: 'feralrun_smuggler', center: { x: -52, z: 1500 }, radius: 16, count: 6 },
  { mobId: 'feralrun_smuggler', center: { x: -18, z: 1476 }, radius: 14, count: 5 },
  { mobId: 'feralrun_smuggler', center: { x: 42, z: 1524 }, radius: 14, count: 5 },
  // Vessik the Turncoat: counts his coin on the east bank above the weir
  { mobId: 'vessik_the_turncoat', center: { x: 52, z: 1552 }, radius: 5, count: 1 },
  // Frostpine icecallers: the rime stairs above the terraces
  { mobId: 'frostpine_icecaller', center: { x: 88, z: 1642 }, radius: 14, count: 5 },
  { mobId: 'frostpine_icecaller', center: { x: 148, z: 1608 }, radius: 14, count: 5 },
  // the Last Lodge perimeter: Veykar's blades and shadowcasters, in pairs
  { mobId: 'forsworn_blade', center: { x: -58, z: 1626 }, radius: 13, count: 4 },
  { mobId: 'forsworn_blade', center: { x: -24, z: 1658 }, radius: 13, count: 4 },
  { mobId: 'forsworn_shadowcaster', center: { x: -62, z: 1652 }, radius: 12, count: 3 },
  { mobId: 'forsworn_shadowcaster', center: { x: -18, z: 1622 }, radius: 12, count: 3 },
];

// Every collect objective in this zone is satisfied by mob loot (questId drops),
// so the zone places no ground collectibles.
export const VETH_OBJECTS: GroundObjectDef[] = [];

// ---------------------------------------------------------------------------
// Items
// ---------------------------------------------------------------------------

export const VETH_ITEMS: Record<string, ItemDef> = {
  // --- quest items ---
  palewidow_silk: {
    id: 'palewidow_silk',
    name: 'Palewidow Silk',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_palewidow_silk',
  },
  waterlogged_ledger: {
    id: 'waterlogged_ledger',
    name: 'Waterlogged Ledger',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_blackmere_ledgers',
  },
  guildless_sigil: {
    id: 'guildless_sigil',
    name: 'Guildless Sigil',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_guildless_debts',
  },
  silent_court_seal: {
    id: 'silent_court_seal',
    name: 'Silent Court Seal',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_silent_court',
  },
  duskmane_pelt_strip: {
    id: 'duskmane_pelt_strip',
    name: 'Duskmane Pelt Strip',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_pelt_lots',
  },
  palewidow_venom_sac: {
    id: 'palewidow_venom_sac',
    name: 'Palewidow Venom Sac',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_venom_ledger',
  },
  quay_manifest: {
    id: 'quay_manifest',
    name: 'Sodden Quay Manifest',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_quay_manifests',
  },
  wisplight_essence: {
    id: 'wisplight_essence',
    name: 'Wisplight Essence',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_wisp_essence',
  },
  drowned_toll_coin: {
    id: 'drowned_toll_coin',
    name: 'Drowned Toll Coin',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_drowned_tolls',
  },
  cutthroat_contract: {
    id: 'cutthroat_contract',
    name: 'Cutthroat Contract',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_broken_contracts',
  },
  court_ledger_page: {
    id: 'court_ledger_page',
    name: 'Court Ledger Page',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_court_records',
  },
  frostpine_war_totem: {
    id: 'frostpine_war_totem',
    name: 'Frostpine War Totem',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_totem_tally',
  },
  rimeclaw_pelt: {
    id: 'rimeclaw_pelt',
    name: 'Rimeclaw Pelt',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_rimeclaw_pelts',
  },
  // --- junk / flavor drops ---
  duskmane_tuft: {
    id: 'duskmane_tuft',
    name: 'Duskmane Tuft',
    kind: 'junk',
    quality: 'poor',
    sellValue: 52,
  },
  guttering_wisp_mote: {
    id: 'guttering_wisp_mote',
    name: 'Guttering Wisp Mote',
    kind: 'junk',
    quality: 'poor',
    sellValue: 56,
  },
  frostpine_charm: {
    id: 'frostpine_charm',
    name: 'Frostpine Charm',
    kind: 'junk',
    quality: 'poor',
    sellValue: 60,
  },
  palefang_pelt: {
    id: 'palefang_pelt',
    name: 'Pelt of Palefang the Silent',
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 900,
  },
  grelnoks_frozen_idol: {
    id: 'grelnoks_frozen_idol',
    name: "Grelnok's Frozen Idol",
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 1300,
  },
  vessiks_little_book: {
    id: 'vessiks_little_book',
    name: "Vessik's Little Book",
    kind: 'junk',
    quality: 'uncommon',
    sellValue: 1150,
  },
  // --- vendor food / drink ---
  nighthollow_black_bread: {
    id: 'nighthollow_black_bread',
    name: 'Nighthollow Black Bread',
    kind: 'food',
    quality: 'common',
    foodHp: 1150,
    sellValue: 145,
    buyValue: 2350,
  },
  pinefrost_tea: {
    id: 'pinefrost_tea',
    name: 'Pinefrost Tea',
    kind: 'drink',
    quality: 'common',
    drinkMana: 1700,
    sellValue: 145,
    buyValue: 2350,
  },
  smoked_blackmere_eel: {
    id: 'smoked_blackmere_eel',
    name: 'Smoked Blackmere Eel',
    kind: 'food',
    quality: 'common',
    foodHp: 1350,
    sellValue: 195,
    buyValue: 3100,
  },
  // --- vendor armor ---
  wispweave_robe: {
    id: 'wispweave_robe',
    name: 'Wispweave Robe',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 78 },
    sellValue: 1150,
    buyValue: 11500,
  },
  quayguard_hauberk: {
    id: 'quayguard_hauberk',
    name: 'Quayguard Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 260 },
    sellValue: 1250,
    buyValue: 12500,
  },
  duskstalker_vest: {
    id: 'duskstalker_vest',
    name: 'Duskstalker Vest',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'common',
    stats: { armor: 148 },
    sellValue: 1200,
    buyValue: 12000,
  },
  // Cloth like zone3's ridgestalker_treads: the shared quest reward for all
  // three archetypes, so every class must be able to wear it.
  nightpath_treads: {
    id: 'nightpath_treads',
    name: 'Nightpath Treads',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 68, agi: 8, sta: 6 },
    sellValue: 1400,
    buyValue: 14000,
  },
  blackriver_legguards: {
    id: 'blackriver_legguards',
    name: 'Blackriver Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'common',
    stats: { armor: 222 },
    sellValue: 1250,
    buyValue: 12500,
  },
  // Cloth like nightpath_treads: the shared reward for the Hoarbound finale,
  // so all three archetypes must be able to wear it.
  terracewatch_leggings: {
    id: 'terracewatch_leggings',
    name: 'Terracewatch Leggings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'uncommon',
    stats: { armor: 80, sta: 12, agi: 10 },
    sellValue: 1800,
  },
  // --- vendor / reward weapons ---
  quays_cutlass: {
    id: 'quays_cutlass',
    name: 'Quays Cutlass',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'common',
    weapon: { min: 24, max: 38, speed: 2.4 },
    sellValue: 1150,
    buyValue: 11500,
  },
  wispcaller_staff: {
    id: 'wispcaller_staff',
    name: 'Wispcaller Staff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 34, max: 54, speed: 2.9 },
    stats: { int: 13, sta: 7 },
    sellValue: 1500,
    buyValue: 15000,
    requiredClass: ['mage', 'priest', 'warlock', 'druid', 'shaman'],
  },
  whispersteel_stiletto: {
    id: 'whispersteel_stiletto',
    name: 'Whispersteel Stiletto',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'uncommon',
    weapon: { min: 23, max: 37, speed: 1.8 },
    stats: { agi: 12 },
    sellValue: 1500,
    buyValue: 15000,
    requiredClass: ['rogue', 'hunter'],
  },
  // --- rare-elite / boss drops ---
  palefang_grips: {
    id: 'palefang_grips',
    name: 'Palefang Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'rare',
    stats: { armor: 80, agi: 9, sta: 7 },
    sellValue: 2600,
  },
  hoarbound_bindings: {
    id: 'hoarbound_bindings',
    name: 'Hoarbound Bindings',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'rare',
    stats: { armor: 60, int: 13, sta: 10 },
    sellValue: 3600,
  },
  forsworn_lamellar: {
    id: 'forsworn_lamellar',
    name: 'Forsworn Lamellar Cuirass',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'rare',
    stats: { armor: 380, str: 14, sta: 13 },
    sellValue: 4600,
  },
  forsworn_edge: {
    id: 'forsworn_edge',
    name: 'Forsworn Edge',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 40, max: 62, speed: 2.5 },
    stats: { str: 12, sta: 10 },
    sellValue: 4900,
  },
  // --- 20-40 re-band quest items (Greyweir and Longwatch chains) ---
  mothwing_dust: {
    id: 'mothwing_dust',
    name: 'Mothwing Dust',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_moth_lamps',
  },
  silt_eel: {
    id: 'silt_eel',
    name: 'Silt Eel',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_silt_eels',
  },
  barge_chit: {
    id: 'barge_chit',
    name: 'Waterlogged Barge Chit',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_ferry_dues',
  },
  ferry_lantern_mote: {
    id: 'ferry_lantern_mote',
    name: 'Ferry Lantern Mote',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_lantern_motes',
  },
  smugglers_tally_knot: {
    id: 'smugglers_tally_knot',
    name: "Smuggler's Tally Knot",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_unlicensed_ferry',
  },
  forged_weir_pass: {
    id: 'forged_weir_pass',
    name: 'Forged Weir Pass',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_forged_passes',
  },
  sunken_ration_tin: {
    id: 'sunken_ration_tin',
    name: 'Sunken Ration Tin',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_stores_ledger',
  },
  hollow_toll_scrip: {
    id: 'hollow_toll_scrip',
    name: 'Hollow Toll Scrip',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_toll_scrip',
  },
  rimeclaw_haunch: {
    id: 'rimeclaw_haunch',
    name: 'Rimeclaw Haunch',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_meat_for_the_line',
  },
  rimebound_fetish: {
    id: 'rimebound_fetish',
    name: 'Rimebound Fetish',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_rites_on_ice',
  },
  frostpine_tallow: {
    id: 'frostpine_tallow',
    name: 'Frostpine Tallow',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_tallow_accounts',
  },
  forsworn_oath_knife: {
    id: 'forsworn_oath_knife',
    name: 'Forsworn Oath Knife',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_oath_knives',
  },
  shadowbound_cipher: {
    id: 'shadowbound_cipher',
    name: 'Shadowbound Cipher',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_veth_ciphers_in_shadow',
  },
  // Cloth like nightpath_treads: shared quest rewards for all three
  // archetypes, so every class must be able to wear them.
  weirwatch_wraps: {
    id: 'weirwatch_wraps',
    name: 'Weirwatch Wraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'uncommon',
    stats: { armor: 58, agi: 9, sta: 8 },
    sellValue: 1600,
  },
  lodgewalk_boots: {
    id: 'lodgewalk_boots',
    name: 'Lodgewalk Boots',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'uncommon',
    stats: { armor: 82, agi: 12, sta: 11 },
    sellValue: 2100,
  },
};

// ---------------------------------------------------------------------------
// Static props (rendering + collision share this placement data). Nighthollow
// sits on the hub plateau; the Blackmere at (-90, 1470) stays clear.
// ---------------------------------------------------------------------------

export const VETH_PROPS: ZonePropsDef = {
  buildings: [
    { kind: 'house', x: 14, z: 1421, w: 7, d: 6, rot: -0.5 },
    { kind: 'house', x: 8, z: 1400, w: 6, d: 5, rot: 0.4 },
    { kind: 'house', x: 18, z: 1410, w: 6, d: 5, rot: 1.2 },
    { kind: 'inn', x: -15, z: 1416, w: 6, d: 7, rot: 0.6 }, // the Quiet Ledger
    { kind: 'chapel', x: -16, z: 1400, w: 5, d: 7, rot: 0.9 }, // shrine of the Agreement
    { kind: 'house', x: 20, z: 1537, w: 7, d: 6, rot: 0.3 }, // the Greyweir toll-house
    { kind: 'inn', x: 34, z: 1637, w: 6, d: 7, rot: -0.4 }, // the Longwatch waystation
  ],
  wells: [{ x: 0, z: 1412, r: 1.5 }],
  stalls: [
    { x: -7.5, z: 1417, rot: Math.PI / 2, r: 1.7 }, // Provisioner Maren
    { x: -4.5, z: 1423.5, rot: -0.6, r: 1.7 }, // Isyra Coldwater
    { x: 22.5, z: 1546, rot: -0.8, r: 1.7 }, // Toll Clerk Odune
    { x: 26, z: 1647, rot: 1.2, r: 1.7 }, // Sutler Kevish
  ],
  mines: [],
  docks: [
    // the Blackmere landing, where the black river widens into the lake
    { x: -72, z: 1462, rot: -2.2, hutLocal: { x: 2.8, z: 2.4, hw: 1.7, hd: 1.5 } },
    // the Greyweir weir landing, Ferrywoman Szel's crossing
    { x: 7, z: 1548, rot: 2.6, hutLocal: { x: 2.8, z: 2.4, hw: 1.7, hd: 1.5 } },
  ],
  tents: [
    // porter camp by the Blackwater Quays
    { x: 30, z: 1372, rot: 0.5, scale: 1 },
    { x: 36, z: 1367, rot: 2.0, scale: 1 },
    // cutthroat ambush bivouac off the north towpath
    { x: -12, z: 1508, rot: 1.5, scale: 1 },
    { x: -8, z: 1514, rot: -1.0, scale: 1 },
    // the Last Lodge outbuildings
    { x: -30, z: 1630, rot: 0.8, scale: 1.2 },
    { x: -24, z: 1636, rot: -0.5, scale: 1.2 },
    // the Longwatch picket tents
    { x: 27, z: 1633, rot: 0.7, scale: 1 },
    { x: 22, z: 1641, rot: -1.2, scale: 1 },
  ],
  crates: [
    [32, 1370],
    [-10, 1510],
    [-26, 1632],
    [17, 1542],
    [30, 1644],
  ],
  campfires: [
    [2, 1408],
    [33, 1369],
    [-11, 1512],
    [-27, 1634],
    [15, 1544],
    [30, 1639],
  ],
  mudHuts: [],
  ruinRings: [
    { x: -52, z: 1528, ringR: 7, columns: 6 }, // the Silent Court colonnade
    { x: 72, z: 1568, ringR: 6, columns: 5 }, // Frostpine Terraces, the fallen stair
    { x: -52, z: 1650, ringR: 6, columns: 5 }, // the Last Lodge boundary stones
  ],
  fences: [
    { x1: -14, z1: 1399, x2: -4, z2: 1397 }, // south gate, west run
    { x1: 4, z1: 1397, x2: 14, z2: 1399 }, // south gate, east run
  ],
  graveyards: [{ x: 18, z: 1395 }],
};
