// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  pxPerYd: 1.3333333333333333,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "23052a47"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "01b48fa8"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "4b6ba10a"
  },
  "veiled_hollow": {
    "w": 720,
    "h": 720,
    "rowHash": "4e10049a"
  },
  "drakelands": {
    "w": 640,
    "h": 800,
    "rowHash": "0296af91"
  },
  "frostveil": {
    "w": 693,
    "h": 693,
    "rowHash": "d6a920e4"
  },
  "amberfall": {
    "w": 613,
    "h": 746,
    "rowHash": "4c562364"
  },
  "willowfen": {
    "w": 587,
    "h": 694,
    "rowHash": "23f05e87"
  },
  "nightbloom": {
    "w": 613,
    "h": 746,
    "rowHash": "c462f192"
  },
  "wraithwood": {
    "w": 613,
    "h": 746,
    "rowHash": "b0dc3087"
  },
  "palmreach": {
    "w": 613,
    "h": 746,
    "rowHash": "c1c05ee5"
  },
  "evergarden": {
    "w": 613,
    "h": 746,
    "rowHash": "ca00c2e8"
  },
  "galecrest": {
    "w": 587,
    "h": 694,
    "rowHash": "e9bc5aaa"
  },
  "farshore_isle": {
    "w": 480,
    "h": 480,
    "rowHash": "16922e27"
  },
  "world_strip": {
    "w": 140,
    "h": 337,
    "rowHash": "eb5ef26f"
  }
},
} as const;
