// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with `npm run assets:mapbg` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: 20061,
  plateWidth: 480,
  hashRows: 16,
  zones: {
  "eastbrook_vale": {
    "w": 480,
    "h": 480,
    "rowHash": "c682c90f"
  },
  "mirefen_marsh": {
    "w": 480,
    "h": 480,
    "rowHash": "01b48fa8"
  },
  "thornpeak_heights": {
    "w": 480,
    "h": 480,
    "rowHash": "9e86b1e9"
  },
  "veiled_hollow": {
    "w": 480,
    "h": 720,
    "rowHash": "5b1dad40"
  },
  "drakelands": {
    "w": 480,
    "h": 800,
    "rowHash": "d7912be5"
  },
  "frostveil": {
    "w": 480,
    "h": 693,
    "rowHash": "435eb65f"
  },
  "amberfall": {
    "w": 480,
    "h": 747,
    "rowHash": "f54a6cc1"
  },
  "willowfen": {
    "w": 480,
    "h": 693,
    "rowHash": "4dcd71c9"
  },
  "nightbloom": {
    "w": 480,
    "h": 747,
    "rowHash": "b328f747"
  },
  "wraithwood": {
    "w": 480,
    "h": 747,
    "rowHash": "b9f90873"
  },
  "palmreach": {
    "w": 480,
    "h": 747,
    "rowHash": "54c125e0"
  },
  "evergarden": {
    "w": 480,
    "h": 747,
    "rowHash": "17a11c04"
  },
  "galecrest": {
    "w": 480,
    "h": 693,
    "rowHash": "77f67a2c"
  },
  "farshore_isle": {
    "w": 480,
    "h": 432,
    "rowHash": "27bae3a0"
  },
  "world_strip": {
    "w": 140,
    "h": 203,
    "rowHash": "1762ceef"
  }
},
} as const;
