// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BridgeAttachSessionReducer from "../bridge_attach_session_reducer";
import BridgeCloseSessionReducer from "../bridge_close_session_reducer";
import BridgeConsumeCommandReducer from "../bridge_consume_command_reducer";
import BridgePingReducer from "../bridge_ping_reducer";
import BridgePublishEventsReducer from "../bridge_publish_events_reducer";
import BridgePublishSnapshotReducer from "../bridge_publish_snapshot_reducer";
import BridgePublishSocialReducer from "../bridge_publish_social_reducer";
import BridgeSaveCharacterReducer from "../bridge_save_character_reducer";
import CommandReducer from "../command_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import DeleteCharacterReducer from "../delete_character_reducer";
import EnterWorldReducer from "../enter_world_reducer";
import LeaveWorldReducer from "../leave_world_reducer";
import ListCharactersReducer from "../list_characters_reducer";
import LoginReducer from "../login_reducer";
import RegisterReducer from "../register_reducer";
import RenameCharacterReducer from "../rename_character_reducer";
import ReportPlayerReducer from "../report_player_reducer";
import ReportPlayerByNameReducer from "../report_player_by_name_reducer";
import SetInputReducer from "../set_input_reducer";

export type BridgeAttachSessionParams = __Infer<typeof BridgeAttachSessionReducer>;
export type BridgeCloseSessionParams = __Infer<typeof BridgeCloseSessionReducer>;
export type BridgeConsumeCommandParams = __Infer<typeof BridgeConsumeCommandReducer>;
export type BridgePingParams = __Infer<typeof BridgePingReducer>;
export type BridgePublishEventsParams = __Infer<typeof BridgePublishEventsReducer>;
export type BridgePublishSnapshotParams = __Infer<typeof BridgePublishSnapshotReducer>;
export type BridgePublishSocialParams = __Infer<typeof BridgePublishSocialReducer>;
export type BridgeSaveCharacterParams = __Infer<typeof BridgeSaveCharacterReducer>;
export type CommandParams = __Infer<typeof CommandReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type DeleteCharacterParams = __Infer<typeof DeleteCharacterReducer>;
export type EnterWorldParams = __Infer<typeof EnterWorldReducer>;
export type LeaveWorldParams = __Infer<typeof LeaveWorldReducer>;
export type ListCharactersParams = __Infer<typeof ListCharactersReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RenameCharacterParams = __Infer<typeof RenameCharacterReducer>;
export type ReportPlayerParams = __Infer<typeof ReportPlayerReducer>;
export type ReportPlayerByNameParams = __Infer<typeof ReportPlayerByNameReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;

