// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import BridgeAddBlockReducer from "../bridge_add_block_reducer";
import BridgeAddFriendReducer from "../bridge_add_friend_reducer";
import BridgeAddGuildMemberReducer from "../bridge_add_guild_member_reducer";
import BridgeAttachSessionReducer from "../bridge_attach_session_reducer";
import BridgeClosePlaySessionReducer from "../bridge_close_play_session_reducer";
import BridgeCloseSessionReducer from "../bridge_close_session_reducer";
import BridgeConsumeCommandReducer from "../bridge_consume_command_reducer";
import BridgeCreateGuildReducer from "../bridge_create_guild_reducer";
import BridgeDeleteGuildReducer from "../bridge_delete_guild_reducer";
import BridgeInsertChatLogReducer from "../bridge_insert_chat_log_reducer";
import BridgeOpenPlaySessionReducer from "../bridge_open_play_session_reducer";
import BridgePingReducer from "../bridge_ping_reducer";
import BridgePublishEventsReducer from "../bridge_publish_events_reducer";
import BridgePublishSnapshotReducer from "../bridge_publish_snapshot_reducer";
import BridgePublishSocialReducer from "../bridge_publish_social_reducer";
import BridgeRemoveBlockReducer from "../bridge_remove_block_reducer";
import BridgeRemoveFriendReducer from "../bridge_remove_friend_reducer";
import BridgeRemoveGuildMemberReducer from "../bridge_remove_guild_member_reducer";
import BridgeSaveCharacterReducer from "../bridge_save_character_reducer";
import BridgeSaveWorldStateReducer from "../bridge_save_world_state_reducer";
import BridgeSetGuildRankReducer from "../bridge_set_guild_rank_reducer";
import CommandReducer from "../command_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import DeleteCharacterReducer from "../delete_character_reducer";
import EnterWorldReducer from "../enter_world_reducer";
import LeaveWorldReducer from "../leave_world_reducer";
import ListCharactersReducer from "../list_characters_reducer";
import LoginReducer from "../login_reducer";
import RegisterReducer from "../register_reducer";
import RenameCharacterReducer from "../rename_character_reducer";
import ReportPlayerReducer from "../report_player_reducer";
import ReportPlayerByNameReducer from "../report_player_by_name_reducer";
import SetInputReducer from "../set_input_reducer";

export type BridgeAddBlockParams = __Infer<typeof BridgeAddBlockReducer>;
export type BridgeAddFriendParams = __Infer<typeof BridgeAddFriendReducer>;
export type BridgeAddGuildMemberParams = __Infer<typeof BridgeAddGuildMemberReducer>;
export type BridgeAttachSessionParams = __Infer<typeof BridgeAttachSessionReducer>;
export type BridgeClosePlaySessionParams = __Infer<typeof BridgeClosePlaySessionReducer>;
export type BridgeCloseSessionParams = __Infer<typeof BridgeCloseSessionReducer>;
export type BridgeConsumeCommandParams = __Infer<typeof BridgeConsumeCommandReducer>;
export type BridgeCreateGuildParams = __Infer<typeof BridgeCreateGuildReducer>;
export type BridgeDeleteGuildParams = __Infer<typeof BridgeDeleteGuildReducer>;
export type BridgeInsertChatLogParams = __Infer<typeof BridgeInsertChatLogReducer>;
export type BridgeOpenPlaySessionParams = __Infer<typeof BridgeOpenPlaySessionReducer>;
export type BridgePingParams = __Infer<typeof BridgePingReducer>;
export type BridgePublishEventsParams = __Infer<typeof BridgePublishEventsReducer>;
export type BridgePublishSnapshotParams = __Infer<typeof BridgePublishSnapshotReducer>;
export type BridgePublishSocialParams = __Infer<typeof BridgePublishSocialReducer>;
export type BridgeRemoveBlockParams = __Infer<typeof BridgeRemoveBlockReducer>;
export type BridgeRemoveFriendParams = __Infer<typeof BridgeRemoveFriendReducer>;
export type BridgeRemoveGuildMemberParams = __Infer<typeof BridgeRemoveGuildMemberReducer>;
export type BridgeSaveCharacterParams = __Infer<typeof BridgeSaveCharacterReducer>;
export type BridgeSaveWorldStateParams = __Infer<typeof BridgeSaveWorldStateReducer>;
export type BridgeSetGuildRankParams = __Infer<typeof BridgeSetGuildRankReducer>;
export type CommandParams = __Infer<typeof CommandReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type DeleteCharacterParams = __Infer<typeof DeleteCharacterReducer>;
export type EnterWorldParams = __Infer<typeof EnterWorldReducer>;
export type LeaveWorldParams = __Infer<typeof LeaveWorldReducer>;
export type ListCharactersParams = __Infer<typeof ListCharactersReducer>;
export type LoginParams = __Infer<typeof LoginReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RenameCharacterParams = __Infer<typeof RenameCharacterReducer>;
export type ReportPlayerParams = __Infer<typeof ReportPlayerReducer>;
export type ReportPlayerByNameParams = __Infer<typeof ReportPlayerByNameReducer>;
export type SetInputParams = __Infer<typeof SetInputReducer>;

