import type { AffixDefinition, AffixTier, NumericRoll } from './types';

export const PROCEDURAL_STAT_BUDGET_COST: Record<string, number> = {
  str: 1,
  agi: 1,
  sta: 1,
  int: 1,
  spi: 0.85,
  spellPower: 0.65,
  critRating: 0.25,
  hasteRating: 0.28,
  hitRating: 0.32,
  armor: 0.08,
  healthOnKill: 0.5,
  manaOnKill: 0.5,
};

function tiers(
  stat: string,
  ranges: readonly [NumericRoll, NumericRoll, NumericRoll, NumericRoll],
): AffixTier[] {
  return [
    {
      tier: 1,
      minItemLevel: 1,
      budgetCost: PROCEDURAL_STAT_BUDGET_COST[stat],
      rolls: { [stat]: ranges[0] },
    },
    {
      tier: 2,
      minItemLevel: 6,
      budgetCost: PROCEDURAL_STAT_BUDGET_COST[stat],
      rolls: { [stat]: ranges[1] },
    },
    {
      tier: 3,
      minItemLevel: 12,
      budgetCost: PROCEDURAL_STAT_BUDGET_COST[stat],
      rolls: { [stat]: ranges[2] },
    },
    {
      tier: 4,
      minItemLevel: 18,
      budgetCost: PROCEDURAL_STAT_BUDGET_COST[stat],
      rolls: { [stat]: ranges[3] },
    },
  ];
}

export const PROCEDURAL_AFFIXES: Record<string, AffixDefinition> = {
  mighty: {
    id: 'mighty',
    family: 'primary.strength',
    position: 'prefix',
    displayName: 'Mighty',
    nameFragmentId: 'procedural.name.mighty',
    tags: ['melee'],
    minItemLevel: 1,
    weight: 1,
    tiers: tiers('str', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 6 },
      { min: 6, max: 9 },
    ]),
  },
  deft: {
    id: 'deft',
    family: 'primary.agility',
    position: 'prefix',
    displayName: 'Deft',
    nameFragmentId: 'procedural.name.deft',
    tags: ['melee', 'ranged'],
    minItemLevel: 1,
    weight: 1,
    tiers: tiers('agi', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 6 },
      { min: 6, max: 9 },
    ]),
  },
  stalwart: {
    id: 'stalwart',
    family: 'primary.stamina',
    position: 'prefix',
    displayName: 'Stalwart',
    nameFragmentId: 'procedural.name.stalwart',
    tags: ['armor', 'weapon', 'jewelry'],
    minItemLevel: 1,
    weight: 1.2,
    tiers: tiers('sta', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 7 },
      { min: 7, max: 10 },
    ]),
  },
  sages: {
    id: 'sages',
    family: 'primary.intellect',
    position: 'prefix',
    displayName: "Sage's",
    nameFragmentId: 'procedural.name.sages',
    tags: ['caster'],
    minItemLevel: 1,
    weight: 1,
    tiers: tiers('int', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 6 },
      { min: 6, max: 9 },
    ]),
  },
  spiritual: {
    id: 'spiritual',
    family: 'primary.spirit',
    position: 'prefix',
    displayName: 'Spiritual',
    nameFragmentId: 'procedural.name.spiritual',
    tags: ['caster'],
    minItemLevel: 1,
    weight: 0.85,
    tiers: tiers('spi', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 7 },
      { min: 7, max: 10 },
    ]),
  },
  focused: {
    id: 'focused',
    family: 'offense.spell_power',
    position: 'suffix',
    displayName: 'of Focus',
    nameFragmentId: 'procedural.name.of_focus',
    tags: ['caster'],
    minItemLevel: 4,
    weight: 0.9,
    tiers: tiers('spellPower', [
      { min: 1, max: 3 },
      { min: 3, max: 6 },
      { min: 6, max: 10 },
      { min: 10, max: 15 },
    ]),
  },
  striking: {
    id: 'striking',
    family: 'rating.crit',
    position: 'suffix',
    displayName: 'of Striking',
    nameFragmentId: 'procedural.name.of_striking',
    tags: ['armor', 'weapon', 'jewelry'],
    minItemLevel: 4,
    weight: 0.8,
    tiers: tiers('critRating', [
      { min: 2, max: 4 },
      { min: 4, max: 8 },
      { min: 8, max: 14 },
      { min: 14, max: 20 },
    ]),
  },
  alacrity: {
    id: 'alacrity',
    family: 'rating.haste',
    position: 'suffix',
    displayName: 'of Alacrity',
    nameFragmentId: 'procedural.name.of_alacrity',
    tags: ['armor', 'weapon', 'jewelry'],
    minItemLevel: 6,
    weight: 0.75,
    tiers: tiers('hasteRating', [
      { min: 2, max: 4 },
      { min: 4, max: 8 },
      { min: 8, max: 13 },
      { min: 13, max: 19 },
    ]),
  },
  precision: {
    id: 'precision',
    family: 'rating.hit',
    position: 'suffix',
    displayName: 'of Precision',
    nameFragmentId: 'procedural.name.of_precision',
    tags: ['armor', 'weapon', 'jewelry'],
    minItemLevel: 10,
    weight: 0.65,
    tiers: tiers('hitRating', [
      { min: 1, max: 3 },
      { min: 3, max: 6 },
      { min: 6, max: 11 },
      { min: 11, max: 16 },
    ]),
  },
  warded: {
    id: 'warded',
    family: 'defense.armor',
    position: 'prefix',
    displayName: 'Warded',
    nameFragmentId: 'procedural.name.warded',
    tags: ['armor'],
    excludedTags: ['jewelry'],
    minItemLevel: 1,
    weight: 0.75,
    tiers: tiers('armor', [
      { min: 4, max: 8 },
      { min: 8, max: 16 },
      { min: 16, max: 28 },
      { min: 28, max: 42 },
    ]),
  },
  reaping: {
    id: 'reaping',
    family: 'resource.health_on_kill',
    position: 'suffix',
    displayName: 'of Reaping',
    nameFragmentId: 'procedural.name.of_reaping',
    tags: ['melee', 'ranged'],
    minItemLevel: 8,
    weight: 0.35,
    tiers: tiers('healthOnKill', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 7 },
      { min: 7, max: 10 },
    ]),
  },
  remembrance: {
    id: 'remembrance',
    family: 'resource.mana_on_kill',
    position: 'suffix',
    displayName: 'of Remembrance',
    nameFragmentId: 'procedural.name.of_remembrance',
    tags: ['caster'],
    minItemLevel: 8,
    weight: 0.35,
    tiers: tiers('manaOnKill', [
      { min: 1, max: 2 },
      { min: 2, max: 4 },
      { min: 4, max: 7 },
      { min: 7, max: 10 },
    ]),
  },
};

export const PROCEDURAL_AFFIX_IDS = Object.freeze(Object.keys(PROCEDURAL_AFFIXES));
