import type { ArmorType, ItemSlot, PlayerClass } from '../../types';
import type { ProceduralItemBase } from './types';

const MARTIAL_CLASSES: PlayerClass[] = ['warrior', 'rogue', 'hunter', 'shaman', 'paladin'];
const ROGUE_CLASSES: PlayerClass[] = ['rogue', 'hunter'];
const CASTER_CLASSES: PlayerClass[] = ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'];
const MARTIAL_TWO_HAND_CLASSES: PlayerClass[] = ['warrior', 'paladin', 'hunter', 'shaman'];
const HUNTER_CLASSES: PlayerClass[] = ['hunter'];
const MAIL_CLASSES: PlayerClass[] = ['warrior', 'paladin', 'shaman'];

const ARMOR_PER_LEVEL: Record<ArmorType, number> = {
  cloth: 2.5,
  leather: 3.2,
  mail: 5.14,
};

function armorBase(input: {
  id: string;
  name: string;
  slot: Exclude<ItemSlot, 'mainhand' | 'offhand' | 'neck' | 'ring' | 'ring1' | 'ring2'>;
  armorType: ArmorType;
  sourceLevel: number;
  slotMultiplier: number;
  tags: ProceduralItemBase['tags'];
}): ProceduralItemBase {
  return {
    ...input,
    kind: 'armor',
    baseArmor: Math.round(
      input.sourceLevel * ARMOR_PER_LEVEL[input.armorType] * input.slotMultiplier,
    ),
    visualItemId: input.id,
    dropWeight: 18,
  };
}

export const PROCEDURAL_LOOT_CONTENT_REVISION = 2;

export const PROCEDURAL_ITEM_BASES: Record<string, ProceduralItemBase> = {
  // Keep the original six ids first so forced-base saves and the authored first-slice
  // fixtures remain easy to audit. Newly added families append below them.
  iron_broadsword: {
    id: 'iron_broadsword',
    name: 'Iron Broadsword',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'onehand',
    requiredClass: MARTIAL_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 2.4, damageSpread: 0.22 },
    weaponType: 'sword',
    tags: ['weapon', 'melee', 'onehand'],
    visualItemId: 'iron_broadsword',
    weaponVisualId: 'sword_b',
    slotMultiplier: 1,
    dropWeight: 42,
  },
  ashwood_staff: {
    id: 'ashwood_staff',
    name: 'Ashwood Staff',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    requiredClass: CASTER_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 3, damageSpread: 0.18 },
    weaponType: 'staff',
    tags: ['weapon', 'caster', 'twohand'],
    visualItemId: 'ashwood_staff',
    weaponVisualId: 'staff_b',
    slotMultiplier: 1.3,
    dropWeight: 42,
  },
  mirefen_leather_gloves: armorBase({
    id: 'mirefen_leather_gloves',
    name: 'Mirefen Leather Gloves',
    slot: 'gloves',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 0.7,
    tags: ['armor', 'leather', 'light_slot', 'melee', 'ranged', 'caster'],
  }),
  thornpeak_mail_chest: armorBase({
    id: 'thornpeak_mail_chest',
    name: 'Thornpeak Mail Chest',
    slot: 'chest',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 1,
    tags: ['armor', 'mail', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  gravecaller_cloth_hood: armorBase({
    id: 'gravecaller_cloth_hood',
    name: 'Gravecaller Cloth Hood',
    slot: 'helmet',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 0.85,
    tags: ['armor', 'cloth', 'heavy_slot', 'caster'],
  }),
  gravecaller_ring: {
    id: 'gravecaller_ring',
    name: 'Gravecaller Ring',
    kind: 'armor',
    slot: 'ring',
    sourceLevel: 18,
    tags: ['armor', 'jewelry', 'caster', 'melee', 'ranged', 'light_slot'],
    visualItemId: 'gravecaller_ring',
    slotMultiplier: 0.6,
    dropWeight: 63,
  },

  gravecaller_cloth_mantle: armorBase({
    id: 'gravecaller_cloth_mantle',
    name: 'Gravecaller Cloth Mantle',
    slot: 'shoulder',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 0.75,
    tags: ['armor', 'cloth', 'heavy_slot', 'caster'],
  }),
  gravecaller_cloth_raiment: armorBase({
    id: 'gravecaller_cloth_raiment',
    name: 'Gravecaller Cloth Raiment',
    slot: 'chest',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 1,
    tags: ['armor', 'cloth', 'heavy_slot', 'caster'],
  }),
  gravecaller_cloth_sash: armorBase({
    id: 'gravecaller_cloth_sash',
    name: 'Gravecaller Cloth Sash',
    slot: 'waist',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 0.7,
    tags: ['armor', 'cloth', 'light_slot', 'caster'],
  }),
  gravecaller_cloth_leggings: armorBase({
    id: 'gravecaller_cloth_leggings',
    name: 'Gravecaller Cloth Leggings',
    slot: 'legs',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 0.9,
    tags: ['armor', 'cloth', 'heavy_slot', 'caster'],
  }),
  gravecaller_cloth_handwraps: armorBase({
    id: 'gravecaller_cloth_handwraps',
    name: 'Gravecaller Cloth Handwraps',
    slot: 'gloves',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 0.7,
    tags: ['armor', 'cloth', 'light_slot', 'caster'],
  }),
  gravecaller_cloth_slippers: armorBase({
    id: 'gravecaller_cloth_slippers',
    name: 'Gravecaller Cloth Slippers',
    slot: 'feet',
    armorType: 'cloth',
    sourceLevel: 16,
    slotMultiplier: 0.65,
    tags: ['armor', 'cloth', 'light_slot', 'caster'],
  }),

  mirefen_leather_hood: armorBase({
    id: 'mirefen_leather_hood',
    name: 'Mirefen Leather Hood',
    slot: 'helmet',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 0.85,
    tags: ['armor', 'leather', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  mirefen_leather_shoulderguards: armorBase({
    id: 'mirefen_leather_shoulderguards',
    name: 'Mirefen Leather Shoulderguards',
    slot: 'shoulder',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 0.75,
    tags: ['armor', 'leather', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  mirefen_leather_jerkin: armorBase({
    id: 'mirefen_leather_jerkin',
    name: 'Mirefen Leather Jerkin',
    slot: 'chest',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 1,
    tags: ['armor', 'leather', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  mirefen_leather_belt: armorBase({
    id: 'mirefen_leather_belt',
    name: 'Mirefen Leather Belt',
    slot: 'waist',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 0.7,
    tags: ['armor', 'leather', 'light_slot', 'melee', 'ranged', 'caster'],
  }),
  mirefen_leather_leggings: armorBase({
    id: 'mirefen_leather_leggings',
    name: 'Mirefen Leather Leggings',
    slot: 'legs',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 0.9,
    tags: ['armor', 'leather', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  mirefen_leather_boots: armorBase({
    id: 'mirefen_leather_boots',
    name: 'Mirefen Leather Boots',
    slot: 'feet',
    armorType: 'leather',
    sourceLevel: 8,
    slotMultiplier: 0.65,
    tags: ['armor', 'leather', 'light_slot', 'melee', 'ranged', 'caster'],
  }),

  thornpeak_mail_helm: armorBase({
    id: 'thornpeak_mail_helm',
    name: 'Thornpeak Mail Helm',
    slot: 'helmet',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 0.85,
    tags: ['armor', 'mail', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  thornpeak_mail_pauldrons: armorBase({
    id: 'thornpeak_mail_pauldrons',
    name: 'Thornpeak Mail Pauldrons',
    slot: 'shoulder',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 0.75,
    tags: ['armor', 'mail', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  thornpeak_mail_girdle: armorBase({
    id: 'thornpeak_mail_girdle',
    name: 'Thornpeak Mail Girdle',
    slot: 'waist',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 0.7,
    tags: ['armor', 'mail', 'light_slot', 'melee', 'ranged', 'caster'],
  }),
  thornpeak_mail_legguards: armorBase({
    id: 'thornpeak_mail_legguards',
    name: 'Thornpeak Mail Legguards',
    slot: 'legs',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 0.9,
    tags: ['armor', 'mail', 'heavy_slot', 'melee', 'ranged', 'caster'],
  }),
  thornpeak_mail_gauntlets: armorBase({
    id: 'thornpeak_mail_gauntlets',
    name: 'Thornpeak Mail Gauntlets',
    slot: 'gloves',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 0.7,
    tags: ['armor', 'mail', 'light_slot', 'melee', 'ranged', 'caster'],
  }),
  thornpeak_mail_sabatons: armorBase({
    id: 'thornpeak_mail_sabatons',
    name: 'Thornpeak Mail Sabatons',
    slot: 'feet',
    armorType: 'mail',
    sourceLevel: 14,
    slotMultiplier: 0.65,
    tags: ['armor', 'mail', 'light_slot', 'melee', 'ranged', 'caster'],
  }),

  thornpeak_war_axe: {
    id: 'thornpeak_war_axe',
    name: 'Thornpeak War Axe',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'onehand',
    requiredClass: MARTIAL_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 2.6, damageSpread: 0.24 },
    weaponType: 'axe',
    tags: ['weapon', 'melee', 'onehand'],
    visualItemId: 'thornpeak_war_axe',
    weaponVisualId: 'axe_b',
    slotMultiplier: 1,
    dropWeight: 42,
  },
  iron_flanged_mace: {
    id: 'iron_flanged_mace',
    name: 'Iron Flanged Mace',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'onehand',
    requiredClass: MARTIAL_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 2.5, damageSpread: 0.2 },
    weaponType: 'mace',
    tags: ['weapon', 'melee', 'onehand'],
    visualItemId: 'iron_flanged_mace',
    weaponVisualId: 'hammer_b',
    slotMultiplier: 1,
    dropWeight: 42,
  },
  mirefen_dirk: {
    id: 'mirefen_dirk',
    name: 'Mirefen Dirk',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'onehand',
    requiredClass: ROGUE_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 1.7, damageSpread: 0.16 },
    weaponType: 'dagger',
    dagger: true,
    tags: ['weapon', 'melee', 'onehand'],
    visualItemId: 'mirefen_dirk',
    weaponVisualId: 'dagger_b',
    slotMultiplier: 1,
    dropWeight: 42,
  },
  gravecaller_wand: {
    id: 'gravecaller_wand',
    name: 'Gravecaller Wand',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'onehand',
    requiredClass: CASTER_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 1.8, damageSpread: 0.14 },
    weaponType: 'wand',
    tags: ['weapon', 'caster', 'onehand'],
    visualItemId: 'gravecaller_wand',
    weaponVisualId: 'wand_a',
    slotMultiplier: 1,
    dropWeight: 42,
  },
  thornpeak_polearm: {
    id: 'thornpeak_polearm',
    name: 'Thornpeak Polearm',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    requiredClass: MARTIAL_TWO_HAND_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 3.2, damageSpread: 0.23 },
    weaponType: 'polearm',
    tags: ['weapon', 'melee', 'twohand'],
    visualItemId: 'thornpeak_polearm',
    weaponVisualId: 'spear_a',
    slotMultiplier: 1.3,
    dropWeight: 42,
  },
  mirefen_hunting_bow: {
    id: 'mirefen_hunting_bow',
    name: 'Mirefen Hunting Bow',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    requiredClass: HUNTER_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 2.8, damageSpread: 0.2 },
    weaponType: 'bow',
    tags: ['weapon', 'ranged', 'twohand'],
    visualItemId: 'mirefen_hunting_bow',
    weaponVisualId: 'fletcher_s_guild_bow',
    slotMultiplier: 1.3,
    dropWeight: 42,
  },
  thornpeak_crossbow: {
    id: 'thornpeak_crossbow',
    name: 'Thornpeak Crossbow',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    requiredClass: HUNTER_CLASSES,
    sourceLevel: 5,
    baseWeapon: { speed: 3, damageSpread: 0.22 },
    weaponType: 'crossbow',
    tags: ['weapon', 'ranged', 'twohand'],
    visualItemId: 'thornpeak_crossbow',
    weaponVisualId: 'simple_farmhand_crossbow',
    slotMultiplier: 1.3,
    dropWeight: 42,
  },

  gravecaller_pendant: {
    id: 'gravecaller_pendant',
    name: 'Gravecaller Pendant',
    kind: 'armor',
    slot: 'neck',
    sourceLevel: 18,
    tags: ['armor', 'jewelry', 'caster', 'melee', 'ranged', 'light_slot'],
    visualItemId: 'gravecaller_pendant',
    slotMultiplier: 0.65,
    dropWeight: 31,
  },
  thornpeak_bulwark: {
    id: 'thornpeak_bulwark',
    name: 'Thornpeak Bulwark',
    kind: 'armor',
    slot: 'offhand',
    armorType: 'mail',
    requiredClass: MAIL_CLASSES,
    sourceLevel: 14,
    baseArmor: 144,
    baseBlockValue: 10,
    shield: true,
    tags: ['armor', 'shield', 'mail', 'melee', 'caster', 'heavy_slot'],
    visualItemId: 'thornpeak_bulwark',
    slotMultiplier: 0.75,
    dropWeight: 47,
  },
  gravecaller_focus: {
    id: 'gravecaller_focus',
    name: 'Gravecaller Focus',
    kind: 'held_offhand',
    slot: 'offhand',
    requiredClass: CASTER_CLASSES,
    sourceLevel: 16,
    tags: ['held_offhand', 'caster', 'light_slot'],
    visualItemId: 'gravecaller_focus',
    slotMultiplier: 0.75,
    dropWeight: 47,
  },
};

export const PROCEDURAL_BASE_IDS = Object.freeze(Object.keys(PROCEDURAL_ITEM_BASES));
