import type { ProceduralItemBase } from './types';

export const PROCEDURAL_ITEM_BASES: Record<string, ProceduralItemBase> = {
  iron_broadsword: {
    id: 'iron_broadsword',
    name: 'Iron Broadsword',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'onehand',
    requiredClass: ['warrior', 'paladin', 'rogue'],
    sourceLevel: 5,
    baseWeapon: { speed: 2.4, damageSpread: 0.22 },
    tags: ['weapon', 'melee', 'onehand'],
    visualItemId: 'worn_sword',
    weaponVisualId: 'sword_a',
    slotMultiplier: 1.15,
  },
  ashwood_staff: {
    id: 'ashwood_staff',
    name: 'Ashwood Staff',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    requiredClass: ['mage', 'priest', 'warlock', 'druid', 'shaman'],
    sourceLevel: 5,
    baseWeapon: { speed: 3, damageSpread: 0.18 },
    tags: ['weapon', 'caster', 'twohand'],
    visualItemId: 'gnarled_staff',
    weaponVisualId: 'staff_a',
    slotMultiplier: 1.75,
  },
  mirefen_leather_gloves: {
    id: 'mirefen_leather_gloves',
    name: 'Mirefen Leather Gloves',
    kind: 'armor',
    slot: 'gloves',
    armorType: 'leather',
    requiredClass: ['hunter', 'rogue', 'druid'],
    sourceLevel: 8,
    baseArmor: 18,
    tags: ['armor', 'leather', 'light_slot', 'melee', 'ranged'],
    visualItemId: 'roughspun_gloves',
    slotMultiplier: 0.65,
  },
  thornpeak_mail_chest: {
    id: 'thornpeak_mail_chest',
    name: 'Thornpeak Mail Chest',
    kind: 'armor',
    slot: 'chest',
    armorType: 'mail',
    requiredClass: ['warrior', 'paladin', 'hunter', 'shaman'],
    sourceLevel: 14,
    baseArmor: 72,
    tags: ['armor', 'mail', 'heavy_slot', 'melee', 'ranged'],
    visualItemId: 'militia_vest',
    slotMultiplier: 1,
  },
  gravecaller_cloth_hood: {
    id: 'gravecaller_cloth_hood',
    name: 'Gravecaller Cloth Hood',
    kind: 'armor',
    slot: 'helmet',
    armorType: 'cloth',
    requiredClass: ['mage', 'priest', 'warlock'],
    sourceLevel: 16,
    baseArmor: 34,
    tags: ['armor', 'cloth', 'heavy_slot', 'caster'],
    visualItemId: 'wayfarers_hood',
    slotMultiplier: 0.85,
  },
  gravecaller_ring: {
    id: 'gravecaller_ring',
    name: 'Gravecaller Ring',
    kind: 'armor',
    slot: 'ring',
    sourceLevel: 18,
    tags: ['armor', 'jewelry', 'caster', 'melee', 'ranged', 'light_slot'],
    visualItemId: 'seal_of_the_nine_oaths',
    slotMultiplier: 0.55,
  },
};

export const PROCEDURAL_BASE_IDS = Object.freeze(Object.keys(PROCEDURAL_ITEM_BASES));
