// GENERATED by scripts/gen_decals.mjs -- do not edit by hand.
//
// The built-in ground-decal library: every image under public/textures/decals/
// is drawn by that script from shape math and hash noise (original work, no
// third-party assets). Re-run `node scripts/gen_decals.mjs` after editing a
// recipe there.

export type DecalCategory = 'arcane' | 'burn' | 'damage' | 'gore' | 'nature' | 'tracks' | 'marker';

export interface DecalDef {
  /** File stem under public/textures/decals/ and the id half of `builtin:<key>`. */
  key: string;
  /** Display name (editor UI is English-only; see the i18n deferral note). */
  name: string;
  category: DecalCategory;
  /** Default stamp footprint in yards (diameter). */
  size: number;
  /** Default emissive strength 0..1 (magic circles read as lit). */
  glow?: number;
  /** Default tint (0xRRGGBB) multiplied into the art; absent = untinted. */
  tint?: number;
  /** Encoded size in bytes, for the budget report. */
  bytes: number;
}

export const DECAL_LIBRARY: readonly DecalDef[] = [
  { key: 'pentagram', name: 'Pentagram', category: 'arcane', size: 10, glow: 0.35, tint: 0xd94f4f, bytes: 78814 },
  { key: 'summon_circle', name: 'Summoning Circle', category: 'arcane', size: 12, glow: 0.45, tint: 0x7f6bff, bytes: 58658 },
  { key: 'rune_circle', name: 'Rune Circle', category: 'arcane', size: 8, glow: 0.4, tint: 0x59c6ff, bytes: 40086 },
  { key: 'hexagram', name: 'Hexagram Seal', category: 'arcane', size: 10, glow: 0.4, tint: 0xffc857, bytes: 23916 },
  { key: 'ward_seal', name: 'Ward Seal', category: 'arcane', size: 9, glow: 0.3, tint: 0x8fe3c1, bytes: 8072 },
  { key: 'teleport_pad', name: 'Teleport Pad', category: 'arcane', size: 7, glow: 0.55, tint: 0x69f0ff, bytes: 18406 },
  { key: 'blood_rune', name: 'Blood Rune', category: 'arcane', size: 6, glow: 0.15, tint: 0xa11d1d, bytes: 18334 },
  { key: 'blast_scorch', name: 'Blast Scorch', category: 'burn', size: 8, bytes: 39896 },
  { key: 'impact_crater', name: 'Impact Crater', category: 'burn', size: 12, bytes: 51202 },
  { key: 'scorch_streak', name: 'Scorch Streak', category: 'burn', size: 9, bytes: 18864 },
  { key: 'ash_burst', name: 'Ash Burst', category: 'burn', size: 7, bytes: 86698 },
  { key: 'crack_star', name: 'Ground Fracture', category: 'damage', size: 9, bytes: 14418 },
  { key: 'crack_web', name: 'Crazed Cracks', category: 'damage', size: 7, bytes: 20740 },
  { key: 'claw_marks', name: 'Claw Marks', category: 'damage', size: 5, bytes: 15104 },
  { key: 'shrapnel_pocks', name: 'Shrapnel Pocks', category: 'damage', size: 6, bytes: 8626 },
  { key: 'blood_pool', name: 'Blood Pool', category: 'gore', size: 4, bytes: 14714 },
  { key: 'blood_splatter', name: 'Blood Splatter', category: 'gore', size: 5, bytes: 14512 },
  { key: 'blood_drag', name: 'Drag Smear', category: 'gore', size: 7, bytes: 23260 },
  { key: 'moss_patch', name: 'Moss Patch', category: 'nature', size: 6, bytes: 49172 },
  { key: 'puddle', name: 'Puddle', category: 'nature', size: 5, bytes: 10024 },
  { key: 'mud_splat', name: 'Mud Splat', category: 'nature', size: 5, bytes: 53012 },
  { key: 'dirt_wear', name: 'Worn Dirt', category: 'nature', size: 8, bytes: 37618 },
  { key: 'gravel_scatter', name: 'Gravel Scatter', category: 'nature', size: 6, bytes: 17878 },
  { key: 'leaf_litter', name: 'Leaf Litter', category: 'nature', size: 6, bytes: 15366 },
  { key: 'sand_drift', name: 'Sand Drift', category: 'nature', size: 9, bytes: 19546 },
  { key: 'snow_drift', name: 'Snow Drift', category: 'nature', size: 9, bytes: 30156 },
  { key: 'oil_stain', name: 'Oil Stain', category: 'nature', size: 5, bytes: 42516 },
  { key: 'boot_prints', name: 'Boot Prints', category: 'tracks', size: 4, bytes: 10018 },
  { key: 'paw_prints', name: 'Beast Tracks', category: 'tracks', size: 4, bytes: 12468 },
  { key: 'wagon_ruts', name: 'Wagon Ruts', category: 'tracks', size: 10, bytes: 15628 },
  { key: 'arrow_marker', name: 'Arrow Marker', category: 'marker', size: 5, glow: 0.2, tint: 0xffd166, bytes: 1920 },
  { key: 'hazard_ring', name: 'Hazard Ring', category: 'marker', size: 8, glow: 0.25, tint: 0xff7043, bytes: 10250 },
  { key: 'campfire_soot', name: 'Campfire Scar', category: 'burn', size: 4, bytes: 50354 },
];

export const DECAL_CATEGORY_ORDER: readonly DecalCategory[] = [
  'arcane',
  'burn',
  'damage',
  'gore',
  'nature',
  'tracks',
  'marker',
];
