// GENERATED by scripts/assets/build_leaf_atlas.mjs - do not edit by hand.
// The painted leaf-card atlases the Tree Generator scatters over its canopy
// volumes. Every sheet is 4x2 cards of 256px. A card's stalk meets the
// anchor edge of its cell at u = 0.5, which is where the leaf quad's pivot
// sits, so leaves swing around their stalk instead of their middle.

export type LeafAnchor = 'bottom' | 'top';

export interface LeafSet {
  /** File key: public/textures/foliage/leaves/<key>.png */
  key: string;
  /** Maker-facing name in the Tree panel. */
  label: string;
  /** Shape family (sets sharing a shape differ only in palette). */
  shape: string;
  palette: string;
  /** Which cell edge the stalk meets: upright sprigs 'bottom', hanging
   *  strands 'top' (the quad is built hanging DOWN from its pivot). */
  anchor: LeafAnchor;
  /** Advisory: which biome groups the picker files this under. */
  biomes: readonly string[];
  /** The bright parts should also drive an emissive map (magic/fire sets). */
  glow: boolean;
  /** Fraction of the sheet that survives the alpha cutout (density tuning). */
  coverage: number;
}

export const LEAF_ATLAS_COLS = 4;
export const LEAF_ATLAS_ROWS = 2;
export const LEAF_ATLAS_CELLS = 8;

export const LEAF_SETS: readonly LeafSet[] = [
  {
    key: 'broadleaf',
    label: 'Broadleaf',
    shape: 'broadleaf',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.331,
  },
  {
    key: 'broadleaf_spring',
    label: 'Broadleaf (Spring)',
    shape: 'broadleaf',
    palette: 'spring',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.331,
  },
  {
    key: 'broadleaf_autumn',
    label: 'Broadleaf (Autumn)',
    shape: 'broadleaf',
    palette: 'autumn',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.331,
  },
  {
    key: 'broadleaf_dark',
    label: 'Broadleaf (Dark)',
    shape: 'broadleaf',
    palette: 'dark',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.331,
  },
  {
    key: 'broadleaf_arcane',
    label: 'Broadleaf (Arcane)',
    shape: 'broadleaf',
    palette: 'arcane',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: true,
    coverage: 0.331,
  },
  {
    key: 'broadleaf_ember',
    label: 'Broadleaf (Ember)',
    shape: 'broadleaf',
    palette: 'ember',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: true,
    coverage: 0.331,
  },
  {
    key: 'oak',
    label: 'Oak',
    shape: 'oak',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.329,
  },
  {
    key: 'oak_autumn',
    label: 'Oak (Autumn)',
    shape: 'oak',
    palette: 'autumn',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.329,
  },
  {
    key: 'oak_dark',
    label: 'Oak (Dark)',
    shape: 'oak',
    palette: 'dark',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.329,
  },
  {
    key: 'birch',
    label: 'Birch',
    shape: 'birch',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.286,
  },
  {
    key: 'birch_spring',
    label: 'Birch (Spring)',
    shape: 'birch',
    palette: 'spring',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.286,
  },
  {
    key: 'birch_autumn',
    label: 'Birch (Autumn)',
    shape: 'birch',
    palette: 'autumn',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.286,
  },
  {
    key: 'maple',
    label: 'Maple',
    shape: 'maple',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.394,
  },
  {
    key: 'maple_autumn',
    label: 'Maple (Autumn)',
    shape: 'maple',
    palette: 'autumn',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: false,
    coverage: 0.394,
  },
  {
    key: 'maple_ember',
    label: 'Maple (Ember)',
    shape: 'maple',
    palette: 'ember',
    anchor: 'bottom',
    biomes: ['forest', 'standard'],
    glow: true,
    coverage: 0.394,
  },
  {
    key: 'willow',
    label: 'Willow',
    shape: 'willow',
    palette: 'summer',
    anchor: 'top',
    biomes: ['forest', 'magic'],
    glow: false,
    coverage: 0.175,
  },
  {
    key: 'willow_autumn',
    label: 'Willow (Autumn)',
    shape: 'willow',
    palette: 'autumn',
    anchor: 'top',
    biomes: ['forest', 'magic'],
    glow: false,
    coverage: 0.175,
  },
  {
    key: 'willow_arcane',
    label: 'Willow (Arcane)',
    shape: 'willow',
    palette: 'arcane',
    anchor: 'top',
    biomes: ['forest', 'magic'],
    glow: true,
    coverage: 0.175,
  },
  {
    key: 'needle',
    label: 'Conifer',
    shape: 'needle',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['forest', 'standard', 'dark'],
    glow: false,
    coverage: 0.09,
  },
  {
    key: 'needle_dry',
    label: 'Conifer (Dry)',
    shape: 'needle',
    palette: 'dry',
    anchor: 'bottom',
    biomes: ['forest', 'standard', 'dark'],
    glow: false,
    coverage: 0.09,
  },
  {
    key: 'needle_dark',
    label: 'Conifer (Dark)',
    shape: 'needle',
    palette: 'dark',
    anchor: 'bottom',
    biomes: ['forest', 'standard', 'dark'],
    glow: false,
    coverage: 0.09,
  },
  {
    key: 'frond',
    label: 'Palm frond',
    shape: 'frond',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['tropical', 'desert'],
    glow: false,
    coverage: 0.303,
  },
  {
    key: 'frond_dry',
    label: 'Palm frond (Dry)',
    shape: 'frond',
    palette: 'dry',
    anchor: 'bottom',
    biomes: ['tropical', 'desert'],
    glow: false,
    coverage: 0.303,
  },
  {
    key: 'jungle',
    label: 'Jungle blade',
    shape: 'jungle',
    palette: 'summer',
    anchor: 'bottom',
    biomes: ['tropical'],
    glow: false,
    coverage: 0.419,
  },
  {
    key: 'jungle_spring',
    label: 'Jungle blade (Spring)',
    shape: 'jungle',
    palette: 'spring',
    anchor: 'bottom',
    biomes: ['tropical'],
    glow: false,
    coverage: 0.419,
  },
  {
    key: 'acacia',
    label: 'Acacia',
    shape: 'acacia',
    palette: 'sage',
    anchor: 'bottom',
    biomes: ['desert'],
    glow: false,
    coverage: 0.18,
  },
  {
    key: 'acacia_dry',
    label: 'Acacia (Dry)',
    shape: 'acacia',
    palette: 'dry',
    anchor: 'bottom',
    biomes: ['desert'],
    glow: false,
    coverage: 0.18,
  },
];

export const DEFAULT_LEAF_SET = 'broadleaf';

export function leafSetPath(key: string): string {
  return `textures/foliage/leaves/${key}.png`;
}

export function leafSet(key: string): LeafSet | null {
  return LEAF_SETS.find((s) => s.key === key) ?? null;
}
