import type { RitualChoreography, RitualShape } from './ability_vfx/ritual_choreography_core';
import type { AbilityVfxArchetype, AbilityVfxFullSpec, AbilityVfxSpec } from './ability_vfx_core';

type Entry = {
  archetype: AbilityVfxArchetype;
  palette: string;
  tint: string;
  accent: string;
  power: number;
  ritual: RitualChoreography;
  weaponAura?: string;
};
function rite(
  shape: RitualShape,
  archetype: AbilityVfxArchetype,
  palette: string,
  tint: string,
  accent: string,
  radius: number,
  height: number,
  strands: number,
  twist: number,
  beats: readonly number[] = [0],
  power = 1,
  width = 0.065,
): Entry {
  return {
    archetype,
    palette,
    tint,
    accent,
    power,
    ritual: {
      shape,
      radius,
      height,
      strands,
      twist,
      beats: beats.map((time) => time * 0.5),
      width,
      duration: shape === 'precision' ? 0.2 : shape === 'edge' ? 0.3 : 0.32,
      anchor: archetype === 'buff' || archetype === 'summon' ? 'caster' : 'target',
    },
  };
}

/** Intentional cast silhouettes, including the modern specialization and
 * replacement abilities absent from the original gallery. Shared grammar has
 * authored dimensions, tempo, framing and substance for each action. */
export const RITUAL_KIT_CHOREOGRAPHY: Readonly<Record<string, Entry>> = {
  evocation: rite(
    'stitch',
    'buff',
    'arcane',
    '#797fc1',
    '#c4dcfa',
    1.65,
    2.5,
    4,
    0.35,
    [0, 0.2],
    0.8,
    0.06,
  ),
  revive_pet: rite(
    'stitch',
    'heal',
    'nature',
    '#91a777',
    '#e0e7c5',
    0.9,
    1.6,
    3,
    0.7,
    [0, 0.24],
    0.65,
    0.055,
  ),
  valkyrs_calling_impact: rite(
    'feather',
    'nova',
    'holy',
    '#eab65e',
    '#fff2b5',
    5.2,
    7,
    6,
    0.7,
    [0, 0.12, 0.26],
    2.1,
    0.19,
  ),
  hammer_of_grace: rite('edge', 'bolt', 'holy', '#f8bd50', '#fff1b2', 0.7, 1.2, 3, 0.3),
  dawn_devotion: rite('edge', 'buff', 'holy', '#dea749', '#fff0c0', 1, 1.9, 3, 0.8),
  devotion_ward: rite('ward', 'buff', 'holy', '#ac9b67', '#fff4ce', 0.85, 1.65, 4, 0.15),
  solar_step: rite('feather', 'buff', 'gold', '#edb763', '#fff4d5', 0.8, 1.4, 4, -0.7),
  sacred_form: rite('feather', 'buff', 'holy', '#edd594', '#fffae5', 1.3, 2.3, 6, 0.4, [0, 0.3]),
  vowkeeper_strike: rite(
    'ward',
    'strike',
    'holy',
    '#dcb85f',
    '#fff3b7',
    0.7,
    1.6,
    2,
    0.3,
    [0],
    0.7,
  ),
  recall_the_fallen: rite(
    'feather',
    'heal',
    'holy',
    '#f2c681',
    '#ffffe2',
    1.8,
    3.7,
    6,
    0.9,
    [0, 0.28, 0.55],
    1.3,
  ),
  sacred_challenge: rite(
    'edge',
    'burst',
    'gold',
    '#e2b356',
    '#fff3b8',
    0.6,
    1.8,
    2,
    1.2,
    [0],
    0.55,
  ),
  bastion_rite: rite('ward', 'buff', 'holy', '#bdab75', '#fff7d3', 1.1, 2.25, 6, 0.05, [0, 0.18]),
  holy_shield: rite(
    'ward',
    'buff',
    'holy',
    '#efb74d',
    '#fff8d1',
    1.45,
    2.4,
    6,
    0.15,
    [0],
    1.2,
    0.1,
  ),
  avenging_wrath: rite(
    'feather',
    'buff',
    'holy',
    '#ffb72b',
    '#fff6c9',
    2.7,
    3.6,
    6,
    0.4,
    [0],
    1.8,
    0.13,
  ),
  holy_light: rite(
    'stitch',
    'heal',
    'holy',
    '#f5c87c',
    '#fffbed',
    1.05,
    2.25,
    4,
    0.4,
    [0],
    1.1,
    0.09,
  ),
  grace_devotion: rite('feather', 'buff', 'holy', '#dacaa4', '#fffce6', 0.8, 2, 4, -0.2),
  mercy_lance: rite(
    'edge',
    'burst',
    'holy',
    '#f0c879',
    '#fffceb',
    0.6,
    2.2,
    3,
    -0.5,
    [0],
    0.85,
    0.045,
  ),
  faithforged_guard: rite('ward', 'buff', 'gold', '#d78c47', '#fff0bc', 0.85, 2, 2, 0.5, [0, 0.12]),
  radiant_devotion: rite('feather', 'buff', 'holy', '#edce83', '#fff1aa', 1, 2.2, 3, 1.3),
  hushbrand: rite('edge', 'strike', 'holy', '#c9a66b', '#fff9d1', 0.48, 1.35, 2, -0.3, [0], 0.55),
  dawns_embrace: rite(
    'feather',
    'heal',
    'holy',
    '#ebcf95',
    '#fffdf1',
    1.55,
    2.9,
    6,
    0.6,
    [0, 0.22, 0.45],
    1.3,
  ),
  radiant_chorus: rite('chorus', 'heal', 'holy', '#e7bb69', '#fff5c8', 1.8, 2.7, 4, 0.2, [0, 0.23]),
  beacon_of_light: rite(
    'feather',
    'heal',
    'holy',
    '#f6c06b',
    '#fffad7',
    0.65,
    3,
    3,
    0.1,
    [0, 0.25],
    0.8,
  ),
  aura_mastery: rite(
    'ward',
    'buff',
    'holy',
    '#d8b96a',
    '#fff9da',
    1.45,
    2.65,
    6,
    0.4,
    [0, 0.3],
    1.3,
  ),

  frostjaw_trap: rite('trap', 'nova', 'frost', '#83a4b2', '#d5ebef', 1.3, 0.8, 6, 0.2, [0, 0.12]),
  measured_shot: rite(
    'precision',
    'bolt',
    'physical',
    '#adb9ba',
    '#edf4df',
    0.7,
    1.5,
    1,
    0,
    [0],
    0.5,
    0.035,
  ),
  rapid_fire: rite(
    'precision',
    'bolt',
    'physical',
    '#c9ab7c',
    '#fff3c3',
    0.5,
    1.4,
    1,
    0.1,
    [0],
    0.4,
    0.025,
  ),
  cold_focus: rite(
    'precision',
    'buff',
    'frost',
    '#9ac5d2',
    '#e7faff',
    0.85,
    1.8,
    3,
    0.3,
    [0, 0.16],
    0.7,
    0.035,
  ),
  wildheart: rite(
    'growth',
    'heal',
    'nature',
    '#ab9a66',
    '#eee2a4',
    1.05,
    1.65,
    4,
    0.6,
    [0, 0.2],
    0.8,
  ),
  shellskin: rite('ward', 'buff', 'nature', '#81977a', '#bcd3ad', 1.2, 1.8, 6, 0.4, [0, 0.16], 1),
  bloodtrail_assault: rite(
    'veil',
    'buff',
    'blood',
    '#7f3532',
    '#d38a60',
    1.2,
    1.7,
    4,
    -0.8,
    [0, 0.24],
  ),
  pack_rally: rite(
    'feather',
    'buff',
    'nature',
    '#9aa17c',
    '#e6deb2',
    1.25,
    1.65,
    4,
    -1,
    [0, 0.2],
    0.75,
  ),

  veilstep: rite('veil', 'buff', 'shadow', '#8578a6', '#c7b7da', 1, 2.2, 4, 0.7, [0, 0.18], 0.8),
  scouring_mercy: rite('ward', 'heal', 'holy', '#c7c9b2', '#fff9d8', 1, 2.2, 4, 0.2, [0, 0.12]),
  seraphic_vigil: rite(
    'feather',
    'heal',
    'holy',
    '#ddcfba',
    '#fffef0',
    1.35,
    2.8,
    6,
    -0.3,
    [0, 0.24],
  ),
  summon_tithefiend: rite(
    'veil',
    'summon',
    'shadow',
    '#4b3869',
    '#a598b9',
    1.25,
    1.6,
    4,
    1.1,
    [0, 0.17, 0.35],
  ),
  martyrs_aegis: rite('ward', 'heal', 'holy', '#b0c5cb', '#eefbff', 1.1, 2.15, 4, 0, [0, 0.15]),
  choir_of_deliverance: rite(
    'feather',
    'heal',
    'holy',
    '#c3c6dc',
    '#fffae8',
    1.25,
    3.1,
    4,
    0.7,
    [0, 0.3],
  ),

  galeheart_weapon: {
    ...rite('storm', 'buff', 'storm', '#92b9c1', '#dbfff3', 1.15, 1.75, 4, 0.8),
    weaponAura: '#91cad1',
  },
  lifespring_weapon: {
    ...rite('water', 'buff', 'frost', '#409f9c', '#c4ebca', 0.7, 1.3, 2, 0.5),
    weaponAura: '#70c6b3',
  },
  stoneward: rite('ward', 'heal', 'nature', '#8c9974', '#dce4b2', 0.95, 1.9, 6, 0.4, [0, 0.18]),
  tidecall: rite('water', 'heal', 'frost', '#3b9d9e', '#caead6', 1.5, 1.9, 3, 0.6, [0, 0.18]),
  unleash_weapon_pyrebrand: rite(
    'ash',
    'burst',
    'fire',
    '#b4653d',
    '#ffbd70',
    1.2,
    2,
    4,
    0.7,
    [0, 0.13],
  ),
  unleash_weapon_galeheart: rite(
    'storm',
    'burst',
    'storm',
    '#87b5c2',
    '#dffaf2',
    1.2,
    1.9,
    4,
    0.35,
  ),
  unleash_weapon_stonebound: rite(
    'ward',
    'burst',
    'nature',
    '#969273',
    '#ddd2a2',
    1.15,
    1.7,
    4,
    0.1,
  ),
  unleash_weapon_lifespring: rite(
    'water',
    'heal',
    'frost',
    '#369794',
    '#caf3d9',
    1.7,
    2.1,
    3,
    0.4,
    [0, 0.17],
  ),
  unleash_weapon: rite('storm', 'burst', 'storm', '#7aabc4', '#eff9e0', 1.1, 1.9, 4, 0.2),
  primal_exaltation: rite(
    'storm',
    'buff',
    'storm',
    '#88aaba',
    '#e2f6e8',
    2.3,
    3.1,
    6,
    0.35,
    [0, 0.18, 0.4],
    1.4,
  ),
  elemental_trance: rite(
    'storm',
    'buff',
    'storm',
    '#759dab',
    '#d2f1dd',
    1.15,
    2.5,
    4,
    1,
    [0, 0.28],
  ),
  ancestor_return: rite(
    'water',
    'heal',
    'frost',
    '#71a9ae',
    '#dbeddb',
    2,
    3.2,
    4,
    0.9,
    [0, 0.35, 0.7],
    1.3,
  ),

  sacrilegious_march: rite(
    'ash',
    'buff',
    'shadow',
    '#60394c',
    '#ab736a',
    0.9,
    1.8,
    4,
    0.4,
    [0, 0.22],
  ),
  raise_graveguard: rite(
    'bone',
    'summon',
    'shadow',
    '#b3a489',
    '#dfd9b7',
    1.4,
    2.2,
    6,
    0.3,
    [0, 0.2, 0.4],
  ),
  raise_skeletal_warrior: rite(
    'bone',
    'summon',
    'shadow',
    '#c3b699',
    '#e7ddbc',
    1,
    1.6,
    4,
    -0.4,
    [0, 0.2],
  ),
  cursed_accomplice: rite(
    'stitch',
    'heal',
    'shadow',
    '#80566e',
    '#d0a8b7',
    0.9,
    1.8,
    3,
    0.7,
    [0, 0.17],
  ),
  sacrifice_undead: rite(
    'bone',
    'heal',
    'shadow',
    '#ae9f86',
    '#dcc2a5',
    1.2,
    1.9,
    4,
    1.1,
    [0, 0.15],
  ),
  soulwell: rite(
    'stitch',
    'summon',
    'shadow',
    '#657b6c',
    '#abbf9c',
    1.45,
    1.6,
    4,
    1.5,
    [0, 0.25, 0.5],
  ),
  litany_of_guilt: rite(
    'stitch',
    'burst',
    'shadow',
    '#85506f',
    '#c998b5',
    1.4,
    2,
    4,
    0.25,
    [0, 0.24],
  ),
  raise_bone_mage: rite(
    'bone',
    'summon',
    'shadow',
    '#9fb6ac',
    '#dddccb',
    1.15,
    2.5,
    4,
    1.2,
    [0, 0.23],
  ),
  bone_armor: rite('bone', 'buff', 'shadow', '#b5ad91', '#ece2c2', 1.05, 2.4, 6, 0, [0, 0.15, 0.3]),
  cinderhide: rite('ash', 'buff', 'fire', '#5f514a', '#c28d64', 1.2, 2.15, 5, 0.8, [0, 0.3]),
  cruel_pact: rite('stitch', 'buff', 'blood', '#8a3245', '#d18a94', 1.35, 1.9, 3, -0.3, [0, 0.2]),
  dark_pact: rite(
    'stitch',
    'buff',
    'blood',
    '#873747',
    '#c28a9d',
    1.2,
    2.25,
    6,
    1,
    [0, 0.18, 0.36],
  ),
  hex_of_violence: rite(
    'stitch',
    'burst',
    'shadow',
    '#a14d68',
    '#e3a0b7',
    1.2,
    2.1,
    3,
    1.4,
    [0, 0.13, 0.3],
  ),
  unholy_command: rite(
    'bone',
    'buff',
    'shadow',
    '#b1aa84',
    '#dcd8ae',
    1.65,
    2.5,
    6,
    1,
    [0, 0.2],
    1.25,
  ),
  vicarious_suffering: rite(
    'stitch',
    'heal',
    'shadow',
    '#73566b',
    '#b8a2bc',
    1.15,
    2.1,
    4,
    -0.7,
    [0, 0.2],
  ),
  raise_gravewing: rite(
    'bone',
    'summon',
    'shadow',
    '#b8b69d',
    '#e4e7c9',
    1.8,
    2.3,
    6,
    -0.6,
    [0, 0.2, 0.4],
  ),
  hour_of_judgment: rite(
    'stitch',
    'burst',
    'shadow',
    '#a45073',
    '#eabdd0',
    2.25,
    3.5,
    6,
    0.4,
    [0, 0.16, 0.38],
    1.5,
  ),

  moonseed: rite(
    'growth',
    'burst',
    'moon',
    '#9a9fcd',
    '#e1e6ee',
    0.65,
    1.6,
    3,
    0.7,
    [0],
    0.65,
    0.045,
  ),
  overbloom: rite(
    'growth',
    'heal',
    'nature',
    '#6caa69',
    '#d9efb0',
    1.9,
    2.6,
    6,
    1.1,
    [0, 0.16, 0.36],
    1.4,
    0.09,
  ),
  moonlash: rite(
    'moon',
    'burst',
    'moon',
    '#899ecd',
    '#e3f4fa',
    1.4,
    2.5,
    4,
    0.6,
    [0, 0.14],
    1.3,
    0.1,
  ),
  sunlance: rite(
    'growth',
    'burst',
    'nature',
    '#b4a65b',
    '#f5e7aa',
    1.1,
    2.2,
    4,
    -0.5,
    [0, 0.16, 0.35],
    1.1,
  ),
};

export const RITUAL_KIT_FULL_SPECS: Record<string, AbilityVfxFullSpec> = {};
export const RITUAL_KIT_SPECS: Record<string, AbilityVfxSpec> = {};
for (const [id, e] of Object.entries(RITUAL_KIT_CHOREOGRAPHY)) {
  RITUAL_KIT_FULL_SPECS[id] = {
    ...e,
    windup: 0,
    windupStyle: 'none',
    chargeStreams: 1,
    damageCue: id === 'mercy_lance' || id === 'scouring_mercy',
    motifs: [],
    screenFx: false,
    impact: { ring: false, vRing: false, flipbook: false, sparks: 0, light: 0.3 },
    buff: e.weaponAura ? { weaponAura: e.weaponAura, orbit: 'none' } : undefined,
    bolt:
      e.archetype === 'bolt'
        ? {
            style: id === 'hammer_of_grace' ? 'shard' : 'arrow',
            speed: 45,
            headScale: id === 'hammer_of_grace' ? 0.8 : 0.35,
            volley: 1,
            tracer: true,
          }
        : undefined,
  };
  RITUAL_KIT_SPECS[id] = {
    a: e.archetype,
    p: e.palette,
    c: e.tint,
    pw: e.power,
    sp: 0,
    rg: 0,
    li: 0.3,
    bo: 'none',
    b: e.archetype === 'bolt' ? { v: 45, h: 0.35, vl: 1 } : undefined,
  };
}

/** These performances are driven by live gameplay state or their dedicated
 * event renderer. Register identity without drawing a duplicate ceremony. */
const dedicated: Record<string, [string, string, AbilityVfxArchetype]> = {
  solar_invocation: ['holy', '#eac47f', 'heal'],
  divine_ascension: ['holy', '#f6ce71', 'buff'],
  final_edict: ['holy', '#edbb65', 'strike'],
  sunward_disc: ['holy', '#ebc065', 'bolt'],
  bastion_sweep: ['holy', '#d9b576', 'nova'],
  dawnfall: ['holy', '#f4b85a', 'nova'],
  life_covenant: ['holy', '#efdab1', 'heal'],
  guardian_covenant: ['holy', '#debc80', 'heal'],
  valkyrs_calling: ['holy', '#f6d290', 'dash'],
  oath_chain: ['holy', '#d1b373', 'burst'],
  sun_gods_verdict: ['holy', '#eaca73', 'burst'],
  aegis_first_dawn: ['holy', '#e8cd85', 'heal'],
  veilbound_march: ['holy', '#c5ba94', 'buff'],
  stampede: ['physical', '#b2a284', 'summon'],
  umbral_anchor: ['shadow', '#78678e', 'buff'],
  evil_eye: ['shadow', '#9c5d8e', 'burst'],
  needle_of_fate: ['shadow', '#b18aaf', 'bolt'],
  sentence: ['shadow', '#9f759d', 'burst'],
  possess_evil_eye: ['shadow', '#b885af', 'buff'],
  coven: ['shadow', '#a07291', 'burst'],
};
for (const [id, [palette, tint, archetype]] of Object.entries(dedicated)) {
  RITUAL_KIT_FULL_SPECS[id] = {
    archetype,
    palette,
    tint,
    presentation: 'dedicated',
    power: 1,
    impact: { ring: false, vRing: false },
    windupStyle: 'none',
  };
  RITUAL_KIT_SPECS[id] = { a: archetype, p: palette, c: tint, rg: 0, sp: 0 };
}
for (const id of [
  'hunting_momentum',
  'fieldcraft_reentry',
  'thunder_reservoir',
  'warspirit_cadence',
  'stormsurge',
  'maledict_gaze',
  'funeral_harvest',
]) {
  RITUAL_KIT_FULL_SPECS[id] = {
    archetype: 'buff',
    palette: 'physical',
    presentation: 'passive',
    impact: { ring: false, vRing: false },
    windupStyle: 'none',
  };
  RITUAL_KIT_SPECS[id] = { a: 'buff', p: 'physical', c: '#999999', rg: 0, sp: 0 };
}

/** Resolve from the actual caster's live enchantment, including remote actors. */
export function ritualVariantAbilityId(id: string, auras: readonly { id: string }[]): string {
  if (id !== 'unleash_weapon') return id;
  if (auras.some((a) => a.id === 'flametongue_weapon')) return 'unleash_weapon_pyrebrand';
  if (auras.some((a) => a.id === 'galeheart_weapon')) return 'unleash_weapon_galeheart';
  if (auras.some((a) => a.id === 'rockbiter_weapon')) return 'unleash_weapon_stonebound';
  if (auras.some((a) => a.id === 'lifespring_weapon')) return 'unleash_weapon_lifespring';
  return id;
}
