// Roach King's showmanship rides the existing capped, prewarmed primitive
// pools. Exact hazard footprints remain owned by the sim's rune/death zones.
import type { AbilityVfxFullSpec, AbilityVfxSpec } from './ability_vfx_core';

export const ROACH_KING_VFX_SPECS: Readonly<Record<string, AbilityVfxSpec>> = {
  rift_asmon_coronation: {
    c: '#a94dff',
    p: 'shadow',
    pw: 1.9,
    sp: 60,
    vr: 1,
    db: 1,
    sm: 1,
    li: 3.4,
    wu: 3,
    fin: 1,
    a: 'buff',
  },
  rift_roach_crown: {
    c: '#e4a638',
    p: 'shadow',
    pw: 1.3,
    sp: 24,
    vr: 1,
    li: 1.5,
    bo: 'halo',
    a: 'buff',
  },
  rift_asmon_desk_slam: {
    c: '#efa835',
    p: 'nature',
    pw: 1.8,
    sp: 48,
    vr: 1,
    db: 1,
    sm: 1,
    li: 2.8,
    a: 'burst',
  },
  rift_asmon_tribute: {
    c: '#b267ef',
    p: 'shadow',
    pw: 1.6,
    sp: 36,
    vr: 1,
    sm: 1,
    li: 2.2,
    a: 'summon',
  },
  rift_asmon_filth: {
    c: '#db9230',
    p: 'nature',
    pw: 1.7,
    sp: 44,
    vr: 1,
    db: 1,
    sm: 1,
    li: 2.4,
    a: 'burst',
  },
  rift_asmon_swarm: {
    c: '#9749ef',
    p: 'shadow',
    pw: 1.9,
    sp: 60,
    vr: 1,
    sm: 1,
    li: 3,
    fin: 1,
    a: 'nova',
  },
  rift_asmon_roachling_bite: {
    c: '#d49638',
    p: 'nature',
    pw: 0.65,
    sp: 8,
    li: 0.25,
    a: 'strike',
  },
  rift_asmon_beetle_burst: {
    c: '#c48c28',
    p: 'nature',
    pw: 1.2,
    sp: 28,
    vr: 1,
    db: 1,
    sm: 1,
    li: 1.2,
    a: 'burst',
  },
};

export const ROACH_KING_VFX_FULL_SPECS: Readonly<Record<string, AbilityVfxFullSpec>> = {
  rift_asmon_coronation: {
    bodyGlowScale: 0.12,
    archetype: 'buff',
    palette: 'shadow',
    tint: '#a94dff',
    accent: '#ffc54c',
    rim: '#d7a0ff',
    power: 1.9,
    windup: 3,
    windupStyle: 'ascend',
    motifs: ['swarm', 'implosion', 'pillars'],
    motifAt: 'caster',
    motifR: 3.5,
    buff: { style: 'morph', orbit: 'plates', o: { n: 8, radius: 2.1, rate: 2, size: 0.8 } },
    impact: { flipbook: true, vRing: 2, sparks: 60, debris: true, smoke: true, light: 3.4 },
    screenFx: true,
    finisher: true,
  },
  rift_roach_crown: {
    bodyGlowScale: 0.12,
    archetype: 'buff',
    palette: 'shadow',
    tint: '#e4a638',
    accent: '#bd75ff',
    rim: '#af66de',
    power: 0.85,
    windupStyle: 'none',
    buff: {
      style: 'morph',
      persist: true,
      orbit: 'halo',
      o: {
        n: 9,
        radius: 1.45,
        rate: 0.8,
        size: 0.38,
        weave: 0.25,
        incline: 0.18,
      },
    },
    impact: { flipbook: false, ring: false, sparks: 18, light: 1 },
  },
  rift_asmon_desk_slam: {
    bodyGlowScale: 0.12,
    archetype: 'burst',
    palette: 'nature',
    tint: '#efa835',
    accent: '#ae65e8',
    rim: '#ffcd6c',
    power: 1.8,
    windupStyle: 'compression',
    motifs: ['fissure', 'gavel'],
    motifAt: 'caster',
    motifR: 3,
    burst: { style: 'ground' },
    impact: {
      flipbook: true,
      ring: false,
      vRing: 1.6,
      sparks: 48,
      debris: true,
      smoke: true,
      light: 2.8,
    },
    screenFx: true,
  },
  rift_asmon_tribute: {
    bodyGlowScale: 0.12,
    archetype: 'summon',
    palette: 'shadow',
    tint: '#b267ef',
    accent: '#e9b754',
    rim: '#d5a3ff',
    power: 1.6,
    windupStyle: 'runes',
    motifs: ['chains', 'swarm'],
    motifAt: 'caster',
    motifR: 2.5,
    decal: 'portal',
    spirit: null,
    impact: { flipbook: true, ring: false, vRing: true, sparks: 36, smoke: true, light: 2.2 },
  },
  rift_asmon_filth: {
    bodyGlowScale: 0.12,
    archetype: 'burst',
    palette: 'nature',
    tint: '#db9230',
    accent: '#8f39ce',
    rim: '#edbe51',
    power: 1.7,
    windupStyle: 'vortex',
    motifs: ['fountain', 'swarm'],
    motifAt: 'target',
    motifR: 2.5,
    burst: { style: 'ground' },
    impact: {
      flipbook: true,
      ring: false,
      vRing: true,
      sparks: 44,
      debris: true,
      smoke: true,
      light: 2.4,
    },
  },
  rift_asmon_swarm: {
    bodyGlowScale: 0.12,
    archetype: 'nova',
    palette: 'shadow',
    tint: '#9749ef',
    accent: '#edb647',
    rim: '#d49aff',
    power: 1.9,
    windupStyle: 'vortex',
    motifs: ['swarm', 'claws', 'orbitals'],
    motifAt: 'caster',
    motifR: 3.5,
    nova: { radius: 8 },
    impact: { flipbook: true, ring: false, vRing: 1.8, sparks: 60, smoke: true, light: 3 },
    screenFx: true,
    finisher: true,
  },
  rift_asmon_roachling_bite: {
    bodyGlowScale: 0.12,
    archetype: 'strike',
    palette: 'nature',
    tint: '#d49638',
    accent: '#bc69df',
    power: 0.65,
    windupStyle: 'none',
    strike: { arc: 'bite' },
    impact: { flipbook: false, ring: false, sparks: 8, light: 0.25 },
  },
  rift_asmon_beetle_burst: {
    bodyGlowScale: 0.12,
    archetype: 'burst',
    palette: 'nature',
    tint: '#c48c28',
    accent: '#9349d4',
    power: 1.2,
    windupStyle: 'compression',
    motifs: ['swarm'],
    motifAt: 'caster',
    burst: { style: 'ground' },
    impact: {
      flipbook: true,
      ring: false,
      vRing: true,
      sparks: 28,
      debris: true,
      smoke: true,
      light: 1.2,
    },
  },
};
