window.TALENT_LAB_DATA = {
  classes: {
    hunter: {
      name: 'Hunter',
      mark: 'H',
      color: '#d4a94f',
      softColor: '#6f5427',
      summary: 'Focus, field control, and three different relationships with the beast and range.',
      shared: [
        'Fell Shot',
        'Rattling Shot',
        'Fettering Slash',
        'Hushing Shot',
        'Trailbreak',
        'Shellskin',
        'Wildheart',
        'Frostjaw Trap',
      ],
      specs: [
        {
          id: 'packlord',
          name: 'Packlord',
          role: 'Pet damage',
          resource: 'Focus plus visible Pack Ferocity',
          thesis: 'The beast is the weapon. Build it bigger and redder, unleash the clap, then watch it calm.',
          decision: 'Spend Focus for immediate pressure, or continue empowering the beast for a stronger unleash.',
          exclusive: ['Pack Command', 'Pack Ferocity', 'Unleash Beast', 'Howling Rage'],
          loop: [
            ['Pack Command', "The pet strikes, Focus rises, and the Hunter's Pack Ferocity buff gains a stage."],
            ['Grow', 'The pet becomes larger, redder, and gains stronger cleave.'],
            ['Spend', 'Fell Shot fills the gap and commands extra cleave during frenzy.'],
            ['Unleash Beast', 'At full Ferocity, the command becomes a heavy clap and short frenzy.'],
            ['Calm', 'The pet returns to normal and the growth cycle begins again.'],
          ],
          actions: [
            ['Pack Command', 'exclusive'],
            ['Fell Shot', 'shared'],
            ['Unleash Beast', 'payoff'],
            ['Howling Rage', 'exclusive'],
            ['Trailbreak', 'shared'],
            ['Hushing Shot', 'shared'],
          ],
        },
        {
          id: 'coldsight',
          name: 'Coldsight',
          role: 'Ranged damage',
          resource: 'Focus',
          thesis: 'Create room, build deliberately, and commit to the shot only when the position is safe.',
          decision: 'Keep building while moving, or spend Focus on a high-value cast before the window closes.',
          exclusive: ['Measured Shot', 'Long Draw', 'Fevered Draw', 'Cold Focus'],
          loop: [
            ['Measured Shot', 'A controlled hit builds Focus.'],
            ['Create space', 'Movement and control buy the time needed for the next cast.'],
            ['Long Draw', 'Commit Focus to the deliberate primary-target hit.'],
            ['Fevered Draw', 'Maintain pressure when movement prevents another long cast.'],
            ['Cold Focus', 'Compress the same builder and spender cadence into a burst window.'],
          ],
          actions: [
            ['Measured Shot', 'exclusive'],
            ['Long Draw', 'exclusive'],
            ['Fevered Draw', 'exclusive'],
            ['Cold Focus', 'exclusive'],
            ['Trailbreak', 'shared'],
            ['Hushing Shot', 'shared'],
          ],
        },
        {
          id: 'fieldcraft',
          name: 'Fieldcraft',
          role: 'Melee damage',
          resource: 'Focus plus three Hunting Momentum stages',
          thesis: 'Close, wound, tear, detonate, disengage, and hunt again.',
          decision: 'Remain in melee for a stronger Momentum payoff, or leave early and preserve the re-entry.',
          exclusive: [
            'Bloodhook',
            'Gutting Strike',
            'Woundrend',
            'Shrapnel Charge',
            'Bloodtrail Assault',
          ],
          loop: [
            ['Bloodhook', 'Rush to the target and apply the primary bleed.'],
            ['Gutting Strike', 'Build Focus and Hunting Momentum in melee.'],
            ['Woundrend', 'Spend Focus, trigger a bleed tick, and refresh the wound.'],
            ['Shrapnel Charge', 'Turn the prepared wound into target-centered area pressure.'],
            ['Trailbreak', 'Leave danger without losing Momentum, then re-enter.'],
          ],
          actions: [
            ['Bloodhook', 'exclusive'],
            ['Gutting Strike', 'exclusive'],
            ['Woundrend', 'exclusive'],
            ['Shrapnel Charge', 'exclusive'],
            ['Trailbreak', 'shared'],
            ['Hushing Shot', 'shared'],
          ],
        },
      ],
      talents: [
        {
          level: 5,
          theme: 'Movement',
          options: [
            ['Tactical Retreat', 'A second Trailbreak charge that also clears roots and slows.'],
            ['Enduring Courser', "Courser's Guise gains a predictable opening speed burst."],
            ["Predator's Pace", 'A successful Focus generator grants frequent rotational movement.'],
          ],
        },
        {
          level: 8,
          theme: 'Defense',
          options: [
            ['Receding Shell', 'End Shellskin early and recover cooldown from unused duration.'],
            ['Shared Recovery', 'Wildheart also protects and restores the active pet.'],
            ['Beastguard', 'Redirect ordinary pressure to the pet with a safe no-pet fallback.'],
          ],
        },
        {
          level: 11,
          theme: 'Control',
          options: [
            ['Double Hush', 'Hushing Shot gains a second charge.'],
            ['Binding Payload', 'Frostjaw Trap roots the group before leaving a slow.'],
            ['Crippling Pursuit', 'Existing slows can briefly root a pursued enemy.'],
          ],
        },
        {
          level: 14,
          theme: 'Kit',
          options: [
            ['Efficient Rhythm', 'Focused spending empowers the next generator.'],
            ['Trapcraft', 'Frostjaw Trap restores Focus and helps Trailbreak recover.'],
            ['Guise Mastery', 'Time a stronger Harrier, Marten, or Courser state.'],
          ],
        },
        {
          level: 17,
          theme: 'Major cooldown',
          options: [
            ['Apex Instinct', 'The specialization cooldown primes three stronger, cheaper spenders.'],
            ['Shell and Fang', 'Trade full Shellskin protection for attack-compatible defense.'],
            ['Pack Rally', 'Turn Courser into a party movement and pressure window.'],
          ],
        },
        {
          level: 20,
          theme: 'Capstone',
          options: [
            ['Overdraw', 'Every third spender gains primary and nearby-target damage.'],
            ['Chain Reaction', 'Frostjaw Trap prepares a controlled area echo window.'],
            ['Fang Chorus', 'Every spender commands a pet echo, with a clap every third echo.'],
          ],
        },
      ],
    },
    shaman: {
      name: 'Shaman',
      mark: 'S',
      color: '#58aee8',
      softColor: '#26526f',
      summary: 'A shared elemental backbone, then one storm, weapon, or healing-current engine.',
      shared: [
        'Arc Bolt',
        'Mending Waters',
        'Earthen Jolt',
        'Cinder Jolt',
        'Rime Jolt',
        'Thunder Ward',
        'Shadewolf',
      ],
      specs: [
        {
          id: 'thundercall',
          name: 'Thundercall',
          role: 'Ranged damage',
          resource: 'Mana plus five visible Thunder charges',
          thesis: 'Build electrical pressure and choose whether to vent it into one target or a group.',
          decision: 'Discharge now for urgency, or hold for a more efficient full-bank payoff.',
          exclusive: ['Pyrebrand Weapon', 'Thunder charges', 'Faultwake vent', 'Primal Mastery'],
          loop: [
            ['Arc Bolt', 'A successful impact grants one Thunder charge.'],
            ['Bank', 'Thunder Ward and the aura show the growing five-stage storm.'],
            ['Earthen Jolt', 'Vent the bank into concentrated single-target damage.'],
            ['Faultwake', 'Vent the bank into prepared target-centered area damage.'],
            ['Primal Mastery', 'Accelerate the same build-and-vent decision.'],
          ],
          actions: [
            ['Arc Bolt', 'shared'],
            ['Earthen Jolt', 'shared'],
            ['Faultwake', 'exclusive'],
            ['Primal Mastery', 'exclusive'],
            ['Thunder Ward', 'shared'],
            ['Shadewolf', 'shared'],
          ],
        },
        {
          id: 'warspirit',
          name: 'Warspirit',
          role: 'Melee damage or off-tank',
          resource: 'Mana plus a three-hit Stormcast cadence',
          thesis: 'Weapon hits earn spells. Galeheart deals damage, while Stonebound trades it for control and survival.',
          decision: 'Choose the offensive or defensive posture, then spend each earned instant on damage, control, or healing.',
          exclusive: [
            'Galeheart Weapon',
            'Stonebound Weapon',
            'Ancestral Strike',
            'Stormcast',
            'Off-tank riders',
          ],
          loop: [
            ['Choose posture', 'Galeheart brings echoes. Stonebound brings mitigation and threat.'],
            ['Melee cadence', 'Landed attacks advance one visible three-step rhythm.'],
            ['Third hit', 'Trigger Galeheart echoes and arm Stormcast.'],
            ['Spend Stormcast', 'Make Arc Bolt, a Jolt, or Mending Waters instant and cheaper.'],
            ['Repeat', 'Ancestral Strike advances the next cadence faster.'],
          ],
          actions: [
            ['Galeheart Weapon', 'exclusive'],
            ['Stonebound Weapon', 'exclusive'],
            ['Ancestral Strike', 'exclusive'],
            ['Earthen Jolt', 'shared'],
            ['Mending Waters', 'shared'],
            ['Shadewolf', 'shared'],
          ],
        },
        {
          id: 'spiritmend',
          name: 'Spiritmend',
          role: 'Healing',
          resource: 'Mana plus visible Mending Currents on allies',
          thesis: 'Prepare efficient healing as currents, then collapse every reached pool into a large group recovery.',
          decision: 'Leave currents ticking, enlarge them for expected damage, or consume them now to save the group.',
          exclusive: ['Lifespring Weapon', 'Mending Current', 'Tidecall', 'Cascading Mend'],
          loop: [
            ['Mending Waters', 'Create or enlarge one Mending Current on the ally.'],
            ['Tidecall', 'Instantly save or prepare one target and refresh the pool.'],
            ['Hold', 'Let the same stored amount heal efficiently over time.'],
            ['Cascading Mend', 'Bounce through the group and consume every reached owned pool.'],
            ['Rebuild', 'Prepare the next expected damage window.'],
          ],
          actions: [
            ['Mending Waters', 'shared'],
            ['Tidecall', 'exclusive'],
            ['Cascading Mend', 'exclusive'],
            ['Lifespring Weapon', 'exclusive'],
            ['Thunder Ward', 'shared'],
            ['Shadewolf', 'shared'],
          ],
        },
      ],
      talents: [
        {
          level: 5,
          theme: 'Movement',
          options: [
            ['Wolfstep', 'Shadewolf becomes instant and clears roots and slows.'],
            ['Gathering Winds', 'Entering Shadewolf grants a planned movement burst.'],
            ['Flowing Elements', 'A Jolt prepares a moving Arc Bolt or Mending Waters cast.'],
          ],
        },
        {
          level: 8,
          theme: 'Defense',
          options: [
            ['Stoneward', 'Prepare a six-charge healing shield on the expected target.'],
            ['Warded Elements', 'Thunder Ward retaliation briefly reduces incoming damage.'],
            ['Ancestral Mending', 'Recover automatically after a large unpredictable hit.'],
          ],
        },
        {
          level: 11,
          theme: 'Control',
          options: [
            ['Fault Rebuke', 'Earthen Jolt interrupts and locks a spell school.'],
            ['Rime Lock', 'Rime Jolt briefly roots its target.'],
            ['Gripping Earth', 'Gain target-centered group control without precision placement.'],
          ],
        },
        {
          level: 14,
          theme: 'Kit',
          options: [
            ['Flow State', 'Mana spending creates a predictable efficiency cycle.'],
            ['Imbue Mastery', 'Commit harder to the selected specialization enhancement.'],
            ['Ward Cycle', 'The core rotation restores defense and Mana.'],
          ],
        },
        {
          level: 17,
          theme: 'Major cooldown',
          options: [
            ['Primal Exaltation', 'Gain a specialization-specific throughput window.'],
            ['Wayfarer Grace', 'Exiting Shadewolf enables an extended moving-cast window.'],
            ['Ancestral Bulwark', 'Thunder Ward becomes a major defensive window.'],
          ],
        },
        {
          level: 20,
          theme: 'Capstone',
          options: [
            ['Deep Reservoir', 'Retain part of the specialization bank after its payoff.'],
            ['Echoing Elements', 'The specialization payoff repeats once at reduced power.'],
            ['Living Weapon', 'Make the selected weapon enhancement define the build.'],
          ],
        },
      ],
    },
    priest: {
      name: 'Priest',
      mark: 'P',
      color: '#d9c8ff',
      softColor: '#5b4c79',
      summary: 'Spiritual links connecting offense, protection, group recovery, and sympathetic suffering.',
      shared: [
        'Scouring Hymn',
        'Solemn Prayer',
        'Urgent Prayer',
        'Psalm of Warding',
        'Dirge of Decay',
        'Mindfracture',
        'Litany of Woe',
        'Veilstep',
        'Terror Canticle',
      ],
      specs: [
        {
          id: 'doctrine',
          name: 'Doctrine',
          role: 'Damage-linked healing',
          resource: 'Mana plus one protected ally link',
          thesis: 'Ward one ally, then turn controlled offense into clean healing for that chosen person.',
          decision: 'Choose who receives the link and whether the next cast should damage, ward, or heal directly.',
          exclusive: ['Scouring Mercy', 'Doctrine ally link'],
          loop: [
            ['Psalm of Warding', 'Protect one ally and establish the Doctrine link.'],
            ['Scouring Hymn', 'Damage the enemy and convert part of that result into healing.'],
            ['Scouring Mercy', 'Damage an enemy or directly heal an ally with the same action.'],
            ['Reassess', 'Move the link when another ally becomes the priority.'],
            ['Direct prayer', 'Use clean healing when no enemy can be attacked safely.'],
          ],
          actions: [
            ['Psalm of Warding', 'shared'],
            ['Scouring Hymn', 'shared'],
            ['Scouring Mercy', 'exclusive'],
            ['Solemn Prayer', 'shared'],
            ['Veilstep', 'shared'],
            ['Terror Canticle', 'shared'],
          ],
        },
        {
          id: 'benison',
          name: 'Benison',
          role: 'Group healing',
          resource: 'Mana plus attached Seraphic Vigils',
          thesis: 'Commit to the largest immediate prayers and place visible angelic protection before danger arrives.',
          decision: 'Choose between a large cast, immediate group recovery, or a vigil on one endangered ally.',
          exclusive: ['Choirmend', 'Sunburst Canticle', 'Seraphic Vigil', 'Attached angel state'],
          loop: [
            ['Solemn Prayer', 'Deliver large single-target triage.'],
            ['Seraphic Vigil', 'Prepare one selected ally before the dangerous moment.'],
            ['Choirmend', 'Commit to the large group cast when time permits.'],
            ['Sunburst Canticle', 'Recover the group immediately while moving.'],
            ['Choir of Deliverance', 'Answer sustained group damage with the major-prayer choice.'],
          ],
          actions: [
            ['Solemn Prayer', 'shared'],
            ['Urgent Prayer', 'shared'],
            ['Choirmend', 'exclusive'],
            ['Sunburst Canticle', 'exclusive'],
            ['Seraphic Vigil', 'exclusive'],
            ['Veilstep', 'shared'],
          ],
        },
        {
          id: 'vespers',
          name: 'Vespers',
          role: 'Shadow damage',
          resource: 'Mana plus five Gloomtithe stages',
          thesis: 'Bind one Effigy, spread its suffering through linked enemies, then manifest the banked pain.',
          decision: 'Spread Dirge for group echoes, focus the Effigy, or summon early for Mana and pressure.',
          exclusive: ['Effigy', 'Gloomtithe', 'Tithefiend', 'Gloamveil', 'Suffering echoes'],
          loop: [
            ['Dirge of Decay', 'Prepare enemies as eligible suffering links.'],
            ['Mindfracture', 'Bind one prepared enemy as the primary Effigy.'],
            ['Echo', 'Eligible damage against the Effigy spreads to linked enemies.'],
            ['Gloomtithe', 'Effigy pressure builds one visible five-stage bank.'],
            ['Tithefiend', 'Consume the bank into an autonomous shade and Mana return.'],
          ],
          actions: [
            ['Dirge of Decay', 'shared'],
            ['Mindfracture', 'shared'],
            ['Litany of Woe', 'shared'],
            ['Tithefiend', 'exclusive'],
            ['Gloamveil', 'exclusive'],
            ['Veilstep', 'shared'],
          ],
        },
      ],
      talents: [
        {
          level: 5,
          theme: 'Movement',
          options: [
            ['Sheltering Step', 'Psalm of Warding gives its target a movement burst.'],
            ['Veil Unbound', 'Veilstep clears roots and slows, then accelerates the Priest.'],
            ['Processional Grace', 'Veilstep opens a short moving-cast window.'],
          ],
        },
        {
          level: 8,
          theme: 'Defense',
          options: [
            ['Last Prayer', 'Gain an immediate personal recovery action.'],
            ['Shattered Psalm', 'A fully consumed Psalm heals its target.'],
            ['Wounded Halo', 'A large hit automatically creates a temporary absorb.'],
          ],
        },
        {
          level: 11,
          theme: 'Control',
          options: [
            ['Hushword', 'Gain one targeted silence action.'],
            ['Lingering Dread', 'Terror Canticle recovers faster and leaves a slow.'],
            ['Binding Psalm', 'An enemy that consumes the ward is briefly rooted.'],
          ],
        },
        {
          level: 14,
          theme: 'Kit',
          options: [
            ['Stilled Mind', 'Protect one free, uninterruptible Priest spell.'],
            ['Measured Faith', 'Every third Mana spell prepares a cheaper follow-up.'],
            ['Living Covenant', 'Amplify the selected specialization link without another action.'],
          ],
        },
        {
          level: 17,
          theme: 'Major prayer',
          options: [
            ['Anointing', 'Increase one ally or the Priest through a concentrated power window.'],
            ["Martyr's Aegis", 'Greatly reduce one ally\'s incoming damage.'],
            ['Choir of Deliverance', 'Channel repeated healing across the nearby party.'],
          ],
        },
        {
          level: 20,
          theme: 'Capstone',
          options: [
            ['Twin Covenant', 'Manage two links, vigils, or Effigies instead of one.'],
            ['Second Verse', 'Repeat the specialization payoff once at reduced power.'],
            ['Incarnate Spirit', 'Turn shields, angels, or Tithefiend into the defining manifestation.'],
          ],
        },
      ],
    },
  },
};
