// World of ClaudeCraft (WoCC) native OpenCode guard plugin.
//
// This plugin is the OpenCode-native translation of three Claude Code project
// hooks that live in .claude/hooks/. It uses OpenCode's own plugin API (the
// plugin factory and the `tool.execute.before` hook), never a copied shell
// script and never Claude's hook protocol.
//
// 1. Generated-file guard: the behavioral equivalent of deny-generated-edit.sh.
//    Blocks the edit/write/apply_patch tools on generated artifacts
//    (*.generated.ts and anything under an i18n.resolved.generated/ directory)
//    before they can modify a file that must be regenerated by its owning build
//    step. Regenerators are unaffected: they write through node/npm build
//    scripts (bash), which this hook never sees.
//
// 2. Instant QA scan: the behavioral equivalent of qa-stop.sh. Scans the
//    incoming content of write/edit/apply_patch for the hard copy invariants:
//    em/en dash and emoji anywhere, a stray .only( that would silently disable
//    a test suite, a leftover debugger statement, and a Math.random/Date.now/
//    performance.now call added under src/sim/ (the determinism invariant;
//    tests/architecture.test.ts remains the deep guard). Locale overlays, the
//    i18n resolved bundles, the Russian doc mirrors, and lockfiles are excluded,
//    matching the pre-push copy scan. A tool.execute.before error needs no loop
//    guard (unlike Claude's Stop hook): the model sees the blocked call's error
//    and fixes the content rather than being re-gated after an unedited reply.
//
// 3. Hooks-path setup: the behavioral equivalent of ensure-hooks.sh. On load it
//    idempotently points this clone's core.hooksPath at .githooks so the pre-push
//    QA floor (tsc, guard tests, biome, copy rules) actually runs. It only acts
//    when nothing already owns the local hook path, so it never clobbers husky
//    or a contributor's own setup; a pre-existing value that points at another
//    checkout's .githooks is left alone with a warning.
//
// The pure logic lives in .opencode/lib/woc-guard-core.ts. OpenCode treats
// every exported function of a module in .opencode/plugins/ as a plugin, so
// this file exports exactly one function (the plugin) and nothing else.

import type { ToolInput, ToolOutput, WocGuardContext } from '../lib/woc-guard-core';
import {
  addedLinesFor,
  ensureHooksPath,
  filePathOf,
  isGeneratedPath,
  scanAddedLines,
} from '../lib/woc-guard-core';

const PLUGIN_NAME = 'woc-guard';
const GENERATED_BLOCK =
  'is a generated artifact. Never hand-edit generated files; change the owning source (catalog, overlay, map) and regenerate via the owning build step (npm run build chains them; see the root CLAUDE.md invariant).';
const QA_BLOCK_HEAD =
  'line(s) this change would add violate a hard project invariant. Fix them before proceeding (no em dashes, en dashes, or emojis anywhere; no stray .only() that disables a test suite; no leftover debugger statement; no Math.random/Date.now/performance.now in src/sim, use Rng and sim time):';

export interface WocGuardHooks {
  'tool.execute.before': (input: ToolInput, output: ToolOutput) => Promise<void>;
}

export const wocGuard = async (context: WocGuardContext = {}): Promise<WocGuardHooks> => {
  const directory = context.directory ?? context.worktree ?? process.cwd();
  // import.meta.url is this module's own location, so runtime verification can
  // prove the plugin was loaded from the repository-local .opencode/plugins/.
  const source = new URL('', import.meta.url).pathname;

  const hooks = ensureHooksPath(directory);
  // Log through OpenCode's native plugin logging channel (client.app.log) so
  // the entry goes to the session log sink and never pollutes command stdout
  // (opencode debug agent must emit pure JSON). Silently skip when no client
  // is present, which is the case in the unit tests.
  const app = context.client?.app;
  if (app?.log) {
    // The SDK client's app.log takes a Hey-API options object with a nested
    // `body`, not a bare payload.
    void app.log({
      body: {
        service: PLUGIN_NAME,
        level: 'info',
        message: `loaded from ${source}; ${hooks.message}`,
      },
    });
  }

  return {
    'tool.execute.before': async (input, output) => {
      const tool = input?.tool ?? '';
      const args = (output?.args ?? {}) as Record<string, unknown>;
      const file = filePathOf(args);
      if (!file) return;
      const mutating =
        tool === 'edit' || tool === 'write' || tool === 'apply_patch' || tool === 'patch';

      // The generated-file guard covers only mutating tools, matching the
      // Claude hook's Edit|Write matcher: reads of generated artifacts are
      // legitimate (an agent must read them to regenerate), so they pass.
      if (mutating && isGeneratedPath(file)) {
        throw new Error(`Blocked: ${file} ${GENERATED_BLOCK}`);
      }

      const violations = scanAddedLines(file, addedLinesFor(tool, args));
      if (violations.length > 0) {
        const body = violations.map((v) => `- ${v.path} [${v.kind}]: ${v.line}`).join('\n');
        throw new Error(`QA guard blocked: ${violations.length} ${QA_BLOCK_HEAD}\n${body}`);
      }
    },
  };
};
