#!/usr/bin/env node
// Regenerates src/sim/maps/index.generated.ts, the registry of Studio-published maps
// the game client can boot with ?map=<slug> (src/main.ts).
//
// Source of truth: data/maps/<slug>.map.json (the published map document) beside its
// compiled module src/sim/maps/<slug>.generated.ts, both written by the Studio
// "Publish to Game" step. This script only rebuilds the registry so the public tree
// never needs Studio to add, rename or drop a published map: delete the two files
// and re-run it. Entries are emitted in slug order for a stable file.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const mapsDir = join(root, 'data', 'maps');
const outFile = join(root, 'src', 'sim', 'maps', 'index.generated.ts');

const entries = readdirSync(mapsDir)
  .filter((name) => name.endsWith('.map.json'))
  .map((name) => name.slice(0, -'.map.json'.length))
  .sort()
  .map((slug) => {
    const doc = JSON.parse(readFileSync(join(mapsDir, `${slug}.map.json`), 'utf8'));
    const module = join(root, 'src', 'sim', 'maps', `${slug}.generated.ts`);
    if (!existsSync(module)) {
      throw new Error(`published map ${slug} has no compiled module at ${module}`);
    }
    const name = typeof doc?.meta?.name === 'string' ? doc.meta.name : slug;
    const seed = Number.isFinite(doc?.meta?.seed) ? doc.meta.seed : 0;
    return { slug, name, seed };
  });

const body = entries
  .map(
    (e) =>
      `  {\n    slug: ${JSON.stringify(e.slug)},\n    name: ${JSON.stringify(e.name)},\n` +
      `    seed: ${e.seed},\n    load: async () => (await import('./${e.slug}.generated')).loadPublishedMap(),\n  },`,
  )
  .join('\n');

const out = `// GENERATED by scripts/gen_published_maps.mjs - do not edit by hand.
// The registry of Studio-published maps. The game client boots one with
// ?map=<slug> (src/main.ts); dynamic import keeps map bytes out of the main
// bundle until a map is actually chosen.
import type { WorldContent } from '../types';

export interface PublishedMapEntry {
  slug: string;
  name: string;
  seed: number;
  load(): Promise<WorldContent>;
}

export const PUBLISHED_MAPS: readonly PublishedMapEntry[] = [
${body}
];

export function publishedMapBySlug(slug: string): PublishedMapEntry | undefined {
  return PUBLISHED_MAPS.find((m) => m.slug === slug);
}
`;

writeFileSync(outFile, out);
console.log(`wrote ${outFile} (${entries.length} published map${entries.length === 1 ? '' : 's'})`);
