// Emits src/sim/dungeon_kit_dims.generated.ts: the NATIVE largest dimension (in
// yards) of every dungeon-kit GLB, straight out of the file.
//
// Why this table has to exist: the dungeon kit is drawn two different ways.
//   * The battleground/dungeon renderers instance the raw merged geometry
//     (render/dungeon.ts extractModule) at the model's OWN units, so a
//     BgModulePlacement.scale of 1 means "actual size".
//   * A placed catalogue asset is normalized to 2.2yd on its largest dimension
//     first (render/asset_scale.ts), so a MapPlacement.scale of 1 means "2.2yd".
// Converting between the two needs the native size, and nothing else in the
// build records it. dungeonKitPlacementScale() in sim/dungeon_kit_dims does the
// conversion; both directions of the region round trip go through it.
//
// Run: node scripts/gen_dungeon_kit_dims.mjs

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const MODELS = 'public/models/dungeon';
const OUT = 'src/sim/dungeon_kit_dims.generated.ts';

/** Componentwise divisor that turns a normalized integer accessor into floats. */
const NORMALIZE = { 5120: 127, 5121: 255, 5122: 32767, 5123: 65535 };

function readGlbJson(bytes) {
  if (bytes.readUInt32LE(0) !== 0x46546c67) return null; // 'glTF'
  const jsonLen = bytes.readUInt32LE(12);
  return JSON.parse(bytes.subarray(20, 20 + jsonLen).toString('utf8'));
}

function mul(a, b) {
  const out = new Array(16).fill(0);
  for (let c = 0; c < 4; c++) {
    for (let r = 0; r < 4; r++) {
      let s = 0;
      for (let k = 0; k < 4; k++) s += a[k * 4 + r] * b[c * 4 + k];
      out[c * 4 + r] = s;
    }
  }
  return out;
}

function trs(node) {
  if (node.matrix) return node.matrix.slice();
  const [tx, ty, tz] = node.translation ?? [0, 0, 0];
  const [qx, qy, qz, qw] = node.rotation ?? [0, 0, 0, 1];
  const [sx, sy, sz] = node.scale ?? [1, 1, 1];
  const x2 = qx + qx;
  const y2 = qy + qy;
  const z2 = qz + qz;
  const xx = qx * x2;
  const xy = qx * y2;
  const xz = qx * z2;
  const yy = qy * y2;
  const yz = qy * z2;
  const zz = qz * z2;
  const wx = qw * x2;
  const wy = qw * y2;
  const wz = qw * z2;
  return [
    (1 - (yy + zz)) * sx, (xy + wz) * sx, (xz - wy) * sx, 0,
    (xy - wz) * sy, (1 - (xx + zz)) * sy, (yz + wx) * sy, 0,
    (xz + wy) * sz, (yz - wx) * sz, (1 - (xx + yy)) * sz, 0,
    tx, ty, tz, 1,
  ];
}

function apply(m, p) {
  return [
    m[0] * p[0] + m[4] * p[1] + m[8] * p[2] + m[12],
    m[1] * p[0] + m[5] * p[1] + m[9] * p[2] + m[13],
    m[2] * p[0] + m[6] * p[1] + m[10] * p[2] + m[14],
  ];
}

/** The GLB's world-space bounding box, from POSITION accessor min/max only. */
function boundsOf(json) {
  const lo = [Infinity, Infinity, Infinity];
  const hi = [-Infinity, -Infinity, -Infinity];
  const IDENTITY = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1];
  const scene = json.scenes?.[json.scene ?? 0];
  const walk = (index, parent) => {
    const node = json.nodes[index];
    if (!node) return;
    const world = mul(parent, trs(node));
    if (node.mesh !== undefined) {
      for (const prim of json.meshes[node.mesh].primitives ?? []) {
        const acc = json.accessors?.[prim.attributes?.POSITION];
        if (!acc?.min || !acc?.max) continue;
        const d = acc.normalized ? (NORMALIZE[acc.componentType] ?? 1) : 1;
        const min = acc.min.map((v) => v / d);
        const max = acc.max.map((v) => v / d);
        // Every corner: a rotated node can put any of them at an extreme.
        for (let corner = 0; corner < 8; corner++) {
          const p = apply(world, [
            corner & 1 ? max[0] : min[0],
            corner & 2 ? max[1] : min[1],
            corner & 4 ? max[2] : min[2],
          ]);
          for (let i = 0; i < 3; i++) {
            lo[i] = Math.min(lo[i], p[i]);
            hi[i] = Math.max(hi[i], p[i]);
          }
        }
      }
    }
    for (const child of node.children ?? []) walk(child, world);
  };
  for (const root of scene?.nodes ?? []) walk(root, IDENTITY);
  if (!Number.isFinite(lo[0])) return null;
  return [hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2]];
}

const rows = [];
for (const file of readdirSync(MODELS).sort()) {
  if (!file.endsWith('.glb')) continue;
  const kind = file.slice(0, -4);
  let json;
  try {
    json = readGlbJson(readFileSync(join(MODELS, file)));
  } catch {
    json = null;
  }
  const size = json && boundsOf(json);
  if (!size) {
    console.warn(`skipped (no readable bounds): ${kind}`);
    continue;
  }
  const maxDim = Math.max(size[0], size[1], size[2]);
  if (!(maxDim > 0)) continue;
  rows.push([kind, Math.round(maxDim * 10000) / 10000]);
}

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen_dungeon_kit_dims.mjs - do not edit by hand.
// Largest NATIVE dimension (yards) of each dungeon-kit GLB, before the placed-
// asset normalization in render/asset_scale.ts. See that script's header for
// why the two coordinate conventions exist and which side uses which.

export const DUNGEON_KIT_MAX_DIM: Readonly<Record<string, number>> = {
${rows.map(([k, v]) => `  '${k}': ${v},`).join('\n')}
};
`,
);
console.log(`wrote ${OUT} (${rows.length} modules)`);
