// Runs the leveling time-to-kill bench (scripts/leveling_ttk_probe.ts) over every
// class, level and gear tier, one worker process per class, and writes a
// per-cell summary as JSON plus a markdown table.
//
//   npx tsx scripts/leveling_ttk_report.ts [--out docs/balance] [--reps 2]
//       [--classes warrior,mage] [--levels 1-20] [--curve <name>]
//
// With no --curve the bench measures the shipped open-world curve; --curve
// measures an alternative from scripts/leveling_ttk_curves.ts in its place
// (--curve untuned is the raw template ladders).

import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { PlayerClass } from '../src/sim/types';
import { LEVELING_CURVES } from './leveling_ttk_curves';
import {
  LEVELING_CLASSES,
  LEVELING_GEAR_TIERS,
  type LevelingCellResult,
  median,
  runLevelingCells,
} from './leveling_ttk_probe';

interface Args {
  out: string;
  reps: number;
  classes: PlayerClass[];
  levels: number[];
  curve: string | null;
  worker: boolean;
}

function parseArgs(argv: readonly string[]): Args {
  const get = (flag: string): string | undefined => {
    const i = argv.indexOf(flag);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const levelSpec = get('--levels') ?? '1-20';
  const [lo, hi] = levelSpec.split('-').map(Number);
  const levels = Array.from({ length: (hi ?? lo) - lo + 1 }, (_, i) => lo + i);
  const classes = (get('--classes')?.split(',') ?? LEVELING_CLASSES) as PlayerClass[];
  const curve = get('--curve') ?? null;
  if (curve && !LEVELING_CURVES[curve]) {
    throw new Error(`unknown curve ${curve}; known: ${Object.keys(LEVELING_CURVES).join(', ')}`);
  }
  return {
    out: get('--out') ?? 'docs/balance',
    reps: Number(get('--reps') ?? 2),
    classes,
    levels,
    curve,
    worker: argv.includes('--worker'),
  };
}

function runWorker(args: Args): LevelingCellResult[] {
  const curve = args.curve ? LEVELING_CURVES[args.curve] : undefined;
  const cells: LevelingCellResult[] = [];
  for (const cls of args.classes) {
    for (const level of args.levels) {
      cells.push(
        ...runLevelingCells({
          cls,
          level,
          repetitions: args.reps,
          mobTransform: curve?.transform,
          mobStamp: curve?.stamp,
        }),
      );
    }
  }
  return cells;
}

function spawnWorker(cls: PlayerClass, args: Args, outFile: string): Promise<void> {
  const self = fileURLToPath(import.meta.url);
  const childArgs = [
    ...process.execArgv,
    self,
    '--worker',
    '--classes',
    cls,
    '--levels',
    `${args.levels[0]}-${args.levels[args.levels.length - 1]}`,
    '--reps',
    String(args.reps),
    '--out',
    outFile,
    ...(args.curve ? ['--curve', args.curve] : []),
  ];
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, childArgs, { stdio: ['ignore', 'inherit', 'inherit'] });
    child.on('exit', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cls} worker exited ${code}`)),
    );
  });
}

function fmt(n: number, digits = 1): string {
  return Number.isFinite(n) ? n.toFixed(digits) : '-';
}

export function summarize(cells: readonly LevelingCellResult[], title: string): string {
  const classes = [...new Set(cells.map((c) => c.cls))];
  const levels = [...new Set(cells.map((c) => c.level))].sort((a, b) => a - b);
  const lines: string[] = [`# ${title}`, ''];
  lines.push(
    'Each cell: median seconds to kill a same-level normal open-world mob, then the median',
    'damage taken per kill as a share of max health. "x" counts deaths. Generated by',
    '`scripts/leveling_ttk_report.ts`; method in `scripts/leveling_ttk_probe.ts`.',
    '',
  );
  for (const tier of LEVELING_GEAR_TIERS) {
    lines.push(`## Gear tier: ${tier}`, '');
    lines.push(`| Level | ${classes.join(' | ')} | All classes |`);
    lines.push(`|---|${classes.map(() => '---').join('|')}|---|`);
    for (const level of levels) {
      const row: string[] = [];
      const all: number[] = [];
      for (const cls of classes) {
        const cell = cells.find((c) => c.cls === cls && c.level === level && c.tier === tier);
        if (!cell) {
          row.push('-');
          continue;
        }
        const secs = cell.fights.map((f) => f.seconds);
        all.push(...secs);
        const dmg = median(cell.fights.map((f) => f.damageTakenPct)) * 100;
        const deaths = cell.fights.filter((f) => f.outcome === 'died').length;
        row.push(`${fmt(median(secs))}s ${fmt(dmg, 0)}%${deaths ? ` ${deaths}x` : ''}`);
      }
      lines.push(`| ${level} | ${row.join(' | ')} | ${fmt(median(all))}s |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  if (args.worker) {
    writeFileSync(args.out, JSON.stringify(runWorker(args)));
    return;
  }
  mkdirSync(args.out, { recursive: true });
  const tag = args.curve ? `leveling-ttk-${args.curve}` : 'leveling-ttk';
  const partFiles = args.classes.map((cls) => path.join(args.out, `.${tag}-${cls}.part.json`));
  await Promise.all(args.classes.map((cls, i) => spawnWorker(cls, args, partFiles[i])));
  const cells: LevelingCellResult[] = partFiles.flatMap(
    (file) => JSON.parse(readFileSync(file, 'utf8')) as LevelingCellResult[],
  );
  for (const file of partFiles) rmSync(file, { force: true });
  const compact = cells.map((c) => ({
    cls: c.cls,
    level: c.level,
    tier: c.tier,
    playerMaxHp: c.playerMaxHp,
    fights: c.fights.length,
    medianSeconds: median(c.fights.map((f) => f.seconds)),
    medianDamageTaken: median(c.fights.map((f) => f.damageTaken)),
    deaths: c.fights.filter((f) => f.outcome !== 'killed').length,
  }));
  writeFileSync(path.join(args.out, `${tag}.json`), `${JSON.stringify(compact, null, 1)}\n`);
  const title = args.curve
    ? `Leveling time-to-kill, curve "${args.curve}"`
    : 'Leveling time-to-kill, shipped open-world curve';
  writeFileSync(path.join(args.out, `${tag}.md`), `${summarize(cells, title)}\n`);
  console.log(`wrote ${path.join(args.out, `${tag}.{json,md}`)} (${cells.length} cells)`);
}

void main();
