// GENERATED by scripts/gen_published_maps.mjs - do not edit by hand.
// The registry of Studio-published maps. The game client boots one with
// ?map=<slug> (src/main.ts); dynamic import keeps map bytes out of the main
// bundle until a map is actually chosen.
import type { WorldContent } from '../types';

export interface PublishedMapEntry {
  slug: string;
  name: string;
  seed: number;
  load(): Promise<WorldContent>;
}

export const PUBLISHED_MAPS: readonly PublishedMapEntry[] = [
  {
    slug: "deepglass",
    name: "deepglass",
    seed: 20261,
    load: async () => (await import('./deepglass.generated')).loadPublishedMap(),
  },
];

export function publishedMapBySlug(slug: string): PublishedMapEntry | undefined {
  return PUBLISHED_MAPS.find((m) => m.slug === slug);
}
