// ---------------------------------------------------------------------------
// The CLASSIC WARRIOR: the pre-overhaul warrior kit (branch state 8404b398a),
// resurrected VERBATIM as its own class so PTR testers can compare the two
// warrior designs side by side (owner request 2026-07-11). Every ability the
// old kit shipped or talent-granted was retuned in place by the overhaul, so
// each record here is the 8404b398a body under a cw_-prefixed id; the class
// and its talents reference only cw_ ids. Data-as-code: correctly large.
// Regeneration: scripts are one-off; the source of truth is the 8404b398a tree.
// ---------------------------------------------------------------------------

import type { AbilityDef } from '../types';
// Type-only import: erased at compile time, so no runtime cycle with classes.ts.
import type { ClassDef } from './classes';

export const WARRIOR_CLASSIC_CLASS: ClassDef = {
  id: 'warrior_classic',
  name: 'Classic Warrior',
  baseStats: { str: 23, agi: 20, sta: 22, int: 10, spi: 11, armor: 50 },
  statsPerLevel: { str: 2, agi: 1, sta: 2, int: 0, spi: 0, armor: 12 },
  baseHp: 50,
  hpPerLevel: 18,
  baseMana: 100, // rage cap
  manaPerLevel: 0,
  resourceType: 'rage',
  startWeapon: 'worn_sword',
  startChest: 'recruit_tunic',
  startItems: [{ itemId: 'baked_bread', count: 5 }],
  abilities: [
    'cw_heroic_strike',
    'cw_battle_shout',
    'cw_commanding_shout',
    'cw_charge',
    'cw_rend',
    'cw_thunder_clap',
    'cw_hamstring',
    'cw_bloodrage',
    'cw_overpower',
    'cw_execute',
    'cw_slam',
    'cw_cleave',
    'cw_defensive_stance',
    'cw_demoralizing_shout',
    'cw_sunder_armor',
    'cw_taunt',
  ],
  color: 0xc79c6e,
};

export const WARRIOR_CLASSIC_ABILITIES: Record<string, AbilityDef> = {
  cw_heroic_strike: {
    id: 'cw_heroic_strike',
    name: 'Reaver Strike',
    class: 'warrior_classic',
    learnLevel: 1,
    cost: 15,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    onNextSwing: true,
    offGcd: true,
    threat: { flat: 20 }, // classic per-rank values: 20/39/59/78
    effects: [{ type: 'weaponDamage', bonus: 11 }],
    ranks: [
      {
        rank: 2,
        level: 8,
        cost: 15,
        threatFlat: 39,
        effects: [{ type: 'weaponDamage', bonus: 21 }],
      },
      {
        rank: 3,
        level: 14,
        cost: 15,
        threatFlat: 59,
        effects: [{ type: 'weaponDamage', bonus: 32 }],
      },
      {
        rank: 4,
        level: 20,
        cost: 15,
        threatFlat: 78,
        effects: [{ type: 'weaponDamage', bonus: 44 }],
      },
    ],
    description: 'A strong attack that increases melee damage by $d. Activates on your next swing.',
  },
  cw_battle_shout: {
    id: 'cw_battle_shout',
    name: 'Iron Bellow',
    class: 'warrior_classic',
    learnLevel: 1,
    cost: 10,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    exclusiveGroup: 'warrior_shout',
    effects: [{ type: 'buffTarget', kind: 'buff_ap_pct', value: 10, duration: 120, party: true }],
    description: 'A shout that increases the attack power of all party members by $b% for 2 min.',
  },
  cw_commanding_shout: {
    id: 'cw_commanding_shout',
    name: 'Bolstering Cry',
    class: 'warrior_classic',
    learnLevel: 11,
    cost: 10,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    exclusiveGroup: 'warrior_shout',
    effects: [{ type: 'selfBuff', kind: 'buff_sta', value: 6, duration: 120 }],
    ranks: [
      {
        rank: 2,
        level: 24,
        cost: 10,
        effects: [{ type: 'selfBuff', kind: 'buff_sta', value: 11, duration: 120 }],
      },
    ],
    description: 'Increases your Stamina by $b for 2 min.',
  },
  cw_charge: {
    id: 'cw_charge',
    name: 'Onrush',
    class: 'warrior_classic',
    learnLevel: 4,
    cost: 0,
    castTime: 0,
    cooldown: 15,
    range: 25,
    minRange: 8,
    school: 'physical',
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'charge' }, { type: 'stun', duration: 1 }],
    description: 'Charges an enemy, generating 9 rage and stunning it for 1 sec. 8-25 yd range.',
  },
  cw_rend: {
    id: 'cw_rend',
    name: 'Deep Gash',
    class: 'warrior_classic',
    learnLevel: 4,
    cost: 10,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 15, duration: 9, interval: 3 }],
    ranks: [
      {
        rank: 2,
        level: 10,
        cost: 10,
        effects: [{ type: 'dot', total: 21, duration: 9, interval: 3 }],
      },
      {
        rank: 3,
        level: 16,
        cost: 10,
        effects: [{ type: 'dot', total: 36, duration: 12, interval: 3 }],
      },
    ],
    description: 'Wounds the target, causing them to bleed for $d damage over $t sec.',
  },
  cw_thunder_clap: {
    id: 'cw_thunder_clap',
    name: 'Quaking Blow',
    class: 'warrior_classic',
    learnLevel: 6,
    cost: 20,
    castTime: 0,
    cooldown: 4,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    threat: { mult: 2.5 }, // classic: thunder clap damage causes 2.5x threat
    effects: [
      { type: 'aoeDamage', min: 12, max: 14, radius: 8 },
      { type: 'aoeAttackSpeed', mult: 1.1, duration: 10, radius: 8 },
    ],
    ranks: [
      {
        rank: 2,
        level: 14,
        cost: 20,
        effects: [
          { type: 'aoeDamage', min: 23, max: 27, radius: 8 },
          { type: 'aoeAttackSpeed', mult: 1.1, duration: 10, radius: 8 },
        ],
      },
      {
        rank: 3,
        level: 20,
        cost: 20,
        effects: [
          { type: 'aoeDamage', min: 37, max: 43, radius: 8 },
          { type: 'aoeAttackSpeed', mult: 1.1, duration: 10, radius: 8 },
        ],
      },
    ],
    description: 'Blasts nearby enemies for $d damage and slows their attacks by 10% for 10 sec.',
  },
  cw_hamstring: {
    id: 'cw_hamstring',
    name: 'Hobbling Cut',
    class: 'warrior_classic',
    learnLevel: 8,
    cost: 10,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [
      { type: 'directDamage', min: 5, max: 5 },
      { type: 'slow', mult: 0.5, duration: 15 },
    ],
    ranks: [
      {
        rank: 2,
        level: 16,
        cost: 10,
        effects: [
          { type: 'directDamage', min: 12, max: 12 },
          { type: 'slow', mult: 0.5, duration: 15 },
        ],
      },
    ],
    description: 'Maims the enemy for $d damage, slowing its movement by 50% for 15 sec.',
  },
  cw_bloodrage: {
    id: 'cw_bloodrage',
    name: 'Blood Toll',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 60,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [
      { type: 'selfDamagePctMax', pct: 0.08 },
      { type: 'gainResource', amount: 10 },
    ],
    description: 'Generates 10 rage at the cost of health.',
  },
  cw_overpower: {
    id: 'cw_overpower',
    name: 'Redhand',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 5,
    castTime: 0,
    cooldown: 5,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    requiresDodgeProc: true,
    effects: [{ type: 'weaponStrike', bonus: 5, cannotBeDodged: true }],
    ranks: [
      {
        rank: 2,
        level: 16,
        cost: 5,
        effects: [{ type: 'weaponStrike', bonus: 15, cannotBeDodged: true }],
      },
    ],
    description:
      'Instant attack for weapon damage plus $d. Only usable after the target dodges. Cannot be dodged.',
  },
  cw_execute: {
    id: 'cw_execute',
    name: 'Early Grave',
    class: 'warrior_classic',
    learnLevel: 14,
    cost: 15,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    requiresTargetHpBelow: 0.2,
    effects: [{ type: 'directDamage', min: 60, max: 75 }],
    description:
      'Attempt to finish off a wounded foe, causing $d damage. Only usable on enemies below 20% health.',
  },
  cw_slam: {
    id: 'cw_slam',
    name: 'Brute Swing',
    class: 'warrior_classic',
    learnLevel: 16,
    cost: 15,
    castTime: 1.5,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 25 }],
    description: 'Slams the opponent for weapon damage plus $d.',
  },
  cw_cleave: {
    id: 'cw_cleave',
    name: 'Reaping Arc',
    class: 'warrior_classic',
    learnLevel: 18,
    cost: 20,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    threat: { flat: 30 }, // classic 100 at rank 5/level 58, scaled to the 1-20 band
    effects: [{ type: 'aoeDamage', min: 20, max: 26, radius: 5 }],
    description: 'A sweeping strike that hits all enemies in front of you for $d damage.',
  },
  cw_defensive_stance: {
    id: 'cw_defensive_stance',
    name: 'Guarded Stance',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 1,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'defensive_stance', value: 0.9, duration: 3600 }],
    description:
      'A defensive combat stance: you generate 30% more threat but deal and take 10% less damage. Cast again to leave the stance.',
  },
  cw_demoralizing_shout: {
    id: 'cw_demoralizing_shout',
    name: 'Direhowl',
    class: 'warrior_classic',
    learnLevel: 14,
    cost: 10,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'aoeAttackPower', amount: 30, duration: 30, radius: 10 }],
    ranks: [
      {
        rank: 2,
        level: 20,
        cost: 10,
        effects: [{ type: 'aoeAttackPower', amount: 45, duration: 30, radius: 10 }],
      },
    ],
    description:
      'Lets out a fearsome shout, reducing the attack power of all nearby enemies by $b for 30 sec.',
  },
  cw_sunder_armor: {
    id: 'cw_sunder_armor',
    name: 'Armor Shear',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 15,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    threat: { flat: 100 }, // classic rank-1 value (260 by rank 5 at 58)
    effects: [{ type: 'sunder', armor: 25, maxStacks: 5 }],
    ranks: [
      {
        rank: 2,
        level: 16,
        cost: 15,
        threatFlat: 130,
        effects: [{ type: 'sunder', armor: 40, maxStacks: 5 }],
      },
    ],
    description:
      "Sunders the target's armor, reducing it by $d% per application. Stacks up to 5 times. Generates a high amount of threat.",
  },
  cw_taunt: {
    id: 'cw_taunt',
    name: 'Goad',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 10,
    range: 8,
    school: 'physical',
    requiresTarget: true,
    offGcd: true,
    effects: [{ type: 'taunt' }],
    description:
      'Taunts the target: your threat rises to match its most hated enemy and it is compelled to attack you for 3 sec.',
  },

  // ====================== MAGE ======================,
  cw_bloodthirst: {
    id: 'cw_bloodthirst',
    name: 'Bloodletting',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 30,
    castTime: 0,
    cooldown: 6,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 35, weaponMult: 0.6 }],
    description:
      'Instantly attack in a blood frenzy for 60% weapon damage plus $d. (Fury signature)',
  },
  cw_mortal_strike: {
    id: 'cw_mortal_strike',
    name: 'Maiming Strike',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 30,
    castTime: 0,
    cooldown: 6,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    threat: { mult: 1.2 },
    effects: [{ type: 'weaponStrike', bonus: 40 }],
    description: 'A vicious strike dealing weapon damage plus $d. (Arms signature)',
  },
  cw_shield_slam: {
    id: 'cw_shield_slam',
    name: 'Shieldcrack',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 20,
    castTime: 0,
    cooldown: 6,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    threat: { flat: 110 },
    effects: [{ type: 'weaponStrike', bonus: 30, weaponMult: 0.5 }],
    description:
      'Slam the target with your shield for 50% weapon damage plus $d and massive threat. (Protection signature)',
  },
  cw_whirlwind: {
    id: 'cw_whirlwind',
    name: 'Bladed Gyre',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 25,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'aoeDamage', min: 30, max: 42, radius: 8 }],
    description: 'Spin in a deadly arc, striking all nearby enemies for $d. (Fury talent)',
  },
  cw_berserker_rage: {
    id: 'cw_berserker_rage',
    name: 'Seething Fury',
    class: 'warrior_classic',
    learnLevel: 10,
    cost: 0,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'gainResource', amount: 20 }],
    description: 'Enter a berserker rage, generating 20 rage. (Warrior talent)',
  },
};
