// Dungeon content: mob templates that only spawn inside instances, spawn
// lists, and the DungeonDef registry merged by sim/data.ts.

import type { DungeonDef, DungeonSpawn, ItemDef, MobTemplate } from '../types';
import { MOLTENHEART_CHROMA_ID, MOLTENHEART_CHROMA_ITEM_ID } from './skins';

// Undermount raid gear. Wing 1 and 2 primary-stat sums are the engine-derived
// ilvl 33 epic budgets: feet 15, mainhand 23, ring 14, legs 21, and waist 16.
// Volzharr's ilvl 35 budgets are chest/mainhand 25, ring 15, feet 16, waist 17,
// and 33 for Corebreaker's two-hand stat multiplier.
// Unless a number is one of those budgets or a PRD-locked loot chance, numeric
// armor, weapon, rating, and vendor values in this block are (tuning).
export const UNDERMOUNT_ITEMS: Record<string, ItemDef> = {
  slag_tempered_sabatons: {
    id: 'slag_tempered_sabatons',
    name: 'Slag-Tempered Sabatons',
    kind: 'armor',
    slot: 'feet',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 125, str: 8, sta: 7 },
    sellValue: 4500,
    requiredClass: ['warrior', 'paladin'],
  },
  glasswalker_treads: {
    id: 'glasswalker_treads',
    name: 'Glasswalker Treads',
    kind: 'armor',
    slot: 'feet',
    armorType: 'leather',
    quality: 'epic',
    stats: { armor: 92, agi: 9, sta: 6 },
    critRating: 40,
    sellValue: 4500,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  twice_fired_slippers: {
    id: 'twice_fired_slippers',
    name: 'Twice-Fired Slippers',
    kind: 'armor',
    slot: 'feet',
    armorType: 'cloth',
    quality: 'epic',
    stats: { armor: 55, int: 9, spi: 6 },
    sellValue: 4500,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
  },
  stokebrand_striders: {
    id: 'stokebrand_striders',
    name: 'Stokebrand Striders',
    kind: 'armor',
    slot: 'feet',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 125, int: 8, sta: 7 },
    hasteRating: 40,
    sellValue: 4500,
    requiredClass: ['shaman'],
  },
  saans_stoking_iron: {
    id: 'saans_stoking_iron',
    name: "Saan's Stoking Iron",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 40, max: 65, speed: 3 },
    stats: { int: 15, spi: 8 },
    hasteRating: 65,
    sellValue: 7000,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  glassblowers_shiv: {
    id: 'glassblowers_shiv',
    name: "Glassblower's Shiv",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 27, max: 43, speed: 2, dagger: true },
    stats: { agi: 16, sta: 7 },
    critRating: 65,
    sellValue: 7000,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  sluicebearer: {
    id: 'sluicebearer',
    name: 'Sluicebearer',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 34, max: 50, speed: 2.4 },
    stats: { int: 14, spi: 9 },
    sellValue: 7000,
    requiredClass: ['priest', 'shaman', 'paladin', 'druid'],
  },
  cindertoad_signet: {
    id: 'cindertoad_signet',
    name: 'Cindertoad Signet',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    stats: { armor: 40, sta: 14 },
    sellValue: 5000,
  },
  ring_of_the_first_quench: {
    id: 'ring_of_the_first_quench',
    name: 'Ring of the First Quench',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    stats: { int: 8, spi: 6 },
    critRating: 40,
    sellValue: 5000,
    requiredClass: ['priest', 'shaman', 'paladin', 'druid'],
  },
  coalglow_band: {
    id: 'coalglow_band',
    name: 'Coalglow Band',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    stats: { int: 14 },
    critRating: 40,
    sellValue: 5000,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'druid'],
  },
  crownforged_warleggings: {
    id: 'crownforged_warleggings',
    name: 'Crownforged Warleggings',
    kind: 'armor',
    slot: 'legs',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 210, str: 11, sta: 10 },
    critRating: 40,
    sellValue: 6000,
    requiredClass: ['warrior', 'paladin'],
    set: 'crownforged',
  },
  nighttalon_prowlers: {
    id: 'nighttalon_prowlers',
    name: 'Nighttalon Prowlers',
    kind: 'armor',
    slot: 'legs',
    armorType: 'leather',
    quality: 'epic',
    stats: { armor: 155, agi: 13, sta: 8 },
    critRating: 40,
    sellValue: 6000,
    requiredClass: ['rogue', 'hunter', 'druid'],
    set: 'nighttalon',
  },
  soulflame_kilt: {
    id: 'soulflame_kilt',
    name: 'Soulflame Kilt',
    kind: 'armor',
    slot: 'legs',
    armorType: 'cloth',
    quality: 'epic',
    stats: { armor: 90, int: 13, spi: 8 },
    hasteRating: 40,
    sellValue: 6000,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
    set: 'soulflame',
  },
  stormcallers_legwraps: {
    id: 'stormcallers_legwraps',
    name: "Stormcaller's Legwraps",
    kind: 'armor',
    slot: 'legs',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 210, int: 12, sta: 9 },
    hasteRating: 40,
    sellValue: 6000,
    requiredClass: ['shaman'],
    set: 'stormcallers',
  },
  the_even_temper: {
    id: 'the_even_temper',
    name: 'The Even Temper',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 43, max: 62, speed: 3 },
    stats: { str: 16, sta: 7 },
    critRating: 65,
    sellValue: 7000,
    requiredClass: ['warrior', 'shaman', 'paladin'],
  },
  cinderarc_odrenns_rod: {
    id: 'cinderarc_odrenns_rod',
    name: "Cinderarc, Odrenn's Rod",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 31, max: 46, speed: 2.2 },
    stats: { int: 15, spi: 8 },
    hasteRating: 65,
    sellValue: 7000,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  twicetempered_girdle: {
    id: 'twicetempered_girdle',
    name: 'Twicetempered Girdle',
    kind: 'armor',
    slot: 'waist',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 145, str: 9, sta: 7 },
    sellValue: 5000,
    requiredClass: ['warrior', 'paladin'],
  },
  ashwalk_sandals: {
    id: 'ashwalk_sandals',
    name: 'Ashwalk Sandals',
    kind: 'armor',
    slot: 'feet',
    armorType: 'cloth',
    quality: 'epic',
    stats: { armor: 55, int: 10, spi: 5 },
    hasteRating: 40,
    sellValue: 4500,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
  },
  quenchsilk_cord: {
    id: 'quenchsilk_cord',
    name: 'Quenchsilk Cord',
    kind: 'armor',
    slot: 'waist',
    armorType: 'cloth',
    quality: 'epic',
    stats: { armor: 60, int: 10, spi: 6 },
    hasteRating: 40,
    sellValue: 5000,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
  },
  slakeleather_belt: {
    id: 'slakeleather_belt',
    name: 'Slakeleather Belt',
    kind: 'armor',
    slot: 'waist',
    armorType: 'leather',
    quality: 'epic',
    stats: { armor: 105, agi: 10, sta: 6 },
    critRating: 40,
    sellValue: 5000,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  crownforged_heartplate: {
    id: 'crownforged_heartplate',
    name: 'Crownforged Heartplate',
    kind: 'armor',
    slot: 'chest',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 255, str: 13, sta: 12 },
    critRating: 40,
    sellValue: 7500,
    requiredClass: ['warrior', 'paladin'],
    set: 'crownforged',
  },
  nighttalon_emberweave: {
    id: 'nighttalon_emberweave',
    name: 'Nighttalon Emberweave',
    kind: 'armor',
    slot: 'chest',
    armorType: 'leather',
    quality: 'epic',
    stats: { armor: 190, agi: 15, sta: 10 },
    critRating: 40,
    sellValue: 7500,
    requiredClass: ['rogue', 'hunter', 'druid'],
    set: 'nighttalon',
  },
  soulflame_vestments: {
    id: 'soulflame_vestments',
    name: 'Soulflame Vestments',
    kind: 'armor',
    slot: 'chest',
    armorType: 'cloth',
    quality: 'epic',
    stats: { armor: 110, int: 15, spi: 10 },
    hasteRating: 40,
    sellValue: 7500,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
    set: 'soulflame',
  },
  stormcallers_hauberk: {
    id: 'stormcallers_hauberk',
    name: "Stormcaller's Hauberk",
    kind: 'armor',
    slot: 'chest',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 255, int: 14, sta: 11 },
    hasteRating: 40,
    sellValue: 7500,
    requiredClass: ['shaman'],
    set: 'stormcallers',
  },
  volzharrs_knucklestone: {
    id: 'volzharrs_knucklestone',
    name: "Volzharr's Knucklestone",
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    stats: { str: 8, sta: 7 },
    critRating: 40,
    sellValue: 6500,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  magmastrider_greaves: {
    id: 'magmastrider_greaves',
    name: 'Magmastrider Greaves',
    kind: 'armor',
    slot: 'feet',
    armorType: 'mail',
    quality: 'epic',
    stats: { armor: 135, str: 9, sta: 7 },
    sellValue: 6000,
    requiredClass: ['warrior', 'paladin'],
  },
  footwraps_of_the_waking_floor: {
    id: 'footwraps_of_the_waking_floor',
    name: 'Footwraps of the Waking Floor',
    kind: 'armor',
    slot: 'feet',
    armorType: 'cloth',
    quality: 'epic',
    stats: { armor: 60, int: 10, spi: 6 },
    hasteRating: 40,
    sellValue: 6000,
    requiredClass: ['mage', 'priest', 'warlock', 'druid'],
  },
  forgeheat_cinch: {
    id: 'forgeheat_cinch',
    name: 'Forgeheat Cinch',
    kind: 'armor',
    slot: 'waist',
    armorType: 'leather',
    quality: 'epic',
    stats: { armor: 112, agi: 10, sta: 7 },
    hasteRating: 40,
    sellValue: 6500,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  corebreaker_heart_of_the_undermount: {
    id: 'corebreaker_heart_of_the_undermount',
    name: 'Corebreaker, Heart of the Undermount',
    kind: 'weapon',
    slot: 'mainhand',
    hand: 'twohand',
    quality: 'epic',
    weapon: { min: 56, max: 86, speed: 3.6 },
    stats: { str: 20, sta: 13 },
    critRating: 65,
    hasteRating: 20,
    sellValue: 10000,
    requiredClass: ['warrior', 'hunter', 'shaman', 'paladin'],
  },
  the_last_restraint: {
    id: 'the_last_restraint',
    name: 'The Last Restraint',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 45, max: 65, speed: 3.2 },
    stats: { int: 16, spi: 9 },
    hasteRating: 65,
    sellValue: 10000,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  band_of_the_ninth_quench: {
    id: 'band_of_the_ninth_quench',
    name: 'Band of the Ninth Quench',
    kind: 'armor',
    slot: 'ring',
    quality: 'epic',
    stats: { str: 8, agi: 7 },
    hasteRating: 40,
    sellValue: 6500,
    requiredClass: ['warrior', 'paladin', 'hunter', 'rogue', 'shaman', 'druid'],
  },
  [MOLTENHEART_CHROMA_ITEM_ID]: {
    id: MOLTENHEART_CHROMA_ITEM_ID,
    name: 'Moltenheart',
    kind: 'tool',
    quality: 'epic',
    use: { type: 'mechChroma', chromaId: MOLTENHEART_CHROMA_ID },
    sellValue: 0,
    noVendorSell: true,
    noDiscard: true,
    noMarketList: true,
  },
};

const UNDERMOUNT_WING1_LOOT: MobTemplate['loot'] = [
  { copper: 150000, chance: 1 }, // raid payout (tuning)
  { itemId: 'slag_tempered_sabatons', chance: 0.25, rollGroup: 'undermount_wing1_guaranteed' },
  { itemId: 'glasswalker_treads', chance: 0.25, rollGroup: 'undermount_wing1_guaranteed' },
  { itemId: 'twice_fired_slippers', chance: 0.25, rollGroup: 'undermount_wing1_guaranteed' },
  { itemId: 'stokebrand_striders', chance: 0.25, rollGroup: 'undermount_wing1_guaranteed' },
  { itemId: 'saans_stoking_iron', chance: 0.12, rollGroup: 'undermount_wing1_bonus' },
  { itemId: 'glassblowers_shiv', chance: 0.1, rollGroup: 'undermount_wing1_bonus' },
  { itemId: 'sluicebearer', chance: 0.1, rollGroup: 'undermount_wing1_bonus' },
  { itemId: 'cindertoad_signet', chance: 0.08, rollGroup: 'undermount_wing1_bonus' },
  { itemId: 'ring_of_the_first_quench', chance: 0.08, rollGroup: 'undermount_wing1_bonus' },
  { itemId: 'coalglow_band', chance: 0.07, rollGroup: 'undermount_wing1_bonus' },
];

const UNDERMOUNT_WING2_LOOT: MobTemplate['loot'] = [
  { copper: 150000, chance: 1 }, // raid payout (tuning)
  { itemId: 'crownforged_warleggings', chance: 0.25, rollGroup: 'undermount_wing2_guaranteed' },
  { itemId: 'nighttalon_prowlers', chance: 0.25, rollGroup: 'undermount_wing2_guaranteed' },
  { itemId: 'soulflame_kilt', chance: 0.25, rollGroup: 'undermount_wing2_guaranteed' },
  { itemId: 'stormcallers_legwraps', chance: 0.25, rollGroup: 'undermount_wing2_guaranteed' },
  { itemId: 'the_even_temper', chance: 0.12, rollGroup: 'undermount_wing2_bonus' },
  { itemId: 'cinderarc_odrenns_rod', chance: 0.12, rollGroup: 'undermount_wing2_bonus' },
  { itemId: 'twicetempered_girdle', chance: 0.1, rollGroup: 'undermount_wing2_bonus' },
  { itemId: 'ashwalk_sandals', chance: 0.08, rollGroup: 'undermount_wing2_bonus' },
  { itemId: 'quenchsilk_cord', chance: 0.07, rollGroup: 'undermount_wing2_bonus' },
  { itemId: 'slakeleather_belt', chance: 0.06, rollGroup: 'undermount_wing2_bonus' },
];

const UNDERMOUNT_WING3_LOOT: MobTemplate['loot'] = [
  { copper: 150000, chance: 1 }, // 15g raid payout
  { itemId: 'crownforged_heartplate', chance: 0.25, rollGroup: 'undermount_wing3_t2_chests' },
  { itemId: 'nighttalon_emberweave', chance: 0.25, rollGroup: 'undermount_wing3_t2_chests' },
  { itemId: 'soulflame_vestments', chance: 0.25, rollGroup: 'undermount_wing3_t2_chests' },
  { itemId: 'stormcallers_hauberk', chance: 0.25, rollGroup: 'undermount_wing3_t2_chests' },
  { itemId: 'volzharrs_knucklestone', chance: 0.25, rollGroup: 'undermount_wing3_offpieces' },
  { itemId: 'magmastrider_greaves', chance: 0.25, rollGroup: 'undermount_wing3_offpieces' },
  {
    itemId: 'footwraps_of_the_waking_floor',
    chance: 0.25,
    rollGroup: 'undermount_wing3_offpieces',
  },
  { itemId: 'forgeheat_cinch', chance: 0.25, rollGroup: 'undermount_wing3_offpieces' },
  {
    itemId: 'corebreaker_heart_of_the_undermount',
    chance: 0.03,
    rollGroup: 'undermount_wing3_chase',
  },
  { itemId: 'the_last_restraint', chance: 0.03, rollGroup: 'undermount_wing3_chase' },
  { itemId: 'band_of_the_ninth_quench', chance: 0.1, rollGroup: 'undermount_wing3_chase' },
  { itemId: MOLTENHEART_CHROMA_ITEM_ID, chance: 0.01, rollGroup: 'undermount_wing3_chase' },
];

export const DUNGEON_MOBS: Record<string, MobTemplate> = {
  // ---- The Hollow Crypt (5-player elite instance) ----
  crypt_shambler: {
    id: 'crypt_shambler',
    name: 'Crypt Shambler',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 2.4,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [
      { copper: 90, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.8 },
    ],
    scale: 1.1,
    color: 0xb8c4c4,
  },
  hollow_acolyte: {
    id: 'hollow_acolyte',
    name: 'Hollow Acolyte',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [
      { copper: 110, chance: 1 },
      { itemId: 'linen_scrap', chance: 0.6 },
    ],
    scale: 1.0,
    color: 0x5b2c6f,
  },
  bonechill_widow: {
    id: 'bonechill_widow',
    name: 'Bonechill Widow',
    minLevel: 8,
    maxLevel: 9,
    family: 'spider',
    elite: true,
    hpBase: 48,
    hpPerLevel: 19,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 1.8,
    armorPerLevel: 12,
    moveSpeed: 8,
    aggroRadius: 13,
    loot: [
      { copper: 120, chance: 1 },
      { itemId: 'spider_leg', chance: 0.7 },
    ],
    scale: 1.25,
    color: 0xd6eaf8,
  },
  sexton_marrow: {
    id: 'sexton_marrow',
    name: 'Sexton Marrow',
    minLevel: 9,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    // Named mid-boss: the boss CC/snare immunity rule applies on both
    // difficulties even without the boss: true flag (see morthen).
    ccImmune: true,
    slowImmune: true,
    hpBase: 110,
    hpPerLevel: 24,
    dmgBase: 9,
    dmgPerLevel: 2.5,
    attackSpeed: 2.2,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 14,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [
      { copper: 400, chance: 1 },
      { itemId: 'quilted_trousers', chance: 0.4 },
      { itemId: 'oiled_boots', chance: 0.4 },
    ],
    scale: 1.2,
    color: 0x839192,
  },
  morthen: {
    id: 'morthen',
    name: 'Morthen the Gravecaller',
    minLevel: 10,
    maxLevel: 10,
    family: 'undead',
    elite: true,
    boss: true,
    // Endgame-instance bosses can be neither controlled nor kited on EITHER
    // difficulty (the heroic entity stamp in instances/difficulty.ts stays as
    // belt and braces): the normal-difficulty economy retune assumes swings land.
    ccImmune: true,
    slowImmune: true,
    hpBase: 230,
    hpPerLevel: 32,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.6,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 16,
    aoePulse: { min: 12, max: 18, radius: 12, every: 10, name: 'Shadow Pulse' },
    loot: [
      { copper: 2500, chance: 1 },
      { itemId: 'cryptbone_greaves', chance: 0.34, rollGroup: 'morthen_guaranteed_uncommon' },
      { itemId: 'quilted_trousers', chance: 0.33, rollGroup: 'morthen_guaranteed_uncommon' },
      { itemId: 'oiled_boots', chance: 0.33, rollGroup: 'morthen_guaranteed_uncommon' },
      { itemId: 'greyjaw_hide_boots', chance: 0.25, rollGroup: 'morthen_bonus' },
      { itemId: 'gravewoven_bag', chance: 0.2, rollGroup: 'morthen_bonus' },
      { itemId: 'cryptbone_helm', chance: 0.18, rollGroup: 'morthen_bonus' },
      { itemId: 'cryptbone_pauldrons', chance: 0.18, rollGroup: 'morthen_bonus' },
    ],
    scale: 1.35,
    color: 0x4a235a,
  },

  // ---- The Sunken Bastion (5-player elite instance, ~L13) ----
  bastion_revenant: {
    id: 'bastion_revenant',
    name: 'Bastion Revenant',
    minLevel: 12,
    maxLevel: 13,
    family: 'undead',
    elite: true,
    hpBase: 54,
    hpPerLevel: 21,
    dmgBase: 9,
    dmgPerLevel: 2.4,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 6.5,
    aggroRadius: 12,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [
      { copper: 150, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.7 },
      { itemId: 'mistveil_cord', chance: 0.06, rollGroup: 'revenant_bonus' },
    ],
    scale: 1.1,
    color: 0x7fa8a0,
    mortalStrike: { chance: 0.3, healReduction: 0.5, duration: 6, name: 'Maiming Strike' },
  },
  tidebound_acolyte: {
    id: 'tidebound_acolyte',
    name: 'Tidebound Acolyte',
    minLevel: 12,
    maxLevel: 13,
    family: 'humanoid',
    elite: true,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.0,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [
      { copper: 170, chance: 1 },
      { itemId: 'linen_scrap', chance: 0.5 },
      { itemId: 'mistveil_grips', chance: 0.06, rollGroup: 'acolyte_bonus' },
    ],
    desperateHeal: { belowHpPct: 0.3, healPct: 0.25 },
    scale: 1.0,
    color: 0x1f618d,
  },
  drowned_thrall: {
    id: 'drowned_thrall',
    name: 'Drowned Thrall',
    minLevel: 11,
    maxLevel: 11,
    family: 'undead',
    hpBase: 40,
    hpPerLevel: 14,
    dmgBase: 7,
    dmgPerLevel: 2.0,
    attackSpeed: 2.0,
    armorPerLevel: 10,
    moveSpeed: 7.5,
    aggroRadius: 12,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [], // summoned add — nothing to loot
    scale: 0.95,
    color: 0x6fae9e,
  },
  knight_commander_olen: {
    id: 'knight_commander_olen',
    name: 'Knight-Commander Olen',
    minLevel: 13,
    maxLevel: 13,
    family: 'undead',
    elite: true,
    // Named mid-boss: CC- and snare-immune on both difficulties (see morthen).
    ccImmune: true,
    slowImmune: true,
    hpBase: 120,
    hpPerLevel: 26,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 14,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [
      { copper: 800, chance: 1 },
      { itemId: 'trollhide_leggings', chance: 0.5, rollGroup: 'olen_guaranteed_uncommon' },
      { itemId: 'marshstrider_boots', chance: 0.5, rollGroup: 'olen_guaranteed_uncommon' },
      { itemId: 'fenmist_robe', chance: 0.25, rollGroup: 'olen_bonus' },
      { itemId: 'tideguard_greaves', chance: 0.1, rollGroup: 'olen_bonus' },
      { itemId: 'tideguard_sabatons', chance: 0.1, rollGroup: 'olen_bonus' },
      { itemId: 'eelscale_leggings', chance: 0.1, rollGroup: 'olen_bonus' },
    ], // his greaves are Maren's quest reward, not a drop
    scale: 1.2,
    color: 0x95a5a6,
    cleave: { radius: 8, mult: 0.6, name: 'Reaping Arc' },
  },
  vael_the_mistcaller: {
    id: 'vael_the_mistcaller',
    name: 'Vael the Fogbinder',
    minLevel: 13,
    maxLevel: 13,
    family: 'humanoid',
    elite: true,
    boss: true,
    // Boss rule: CC- and snare-immune on both difficulties (see morthen).
    ccImmune: true,
    slowImmune: true,
    hpBase: 240,
    hpPerLevel: 34,
    dmgBase: 12,
    dmgPerLevel: 2.6,
    attackSpeed: 2.4,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 16,
    aoePulse: { min: 16, max: 24, radius: 12, every: 10, name: 'Mist Surge' },
    summonAdds: { mobId: 'drowned_thrall', count: 2, atHpPct: [0.6, 0.3] },
    loot: [
      { copper: 5000, chance: 1 },
      { itemId: 'trollhide_leggings', chance: 0.34, rollGroup: 'vael_guaranteed_uncommon' },
      { itemId: 'marshstrider_boots', chance: 0.33, rollGroup: 'vael_guaranteed_uncommon' },
      { itemId: 'fenmist_robe', chance: 0.33, rollGroup: 'vael_guaranteed_uncommon' },
      { itemId: 'deepfen_pearl', chance: 1 },
      { itemId: 'eelskin_tunic', chance: 0.2, rollGroup: 'vael_bonus' },
      { itemId: 'tidescale_vest', chance: 0.1, rollGroup: 'vael_bonus' },
      { itemId: 'drowned_prayer_leggings', chance: 0.1, rollGroup: 'vael_bonus' },
      { itemId: 'drowned_prayer_sandals', chance: 0.1, rollGroup: 'vael_bonus' },
      { itemId: 'eelscale_treads', chance: 0.1, rollGroup: 'vael_bonus' },
      { itemId: 'mistveil_cord', chance: 0.12, rollGroup: 'vael_bonus' },
      { itemId: 'mistveil_grips', chance: 0.12, rollGroup: 'vael_bonus' },
      { itemId: 'mistcallers_duffel', chance: 0.1, rollGroup: 'vael_bonus' },
    ],
    scale: 1.35,
    color: 0x48c9b0,
  },

  // ---- Gravewyrm Sanctum (5-player elite instance, L20 finale) ----
  sanctum_boneguard: {
    id: 'sanctum_boneguard',
    name: 'Sanctum Boneguard',
    minLevel: 19,
    maxLevel: 19,
    family: 'undead',
    elite: true,
    hpBase: 64,
    hpPerLevel: 23,
    dmgBase: 12,
    dmgPerLevel: 2.7,
    attackSpeed: 2.3,
    armorPerLevel: 22,
    moveSpeed: 6.5,
    aggroRadius: 12,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [
      { copper: 300, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.6 },
      { itemId: 'boundstone_helm', chance: 0.04, rollGroup: 'boneguard_bonus' },
      { itemId: 'boundstone_girdle', chance: 0.04, rollGroup: 'boneguard_bonus' },
    ],
    scale: 1.15,
    color: 0xcfc8b0,
  },
  sanctum_drakonid: {
    id: 'sanctum_drakonid',
    name: 'Sanctum Scaleguard',
    minLevel: 19,
    maxLevel: 20,
    family: 'dragonkin',
    elite: true,
    hpBase: 68,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 13,
    loot: [
      { copper: 350, chance: 1 },
      { itemId: 'cracked_wyrm_scale', chance: 0.5 },
      { itemId: 'gravewyrm_mantle', chance: 0.05, rollGroup: 'drakonid_bonus' },
      { itemId: 'gravewyrm_gauntlets', chance: 0.05, rollGroup: 'drakonid_bonus' },
      { itemId: 'gravewyrm_thornmaul', chance: 0.05 },
    ],
    scale: 1.45,
    color: 0x567d46, // Korzul's rig at 0.8x his bulk
  },
  raised_bonewalker: {
    id: 'raised_bonewalker',
    name: 'Raised Bonewalker',
    minLevel: 18,
    maxLevel: 18,
    family: 'undead',
    hpBase: 42,
    hpPerLevel: 15,
    dmgBase: 9,
    dmgPerLevel: 2.2,
    attackSpeed: 2.2,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    charge: {
      minRange: 5,
      maxRange: 30,
      cooldown: 12,
      stunDuration: 0.5,
      name: 'Onrush',
      school: 'physical',
    },
    loot: [], // summoned add — nothing to loot
    scale: 1.0,
    color: 0xc8cfc8,
  },
  korgath_the_bound: {
    id: 'korgath_the_bound',
    name: 'Korgath the Bound',
    minLevel: 20,
    maxLevel: 20,
    family: 'ogre',
    elite: true,
    // Named mid-boss: CC- and snare-immune on both difficulties (see morthen).
    ccImmune: true,
    slowImmune: true,
    hpBase: 260,
    hpPerLevel: 36,
    dmgBase: 14,
    dmgPerLevel: 2.9,
    attackSpeed: 2.8,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 15,
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    stomp: { radius: 10, every: 12, duration: 1.5, min: 20, max: 30, name: 'Shuddering Stomp' },
    loot: [
      { copper: 5000, chance: 1 },
      { itemId: 'boneplate_vest', chance: 0.34, rollGroup: 'korgath_guaranteed_uncommon' },
      { itemId: 'revenant_silk_robe', chance: 0.33, rollGroup: 'korgath_guaranteed_uncommon' },
      { itemId: 'nightwalk_jerkin', chance: 0.33, rollGroup: 'korgath_guaranteed_uncommon' },
      { itemId: 'zealotsbane_blade', chance: 0.19, rollGroup: 'korgath_bonus' },
      { itemId: 'korgaths_chainwraps', chance: 0.1, rollGroup: 'korgath_bonus' },
      { itemId: 'staff_of_velkhar', chance: 0.1, rollGroup: 'korgath_bonus' },
      { itemId: 'shadowmeld_tunic', chance: 0.1, rollGroup: 'korgath_bonus' },
      { itemId: 'wyrmcult_grand_robe', chance: 0.1, rollGroup: 'korgath_bonus' },
      { itemId: 'gravewyrm_sabatons', chance: 0.1, rollGroup: 'korgath_bonus' },
      { itemId: 'wyrmcult_soulsteps', chance: 0.1, rollGroup: 'korgath_bonus' },
      { itemId: 'wyrmshadow_treads', chance: 0.05, rollGroup: 'korgath_bonus' },
      { itemId: 'boundstone_helm', chance: 0.08, rollGroup: 'korgath_bonus' },
      { itemId: 'gravewyrm_mantle', chance: 0.08, rollGroup: 'korgath_bonus' },
    ],
    scale: 1.5,
    color: 0x8f6f46,
  },
  grand_necromancer_velkhar: {
    id: 'grand_necromancer_velkhar',
    name: 'Grand Necromancer Velkhar',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    elite: true,
    // Named mid-boss: CC- and snare-immune on both difficulties (see morthen).
    ccImmune: true,
    slowImmune: true,
    hpBase: 230,
    hpPerLevel: 33,
    dmgBase: 13,
    dmgPerLevel: 2.8,
    attackSpeed: 2.0,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 15,
    summonAdds: { mobId: 'raised_bonewalker', count: 3, atHpPct: [0.66, 0.33] },
    loot: [
      { copper: 5000, chance: 1 },
      { itemId: 'boneplate_vest', chance: 0.34, rollGroup: 'velkhar_guaranteed_uncommon' },
      { itemId: 'revenant_silk_robe', chance: 0.33, rollGroup: 'velkhar_guaranteed_uncommon' },
      { itemId: 'nightwalk_jerkin', chance: 0.33, rollGroup: 'velkhar_guaranteed_uncommon' },
      { itemId: 'emberwood_staff', chance: 0.2, rollGroup: 'velkhar_bonus' },
      { itemId: 'boneguard_breastplate', chance: 0.1, rollGroup: 'velkhar_bonus' },
      { itemId: 'shadowmeld_tunic', chance: 0.1, rollGroup: 'velkhar_bonus' },
      { itemId: 'staff_of_velkhar', chance: 0.1, rollGroup: 'velkhar_bonus' },
      { itemId: 'gravewyrm_stalkers_treads', chance: 0.1, rollGroup: 'velkhar_bonus' },
      { itemId: 'deathlord_legguards', chance: 0.05, rollGroup: 'velkhar_bonus' },
      { itemId: 'necromancers_soulsteps', chance: 0.05, rollGroup: 'velkhar_bonus' },
      { itemId: 'wyrmshadow_legguards', chance: 0.05, rollGroup: 'velkhar_bonus' },
    ],
    scale: 1.25,
    color: 0x512e5f,
  },
  korzul_the_gravewyrm: {
    id: 'korzul_the_gravewyrm',
    name: 'Korzul the Gravewyrm',
    minLevel: 20,
    maxLevel: 20,
    family: 'dragonkin',
    elite: true,
    boss: true,
    // Boss rule: CC- and snare-immune on both difficulties (see morthen).
    ccImmune: true,
    slowImmune: true,
    hpBase: 420,
    hpPerLevel: 48,
    dmgBase: 15,
    dmgPerLevel: 3.0,
    attackSpeed: 2.6,
    armorPerLevel: 34,
    moveSpeed: 7,
    aggroRadius: 18,
    // Grave Inferno (2026-07): the old Necrotic Shockwave aoePulse hit every
    // melee for an unavoidable, unmitigated 570-798 each 8s. Replaced by a
    // Geddon-style stationary channel: 8s rooted, no melee, four escalating
    // fire pulses (base x1/2/3/4 x the per-mob mechanic multiplier), 14yd.
    // Moving out at the windup eats the small first pulse or nothing.
    // The 50% hp gate (2026-07-26) guarantees the channel fires once per kill
    // on BOTH difficulties: a group out-pacing the 30s cadence used to skip
    // the mechanic entirely. One gate only, and it lands before the 30% enrage
    // so the burn phase never stacks on enraged melee.
    infernoChannel: {
      every: 30,
      duration: 8,
      pulses: 4,
      min: 7,
      max: 9,
      radius: 14,
      name: 'Grave Inferno',
      school: 'fire',
      atHpPct: [0.5],
    },
    enrage: { belowHpPct: 0.3, dmgMult: 1.5, hasteMult: 1.3 },
    loot: [
      { copper: 50000, chance: 1 },
      { itemId: 'boneplate_vest', chance: 0.34, rollGroup: 'korzul_guaranteed_uncommon' },
      { itemId: 'revenant_silk_robe', chance: 0.33, rollGroup: 'korzul_guaranteed_uncommon' },
      { itemId: 'nightwalk_jerkin', chance: 0.33, rollGroup: 'korzul_guaranteed_uncommon' },
      { itemId: 'cultist_flayer', chance: 0.1, rollGroup: 'korzul_bonus' },
      { itemId: 'wyrmfang_greatblade', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'staff_of_the_gravewyrm', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'fang_of_korzul', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'deathlord_warplate', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'necromancers_starshroud', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'wyrmshadow_harness', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'boundstone_girdle', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'gravewyrm_gauntlets', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'deathlords_dread_visage', chance: 0.04, rollGroup: 'korzul_bonus' },
      { itemId: 'necromancers_soulspire_mantle', chance: 0.04, rollGroup: 'korzul_bonus' },
      { itemId: 'wyrmshadow_talongrips', chance: 0.04, rollGroup: 'korzul_bonus' },
      { itemId: 'nightfangs_greatstaff', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'wildgrowth_leggings', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'grovewardens_grips', chance: 0.05, rollGroup: 'korzul_bonus' },
      { itemId: 'verdant_walkers', chance: 0.05, rollGroup: 'korzul_bonus' },
    ],
    scale: 1.8,
    color: 0x3d5c45,
  },

  // ---- Abandoned Crypt raid encounter (10-player, Nythraxis) ----
  nythraxis_skeleton_warrior: {
    id: 'nythraxis_skeleton_warrior',
    name: 'Risen Royal Guard',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    ccImmune: true,
    hpBase: 150,
    hpPerLevel: 28,
    dmgBase: 26,
    dmgPerLevel: 5.6,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 10,
    aggroRadius: 14,
    loot: [],
    scale: 1.25,
    color: 0xc7c0b2,
  },
  nythraxis_heroic_warrior_add: {
    id: 'nythraxis_heroic_warrior_add',
    name: 'Spirit of Aldren',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    ccImmune: true,
    hpBase: 150,
    hpPerLevel: 28,
    dmgBase: 26,
    dmgPerLevel: 5.6,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 10,
    aggroRadius: 14,
    cleave: { radius: 8, mult: 0.55, name: 'Royal Cleave' },
    loot: [],
    scale: 1.25,
    color: 0xc7c0b2,
  },
  nythraxis_heroic_priest_add: {
    id: 'nythraxis_heroic_priest_add',
    name: 'Spirit of Malric',
    quietMechanics: true,
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    // Deliberately CC-able (unlike the other adds): the raid MUST stun/silence him
    // to break his escalating heal channel. See channelHeal and the priest-add
    // exemption in the Nythraxis control-immunity gate (sim.applyAura).
    ccImmune: false,
    // Squishy: low health so a focused raid can burn him, but his heal is strong,
    // so stunning/silencing is usually the better answer than racing his HP.
    hpBase: 80,
    hpPerLevel: 14,
    dmgBase: 12,
    dmgPerLevel: 2.6,
    attackSpeed: 2.4,
    armorPerLevel: 14,
    moveSpeed: 9.5,
    aggroRadius: 14,
    // Escalating channeled heal on Nythraxis. Tuned against ~550 raid DPS (10 x
    // ~55) at the heroic gear level: the adds inherit mechanicHealMult (1.6), so
    // the raw 400 -> 1800 ramp lands ~640 (a light drain early) up to ~2880 per 3s
    // at cap (~960 HPS, ~1.7x raid DPS). Ignoring Malric a few ticks lets the boss
    // gain ground; a stun/incapacitate/silence resets the ramp. Even a max-geared
    // raid (~850 DPS) cannot out-damage a capped channel, so the interrupt stays
    // mandatory rather than optional.
    channelHeal: {
      radius: 45,
      // 4s per cast: slow enough that each heal is a visible, reactable channel (the
      // old 3s felt too fast), with the per-heal amount cut ~20% so he is not
      // out-healing a fair raid DPS check.
      every: 4,
      baseHeal: 320,
      rampAdd: 240,
      maxHeal: 1440,
      name: "Malric's Mending",
      school: 'shadow',
    },
    loot: [],
    scale: 1.18,
    color: 0x6b4a89,
  },
  nythraxis_heroic_rogue_add: {
    id: 'nythraxis_heroic_rogue_add',
    name: 'Spirit of Voss',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    // Untauntable (ignoreTaunt) but CC-able: the raid cannot tank-lock him onto a
    // target, they have to stun/root him off the healers. Low health so a peel
    // plus CC handles him. See the controllable-add exemption in sim.applyAura.
    ccImmune: false,
    hpBase: 90,
    hpPerLevel: 16,
    dmgBase: 16,
    dmgPerLevel: 3.4,
    attackSpeed: 2.0,
    armorPerLevel: 16,
    moveSpeed: 8,
    aggroRadius: 14,
    ignoreTaunt: true,
    loot: [],
    scale: 1.12,
    color: 0x776f83,
  },
  // Brother Aldric is now a dynamically-spawned NPC (see NPCS.brother_aldric_raid
  // in zone3.ts and spawnNythraxisAldric in sim.ts), not a mob.
  nythraxis_scourge_of_thornpeak: {
    id: 'nythraxis_scourge_of_thornpeak',
    name: 'Nythraxis, Scourge of Thornpeak',
    minLevel: 20,
    maxLevel: 20,
    family: 'undead',
    elite: true,
    boss: true,
    ccImmune: true,
    // Boss rule: snare-immune on both difficulties too (the raid boss was
    // ccImmune from day one but still slowable on normal; see morthen).
    slowImmune: true,
    // 60k on normal (createMob applies the 2.3x elite factor); heroic scales
    // this via the nythraxis_boss_arena healthMultiplier.
    hpBase: 60000 / 2.3,
    hpPerLevel: 0,
    dmgBase: 54,
    dmgPerLevel: 11.4,
    attackSpeed: 2.6,
    armorPerLevel: 42,
    moveSpeed: 10.5,
    aggroRadius: 22,
    // Each nythraxis_drop_* rollGroup is exclusive (one partitioned rng draw per
    // group) and sums to exactly 1.00. The offhand/two-hander epics ride the
    // existing four groups, one per group, with the set-piece chances rebalanced.
    loot: [
      { copper: 150000, chance: 1 },
      { itemId: 'deathless_heartwood', chance: 0.03, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'bonewrought_greatsword', chance: 0.13, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'crownforged_dreadhelm', chance: 0.14, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'nighttalon_crown', chance: 0.14, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'soulflame_cowl', chance: 0.14, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'stormcallers_crown', chance: 0.14, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'nighttalon_shoulderguards', chance: 0.14, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'soulflame_mantle', chance: 0.14, rollGroup: 'nythraxis_drop_1' },
      { itemId: 'kingsbane_last_oath', chance: 0.03, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'bonewrought_bulwark', chance: 0.13, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'crownforged_warspaulders', chance: 0.14, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'nighttalon_shoulderguards', chance: 0.14, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'soulflame_mantle', chance: 0.14, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'crownforged_dreadhelm', chance: 0.14, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'nighttalon_crown', chance: 0.14, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'stormcallers_spaulders', chance: 0.14, rollGroup: 'nythraxis_drop_2' },
      { itemId: 'wraithfire_orb', chance: 0.16, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'crownforged_dreadhelm', chance: 0.14, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'nighttalon_crown', chance: 0.14, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'soulflame_cowl', chance: 0.14, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'stormcallers_crown', chance: 0.14, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'nighttalon_shoulderguards', chance: 0.14, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'soulflame_mantle', chance: 0.14, rollGroup: 'nythraxis_drop_3' },
      { itemId: 'direfang_greatblade', chance: 0.16, rollGroup: 'nythraxis_drop_4' },
      { itemId: 'soulflame_mantle', chance: 0.14, rollGroup: 'nythraxis_drop_4' },
      { itemId: 'crownforged_warspaulders', chance: 0.14, rollGroup: 'nythraxis_drop_4' },
      { itemId: 'nighttalon_shoulderguards', chance: 0.14, rollGroup: 'nythraxis_drop_4' },
      { itemId: 'stormcallers_spaulders', chance: 0.14, rollGroup: 'nythraxis_drop_4' },
      { itemId: 'crownforged_dreadhelm', chance: 0.14, rollGroup: 'nythraxis_drop_4' },
      { itemId: 'nighttalon_crown', chance: 0.14, rollGroup: 'nythraxis_drop_4' },
      // The feral ladder's top rung rides its own bonus group: a fifth,
      // independent draw so the four guaranteed groups above keep their exact
      // 1.00 partitions (a 25% bonus shot, never displacing a set piece).
      { itemId: 'maul_of_the_scourged_wilds', chance: 0.25, rollGroup: 'nythraxis_drop_5' },
    ],
    scale: 3.1,
    color: 0x221b2d,
  },
  vosh_the_glazier: {
    id: 'vosh_the_glazier',
    name: 'Vosh the Glazier',
    minLevel: 24,
    maxLevel: 24,
    family: 'humanoid',
    elite: true,
    boss: true,
    // Raid-boss control immunity, the endgame rule every boss-flagged
    // template carries (tests/dungeon_difficulty.test.ts): no CC, no snares.
    ccImmune: true,
    slowImmune: true,
    // 26k effective on normal (createMob applies the 2.3x elite factor). The
    // Kiln-Keepers are a 10-player wing-1 duo: two health pools fought together,
    // combined 46k, well below the 60k Nythraxis finale. Sized to the level-20
    // mana economy: the ten-bot E2E proved a 62k duo outlasts both healers' full
    // mana pools (wipe at ~150s with Saan at 17%), so the onboarding wing must
    // die inside ~150s of sustained raid damage. Vosh carries the larger pool.
    hpBase: 26000 / 2.3,
    hpPerLevel: 0,
    dmgBase: 46,
    dmgPerLevel: 9.6,
    attackSpeed: 2.6,
    armorPerLevel: 34,
    moveSpeed: 7,
    aggroRadius: 18,
    cleave: { radius: 8, mult: 0.65, name: 'Glasscut Arc' },
    polymorphHex: {
      chance: 0.16,
      duration: 4,
      name: 'Cinder-Toad',
      school: 'fire',
    },
    // Vitrifying Touch: each melee hit has a chance to stack Glazing on the tank,
    // a brittle-glass debuff that raises the physical damage they take. It stacks
    // and refreshes, so an un-swapped tank hardens toward statue-hood and must
    // hand off (the second tank-swap pressure alongside Cinder-Toad).
    expose: { chance: 0.4, dmgIncrease: 0.08, duration: 12, name: 'Glazing' },
    loot: UNDERMOUNT_WING1_LOOT,
    scale: 1.8,
    color: 0x86c6d8,
  },
  saan_the_stoker: {
    id: 'saan_the_stoker',
    name: 'Saan the Stoker',
    minLevel: 24,
    maxLevel: 24,
    family: 'humanoid',
    elite: true,
    boss: true,
    // Raid-boss control immunity, the endgame rule every boss-flagged
    // template carries (tests/dungeon_difficulty.test.ts): no CC, no snares.
    ccImmune: true,
    slowImmune: true,
    // 20k effective on normal (the 2.3x elite factor; see the Vosh comment for
    // the duo's 46k combined budget). Saan is the caster half: a smaller pool
    // than Vosh, but her cross-heal (Anneal) tops off her partner, so the raid
    // must burn the two keepers down together rather than tunnelling one. Her
    // melee is soft; her damage is the Kilnflare Pulse.
    hpBase: 20000 / 2.3,
    hpPerLevel: 0,
    dmgBase: 30,
    dmgPerLevel: 6.2,
    attackSpeed: 2.0,
    armorPerLevel: 22,
    moveSpeed: 7,
    aggroRadius: 18,
    aoePulse: {
      min: 170,
      max: 240,
      radius: 14,
      every: 8,
      name: 'Kilnflare Pulse',
      school: 'fire',
    },
    mendAlly: {
      healMin: 1400,
      healMax: 2000,
      radius: 20,
      every: 12,
      name: 'Anneal',
      school: 'fire',
    },
    loot: UNDERMOUNT_WING1_LOOT,
    scale: 1.65,
    color: 0xd86d32,
  },
  odrenn_the_temperer: {
    id: 'odrenn_the_temperer',
    name: 'Odrenn the Temperer',
    minLevel: 24,
    maxLevel: 24,
    family: 'humanoid',
    elite: true,
    boss: true,
    // Raid-boss control immunity, the endgame rule every boss-flagged
    // template carries (tests/dungeon_difficulty.test.ts): no CC, no snares.
    ccImmune: true,
    slowImmune: true,
    // Wing 2, single boss. 48k effective (2.3x elite factor). The SORT script
    // (geography marks, mixed-mark burn, Cinder Arc, Tempering) lives in
    // encounters/odrenn.ts; this template carries only the data-only texture.
    hpBase: 48000 / 2.3,
    hpPerLevel: 0,
    dmgBase: 52,
    dmgPerLevel: 10.8,
    attackSpeed: 2.6,
    armorPerLevel: 34,
    moveSpeed: 7,
    aggroRadius: 18,
    cleave: { radius: 8, mult: 0.6, name: 'Temper Sweep' },
    aoePulse: { min: 14, max: 20, radius: 30, every: 12, name: 'Forge Draft', school: 'fire' },
    loot: UNDERMOUNT_WING2_LOOT,
    scale: 1.8,
    color: 0xbfa36a,
  },
  undermount_cinderling: {
    id: 'undermount_cinderling',
    name: 'Cinderling',
    minLevel: 24,
    maxLevel: 24,
    family: 'elemental',
    // Dormant embers of the half-formed god. They never fight: aggroRadius 3
    // is the proximity wake (guilt) and the Volzharr module owns their walk.
    // Low HP on purpose: killing a woken shambler denies Volzharr his stack.
    hpBase: 900,
    hpPerLevel: 0,
    dmgBase: 1,
    dmgPerLevel: 0,
    attackSpeed: 10,
    armorPerLevel: 0,
    moveSpeed: 3,
    aggroRadius: 3,
    loot: [],
    scale: 0.7,
    color: 0xff7a29,
  },
  volzharr_buried_furnace: {
    id: 'volzharr_buried_furnace',
    name: 'Volzharr, the Buried Furnace',
    minLevel: 26,
    maxLevel: 26,
    family: 'elemental',
    elite: true,
    boss: true,
    // Raid-boss control immunity, the endgame rule every boss-flagged
    // template carries (tests/dungeon_difficulty.test.ts): no CC, no snares.
    ccImmune: true,
    slowImmune: true,
    // Wing 3, the raid capstone (level 26, drops ilvl 35). 69k effective (2.3x
    // elite factor), the review-corrected 1.15x anchor over the 60k Nythraxis
    // finale since this is a higher-level tier. Mechanics not yet authored:
    // raid-scale stat placeholder.
    hpBase: 69000 / 2.3,
    hpPerLevel: 0,
    dmgBase: 58,
    dmgPerLevel: 12.2,
    attackSpeed: 2.6,
    armorPerLevel: 34,
    moveSpeed: 5.5, // the kite: below player run 7, pass-6 movement finale
    aggroRadius: 18,
    loot: UNDERMOUNT_WING3_LOOT,
    scale: 1.8,
    color: 0x9c3d24,
  },
};

// Trash packs of 2 elites (spaced beyond social-aggro range so groups can
// pull them one pack at a time), a miniboss pair, then Morthen with guards.
const CRYPT_SPAWN_LIST: DungeonSpawn[] = [
  { mobId: 'crypt_shambler', x: -3, z: 18 },
  { mobId: 'crypt_shambler', x: 3, z: 19 },
  { mobId: 'crypt_shambler', x: -9, z: 38 },
  { mobId: 'hollow_acolyte', x: -5, z: 39 },
  { mobId: 'crypt_shambler', x: 9, z: 54 },
  { mobId: 'hollow_acolyte', x: 5, z: 55 },
  { mobId: 'bonechill_widow', x: -5, z: 68 },
  { mobId: 'bonechill_widow', x: -1, z: 70 },
  { mobId: 'sexton_marrow', x: -4, z: 82 },
  { mobId: 'hollow_acolyte', x: 1, z: 83 },
  { mobId: 'morthen', x: 0, z: 98 },
  { mobId: 'crypt_shambler', x: -4, z: 96 },
  { mobId: 'crypt_shambler', x: 4, z: 96 },
];

// Sunken Bastion: same 13-spawn pacing as the crypt — packs of 2 elites,
// the Knight-Commander as miniboss, then Vael on the dais with two guards.
const BASTION_SPAWN_LIST: DungeonSpawn[] = [
  { mobId: 'bastion_revenant', x: -3, z: 18 },
  { mobId: 'bastion_revenant', x: 3, z: 19 },
  { mobId: 'bastion_revenant', x: -9, z: 38 },
  { mobId: 'tidebound_acolyte', x: -5, z: 39 },
  { mobId: 'tidebound_acolyte', x: 9, z: 54 },
  { mobId: 'bastion_revenant', x: 5, z: 55 },
  { mobId: 'bastion_revenant', x: -5, z: 68 },
  { mobId: 'tidebound_acolyte', x: -1, z: 70 },
  { mobId: 'knight_commander_olen', x: -4, z: 82 },
  { mobId: 'bastion_revenant', x: 1, z: 83 },
  { mobId: 'vael_the_mistcaller', x: 0, z: 98 },
  { mobId: 'tidebound_acolyte', x: -4, z: 96 },
  { mobId: 'bastion_revenant', x: 4, z: 96 },
];

// Gravewyrm Sanctum: three chambers — the Boneworks (z<60), the Ritual Vault
// (75-115) and the Wyrm's Hollow (115+) — with Korgath holding the first
// waist, Velkhar the second, and Korzul on the great dais at the end.
const SANCTUM_SPAWN_LIST: DungeonSpawn[] = [
  { mobId: 'sanctum_boneguard', x: -3, z: 20 },
  { mobId: 'sanctum_boneguard', x: 3, z: 21 },
  { mobId: 'sanctum_boneguard', x: -8, z: 30 },
  { mobId: 'sanctum_drakonid', x: -4, z: 31 },
  { mobId: 'sanctum_drakonid', x: 7, z: 44 },
  { mobId: 'sanctum_boneguard', x: 3, z: 45 },
  { mobId: 'sanctum_boneguard', x: -6, z: 58 },
  { mobId: 'sanctum_drakonid', x: -2, z: 59 },
  { mobId: 'korgath_the_bound', x: 0, z: 72 },
  { mobId: 'sanctum_drakonid', x: -7, z: 86 },
  { mobId: 'sanctum_boneguard', x: -3, z: 87 },
  { mobId: 'sanctum_boneguard', x: 6, z: 100 },
  { mobId: 'sanctum_drakonid', x: 2, z: 101 },
  { mobId: 'grand_necromancer_velkhar', x: 0, z: 114 },
  { mobId: 'sanctum_boneguard', x: -4, z: 112 },
  { mobId: 'sanctum_boneguard', x: 4, z: 112 },
  { mobId: 'sanctum_drakonid', x: -5, z: 130 },
  { mobId: 'sanctum_drakonid', x: -1, z: 132 },
  { mobId: 'korzul_the_gravewyrm', x: 0, z: 146 },
  { mobId: 'sanctum_drakonid', x: -5, z: 144 },
  { mobId: 'sanctum_drakonid', x: 5, z: 144 },
];

const NYTHRAXIS_RAID_SPAWN_LIST: DungeonSpawn[] = [
  { mobId: 'nythraxis_scourge_of_thornpeak', x: 0, z: 96 },
];

const UNDERMOUNT_WING1_SPAWN_LIST: DungeonSpawn[] = [
  { mobId: 'vosh_the_glazier', x: -6, z: 40 },
  { mobId: 'saan_the_stoker', x: 6, z: 40 },
];

const UNDERMOUNT_WING2_SPAWN_LIST: DungeonSpawn[] = [{ mobId: 'odrenn_the_temperer', x: 0, z: 40 }];

const UNDERMOUNT_WING3_SPAWN_LIST: DungeonSpawn[] = [
  { mobId: 'volzharr_buried_furnace', x: 0, z: 40 },
  // Dormant Cinderlings: half-sunk magma elementals scattered at AUTHORED fixed
  // positions (no spawn rng), weighted toward the arena's future vent corridors.
  // They never attack; the Volzharr module wakes them one at a time and marches
  // them home to feed him (The Embers Come Home). Proximity wakes one early.
  { mobId: 'undermount_cinderling', x: -22, z: 18 },
  { mobId: 'undermount_cinderling', x: 24, z: 22 },
  { mobId: 'undermount_cinderling', x: -30, z: 44 },
  { mobId: 'undermount_cinderling', x: 31, z: 48 },
  { mobId: 'undermount_cinderling', x: -18, z: 66 },
  { mobId: 'undermount_cinderling', x: 20, z: 70 },
  { mobId: 'undermount_cinderling', x: -8, z: 84 },
  { mobId: 'undermount_cinderling', x: 10, z: 88 },
];

export const DUNGEON_DEFS: Record<string, DungeonDef> = {
  hollow_crypt: {
    id: 'hollow_crypt',
    name: 'The Hollow Crypt',
    index: 0,
    doorPos: { x: 80, z: 90 }, // entrance portal at the chapel ruin
    // Arrive back near the exit portal so the first pack (z 18+) is outside aggro
    // range on entry: no mob can pull the moment you zone in. See dungeon_entry_clearance test.
    entry: { x: 0, z: -2 },
    exitOffset: { x: 0, z: -6 },
    spawns: CRYPT_SPAWN_LIST,
    interior: 'crypt',
    tombDressing: 'coffins',
    suggestedPlayers: 5,
    enterText: 'You descend into the Hollow Crypt...',
    leaveText: 'You climb back into daylight.',
  },
  sunken_bastion: {
    id: 'sunken_bastion',
    name: 'The Sunken Bastion',
    index: 1,
    doorPos: { x: 45, z: 515 }, // drowned keep south of the Gravecaller camp
    entry: { x: 0, z: -2 }, // clear-of-aggro arrival (see dungeon_entry_clearance test)
    exitOffset: { x: 0, z: -6 },
    spawns: BASTION_SPAWN_LIST,
    interior: 'crypt',
    tombDressing: 'cargo',
    suggestedPlayers: 5,
    enterText: 'You wade down into the Sunken Bastion...',
    leaveText: 'You climb out of the drowning dark.',
  },
  gravewyrm_sanctum: {
    id: 'gravewyrm_sanctum',
    name: 'Gravewyrm Sanctum',
    index: 2,
    doorPos: { x: 0, z: 858 }, // sealed gate in the graveyard, off the Sanctum Approach slope
    entry: { x: 0, z: -2 }, // clear-of-aggro arrival (see dungeon_entry_clearance test)
    exitOffset: { x: 0, z: -6 },
    spawns: SANCTUM_SPAWN_LIST,
    interior: 'sanctum',
    suggestedPlayers: 5,
    enterText: 'The air goes cold. Something vast breathes below...',
    leaveText: 'You stagger back into the mountain wind.',
  },
  nythraxis_crypt: {
    id: 'nythraxis_crypt',
    name: 'Abandoned Crypt',
    index: 4,
    doorPos: { x: -152, z: 610 },
    entry: { x: 0, z: 4 },
    exitOffset: { x: 0, z: -6 },
    spawns: [],
    objects: [
      // The three attunement relics: interacting raises the guardian undead
      // (fallen_captain_aldren/corrupted_priest_malric/deathstalker_voss) that
      // drop the keystone halves + diary — see activateNythraxisRelic in sim.ts.
      // Spread down the nave so they read as the crypt's quest interactables.
      // (The Royal Graves live in the overworld for q_nythraxis_graves; they do
      // not belong inside the crypt, where that quest is already complete.)
      { itemId: 'captains_crest', name: 'Crypt Keystone Upper', x: -7, z: 28 },
      { itemId: 'priests_sigil', name: 'Crypt Keystone Lower', x: 0, z: 52 },
      { itemId: 'royal_seal', name: 'Ancient Diary', x: 7, z: 76 },
      // Sealed royal door to the raid: flush-centre on the crypt back wall.
      // Back wall collider spans z 111-113 (centre 112, hd 1); sit the door just
      // in front of its inner face so it reads as set into the wall but stays
      // interactable (isBlocked r=0.5 needs centre z <= 110.5).
      {
        itemId: '',
        name: 'Sealed Royal Door',
        x: 0,
        z: 110.4,
        templateId: 'dungeon_door',
        dungeonId: 'nythraxis_boss_arena',
      },
    ],
    interior: 'crypt',
    tombDressing: 'coffins',
    suggestedPlayers: 1,
    enterText: 'You cross the threshold of the Abandoned Crypt.',
    leaveText: 'You return to the cold air of Thornpeak.',
  },
  the_last_keep: {
    id: 'the_last_keep',
    name: 'The Last Keep',
    // Overflow band: indexes 0..7 are taken (temple 3, orkadia 6, wildheart 7),
    // so the keep claims 8 (instanceOrigin: DUNGEON_OVERFLOW_X_BASE + 600).
    index: 8,
    // On the ward terrace at the keep's west front: clear of the keep's
    // decor collider (r 8.5 at 421,2003), of both ward step tops, and of
    // the terrace mid-walk, so neither the leave-drop (z - 4) nor casual
    // foot traffic clips a collider or the 2yd door trigger (castle_layout)
    doorPos: { x: 413.5, z: 2016.5 },
    // Arrival just inside the entrance hall's south end, 4yd north of the exit
    // portal so zoning in never lands inside the exit's 2yd door trigger.
    entry: { x: 0, z: -5 },
    exitOffset: { x: 0, z: -9 },
    // Zero combat, zero loot by design: the keep is a place to walk, not a
    // fight (the zero-spawn Nythraxis attunement crypt is the precedent). It is
    // deliberately absent from FINDER_ACTIVITIES, so the Dungeon Finder never
    // queues a group into an empty instance (orkadia/wildheart precedent: the
    // finder catalogue is explicit, not derived from DUNGEONS).
    spawns: [],
    objects: [
      // the hall's keepsake: a signet dropped by the garrison that never
      // came home, on the entrance hall floor east of the door
      { itemId: 'last_keep_signet', name: 'Signet of the Last Keep', x: 4, z: 0 },
    ],
    interior: 'lastkeep',
    suggestedPlayers: 1,
    enterText: 'You step into the cold, silent halls of the Last Keep.',
    leaveText: 'You pull the keep door shut and step back into the Drakelands wind.',
  },
  nythraxis_boss_arena: {
    id: 'nythraxis_boss_arena',
    name: 'Nythraxis Raid Arena',
    index: 5,
    doorPos: { x: -152, z: 610 },
    overworldDoor: false,
    entry: { x: 0, z: 4 },
    exitOffset: { x: 0, z: -6 },
    spawns: NYTHRAXIS_RAID_SPAWN_LIST,
    objects: [
      // Three soul wardstones in a wide forward triangle in front of the boss
      // (spawn 0,96), well clear of his body so all three read distinctly and
      // raiders must split to channel them. Kept within the encounter's
      // wardstone search radius (see nythraxisWardstones in sim.ts).
      { itemId: 'bastion_ward_stone', name: 'Left Wardstone', x: -40, z: 79 },
      { itemId: 'bastion_ward_stone', name: 'Right Wardstone', x: 40, z: 79 },
      { itemId: 'bastion_ward_stone', name: 'Threshold Wardstone', x: 0, z: 63 },
    ],
    interior: 'nythraxis',
    tombDressing: 'coffins',
    suggestedPlayers: 10,
    enterText: 'You pass through the sealed royal door.',
    leaveText: 'You return to the cold air of Thornpeak.',
  },
  undermount_wing1: {
    id: 'undermount_wing1',
    name: 'Undermount: The Descent',
    index: 10,
    // Wing 1 has the raid's only overworld entrance: the Undermount fissure in
    // the Wyrmcult territory of Thornpeak. Wings 2 and 3 stay internal (reached
    // through each wing's sealed door), so this is the single walk-in point.
    doorPos: { x: -174, z: 610 },
    entry: { x: 0, z: 4 },
    exitOffset: { x: 0, z: -6 },
    spawns: UNDERMOUNT_WING1_SPAWN_LIST,
    objects: [
      {
        itemId: '',
        name: 'Glazier Door',
        x: 0,
        z: 110,
        templateId: 'dungeon_door',
        dungeonId: 'undermount_wing2',
      },
    ],
    interior: 'undermount',
    suggestedPlayers: 10,
    enterText: 'You descend beneath Thornpeak into glassy dark.',
    leaveText: 'You climb back from the Undermount descent.',
  },
  undermount_wing2: {
    id: 'undermount_wing2',
    name: 'Undermount: The Tempering',
    index: 11,
    overworldDoor: false,
    doorPos: { x: -168, z: 620 },
    entry: { x: 0, z: 4 },
    exitOffset: { x: 0, z: -6 },
    spawns: UNDERMOUNT_WING2_SPAWN_LIST,
    objects: [
      {
        itemId: '',
        name: 'Tempering Door',
        x: 0,
        z: 110,
        templateId: 'dungeon_door',
        dungeonId: 'undermount_wing3',
      },
    ],
    interior: 'undermount',
    suggestedPlayers: 10,
    enterText: 'Hammerfalls echo through the tempering vault.',
    leaveText: 'You retreat from the ringing forgeways.',
  },
  undermount_wing3: {
    id: 'undermount_wing3',
    name: 'Undermount: The Waking',
    index: 12,
    overworldDoor: false,
    doorPos: { x: -162, z: 630 },
    entry: { x: 0, z: 4 },
    exitOffset: { x: 0, z: -6 },
    spawns: UNDERMOUNT_WING3_SPAWN_LIST,
    interior: 'undermount',
    suggestedPlayers: 10,
    enterText: 'The buried furnace stirs in the deep.',
    leaveText: 'You withdraw from the waking heat.',
  },
};
