import type { AbilityDef, PlayerClass } from '../types';
import type { ClassDef } from './classes';

const RATIONS = [{ itemId: 'baked_bread', count: 5 }];
const CASTER_RATIONS = [...RATIONS, { itemId: 'spring_water', count: 5 }];

export const EXPANSION_CLASSES = {
  gravecaller: {
    id: 'gravecaller',
    name: 'Gravecaller',
    baseStats: { str: 9, agi: 11, sta: 18, int: 23, spi: 21, armor: 22 },
    statsPerLevel: { str: 0, agi: 0, sta: 2, int: 3, spi: 2, armor: 4 },
    baseHp: 46,
    hpPerLevel: 14,
    baseMana: 110,
    manaPerLevel: 26,
    resourceType: 'mana',
    startWeapon: 'gnarled_staff',
    startChest: 'apprentice_robe',
    startItems: CASTER_RATIONS,
    ranged: {
      min: 3,
      max: 6,
      speed: 1.8,
      maxRange: 30,
      minRange: 0,
      wand: true,
      school: 'shadow',
    },
    abilities: [
      'pestilent_bolt',
      'blood_tithe',
      'the_wasting',
      'grave_dread',
      'gravecaller_bone_coat',
      'soul_siphon',
      'grave_chill',
      'plague_wind',
      'deaths_bargain',
    ],
    color: 0x66507c,
  },
  briar_warden: {
    id: 'briar_warden',
    name: 'Briar Warden',
    baseStats: { str: 17, agi: 14, sta: 23, int: 18, spi: 19, armor: 48 },
    statsPerLevel: { str: 1, agi: 1, sta: 3, int: 2, spi: 2, armor: 12 },
    baseHp: 54,
    hpPerLevel: 18,
    baseMana: 100,
    manaPerLevel: 22,
    resourceType: 'mana',
    startWeapon: 'training_mace',
    startOffhand: 'eastbrook_buckler',
    startChest: 'footpad_jerkin',
    startItems: CASTER_RATIONS,
    abilities: [
      'briar_skin',
      'withering_presence',
      'barbed_aegis',
      'spore_hex',
      'ironbark_boon',
      'pollen_cloud',
      'vindictive_growth',
      'walking_calamity',
    ],
    color: 0x698744,
  },
} satisfies Record<'gravecaller' | 'briar_warden', ClassDef>;

export const EXPANSION_CLASS_ABILITIES: Record<string, AbilityDef> = {
  pestilent_bolt: {
    id: 'pestilent_bolt',
    name: 'Pestilent Bolt',
    class: 'gravecaller',
    learnLevel: 1,
    cost: 22,
    castTime: 1.8,
    cooldown: 0,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 15, max: 19, spellPowerCoeff: 0.55 }],
    ranks: [
      {
        rank: 2,
        level: 10,
        cost: 38,
        effects: [{ type: 'directDamage', min: 42, max: 50, spellPowerCoeff: 0.55 }],
      },
      {
        rank: 3,
        level: 20,
        cost: 58,
        effects: [{ type: 'directDamage', min: 88, max: 104, spellPowerCoeff: 0.55 }],
      },
      {
        rank: 4,
        level: 30,
        cost: 82,
        effects: [{ type: 'directDamage', min: 146, max: 172, spellPowerCoeff: 0.55 }],
      },
      {
        rank: 5,
        level: 40,
        cost: 108,
        effects: [{ type: 'directDamage', min: 218, max: 256, spellPowerCoeff: 0.55 }],
      },
    ],
    description: 'Hurls diseased shadow for $d Shadow damage. Damage increases with Spell Power.',
  },
  blood_tithe: {
    id: 'blood_tithe',
    name: 'Blood Tithe',
    class: 'gravecaller',
    learnLevel: 2,
    cost: 0,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [
      { type: 'selfDamagePctMax', pct: 0.08 },
      { type: 'gainResource', amount: 28 },
    ],
    description: 'Sacrifices 8% of your maximum health to restore 28 mana.',
  },
  the_wasting: {
    id: 'the_wasting',
    name: 'The Wasting',
    class: 'gravecaller',
    learnLevel: 4,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 48, duration: 18, interval: 3 }],
    description: 'Afflicts the enemy for 48 Shadow damage over 18 sec.',
  },
  grave_dread: {
    id: 'grave_dread',
    name: 'Dread',
    class: 'gravecaller',
    learnLevel: 6,
    cost: 35,
    castTime: 1.5,
    cooldown: 12,
    range: 20,
    school: 'shadow',
    requiresTarget: true,
    fearDr: true,
    effects: [{ type: 'incapacitate', duration: 8 }],
    description: 'Leaves the enemy cowering for up to 8 sec. Damage breaks the effect.',
  },
  gravecaller_bone_coat: {
    id: 'gravecaller_bone_coat',
    name: 'Bone Coat',
    class: 'gravecaller',
    learnLevel: 8,
    cost: 45,
    castTime: 0,
    cooldown: 45,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'selfAbsorbPctMax', pct: 0.2, duration: 12 }],
    description: 'Absorbs damage equal to 20% of your maximum health for 12 sec.',
  },
  soul_siphon: {
    id: 'soul_siphon',
    name: 'Soul Siphon',
    class: 'gravecaller',
    learnLevel: 12,
    cost: 50,
    castTime: 0,
    channel: { duration: 4, ticks: 4 },
    cooldown: 8,
    range: 24,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'drainTick', min: 24, max: 24, healFrac: 1 }],
    description:
      'Drains 24 Shadow damage each second for 4 sec and restores health equal to the damage dealt.',
  },
  grave_chill: {
    id: 'grave_chill',
    name: 'Grave Chill',
    class: 'gravecaller',
    learnLevel: 16,
    cost: 45,
    castTime: 0,
    cooldown: 12,
    range: 30,
    school: 'frost',
    requiresTarget: true,
    effects: [
      { type: 'directDamage', min: 62, max: 74 },
      { type: 'slow', mult: 0.5, duration: 8 },
    ],
    description: 'Deals $d Frost damage and slows movement by 50% for 8 sec.',
  },
  plague_wind: {
    id: 'plague_wind',
    name: 'Plague Wind',
    class: 'gravecaller',
    learnLevel: 24,
    cost: 90,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 96, max: 116, radius: 8 }],
    description: 'Blasts enemies within 8 yd for $d Shadow damage.',
  },
  deaths_bargain: {
    id: 'deaths_bargain',
    name: "Death's Bargain",
    class: 'gravecaller',
    learnLevel: 32,
    cost: 0,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'shadow',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_dr', value: 0.4, duration: 10 }],
    description: 'Reduces all damage you take by 40% for 10 sec.',
  },
  briar_skin: {
    id: 'briar_skin',
    name: 'Briar Skin',
    class: 'briar_warden',
    learnLevel: 1,
    tooltipOmitEffectLines: true,
    cost: 20,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'buffTarget', kind: 'thorns', value: 8, duration: 1800 }],
    ranks: [
      {
        rank: 2,
        level: 10,
        cost: 35,
        effects: [{ type: 'buffTarget', kind: 'thorns', value: 18, duration: 1800 }],
      },
      {
        rank: 3,
        level: 20,
        cost: 55,
        effects: [{ type: 'buffTarget', kind: 'thorns', value: 34, duration: 1800 }],
      },
      {
        rank: 4,
        level: 30,
        cost: 75,
        effects: [{ type: 'buffTarget', kind: 'thorns', value: 56, duration: 1800 }],
      },
      {
        rank: 5,
        level: 40,
        cost: 100,
        effects: [{ type: 'buffTarget', kind: 'thorns', value: 84, duration: 1800 }],
      },
    ],
    description:
      'Covers the target in briars for 30 min. Each melee attacker takes $b Nature damage. The shield has no charges.',
  },
  withering_presence: {
    id: 'withering_presence',
    name: 'Withering Presence',
    class: 'briar_warden',
    learnLevel: 3,
    cost: 35,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'aoeAttackSpeed', mult: 1.15, duration: 12, radius: 10 }],
    description: 'Slows the attacks of enemies within 10 yd by 15% for 12 sec.',
  },
  barbed_aegis: {
    id: 'barbed_aegis',
    name: 'Barbed Aegis',
    class: 'briar_warden',
    learnLevel: 6,
    cost: 40,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'thorns', value: 42, duration: 12 }],
    description:
      'For 12 sec, each melee attacker takes 42 Nature damage. The shield has no charges.',
  },
  spore_hex: {
    id: 'spore_hex',
    name: 'Spore Hex',
    class: 'briar_warden',
    learnLevel: 8,
    cost: 32,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 42, duration: 12, interval: 3 }],
    description: 'Infects the enemy for 42 Nature damage over 12 sec.',
  },
  ironbark_boon: {
    id: 'ironbark_boon',
    name: 'Ironbark Boon',
    class: 'briar_warden',
    learnLevel: 12,
    cost: 55,
    castTime: 0,
    cooldown: 0,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [
      { type: 'buffTarget', kind: 'buff_armor_pct', value: 15, duration: 1800, party: true },
    ],
    description: 'Increases the armor of all party members by $b% for 30 min.',
  },
  pollen_cloud: {
    id: 'pollen_cloud',
    name: 'Pollen Cloud',
    class: 'briar_warden',
    learnLevel: 18,
    cost: 65,
    castTime: 0,
    cooldown: 12,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 54, max: 68, radius: 10 }],
    description: 'Scours enemies within 10 yd for $d Nature damage.',
  },
  vindictive_growth: {
    id: 'vindictive_growth',
    name: 'Vindictive Growth',
    class: 'briar_warden',
    learnLevel: 26,
    cost: 70,
    castTime: 0,
    cooldown: 45,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [
      { type: 'selfBuff', kind: 'thorns', value: 120, duration: 15 },
      { type: 'selfBuff', kind: 'buff_dr', value: 0.2, duration: 15 },
    ],
    description: 'For 15 sec, melee attackers take 120 Nature damage and you take 20% less damage.',
  },
  walking_calamity: {
    id: 'walking_calamity',
    name: 'Walking Calamity',
    class: 'briar_warden',
    learnLevel: 36,
    cost: 100,
    castTime: 0,
    cooldown: 120,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [
      { type: 'selfBuff', kind: 'thorns', value: 240, duration: 20 },
      { type: 'selfBuff', kind: 'buff_dr', value: 0.35, duration: 20 },
    ],
    description: 'For 20 sec, melee attackers take 240 Nature damage and you take 35% less damage.',
  },
};

export const EXPANSION_CLASS_IDS: readonly PlayerClass[] = ['gravecaller', 'briar_warden'];
