import type { GatherNodeDef, GatherNodePlacement, ZonePropsDef } from '../types';

export const GATHER_NODE_TYPES: Record<string, GatherNodeDef> = {
  copper_vein: {
    id: 'copper_vein',
    name: 'Copper Vein',
    profession: 'mining',
    tier: 1,
    visual: 'ore',
  },
  iron_vein: {
    id: 'iron_vein',
    name: 'Iron Vein',
    profession: 'mining',
    tier: 2,
    visual: 'ore',
  },
  stormsilver_vein: {
    id: 'stormsilver_vein',
    name: 'Stormsilver Vein',
    profession: 'mining',
    tier: 3,
    visual: 'ore',
  },
  fallen_oak: {
    id: 'fallen_oak',
    name: 'Fallen Oak',
    profession: 'logging',
    tier: 1,
    visual: 'wood',
  },
  bogwood_fall: {
    id: 'bogwood_fall',
    name: 'Bogwood Fall',
    profession: 'logging',
    tier: 2,
    visual: 'wood',
  },
  highpine_deadfall: {
    id: 'highpine_deadfall',
    name: 'Highpine Deadfall',
    profession: 'logging',
    tier: 3,
    visual: 'wood',
  },
  silverleaf_patch: {
    id: 'silverleaf_patch',
    name: 'Silverleaf Patch',
    profession: 'herbalism',
    tier: 1,
    visual: 'herb',
  },
  mirebloom_patch: {
    id: 'mirebloom_patch',
    name: 'Mirebloom Patch',
    profession: 'herbalism',
    tier: 2,
    visual: 'herb',
  },
  frostcap_patch: {
    id: 'frostcap_patch',
    name: 'Frostcap Patch',
    profession: 'herbalism',
    tier: 3,
    visual: 'herb',
  },
};

export const GATHER_NODE_PLACEMENTS: GatherNodePlacement[] = [
  {
    id: 'eastbrook_copper_dig_01',
    nodeId: 'copper_vein',
    zoneId: 'eastbrook_vale',
    x: -95,
    z: -71,
    rot: 0.4,
  },
  {
    id: 'eastbrook_copper_dig_02',
    nodeId: 'copper_vein',
    zoneId: 'eastbrook_vale',
    x: -78,
    z: -58,
    rot: 1.9,
  },
  {
    id: 'eastbrook_webwood_oak_01',
    nodeId: 'fallen_oak',
    zoneId: 'eastbrook_vale',
    x: -64,
    z: 12,
    rot: 2.2,
  },
  {
    id: 'eastbrook_brightwood_oak_01',
    nodeId: 'fallen_oak',
    zoneId: 'eastbrook_vale',
    x: 35,
    z: 132,
    rot: -0.7,
  },
  {
    id: 'eastbrook_brightwood_silverleaf_01',
    nodeId: 'silverleaf_patch',
    zoneId: 'eastbrook_vale',
    x: 45,
    z: 146,
  },
  {
    id: 'eastbrook_mirror_lake_silverleaf_01',
    nodeId: 'silverleaf_patch',
    zoneId: 'eastbrook_vale',
    x: -111,
    z: 95,
  },

  {
    id: 'mirefen_troll_mounds_iron_01',
    nodeId: 'iron_vein',
    zoneId: 'mirefen_marsh',
    x: -103,
    z: 429,
    rot: -0.8,
  },
  {
    id: 'mirefen_bastion_iron_01',
    nodeId: 'iron_vein',
    zoneId: 'mirefen_marsh',
    x: 54,
    z: 508,
    rot: 1.1,
  },
  {
    id: 'mirefen_widow_bogwood_01',
    nodeId: 'bogwood_fall',
    zoneId: 'mirefen_marsh',
    x: 72,
    z: 327,
    rot: 0.2,
  },
  {
    id: 'mirefen_prowler_bogwood_01',
    nodeId: 'bogwood_fall',
    zoneId: 'mirefen_marsh',
    x: -52,
    z: 226,
    rot: -1.3,
  },
  {
    id: 'mirefen_shallows_mirebloom_01',
    nodeId: 'mirebloom_patch',
    zoneId: 'mirefen_marsh',
    x: -124,
    z: 315,
  },
  {
    id: 'mirefen_chapel_mirebloom_01',
    nodeId: 'mirebloom_patch',
    zoneId: 'mirefen_marsh',
    x: 88,
    z: 408,
  },

  {
    id: 'thornpeak_deeprock_stormsilver_01',
    nodeId: 'stormsilver_vein',
    zoneId: 'thornpeak_heights',
    x: 94,
    z: 605,
    rot: -1.7,
  },
  {
    id: 'thornpeak_stormcrag_stormsilver_01',
    nodeId: 'stormsilver_vein',
    zoneId: 'thornpeak_heights',
    x: 118,
    z: 768,
    rot: 0.8,
  },
  {
    id: 'thornpeak_stalker_highpine_01',
    nodeId: 'highpine_deadfall',
    zoneId: 'thornpeak_heights',
    x: -58,
    z: 602,
    rot: 1.6,
  },
  {
    id: 'thornpeak_ogre_highpine_01',
    nodeId: 'highpine_deadfall',
    zoneId: 'thornpeak_heights',
    x: -104,
    z: 714,
    rot: -0.4,
  },
  {
    id: 'thornpeak_glimmermere_frostcap_01',
    nodeId: 'frostcap_patch',
    zoneId: 'thornpeak_heights',
    x: -82,
    z: 769,
  },
  {
    id: 'thornpeak_sanctum_frostcap_01',
    nodeId: 'frostcap_patch',
    zoneId: 'thornpeak_heights',
    x: 18,
    z: 842,
  },
];

export const GATHER_NODE_PROPS: Pick<ZonePropsDef, 'gatherNodes'> = {
  gatherNodes: GATHER_NODE_PLACEMENTS,
};
