// The Hollow Crypt's trash (docs/design/dungeon-rework/hollow_crypt.md,
// "Trash"): simple, readable pack mechanics in the style of classic five-man
// trash, NOT lessons for the next boss. Each type has one job the group learns
// to answer:
//
//   Ossuary Warrior         Grave Cleave: a telegraphed frontal cone. Step out.
//   Gravecaller Adept       Grave Bolt: a hard shadow bolt. Interrupt it.
//   Ossuary Cutthroat       Rending Leap: leaps onto the farthest caster, bleeds.
//   Gravecaller Necromancer Raise Bones: a channel. Interrupt it, or a minion rises.
//   Bone Minion             grows into a Bone Brute in 8 s; dies in a Bone Burst.
//   Chapel Gargoyle         waits on its perch, dives in; Stone Shriek stuns. Kick it.
//   Crow Caller             Murder Call summons another flock. Kick it.
//   Carrion Crow            weak fast fliers, in flocks.
//   Ossuary Drake           the flying patrol: fire breath in front, tail behind, a wing gust.
//
// Numbers are classic-era normal-mode bases for levels 7 to 10, anchored to
// the shipped crypt trash (Crypt Shambler 7 + 2.2/level, 437 health at level 8)
// and to Morthen's 12 to 18 Shadow Pulse at level 10: a Grave Bolt costs a
// cloth wearer about a sixth of their health, so an uninterrupted one hurts
// but never kills on normal. Heroic scales them through the dungeon's
// difficulty transform (mechanicDamageMult). Merged by data.ts.

import {
  CRYPT_BARROWFLAME_BREATH,
  CRYPT_GRAVE_BOLT,
  CRYPT_GRAVE_CLEAVE,
  CRYPT_MURDER_CALL,
  CRYPT_RAISE_BONES,
  CRYPT_STONE_SHRIEK,
  CRYPT_TAIL_LASH,
  CRYPT_WING_GUST,
} from '../mob/trash_kit/cast_ids';
import type { MobTemplate } from '../types';

const BONE_LOOT = [
  { copper: 95, chance: 1 },
  { itemId: 'bone_fragments', chance: 0.8 },
];
const CASTER_LOOT = [
  { copper: 110, chance: 1 },
  { itemId: 'linen_scrap', chance: 0.6 },
];

export const HOLLOW_CRYPT_TRASH_MOBS: Record<string, MobTemplate> = {
  crypt_ossuary_warrior: {
    id: 'crypt_ossuary_warrior',
    name: 'Ossuary Warrior',
    minLevel: 8,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    hpBase: 55,
    hpPerLevel: 21,
    dmgBase: 7,
    dmgPerLevel: 2.2,
    attackSpeed: 2.4,
    armorPerLevel: 20,
    moveSpeed: 6.5,
    aggroRadius: 12,
    // A wide, slow, telegraphed swing across its front: only the tank eats it.
    breathCone: {
      castId: CRYPT_GRAVE_CLEAVE,
      name: 'Grave Cleave',
      castTime: 1.6,
      every: 10,
      range: 8,
      arcDeg: 110,
      min: 16,
      max: 24,
      school: 'physical',
    },
    loot: BONE_LOOT,
    scale: 1.1,
    color: 0xd8cfb8,
  },
  crypt_gravecaller_adept: {
    id: 'crypt_gravecaller_adept',
    name: 'Gravecaller Adept',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    hpBase: 40,
    hpPerLevel: 17,
    dmgBase: 6,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    // Stands back and throws grave sparks between its Grave Bolts.
    petSpell: {
      name: 'Grave Spark',
      school: 'shadow',
      min: 8,
      max: 12,
      range: 26,
      every: 3,
      windup: 0.6,
    },
    trashKit: {
      bolt: {
        castId: CRYPT_GRAVE_BOLT,
        name: 'Grave Bolt',
        castTime: 2.5,
        every: 9,
        first: 3,
        school: 'shadow',
        range: 30,
        min: 26,
        max: 34,
      },
    },
    loot: CASTER_LOOT,
    scale: 1.0,
    color: 0x8f6cc4,
  },
  crypt_ossuary_cutthroat: {
    id: 'crypt_ossuary_cutthroat',
    name: 'Ossuary Cutthroat',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    hpBase: 45,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 1.9,
    attackSpeed: 1.8,
    armorPerLevel: 14,
    moveSpeed: 7.5,
    aggroRadius: 12,
    trashKit: {
      leap: {
        name: 'Rending Leap',
        every: 14,
        first: 2,
        minRange: 8,
        maxRange: 30,
        seconds: 0.7,
        fixate: 4,
        bleed: { perTick: 5, interval: 2, duration: 8 },
      },
    },
    loot: BONE_LOOT,
    scale: 1.0,
    color: 0xa8b0b0,
  },
  crypt_gravecaller_necromancer: {
    id: 'crypt_gravecaller_necromancer',
    name: 'Gravecaller Necromancer',
    minLevel: 9,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    hpBase: 44,
    hpPerLevel: 18,
    dmgBase: 6,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    petSpell: {
      name: 'Grave Spark',
      school: 'shadow',
      min: 9,
      max: 13,
      range: 26,
      every: 3.4,
      windup: 0.6,
    },
    trashKit: {
      raise: {
        castId: CRYPT_RAISE_BONES,
        name: 'Raise Bones',
        castTime: 3,
        every: 15,
        first: 3,
        school: 'shadow',
        summon: 'crypt_bone_minion',
        maxAlive: 2,
      },
    },
    loot: CASTER_LOOT,
    scale: 1.05,
    color: 0x6fd6a8,
  },
  crypt_bone_minion: {
    id: 'crypt_bone_minion',
    name: 'Bone Minion',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    hpBase: 30,
    hpPerLevel: 12,
    dmgBase: 4,
    dmgPerLevel: 1.3,
    attackSpeed: 1.6,
    armorPerLevel: 8,
    moveSpeed: 9,
    aggroRadius: 10,
    // Kill it fast: left alive it swells into a Bone Brute. Killed, it bursts.
    trashKit: { grow: { after: 8, into: 'crypt_bone_brute', name: 'Bone Growth' } },
    deathThroes: {
      min: 12,
      max: 18,
      radius: 3.5,
      delay: 1.8,
      name: 'Bone Burst',
      school: 'physical',
    },
    loot: [],
    scale: 0.85,
    color: 0xe8e0c8,
  },
  crypt_bone_brute: {
    id: 'crypt_bone_brute',
    name: 'Bone Brute',
    minLevel: 9,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    hpBase: 70,
    hpPerLevel: 24,
    dmgBase: 10,
    dmgPerLevel: 2.6,
    attackSpeed: 2.8,
    armorPerLevel: 22,
    moveSpeed: 6,
    aggroRadius: 12,
    loot: [{ copper: 60, chance: 1 }],
    scale: 1.0,
    color: 0xd9d0bc,
  },
  crypt_chapel_gargoyle: {
    id: 'crypt_chapel_gargoyle',
    name: 'Chapel Gargoyle',
    minLevel: 9,
    maxLevel: 9,
    family: 'elemental',
    elite: true,
    hpBase: 50,
    hpPerLevel: 20,
    dmgBase: 8,
    dmgPerLevel: 2.3,
    attackSpeed: 2.2,
    armorPerLevel: 30,
    moveSpeed: 7,
    // A statue until its pack is pulled (it only wakes this close on its own).
    aggroRadius: 5,
    trashKit: {
      perch: { diveSeconds: 1.1, name: 'Stone Dive' },
      screech: {
        castId: CRYPT_STONE_SHRIEK,
        name: 'Stone Shriek',
        castTime: 2,
        every: 16,
        first: 5,
        school: 'nature',
        radius: 10,
        stun: 2.5,
        min: 6,
        max: 10,
      },
    },
    loot: [
      { copper: 120, chance: 1 },
      { itemId: 'bone_fragments', chance: 0.4 },
    ],
    // A great stone brute over three times a player's height crouched on its
    // arch (the body is authored at 5.8 yd; the melee reach follows the body).
    scale: 1.5,
    color: 0x8c8f99,
  },
  crypt_crow_caller: {
    id: 'crypt_crow_caller',
    name: 'Crow Caller',
    minLevel: 8,
    maxLevel: 8,
    family: 'humanoid',
    elite: true,
    hpBase: 42,
    hpPerLevel: 17,
    dmgBase: 6,
    dmgPerLevel: 1.8,
    attackSpeed: 2.2,
    armorPerLevel: 12,
    moveSpeed: 7,
    aggroRadius: 12,
    petSpell: {
      name: 'Carrion Hex',
      school: 'nature',
      min: 7,
      max: 11,
      range: 26,
      every: 3.2,
      windup: 0.6,
    },
    trashKit: {
      call: {
        castId: CRYPT_MURDER_CALL,
        name: 'Murder Call',
        castTime: 3,
        every: 18,
        first: 5,
        school: 'nature',
        summon: 'crypt_carrion_crow',
        count: 4,
        maxAlive: 6,
      },
    },
    loot: CASTER_LOOT,
    scale: 1.0,
    color: 0x3a3440,
  },
  crypt_carrion_crow: {
    id: 'crypt_carrion_crow',
    name: 'Carrion Crow',
    minLevel: 7,
    maxLevel: 7,
    family: 'beast',
    hpBase: 18,
    hpPerLevel: 7,
    dmgBase: 3,
    dmgPerLevel: 1,
    attackSpeed: 2,
    armorPerLevel: 4,
    moveSpeed: 11,
    aggroRadius: 12,
    untameable: true,
    trashKit: { land: { seconds: 1 } },
    loot: [],
    scale: 1.0,
    color: 0x2b2830,
  },
  crypt_ossuary_drake: {
    id: 'crypt_ossuary_drake',
    name: 'Ossuary Drake',
    minLevel: 10,
    maxLevel: 10,
    family: 'undead',
    elite: true,
    hpBase: 110,
    hpPerLevel: 38,
    dmgBase: 11,
    dmgPerLevel: 2.8,
    attackSpeed: 2.2,
    armorPerLevel: 24,
    moveSpeed: 7.5,
    // It sees you from the sky: a pass overhead is a pull.
    aggroRadius: 16,
    // Spectral fire from the soul caged in its ribs, poured down a long cone.
    breathCone: {
      castId: CRYPT_BARROWFLAME_BREATH,
      name: 'Barrowflame Breath',
      castTime: 2,
      every: 12,
      range: 14,
      arcDeg: 70,
      min: 26,
      max: 34,
      school: 'fire',
    },
    trashKit: {
      land: { seconds: 2.2 },
      tailLash: {
        castId: CRYPT_TAIL_LASH,
        name: 'Tail Lash',
        castTime: 1,
        every: 9,
        first: 6,
        school: 'physical',
        range: 10,
        arcDeg: 120,
        min: 18,
        max: 26,
      },
      wingGust: {
        castId: CRYPT_WING_GUST,
        name: 'Wing Gust',
        castTime: 1.5,
        every: 16,
        first: 10,
        school: 'physical',
        radius: 10,
        knockback: 8,
        min: 10,
        max: 16,
      },
    },
    loot: [
      { copper: 400, chance: 1 },
      { itemId: 'bone_fragments', chance: 1 },
    ],
    scale: 1.0,
    color: 0xe3dccb,
  },
};
