import type {
  DungeonDef,
  DungeonSpawn,
  ItemDef,
  MobTemplate,
  PlayerClass,
  QuestDef,
} from '../types';

const WAR: PlayerClass[] = ['warrior', 'paladin', 'shaman'];
const ROG: PlayerClass[] = ['rogue', 'hunter'];
const MAG: PlayerClass[] = ['mage', 'priest', 'warlock', 'druid'];

export const INFERNAL_ABYSS_ITEMS: Record<string, ItemDef> = {
  infernal_slag: {
    id: 'infernal_slag',
    name: 'Abyssal Slag',
    kind: 'junk',
    quality: 'poor',
    sellValue: 55,
  },
  charred_legion_tablet: {
    id: 'charred_legion_tablet',
    name: 'Charred Legion Tablet',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_infernal_abyss_echoes',
  },
  brands_of_the_first_flame: {
    id: 'brands_of_the_first_flame',
    name: 'Brands of the First Flame',
    kind: 'quest',
    sellValue: 0,
    questId: 'q_infernal_abyss_echoes',
  },
  forgekeepers_ledger: {
    id: 'forgekeepers_ledger',
    name: "Forgekeeper's Ledger",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_infernal_abyss_covenant',
  },
  azazels_broken_covenant: {
    id: 'azazels_broken_covenant',
    name: "Azazel's Broken Covenant",
    kind: 'quest',
    sellValue: 0,
    questId: 'q_infernal_abyss_covenant',
  },
  emberforged_vambraces: {
    id: 'emberforged_vambraces',
    name: 'Emberforged Vambraces',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'rare',
    stats: { armor: 190, str: 5, sta: 4 },
    sellValue: 4200,
    requiredClass: WAR,
  },
  cinderthread_mantle: {
    id: 'cinderthread_mantle',
    name: 'Cinderthread Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'rare',
    stats: { armor: 72, int: 6, spi: 4 },
    sellValue: 4200,
    requiredClass: MAG,
  },
  hellstalker_boots: {
    id: 'hellstalker_boots',
    name: 'Hellstalker Boots',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'rare',
    stats: { armor: 148, agi: 5, sta: 3 },
    sellValue: 4200,
    requiredClass: ROG,
  },
  forgekeepers_warhammer: {
    id: 'forgekeepers_warhammer',
    name: "Forgekeeper's Warhammer",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 28, max: 45, speed: 2.6 },
    stats: { str: 8, sta: 5 },
    sellValue: 4800,
    requiredClass: ['warrior', 'rogue', 'hunter', 'shaman', 'paladin'],
  },
  forgekeepers_runestaff: {
    id: 'forgekeepers_runestaff',
    name: "Forgekeeper's Runestaff",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 30, max: 49, speed: 3.0 },
    stats: { int: 9, spi: 4 },
    sellValue: 4800,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  forgekeepers_fang: {
    id: 'forgekeepers_fang',
    name: "Forgekeeper's Fang",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'rare',
    weapon: { min: 18, max: 29, speed: 1.7, dagger: true },
    stats: { agi: 9, sta: 4 },
    sellValue: 4800,
    requiredClass: ROG,
  },
  azazels_ruinblade: {
    id: 'azazels_ruinblade',
    name: "Azazel's Ruinblade",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 29, max: 46, speed: 2.6 },
    stats: { str: 11, sta: 7 },
    sellValue: 9500,
    requiredClass: ['warrior', 'rogue', 'hunter', 'shaman', 'paladin'],
  },
  azazels_soulstaff: {
    id: 'azazels_soulstaff',
    name: "Azazel's Soulstaff",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 33, max: 54, speed: 3.0 },
    stats: { int: 12, spi: 6 },
    sellValue: 9500,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
  azazels_emberfang: {
    id: 'azazels_emberfang',
    name: "Azazel's Emberfang",
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    weapon: { min: 19, max: 30, speed: 1.7, dagger: true },
    stats: { agi: 12, sta: 6 },
    sellValue: 9500,
    requiredClass: ROG,
  },
  hellforged_bulwark: {
    id: 'hellforged_bulwark',
    name: 'Hellforged Bulwark',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    stats: { armor: 280, str: 8, sta: 10 },
    sellValue: 9000,
    requiredClass: WAR,
  },
  cinderseer_raiment: {
    id: 'cinderseer_raiment',
    name: 'Cinderseer Raiment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    stats: { armor: 95, int: 11, spi: 7 },
    sellValue: 9000,
    requiredClass: MAG,
  },
  abysswalker_harness: {
    id: 'abysswalker_harness',
    name: 'Abysswalker Harness',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    stats: { armor: 178, agi: 12, sta: 6 },
    sellValue: 9000,
    requiredClass: ROG,
  },
};

export const INFERNAL_ABYSS_MOBS: Record<string, MobTemplate> = {
  abyssal_legionnaire: {
    id: 'abyssal_legionnaire',
    name: 'Abyssal Legionnaire',
    minLevel: 20,
    maxLevel: 20,
    family: 'demon',
    elite: true,
    hpBase: 72,
    hpPerLevel: 24,
    dmgBase: 13,
    dmgPerLevel: 2.9,
    attackSpeed: 2.3,
    armorPerLevel: 28,
    moveSpeed: 7,
    aggroRadius: 13,
    cleave: { radius: 7, mult: 0.5, name: 'Burning Cleave' },
    loot: [
      { copper: 420, chance: 1 },
      { itemId: 'infernal_slag', chance: 0.45 },
    ],
    scale: 1.25,
    color: 0x8f2418,
  },
  cinder_magus: {
    id: 'cinder_magus',
    name: 'Cinder Magus',
    minLevel: 20,
    maxLevel: 20,
    family: 'demon',
    elite: true,
    hpBase: 62,
    hpPerLevel: 21,
    dmgBase: 14,
    dmgPerLevel: 3,
    attackSpeed: 2.1,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 14,
    aoePulse: { min: 20, max: 28, radius: 9, every: 10, name: 'Cinderburst', school: 'fire' },
    loot: [
      { copper: 440, chance: 1 },
      { itemId: 'infernal_slag', chance: 0.5 },
      { itemId: 'cinderthread_mantle', chance: 0.025 },
    ],
    scale: 1.1,
    color: 0xc13e1d,
  },
  molten_hellhound: {
    id: 'molten_hellhound',
    name: 'Molten Hellhound',
    minLevel: 20,
    maxLevel: 20,
    family: 'demon',
    elite: true,
    hpBase: 66,
    hpPerLevel: 22,
    dmgBase: 13,
    dmgPerLevel: 3,
    attackSpeed: 1.8,
    armorPerLevel: 20,
    moveSpeed: 8.2,
    aggroRadius: 13,
    loot: [
      { copper: 390, chance: 1 },
      { itemId: 'infernal_slag', chance: 0.4 },
      { itemId: 'hellstalker_boots', chance: 0.025 },
    ],
    scale: 1.2,
    color: 0xdf4a16,
  },
  flamebound_smith: {
    id: 'flamebound_smith',
    name: 'Flamebound Smith',
    minLevel: 20,
    maxLevel: 20,
    family: 'humanoid',
    elite: true,
    hpBase: 76,
    hpPerLevel: 24,
    dmgBase: 14,
    dmgPerLevel: 3,
    attackSpeed: 2.5,
    armorPerLevel: 30,
    moveSpeed: 6.7,
    aggroRadius: 13,
    stomp: { radius: 8, every: 13, duration: 1, min: 18, max: 25, name: 'Anvil Slam' },
    loot: [
      { copper: 460, chance: 1 },
      { itemId: 'infernal_slag', chance: 0.55 },
      { itemId: 'emberforged_vambraces', chance: 0.025 },
    ],
    scale: 1.2,
    color: 0xa83220,
  },
  abyssal_gladiator: {
    id: 'abyssal_gladiator',
    name: 'Abyssal Gladiator',
    minLevel: 20,
    maxLevel: 20,
    family: 'demon',
    elite: true,
    hpBase: 82,
    hpPerLevel: 26,
    dmgBase: 15,
    dmgPerLevel: 3.1,
    attackSpeed: 2.2,
    armorPerLevel: 30,
    moveSpeed: 7.3,
    aggroRadius: 13,
    enrage: { belowHpPct: 0.3, dmgMult: 1.35, hasteMult: 1.2 },
    loot: [
      { copper: 520, chance: 1 },
      { itemId: 'infernal_slag', chance: 0.6 },
    ],
    scale: 1.3,
    color: 0x741d18,
  },
  infernal_cinderling: {
    id: 'infernal_cinderling',
    name: 'Abyssal Cinderling',
    minLevel: 20,
    maxLevel: 20,
    family: 'elemental',
    hpBase: 42,
    hpPerLevel: 15,
    dmgBase: 10,
    dmgPerLevel: 2.3,
    attackSpeed: 1.8,
    armorPerLevel: 14,
    moveSpeed: 8,
    aggroRadius: 12,
    loot: [],
    scale: 0.85,
    color: 0xff6a1f,
  },
  forgekeeper: {
    id: 'forgekeeper',
    name: 'The Forgekeeper',
    minLevel: 20,
    maxLevel: 20,
    family: 'demon',
    elite: true,
    ccImmune: true,
    hpBase: 300,
    hpPerLevel: 38,
    dmgBase: 15,
    dmgPerLevel: 3.1,
    attackSpeed: 2.5,
    armorPerLevel: 34,
    moveSpeed: 6.8,
    aggroRadius: 16,
    bigCast: {
      castId: 'forgekeepers_wrath',
      name: "Forgekeeper's Wrath",
      castTime: 2.5,
      every: 14,
      radius: 13,
      min: 32,
      max: 44,
      school: 'fire',
      yell: 'Every soul is fuel for the forge!',
    },
    summonAdds: { mobId: 'infernal_cinderling', count: 2, atHpPct: [0.5] },
    yells: {
      engage: 'The master demands another weapon. Your bones will serve.',
      summon: 'Cinders, rise from the crucible!',
    },
    loot: [
      { copper: 6500, chance: 1 },
      { itemId: 'forgekeepers_warhammer', chance: 0.34, rollGroup: 'forgekeeper_rare' },
      { itemId: 'forgekeepers_runestaff', chance: 0.33, rollGroup: 'forgekeeper_rare' },
      { itemId: 'forgekeepers_fang', chance: 0.33, rollGroup: 'forgekeeper_rare' },
    ],
    scale: 1.55,
    color: 0xb42b19,
  },
  pyre_golem: {
    id: 'pyre_golem',
    name: 'Pyre Golem',
    minLevel: 20,
    maxLevel: 20,
    family: 'elemental',
    elite: true,
    ccImmune: true,
    hpBase: 330,
    hpPerLevel: 40,
    dmgBase: 16,
    dmgPerLevel: 3.2,
    attackSpeed: 2.8,
    armorPerLevel: 38,
    moveSpeed: 6.2,
    aggroRadius: 16,
    aoePulse: { min: 28, max: 38, radius: 12, every: 9, name: 'Pyre Nova', school: 'fire' },
    stomp: {
      radius: 10,
      every: 13,
      duration: 1.5,
      min: 22,
      max: 30,
      name: 'Molten Quake',
      school: 'fire',
    },
    enrage: { belowHpPct: 0.3, dmgMult: 1.45, hasteMult: 1.25 },
    loot: [
      { copper: 7000, chance: 1 },
      { itemId: 'emberforged_vambraces', chance: 0.34, rollGroup: 'pyre_golem_rare' },
      { itemId: 'cinderthread_mantle', chance: 0.33, rollGroup: 'pyre_golem_rare' },
      { itemId: 'hellstalker_boots', chance: 0.33, rollGroup: 'pyre_golem_rare' },
    ],
    scale: 1.8,
    color: 0xe24c18,
  },
  azazel_infernal_lord: {
    id: 'azazel_infernal_lord',
    name: 'Azazel the Abyssal Lord',
    minLevel: 20,
    maxLevel: 20,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 560,
    hpPerLevel: 54,
    dmgBase: 17,
    dmgPerLevel: 3.4,
    attackSpeed: 2.5,
    armorPerLevel: 38,
    moveSpeed: 7.2,
    aggroRadius: 20,
    bigCast: {
      castId: 'azazel_apocalypse_flame',
      name: 'Apocalypse Flame',
      castTime: 3,
      every: 18,
      radius: 17,
      min: 42,
      max: 58,
      school: 'fire',
      yell: 'The first flame will consume the last hope!',
    },
    aoePulse: {
      min: 30,
      max: 42,
      radius: 13,
      every: 9,
      name: 'Abyssal Firestorm',
      school: 'fire',
      fx: 'nova',
    },
    stomp: {
      radius: 11,
      every: 15,
      duration: 1.5,
      min: 24,
      max: 34,
      name: 'Hellbreaker Stomp',
      school: 'fire',
    },
    summonAdds: { mobId: 'infernal_cinderling', count: 3, atHpPct: [0.7, 0.4] },
    terrify: { radius: 14, every: 20, duration: 3, name: 'Gaze of the Abyss', school: 'shadow' },
    enrage: { belowHpPct: 0.2, dmgMult: 1.6, hasteMult: 1.3 },
    yells: {
      engage: 'Mortals enter my kingdom only once.',
      summon: 'Children of ash, tear them apart!',
      enrage: 'The covenant is broken. I will burn this world myself!',
    },
    battleYells: {
      lines: ['Kneel before the lord beneath the mountain!', 'Your courage is only kindling!'],
      every: 16,
      range: 100,
    },
    loot: [
      { copper: 60000, chance: 1 },
      { itemId: 'hellforged_bulwark', chance: 0.34, rollGroup: 'azazel_guaranteed_armor' },
      { itemId: 'cinderseer_raiment', chance: 0.33, rollGroup: 'azazel_guaranteed_armor' },
      { itemId: 'abysswalker_harness', chance: 0.33, rollGroup: 'azazel_guaranteed_armor' },
      { itemId: 'azazels_ruinblade', chance: 0.08, rollGroup: 'azazel_epic' },
      { itemId: 'azazels_soulstaff', chance: 0.08, rollGroup: 'azazel_epic' },
      { itemId: 'azazels_emberfang', chance: 0.08, rollGroup: 'azazel_epic' },
    ],
    scale: 2.1,
    color: 0x6f130f,
  },
};

export const INFERNAL_ABYSS_QUESTS: Record<string, QuestDef> = {
  q_infernal_abyss_echoes: {
    id: 'q_infernal_abyss_echoes',
    name: 'Echoes Beneath Stormcrag',
    giverNpcId: 'loremaster_caddis',
    turnInNpcId: 'loremaster_caddis',
    text: 'Stormcrag was not born from a storm, $N. The oldest tablets call it a lid, hammered over a fire that fell from beyond the world. A new fissure has opened beneath the eastern crag. Enter it with four allies and recover the legion tablet and the brands carved beside the first flame.',
    completionText:
      'The tablet names a host that marched willingly into the fire. The brands name the power they served: Azazel. This was never a prison built to keep demons out, $N. It was a gate built to let their lord in.',
    objectives: [
      {
        type: 'interact',
        targetObjectItemId: 'charred_legion_tablet',
        count: 1,
        label: 'Charred Legion Tablet deciphered',
      },
      {
        type: 'interact',
        targetObjectItemId: 'brands_of_the_first_flame',
        count: 1,
        label: 'Brands of the First Flame studied',
      },
    ],
    xpReward: 4800,
    copperReward: 3000,
    itemRewards: {},
    minLevel: 20,
    suggestedPlayers: 5,
  },
  q_infernal_abyss_covenant: {
    id: 'q_infernal_abyss_covenant',
    name: 'The Broken Covenant',
    giverNpcId: 'loremaster_caddis',
    turnInNpcId: 'loremaster_caddis',
    text: "The legion's oath promised Azazel a road into our world, but every covenant has a price and a flaw. Return to the Molten Abyss. Find the Forgekeeper's ledger and the broken covenant near the Maw. If we learn what bound him, we may learn how he can be slain.",
    completionText:
      'Here is the flaw: Azazel fed the gate with the names of his own legion. Every servant consumed made him stronger, but tied his life to the forge below. Break the lord in the heart of that forge, and the gate must die with him.',
    objectives: [
      {
        type: 'interact',
        targetObjectItemId: 'forgekeepers_ledger',
        count: 1,
        label: "Forgekeeper's Ledger recovered",
      },
      {
        type: 'interact',
        targetObjectItemId: 'azazels_broken_covenant',
        count: 1,
        label: "Azazel's Broken Covenant read",
      },
    ],
    xpReward: 5000,
    copperReward: 3500,
    itemRewards: {},
    requiresQuest: 'q_infernal_abyss_echoes',
    minLevel: 20,
    suggestedPlayers: 5,
  },
  q_infernal_abyss_azazel: {
    id: 'q_infernal_abyss_azazel',
    name: 'Lord of the Molten Abyss',
    giverNpcId: 'loremaster_caddis',
    turnInNpcId: 'loremaster_caddis',
    text: 'The covenant gives us one chance, $N. Descend past the forge and the Maw with companions you trust. Face Azazel where the first flame touches our world, endure his legions, and extinguish the Abyssal Lord before Stormcrag becomes his open gate.',
    completionText:
      'The mountain is quiet. Not sleeping, not waiting, simply quiet. Azazel built eternity from stolen names, and you ended it with one mortal name of your own. Highwatch will remember it, $N.',
    objectives: [
      {
        type: 'kill',
        targetMobId: 'azazel_infernal_lord',
        count: 1,
        label: 'Azazel the Abyssal Lord slain',
      },
    ],
    xpReward: 6000,
    copperReward: 30000,
    itemRewards: {
      warrior: 'hellforged_bulwark',
      mage: 'cinderseer_raiment',
      rogue: 'abysswalker_harness',
    },
    requiresQuest: 'q_infernal_abyss_covenant',
    minLevel: 20,
    suggestedPlayers: 5,
  },
};

export const INFERNAL_ABYSS_QUEST_ORDER = [
  'q_infernal_abyss_echoes',
  'q_infernal_abyss_covenant',
  'q_infernal_abyss_azazel',
];

const INFERNAL_ABYSS_SPAWNS: DungeonSpawn[] = [
  // Lower junction and the maze switchbacks.
  { mobId: 'abyssal_legionnaire', x: -6, z: 27 },
  { mobId: 'cinder_magus', x: 7, z: 30 },
  { mobId: 'molten_hellhound', x: -17, z: 49 },
  { mobId: 'molten_hellhound', x: -36, z: 61 },
  { mobId: 'abyssal_legionnaire', x: -35, z: 80 },
  { mobId: 'cinder_magus', x: -18, z: 88 },
  { mobId: 'pyre_golem', x: -64, z: 84 },
  // The great forge.
  { mobId: 'flamebound_smith', x: -14, z: 100 },
  { mobId: 'flamebound_smith', x: 14, z: 102 },
  { mobId: 'forgekeeper', x: 0, z: 121 },
  // Optional gladiator side room.
  { mobId: 'abyssal_gladiator', x: 48, z: 110 },
  { mobId: 'abyssal_gladiator', x: 56, z: 123 },
  // The Maw.
  { mobId: 'molten_hellhound', x: -2, z: 153 },
  { mobId: 'cinder_magus', x: 2, z: 170 },
  { mobId: 'abyssal_legionnaire', x: -7, z: 184 },
  { mobId: 'cinder_magus', x: 7, z: 184 },
  // Throne of the first flame.
  { mobId: 'azazel_infernal_lord', x: 0, z: 224 },
];

export const INFERNAL_ABYSS_DUNGEON_DEFS: Record<string, DungeonDef> = {
  infernal_abyss: {
    id: 'infernal_abyss',
    name: 'Molten Abyss',
    index: 6,
    // At the FOOT of the Stormcrag cliff on gentle ground (h ~9.8): x >= 152
    // is already the steep rock face and buries the door in the mountainside.
    doorPos: { x: 148, z: 756 },
    entry: { x: 0, z: -10 },
    exitOffset: { x: 0, z: -14 },
    spawns: INFERNAL_ABYSS_SPAWNS,
    objects: [
      { itemId: 'charred_legion_tablet', name: 'Charred Legion Tablet', x: -48, z: 48 },
      { itemId: 'brands_of_the_first_flame', name: 'Brands of the First Flame', x: -57, z: 88 },
      { itemId: 'forgekeepers_ledger', name: "Forgekeeper's Ledger", x: 61, z: 116 },
      {
        itemId: 'azazels_broken_covenant',
        name: "Azazel's Broken Covenant",
        x: -8,
        z: 184,
      },
    ],
    interior: 'infernal_abyss',
    suggestedPlayers: 5,
    enterText: 'You descend beneath Stormcrag into the Molten Abyss.',
    leaveText: 'You climb from the furnace-dark into the mountain wind.',
  },
};
