import type { AbilityDef } from '../types';

export const LEVEL_40_CLASS_ABILITIES: Record<string, AbilityDef> = {
  gravebreaker: {
    id: 'gravebreaker',
    name: 'Gravebreaker',
    class: 'warrior',
    learnLevel: 30,
    cost: 35,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 150, max: 180, radius: 8 }],
    description: 'Smashes the ground, dealing $d Physical damage to enemies within 8 yd.',
  },
  last_light: {
    id: 'last_light',
    name: 'Last Light',
    class: 'paladin',
    learnLevel: 30,
    cost: 90,
    castTime: 0,
    cooldown: 90,
    range: 0,
    school: 'holy',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_dr', value: 0.35, duration: 12 }],
    description: 'Reduces all damage you take by 35% for 12 sec.',
  },
  blackfletch: {
    id: 'blackfletch',
    name: 'Blackfletch',
    class: 'hunter',
    learnLevel: 30,
    cost: 35,
    castTime: 0,
    cooldown: 8,
    range: 35,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'directDamage', min: 180, max: 218 }],
    description: 'Fires an ashen arrow for $d Physical damage.',
  },
  duskstep: {
    id: 'duskstep',
    name: 'Duskstep',
    class: 'rogue',
    learnLevel: 30,
    cost: 35,
    castTime: 0,
    cooldown: 8,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'weaponStrike', bonus: 120, weaponMult: 0.8 }],
    description: 'Strikes for 80% weapon damage plus $d Physical damage.',
  },
  memorial_grace: {
    id: 'memorial_grace',
    name: 'Memorial Grace',
    class: 'priest',
    learnLevel: 30,
    cost: 120,
    castTime: 1.5,
    cooldown: 12,
    range: 30,
    school: 'holy',
    requiresTarget: true,
    targetType: 'friendly',
    effects: [{ type: 'heal', min: 320, max: 380 }],
    description: 'Heals a friendly target for $d.',
  },
  ancestor_storm: {
    id: 'ancestor_storm',
    name: 'Ancestor Storm',
    class: 'shaman',
    learnLevel: 30,
    cost: 110,
    castTime: 0,
    cooldown: 15,
    range: 0,
    school: 'nature',
    requiresTarget: false,
    effects: [{ type: 'aoeDamage', min: 142, max: 174, radius: 10 }],
    description: 'Calls ancestral lightning for $d Nature damage to enemies within 10 yd.',
  },
  cinder_comet: {
    id: 'cinder_comet',
    name: 'Cinder Comet',
    class: 'mage',
    learnLevel: 30,
    cost: 130,
    castTime: 2,
    cooldown: 12,
    range: 30,
    school: 'fire',
    requiresTarget: false,
    targetMode: 'position',
    effects: [{ type: 'aoeDamage', min: 210, max: 250, radius: 8 }],
    description: 'Calls down a comet for $d Fire damage to enemies within 8 yd of the target area.',
  },
  funeral_pyre: {
    id: 'funeral_pyre',
    name: 'Funeral Pyre',
    class: 'warlock',
    learnLevel: 30,
    cost: 105,
    castTime: 0,
    cooldown: 10,
    range: 30,
    school: 'shadow',
    requiresTarget: true,
    effects: [{ type: 'dot', total: 240, duration: 12, interval: 3 }],
    description: 'Burns the enemy for 240 Shadow damage over 12 sec in 4 ticks.',
  },
  crown_of_briars: {
    id: 'crown_of_briars',
    name: 'Crown of Briars',
    class: 'druid',
    learnLevel: 30,
    cost: 100,
    castTime: 0,
    cooldown: 30,
    range: 30,
    school: 'nature',
    requiresTarget: true,
    targetType: 'friendly',
    tooltipOmitEffectLines: true,
    effects: [{ type: 'buffTarget', kind: 'thorns', value: 96, duration: 20 }],
    description: 'For 20 sec, each melee attacker that strikes the target takes 96 Nature damage.',
  },
};
