// SwordMaster class content. Mechanics for the dual-weapon effects live in
// combat/swordmaster.ts; this module is declarative data only.

import type { AbilityDef } from '../types';
import type { ClassDef } from './classes';

const START_RATIONS = [{ itemId: 'baked_bread', count: 5 }];

export const SWORDMASTER_IDENTITY_ABILITIES = [
  'crescent_sweep',
  'sword_aura',
  'blade_cyclone',
] as const;

export const SWORDMASTER_CLASS: ClassDef = {
  id: 'swordmaster',
  name: 'SwordMaster',
  baseStats: { str: 20, agi: 24, sta: 18, int: 10, spi: 12, armor: 40 },
  statsPerLevel: { str: 2, agi: 2, sta: 1, int: 0, spi: 0, armor: 8 },
  baseHp: 46,
  hpPerLevel: 15,
  baseMana: 100,
  manaPerLevel: 0,
  resourceType: 'energy',
  startWeapon: 'worn_sword',
  startOffhand: 'worn_sword',
  startChest: 'footpad_jerkin',
  startItems: START_RATIONS,
  abilities: [
    'twin_slash',
    'crescent_sweep',
    'fleet_step',
    'sword_aura',
    'wind_lunge',
    'parrying_flow',
    'quickening',
    'blade_dance',
    'twin_finisher',
  ],
  color: 0x22d3ee,
};

export const SWORDMASTER_ABILITIES: Record<string, AbilityDef> = {
  twin_slash: {
    id: 'twin_slash',
    name: 'Twin Slash',
    class: 'swordmaster',
    learnLevel: 1,
    cost: 30,
    castTime: 0,
    cooldown: 0,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'dualWeaponStrike', mainhandMult: 0.75, offhandMult: 0.55 }],
    description: 'Strike the target with both swords in main-hand then off-hand order.',
  },
  crescent_sweep: {
    id: 'crescent_sweep',
    name: 'Crescent Sweep',
    class: 'swordmaster',
    learnLevel: 1,
    cost: 35,
    castTime: 0,
    cooldown: 4,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    selfCentered: true,
    castFx: 'flourish',
    effects: [
      {
        type: 'dualWeaponAoe',
        mainhandMult: 0.55,
        offhandMult: 0.4,
        radius: 6,
        frontal: true,
        maxTargets: 5,
      },
    ],
    description: 'Sweep both swords through up to 5 enemies in a 6 yard frontal arc.',
  },
  fleet_step: {
    id: 'fleet_step',
    name: 'Fleet Step',
    class: 'swordmaster',
    learnLevel: 3,
    cost: 10,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 1.3, duration: 5 }],
    ranks: [
      {
        rank: 2,
        level: 10,
        cost: 10,
        effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 1.35, duration: 5 }],
      },
      {
        rank: 3,
        level: 17,
        cost: 10,
        effects: [{ type: 'selfBuff', kind: 'buff_speed', value: 1.4, duration: 5 }],
      },
    ],
    description: 'Increase movement speed for 5 sec. Higher ranks increase the bonus.',
  },
  sword_aura: {
    id: 'sword_aura',
    name: 'Sword Aura',
    class: 'swordmaster',
    learnLevel: 5,
    cost: 20,
    castTime: 2,
    cooldown: 120,
    range: 0,
    school: 'arcane',
    requiresTarget: false,
    castFx: 'weaponAura',
    effects: [{ type: 'selfBuff', kind: 'buff_str_agi', value: 12, duration: 300 }],
    description:
      'Imbue both swords with azure power, gaining 12 Strength and 12 Agility for 5 min.',
  },
  wind_lunge: {
    id: 'wind_lunge',
    name: 'Wind Lunge',
    class: 'swordmaster',
    learnLevel: 7,
    cost: 15,
    castTime: 0,
    cooldown: 12,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    offGcd: true,
    effects: [{ type: 'blinkForward', distance: 8, breakRoots: true }],
    description: 'Break roots and lunge 8 yards in your facing direction.',
  },
  parrying_flow: {
    id: 'parrying_flow',
    name: 'Parrying Flow',
    class: 'swordmaster',
    learnLevel: 9,
    cost: 20,
    castTime: 0,
    cooldown: 45,
    castFx: 'flourish',
    range: 0,
    school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_dodge', value: 0.2, duration: 8 }],
    description: 'Flow between incoming blows, gaining 20% dodge for 8 sec.',
  },
  quickening: {
    id: 'quickening',
    name: 'Quickening',
    class: 'swordmaster',
    learnLevel: 11,
    cost: 25,
    castTime: 0,
    cooldown: 60,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_haste', value: 1.25, duration: 12 }],
    description: 'Accelerate your attack speed by 25% for 12 sec.',
  },
  blade_dance: {
    id: 'blade_dance',
    name: 'Blade Dance',
    class: 'swordmaster',
    learnLevel: 14,
    cost: 45,
    castTime: 0,
    cooldown: 12,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    selfCentered: true,
    castFx: 'flourish',
    effects: [
      {
        type: 'dualWeaponAoe',
        mainhandMult: 0.65,
        offhandMult: 0.5,
        radius: 7,
        maxTargets: 6,
      },
    ],
    description: 'Dance through nearby enemies, striking up to 6 targets with both swords.',
  },
  twin_finisher: {
    id: 'twin_finisher',
    name: 'Twin Finisher',
    class: 'swordmaster',
    learnLevel: 17,
    cost: 50,
    castTime: 0,
    cooldown: 10,
    range: 0,
    school: 'physical',
    requiresTarget: true,
    effects: [{ type: 'dualWeaponStrike', mainhandMult: 1.25, offhandMult: 1 }],
    description: 'Commit both swords to a heavy two-part finishing strike.',
  },
  blade_cyclone: {
    id: 'blade_cyclone',
    name: 'Blade Cyclone',
    class: 'swordmaster',
    learnLevel: 5,
    specs: ['tempest'],
    cost: 50,
    castTime: 0,
    cooldown: 30,
    range: 0,
    school: 'physical',
    requiresTarget: false,
    selfCentered: true,
    castFx: 'flourish',
    effects: [
      {
        type: 'dualWeaponAoe',
        mainhandMult: 0.9,
        offhandMult: 0.7,
        radius: 9,
        maxTargets: 8,
      },
    ],
    description:
      'Become a cyclone of steel, striking up to 8 enemies within 9 yards with both swords.',
  },
  duelist_flurry: {
    id: 'duelist_flurry',
    name: 'Duelist Flurry',
    class: 'swordmaster',
    learnLevel: 5,
    specs: ['duelist'],
    cost: 20,
    castTime: 0,
    cooldown: 45,
    castFx: 'flourish',
    range: 0,
    school: 'physical',
    requiresTarget: false,
    effects: [{ type: 'selfBuff', kind: 'buff_haste', value: 1.35, duration: 12 }],
    description: 'Enter a measured flurry, increasing attack speed by 35% for 12 sec.',
  },
  azure_rush: {
    id: 'azure_rush',
    name: 'Azure Rush',
    class: 'swordmaster',
    learnLevel: 5,
    specs: ['azure_blade'],
    cost: 20,
    castTime: 0,
    cooldown: 20,
    range: 0,
    school: 'arcane',
    requiresTarget: false,
    offGcd: true,
    effects: [
      { type: 'blinkForward', distance: 12, breakRoots: true },
      { type: 'aoeSlow', mult: 0.5, duration: 3, radius: 5 },
    ],
    description:
      'Rush 12 yards in a flash of azure steel and slow nearby enemies by 50% for 3 sec.',
  },
};
