// Spec-only talent content for the eight non-warrior classes.

import type { PlayerClass } from '../types';
import type { ClassTalents, Role, SpecDef, TalentEffect } from './talents';

function spec(
  id: string,
  cls: PlayerClass,
  name: string,
  role: Role,
  icon: string,
  description: string,
  signature: string,
  masteryName: string,
  masteryDescription: string,
  effect: TalentEffect,
): SpecDef {
  return {
    id,
    class: cls,
    name,
    role,
    icon,
    description,
    signature,
    mastery: { name: masteryName, description: masteryDescription, effect },
  };
}

const PALADIN_SPECS: SpecDef[] = [
  spec(
    'holy',
    'paladin',
    'Holy',
    'healer',
    '+',
    'A devoted healer who turns the Light into steady single-target recovery.',
    'holy_shock',
    'Illumination',
    'Increases all healing done by 12%.',
    { global: { healPct: 0.12 } },
  ),
  spec(
    'protection',
    'paladin',
    'Protection',
    'tank',
    '#',
    'A shield-bearing defender who converts Holy power into threat and mitigation.',
    'holy_shield',
    'Holy Shielding',
    'Increases threat by 25% and armor by 10%.',
    { global: { threatPct: 0.25 }, stats: { armorPct: 0.1 } },
  ),
  spec(
    'retribution',
    'paladin',
    'Retribution',
    'dps',
    'x',
    'A holy warrior who judges enemies with weapon strikes and radiant burst.',
    'repentance',
    'Vengeance',
    'Increases melee and spell ability damage by 6%.',
    { global: { meleeDmgPct: 0.06, spellDmgPct: 0.06 } },
  ),
];

const HUNTER_SPECS: SpecDef[] = [
  spec(
    'beast_mastery',
    'hunter',
    'Beast Mastery',
    'dps',
    '+',
    'A wild commander who fights beside a durable companion.',
    'bestial_wrath',
    'Kindred Spirits',
    'Increases maximum health and attack power by 8%.',
    { stats: { maxHpPct: 0.08, apPct: 0.08 } },
  ),
  spec(
    'marksmanship',
    'hunter',
    'Marksmanship',
    'dps',
    'x',
    'A precise archer built around ranged burst and efficient shots.',
    'trueshot_aura',
    'Trueshot Training',
    'Increases attack power by 12% and critical strike by 2%.',
    { stats: { apPct: 0.12, crit: 0.02 } },
  ),
  spec(
    'survival',
    'hunter',
    'Survival',
    'dps',
    'o',
    'A skirmisher who controls distance and survives close pressure.',
    'wyvern_sting',
    'Lightning Reflexes',
    'Increases Agility by 10% and dodge by 2%.',
    { stats: { agiPct: 0.1, dodge: 0.02 } },
  ),
];

const MAGE_SPECS: SpecDef[] = [
  spec(
    'arcane',
    'mage',
    'Arcane',
    'dps',
    '*',
    'A precision caster using mana efficiency and focused arcane barrages.',
    'arcane_power',
    'Arcane Instability',
    'Increases spell damage by 8% and Intellect by 4.',
    { global: { spellDmgPct: 0.08 }, stats: { int: 4 } },
  ),
  spec(
    'fire',
    'mage',
    'Fire',
    'dps',
    'x',
    'A volatile caster built around fast, high-damage Fire spells.',
    'combustion',
    'Ignite',
    'Increases critical strike chance by 2%. Increases spell damage by 8%.',
    { global: { spellDmgPct: 0.08 }, stats: { crit: 0.02 } },
  ),
  spec(
    'frost',
    'mage',
    'Frost',
    'dps',
    '#',
    'A controlling caster who trades peak burst for survival and slows.',
    'icy_veins',
    'Shatter',
    'Increases armor by 10%. Increases spell damage by 6%.',
    { global: { spellDmgPct: 0.06 }, stats: { armorPct: 0.1 } },
  ),
];

const ROGUE_SPECS: SpecDef[] = [
  spec(
    'assassination',
    'rogue',
    'Assassination',
    'dps',
    'x',
    'A burst specialist using critical strikes and finishers.',
    'cold_blood',
    'Murderous Intent',
    'Increases critical strike chance by 3%. Increases Eviscerate damage by 8%.',
    { stats: { crit: 0.03 }, ability: [{ ability: 'eviscerate', dmgPct: 0.08 }] },
  ),
  spec(
    'combat',
    'rogue',
    'Combat',
    'dps',
    '/',
    'A sustained fighter focused on direct weapon strikes.',
    'blade_flurry',
    'Combat Potency',
    'Increases melee ability damage by 10%.',
    { global: { meleeDmgPct: 0.1 } },
  ),
  spec(
    'subtlety',
    'rogue',
    'Subtlety',
    'dps',
    '>',
    'A stealth attacker built around openers, control, and avoidance.',
    'hemorrhage',
    'Master of Deception',
    'Increases Agility by 4. Increases critical strike chance by 2%.',
    { stats: { agi: 4, crit: 0.02 } },
  ),
];

const PRIEST_SPECS: SpecDef[] = [
  spec(
    'discipline',
    'priest',
    'Discipline',
    'healer',
    '#',
    'A mitigator who shields allies and heals through controlled efficiency.',
    'power_infusion',
    'Focused Will',
    'Increases maximum health by 8%. Increases healing done by 8%.',
    { global: { healPct: 0.08 }, stats: { maxHpPct: 0.08 } },
  ),
  spec(
    'holy',
    'priest',
    'Holy',
    'healer',
    '+',
    'A direct healer with strong throughput and restorative prayers.',
    'holy_nova',
    'Spiritual Healing',
    'Increases all healing done by 14%.',
    { global: { healPct: 0.14 } },
  ),
  spec(
    'shadow',
    'priest',
    'Shadow',
    'dps',
    '*',
    'A damage caster built around Shadow damage over time and mind spells.',
    'shadowform',
    'Shadowform',
    'Increases spell damage by 12% and armor by 8%.',
    { global: { spellDmgPct: 0.12 }, stats: { armorPct: 0.08 } },
  ),
];

const SHAMAN_SPECS: SpecDef[] = [
  spec(
    'elemental',
    'shaman',
    'Elemental',
    'dps',
    '*',
    'A ranged caster who calls lightning, flame, and frost.',
    'elemental_mastery',
    'Elemental Fury',
    'Increases critical strike chance by 2%. Increases spell damage by 10%.',
    { global: { spellDmgPct: 0.1 }, stats: { crit: 0.02 } },
  ),
  spec(
    'enhancement',
    'shaman',
    'Enhancement',
    'dps',
    'x',
    'A weapon fighter who channels the storm through melee swings.',
    'shamanistic_rage',
    'Stormcaller',
    'Increases attack power by 10. Increases melee ability damage by 10%.',
    { global: { meleeDmgPct: 0.1 }, stats: { ap: 10 } },
  ),
  spec(
    'restoration',
    'shaman',
    'Restoration',
    'healer',
    '+',
    'A healer using ancestral waves and efficient nature magic.',
    'natures_swiftness',
    'Purification',
    'Increases healing done by 14%.',
    { global: { healPct: 0.14 } },
  ),
];

const WARLOCK_SPECS: SpecDef[] = [
  spec(
    'affliction',
    'warlock',
    'Affliction',
    'dps',
    '*',
    'A curse-weaver using damage over time and drains.',
    'siphon_life',
    'Potent Afflictions',
    'Increases Shadow spell damage by 4%.',
    { global: { spellDmgPct: 0.04 } },
  ),
  spec(
    'demonology',
    'warlock',
    'Demonology',
    'dps',
    '+',
    'A durable warlock who survives through demonic resilience.',
    'fel_domination',
    'Demonic Knowledge',
    'Increases Stamina by 10%. Increases armor by 10%.',
    { stats: { staPct: 0.1, armorPct: 0.1 } },
  ),
  spec(
    'destruction',
    'warlock',
    'Destruction',
    'dps',
    'x',
    'A burst caster using Shadow Bolt, fire, and Shadowburn.',
    'conflagrate',
    'Ruin',
    'Increases critical strike chance by 2%. Increases spell damage by 3%.',
    { global: { spellDmgPct: 0.03 }, stats: { crit: 0.02 } },
  ),
];

const DRUID_SPECS: SpecDef[] = [
  spec(
    'balance',
    'druid',
    'Balance',
    'dps',
    '*',
    'A caster who uses lunar and nature magic from range.',
    'moonkin_form',
    'Moonfury',
    'Increases Intellect by 4. Increases spell damage by 10%.',
    { global: { spellDmgPct: 0.1 }, stats: { int: 4 } },
  ),
  spec(
    'feral',
    'druid',
    'Feral',
    'tank',
    'x',
    'A shapeshifter who tanks in bear form and fights up close.',
    'feral_charge',
    'Heart of the Wild',
    'Increases armor by 8%. Increases threat generated by 20%. Increases melee ability damage by 6%.',
    { global: { threatPct: 0.2, meleeDmgPct: 0.06 }, stats: { armorPct: 0.08 } },
  ),
  spec(
    'restoration',
    'druid',
    'Restoration',
    'healer',
    '+',
    'A healer using heal-over-time effects and efficient nature magic.',
    'swiftmend',
    'Gift of Nature',
    'Increases healing done by 14%.',
    { global: { healPct: 0.14 } },
  ),
];

export const PALADIN_TALENTS: ClassTalents = {
  class: 'paladin',
  nodes: [],
  specs: PALADIN_SPECS,
};
export const HUNTER_TALENTS: ClassTalents = {
  class: 'hunter',
  nodes: [],
  specs: HUNTER_SPECS,
};
export const MAGE_TALENTS: ClassTalents = {
  class: 'mage',
  nodes: [],
  specs: MAGE_SPECS,
};
export const ROGUE_TALENTS: ClassTalents = {
  class: 'rogue',
  nodes: [],
  specs: ROGUE_SPECS,
};
export const PRIEST_TALENTS: ClassTalents = {
  class: 'priest',
  nodes: [],
  specs: PRIEST_SPECS,
};
export const SHAMAN_TALENTS: ClassTalents = {
  class: 'shaman',
  nodes: [],
  specs: SHAMAN_SPECS,
};
export const WARLOCK_TALENTS: ClassTalents = {
  class: 'warlock',
  nodes: [],
  specs: WARLOCK_SPECS,
};
export const DRUID_TALENTS: ClassTalents = {
  class: 'druid',
  nodes: [],
  specs: DRUID_SPECS,
};
