import type { ClassTalents, SpecDef, TalentNode } from './talents';

const CLASS_NODES: TalentNode[] = [
  {
    id: 'dh_fel_concentration',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    effect: { ability: [{ ability: 'chaos_strike', costPct: -0.1 }] },
    icon: '*',
    name: 'Rift Focus',
    description: 'Reduces the Fury cost of Rift Strike by 10% per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_heightened_senses',
    tree: 'class',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { dodge: 0.01 } },
    icon: '*',
    name: 'Blindfold Instinct',
    description: 'Increases your dodge chance by 1% per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_demonic_tactics',
    tree: 'class',
    kind: 'passive',
    maxRank: 3,
    requires: ['dh_fel_concentration'],
    effect: { stats: { crit: 0.01 } },
    icon: '*',
    name: 'Ashen Stratagem',
    description: 'Increases your critical strike chance by 1% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_demonic_resilience',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { stats: { armorPct: 0.05 } },
    icon: '*',
    name: 'Scarred Ward',
    description: 'Increases your armor by 5% per rank.',
    row: 1,
    col: 1,
  },
  {
    id: 'dh_weapon_mastery',
    tree: 'class',
    kind: 'passive',
    maxRank: 3,
    requires: ['dh_heightened_senses'],
    effect: { stats: { ap: 10 } },
    icon: '*',
    name: 'Twinblade Drill',
    description: 'Increases your attack power by 10 per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_dark_arts',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 5,
    effect: { ability: [{ ability: 'eye_beam', dmgPct: 0.12 }] },
    icon: '*',
    name: 'Ruin Lore',
    description: 'Increases Gaze of Ruin damage by 12% per rank.',
    row: 2,
    col: 0,
  },
  {
    id: 'dh_elusiveness',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 5,
    effect: { ability: [{ ability: 'blur', cooldownPct: -0.15 }] },
    icon: '*',
    name: 'Veil Drift',
    description: 'Reduces the cooldown of Shimmerstep by 15% per rank.',
    row: 2,
    col: 2,
  },
  {
    id: 'dh_metamorphosis',
    tree: 'class',
    kind: 'passive',
    maxRank: 1,
    pointsGate: 8,
    requires: ['dh_dark_arts'],
    effect: { ability: [{ ability: 'metamorphosis', cooldownPct: -0.25 }] },
    icon: '*',
    name: 'Bloom Catalyst',
    description: 'Reduces the cooldown of Demon Ascendance by 25%.',
    row: 3,
    col: 1,
  },
];

const DEVASTATION_NODES: TalentNode[] = [
  {
    id: 'dh_devastation_cruelty',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { crit: 0.01 } },
    icon: '*',
    name: 'Jagged Intent',
    description: 'Increases your critical strike chance by 1% per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_devastation_devastation',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    effect: { ability: [{ ability: 'chaos_strike', dmgPct: 0.12 }] },
    icon: '*',
    name: 'Rift Rupture',
    description: 'Increases Rift Strike damage by 12% per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_devastation_bane',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    requires: ['dh_devastation_cruelty'],
    effect: { ability: [{ ability: 'throw_glaive', dmgPct: 0.18 }] },
    icon: '*',
    name: 'Crescent Bite',
    description: 'Increases Crescent Toss damage by 18% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_devastation_flurry',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { ability: [{ ability: 'blade_dance', cooldownPct: -0.12 }] },
    icon: '*',
    name: 'Razor Tempo',
    description: 'Reduces Razor Cyclone cooldown by 12% per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_devastation_cold_blood',
    tree: 'spec',
    specId: 'devastation',
    kind: 'choice',
    maxRank: 1,
    pointsGate: 5,
    icon: '*',
    name: 'Still Heart',
    description: 'Choose one destructive refinement.',
    row: 2,
    col: 1,
    choices: [
      {
        id: 'dh_cb_crit',
        name: 'Shatterpoint',
        icon: '*',
        description: 'Increases critical strike chance by 5%.',
        effect: { stats: { crit: 0.05 } },
      },
      {
        id: 'dh_cb_ap',
        name: 'Glaivecraft',
        icon: '*',
        description: 'Increases attack power by 20.',
        effect: { stats: { ap: 20 } },
      },
      {
        id: 'dh_cb_chaos',
        name: 'Ruin Spark',
        icon: '*',
        description: 'Increases Rift Strike damage by 20%.',
        effect: { ability: [{ ability: 'chaos_strike', dmgPct: 0.2 }] },
      },
    ],
  },
  {
    id: 'dh_devastation_cataclysm',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 8,
    requires: ['dh_devastation_cold_blood'],
    effect: { global: { meleeDmgPct: 0.08 } },
    icon: '*',
    name: 'Ruin Cascade',
    description: 'Increases melee ability damage by 8% per rank.',
    row: 3,
    col: 1,
  },
];

const VENGEANCE_NODES: TalentNode[] = [
  {
    id: 'dh_vengeance_toughness',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { armorPct: 0.05 } },
    icon: '*',
    name: 'Scarplate',
    description: 'Increases your armor by 5% per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_vengeance_deflection',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { dodge: 0.01 } },
    icon: '*',
    name: 'Glaive Parry',
    description: 'Increases your chance to dodge by 1% per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_vengeance_ardent_defender',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    requires: ['dh_vengeance_toughness'],
    effect: { stats: { maxHpPct: 0.05 } },
    icon: '*',
    name: 'Ironwill Guard',
    description: 'Increases maximum health by 5% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_vengeance_bulwark',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { ability: [{ ability: 'blur', buffPct: 0.15 }] },
    icon: '*',
    name: 'Warding Veil',
    description: 'Increases the strength of Shimmerstep by 15% per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_vengeance_anticipation',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'choice',
    maxRank: 1,
    pointsGate: 5,
    icon: '*',
    name: 'Foresight Guard',
    description: 'Choose one defensive refinement.',
    row: 2,
    col: 1,
    choices: [
      {
        id: 'dh_ant_health',
        name: 'Iron Lungs',
        icon: '*',
        description: 'Increases Stamina by 8.',
        effect: { stats: { sta: 8 } },
      },
      {
        id: 'dh_ant_armor',
        name: 'Hidebound Aspect',
        icon: '*',
        description: 'Increases armor by 15%.',
        effect: { stats: { armorPct: 0.15 } },
      },
      {
        id: 'dh_ant_threat',
        name: 'Spite Engine',
        icon: '*',
        description: 'Increases threat generation by 12%.',
        effect: { global: { threatPct: 0.12 } },
      },
    ],
  },
  {
    id: 'dh_vengeance_vengeance',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 8,
    requires: ['dh_vengeance_anticipation'],
    effect: {
      global: { threatPct: 0.12 },
      ability: [{ ability: 'immolation_aura', dmgPct: 0.12 }],
    },
    icon: '*',
    name: 'Grudge Engine',
    description: 'Increases threat and Burning Brand damage by 12% per rank.',
    row: 3,
    col: 1,
  },
];

const METAMORPHOSIS_NODES: TalentNode[] = [
  {
    id: 'dh_meta_knowledge',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { agi: 2 } },
    icon: '*',
    name: 'Abyssal Lessons',
    description: 'Increases Agility by 2 per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_meta_embrace',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { sta: 2 } },
    icon: '*',
    name: 'Riftbound Vitality',
    description: 'Increases Stamina by 2 per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_meta_resilience',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    requires: ['dh_meta_embrace'],
    effect: { ability: [{ ability: 'metamorphosis', buffPct: 0.12 }] },
    icon: '*',
    name: 'Rift Hardened',
    description: 'Increases Demon Ascendance stat bonuses by 12% per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_meta_tactics',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { ability: [{ ability: 'eye_beam', cooldownPct: -0.12 }] },
    icon: '*',
    name: 'Ruin Geometry',
    description: 'Reduces Gaze of Ruin cooldown by 12% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_meta_fel_stamina',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'choice',
    maxRank: 1,
    pointsGate: 5,
    icon: '*',
    name: 'Sundered Core',
    description: 'Choose one demonic refinement.',
    row: 2,
    col: 1,
    choices: [
      {
        id: 'dh_fs_power',
        name: 'Sundered Mind',
        icon: '*',
        description: 'Increases attack power by 18.',
        effect: { stats: { ap: 18 } },
      },
      {
        id: 'dh_fs_health',
        name: 'Core Vitality',
        icon: '*',
        description: 'Increases maximum health by 10%.',
        effect: { stats: { maxHpPct: 0.1 } },
      },
      {
        id: 'dh_fs_resilience',
        name: 'Wardhide',
        icon: '*',
        description: 'Increases armor by 12%.',
        effect: { stats: { armorPct: 0.12 } },
      },
    ],
  },
  {
    id: 'dh_meta_metamorphosis',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 8,
    requires: ['dh_meta_fel_stamina'],
    effect: { ability: [{ ability: 'metamorphosis', cooldownPct: -0.15, buffPct: 0.1 }] },
    icon: '*',
    name: 'Abyssal Bloom',
    description: 'Reduces Demon Ascendance cooldown by 15% and increases its bonuses by 10% per rank.',
    row: 3,
    col: 1,
  },
];

const SPECS: SpecDef[] = [
  {
    id: 'devastation',
    class: 'demon_hunter',
    name: 'Riftbound',
    role: 'dps',
    icon: '*',
    description: 'A relentless glaive fighter who spends Fury in explosive bursts.',
    signature: 'chaos_strike',
    mastery: {
      name: 'Glaive Geometry',
      description: 'Increases critical strike chance by 3% and melee damage by 8%.',
      effect: { stats: { crit: 0.03 }, global: { meleeDmgPct: 0.08 } },
    },
  },
  {
    id: 'vengeance',
    class: 'demon_hunter',
    name: 'Oathguard',
    role: 'tank',
    icon: '*',
    description: 'A hardened hunter who turns fel fire into threat and survival.',
    signature: 'metamorphosis',
    mastery: {
      name: 'Scarhide Doctrine',
      description: 'Increases armor by 10% and threat generation by 10%.',
      effect: { stats: { armorPct: 0.1 }, global: { threatPct: 0.1 } },
    },
  },
  {
    id: 'metamorphosis',
    class: 'demon_hunter',
    name: 'Abyssal Covenant',
    role: 'dps',
    icon: '*',
    description: 'A chaos channeler who leans into Gaze of Ruin and demon-form windows.',
    signature: 'eye_beam',
    mastery: {
      name: 'Ruin Scholarship',
      description: 'Increases spell damage by 8% and Gaze of Ruin damage by 10%.',
      effect: { global: { spellDmgPct: 0.08 }, ability: [{ ability: 'eye_beam', dmgPct: 0.1 }] },
    },
  },
];

export const DEMON_HUNTER_TALENTS: ClassTalents = {
  class: 'demon_hunter',
  specs: SPECS,
  nodes: [...CLASS_NODES, ...DEVASTATION_NODES, ...VENGEANCE_NODES, ...METAMORPHOSIS_NODES],
};
