import type { ClassTalents, SpecDef, TalentNode } from './talents';

const CLASS_NODES: TalentNode[] = [
  {
    id: 'dh_fel_concentration',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    effect: { ability: [{ ability: 'chaos_strike', costPct: -0.1 }] },
    icon: '*',
    name: 'Fel Concentration',
    description: 'Reduces the Fury cost of Chaos Strike by 10% per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_heightened_senses',
    tree: 'class',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { dodge: 0.01 } },
    icon: '*',
    name: 'Heightened Senses',
    description: 'Increases your dodge chance by 1% per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_demonic_tactics',
    tree: 'class',
    kind: 'passive',
    maxRank: 3,
    requires: ['dh_fel_concentration'],
    effect: { stats: { crit: 0.01 } },
    icon: '*',
    name: 'Demonic Tactics',
    description: 'Increases your critical strike chance by 1% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_demonic_resilience',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { stats: { armorPct: 0.05 } },
    icon: '*',
    name: 'Demonic Resilience',
    description: 'Increases your armor by 5% per rank.',
    row: 1,
    col: 1,
  },
  {
    id: 'dh_weapon_mastery',
    tree: 'class',
    kind: 'passive',
    maxRank: 3,
    requires: ['dh_heightened_senses'],
    effect: { stats: { ap: 10 } },
    icon: '*',
    name: 'Weapon Mastery',
    description: 'Increases your attack power by 10 per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_dark_arts',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 5,
    effect: { ability: [{ ability: 'eye_beam', dmgPct: 0.12 }] },
    icon: '*',
    name: 'Dark Arts',
    description: 'Increases Eye Beam damage by 12% per rank.',
    row: 2,
    col: 0,
  },
  {
    id: 'dh_elusiveness',
    tree: 'class',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 5,
    effect: { ability: [{ ability: 'blur', cooldownPct: -0.15 }] },
    icon: '*',
    name: 'Elusiveness',
    description: 'Reduces the cooldown of Blur by 15% per rank.',
    row: 2,
    col: 2,
  },
  {
    id: 'dh_metamorphosis',
    tree: 'class',
    kind: 'passive',
    maxRank: 1,
    pointsGate: 8,
    requires: ['dh_dark_arts'],
    effect: { ability: [{ ability: 'metamorphosis', cooldownPct: -0.25 }] },
    icon: '*',
    name: 'Metamorphosis',
    description: 'Reduces the cooldown of Metamorphosis by 25%.',
    row: 3,
    col: 1,
  },
];

const DEVASTATION_NODES: TalentNode[] = [
  {
    id: 'dh_devastation_cruelty',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { crit: 0.01 } },
    icon: '*',
    name: 'Cruelty',
    description: 'Increases your critical strike chance by 1% per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_devastation_devastation',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    effect: { ability: [{ ability: 'chaos_strike', dmgPct: 0.12 }] },
    icon: '*',
    name: 'Devastation',
    description: 'Increases Chaos Strike damage by 12% per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_devastation_bane',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    requires: ['dh_devastation_cruelty'],
    effect: { ability: [{ ability: 'throw_glaive', dmgPct: 0.18 }] },
    icon: '*',
    name: 'Bane',
    description: 'Increases Throw Glaive damage by 18% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_devastation_flurry',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { ability: [{ ability: 'blade_dance', cooldownPct: -0.12 }] },
    icon: '*',
    name: 'Flurry',
    description: 'Reduces Blade Dance cooldown by 12% per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_devastation_cold_blood',
    tree: 'spec',
    specId: 'devastation',
    kind: 'choice',
    maxRank: 1,
    pointsGate: 5,
    icon: '*',
    name: 'Cold Blood',
    description: 'Choose one destructive refinement.',
    row: 2,
    col: 1,
    choices: [
      {
        id: 'dh_cb_crit',
        name: 'Critical Mass',
        icon: '*',
        description: 'Increases critical strike chance by 5%.',
        effect: { stats: { crit: 0.05 } },
      },
      {
        id: 'dh_cb_ap',
        name: 'Weapon Expertise',
        icon: '*',
        description: 'Increases attack power by 20.',
        effect: { stats: { ap: 20 } },
      },
      {
        id: 'dh_cb_chaos',
        name: 'Cataclysm',
        icon: '*',
        description: 'Increases Chaos Strike damage by 20%.',
        effect: { ability: [{ ability: 'chaos_strike', dmgPct: 0.2 }] },
      },
    ],
  },
  {
    id: 'dh_devastation_cataclysm',
    tree: 'spec',
    specId: 'devastation',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 8,
    requires: ['dh_devastation_cold_blood'],
    effect: { global: { meleeDmgPct: 0.08 } },
    icon: '*',
    name: 'Cataclysm',
    description: 'Increases melee ability damage by 8% per rank.',
    row: 3,
    col: 1,
  },
];

const VENGEANCE_NODES: TalentNode[] = [
  {
    id: 'dh_vengeance_toughness',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { armorPct: 0.05 } },
    icon: '*',
    name: 'Toughness',
    description: 'Increases your armor by 5% per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_vengeance_deflection',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { dodge: 0.01 } },
    icon: '*',
    name: 'Deflection',
    description: 'Increases your chance to dodge by 1% per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_vengeance_ardent_defender',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    requires: ['dh_vengeance_toughness'],
    effect: { stats: { maxHpPct: 0.05 } },
    icon: '*',
    name: 'Ardent Defender',
    description: 'Increases maximum health by 5% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_vengeance_bulwark',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { ability: [{ ability: 'blur', buffPct: 0.15 }] },
    icon: '*',
    name: 'Bulwark',
    description: 'Increases the strength of Blur by 15% per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_vengeance_anticipation',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'choice',
    maxRank: 1,
    pointsGate: 5,
    icon: '*',
    name: 'Anticipation',
    description: 'Choose one defensive refinement.',
    row: 2,
    col: 1,
    choices: [
      {
        id: 'dh_ant_health',
        name: 'Endurance Training',
        icon: '*',
        description: 'Increases Stamina by 8.',
        effect: { stats: { sta: 8 } },
      },
      {
        id: 'dh_ant_armor',
        name: 'Dire Bear',
        icon: '*',
        description: 'Increases armor by 15%.',
        effect: { stats: { armorPct: 0.15 } },
      },
      {
        id: 'dh_ant_threat',
        name: 'Vengeance',
        icon: '*',
        description: 'Increases threat generation by 12%.',
        effect: { global: { threatPct: 0.12 } },
      },
    ],
  },
  {
    id: 'dh_vengeance_vengeance',
    tree: 'spec',
    specId: 'vengeance',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 8,
    requires: ['dh_vengeance_anticipation'],
    effect: {
      global: { threatPct: 0.12 },
      ability: [{ ability: 'immolation_aura', dmgPct: 0.12 }],
    },
    icon: '*',
    name: 'Vengeance',
    description: 'Increases threat and Immolation Aura damage by 12% per rank.',
    row: 3,
    col: 1,
  },
];

const METAMORPHOSIS_NODES: TalentNode[] = [
  {
    id: 'dh_meta_knowledge',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { agi: 2 } },
    icon: '*',
    name: 'Demonic Knowledge',
    description: 'Increases Agility by 2 per rank.',
    row: 0,
    col: 0,
  },
  {
    id: 'dh_meta_embrace',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 3,
    effect: { stats: { sta: 2 } },
    icon: '*',
    name: 'Demonic Embrace',
    description: 'Increases Stamina by 2 per rank.',
    row: 0,
    col: 2,
  },
  {
    id: 'dh_meta_resilience',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    requires: ['dh_meta_embrace'],
    effect: { ability: [{ ability: 'metamorphosis', buffPct: 0.12 }] },
    icon: '*',
    name: 'Demonic Resilience',
    description: 'Increases Metamorphosis stat bonuses by 12% per rank.',
    row: 1,
    col: 2,
  },
  {
    id: 'dh_meta_tactics',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 2,
    effect: { ability: [{ ability: 'eye_beam', cooldownPct: -0.12 }] },
    icon: '*',
    name: 'Demonic Tactics',
    description: 'Reduces Eye Beam cooldown by 12% per rank.',
    row: 1,
    col: 0,
  },
  {
    id: 'dh_meta_fel_stamina',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'choice',
    maxRank: 1,
    pointsGate: 5,
    icon: '*',
    name: 'Fel Stamina',
    description: 'Choose one demonic refinement.',
    row: 2,
    col: 1,
    choices: [
      {
        id: 'dh_fs_power',
        name: 'Fel Intellect',
        icon: '*',
        description: 'Increases attack power by 18.',
        effect: { stats: { ap: 18 } },
      },
      {
        id: 'dh_fs_health',
        name: 'Fel Stamina',
        icon: '*',
        description: 'Increases maximum health by 10%.',
        effect: { stats: { maxHpPct: 0.1 } },
      },
      {
        id: 'dh_fs_resilience',
        name: 'Demonic Resilience',
        icon: '*',
        description: 'Increases armor by 12%.',
        effect: { stats: { armorPct: 0.12 } },
      },
    ],
  },
  {
    id: 'dh_meta_metamorphosis',
    tree: 'spec',
    specId: 'metamorphosis',
    kind: 'passive',
    maxRank: 2,
    pointsGate: 8,
    requires: ['dh_meta_fel_stamina'],
    effect: { ability: [{ ability: 'metamorphosis', cooldownPct: -0.15, buffPct: 0.1 }] },
    icon: '*',
    name: 'Metamorphosis',
    description: 'Reduces Metamorphosis cooldown by 15% and increases its bonuses by 10% per rank.',
    row: 3,
    col: 1,
  },
];

const SPECS: SpecDef[] = [
  {
    id: 'devastation',
    class: 'demon_hunter',
    name: 'Devastation',
    role: 'dps',
    icon: '*',
    description: 'A relentless glaive fighter who spends Fury in explosive bursts.',
    signature: 'chaos_strike',
    mastery: {
      name: 'Demonic Tactics',
      description: 'Increases critical strike chance by 3% and melee damage by 8%.',
      effect: { stats: { crit: 0.03 }, global: { meleeDmgPct: 0.08 } },
    },
  },
  {
    id: 'vengeance',
    class: 'demon_hunter',
    name: 'Vengeance',
    role: 'tank',
    icon: '*',
    description: 'A hardened hunter who turns fel fire into threat and survival.',
    signature: 'metamorphosis',
    mastery: {
      name: 'Demonic Resilience',
      description: 'Increases armor by 10% and threat generation by 10%.',
      effect: { stats: { armorPct: 0.1 }, global: { threatPct: 0.1 } },
    },
  },
  {
    id: 'metamorphosis',
    class: 'demon_hunter',
    name: 'Metamorphosis',
    role: 'dps',
    icon: '*',
    description: 'A chaos channeler who leans into Eye Beam and demonic windows.',
    signature: 'eye_beam',
    mastery: {
      name: 'Dark Arts',
      description: 'Increases spell damage by 8% and Eye Beam damage by 10%.',
      effect: { global: { spellDmgPct: 0.08 }, ability: [{ ability: 'eye_beam', dmgPct: 0.1 }] },
    },
  },
];

export const DEMON_HUNTER_TALENTS: ClassTalents = {
  class: 'demon_hunter',
  specs: SPECS,
  nodes: [...CLASS_NODES, ...DEVASTATION_NODES, ...VENGEANCE_NODES, ...METAMORPHOSIS_NODES],
};
