// Authored Roach King kit. Stats use the existing rift boss/add baseline and
// take the rank transform at spawn, exactly like every other rift creature.
import type { MobTemplate } from '../../types';
import { RIFT_ESSENCE_ITEM_ID } from './items';

export const ROACH_KING_ID = 'rift_boss_asmon';
export const ROACH_CROWN_AURA = 'rift_roach_crown';
export const ROACHLING_ID = 'rift_roachling';
export const GARBAGE_BEETLE_ID = 'rift_garbage_beetle';

export const ROACH_KING_MOBS: Record<string, MobTemplate> = {
  [ROACH_KING_ID]: {
    id: ROACH_KING_ID,
    name: 'Asmon, the Roach King',
    minLevel: 18,
    maxLevel: 23,
    family: 'humanoid',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 780,
    hpPerLevel: 66,
    dmgBase: 18,
    dmgPerLevel: 3.5,
    attackSpeed: 2.7,
    armorPerLevel: 32,
    moveSpeed: 7,
    aggroRadius: 18,
    scale: 2.8,
    color: 0xffffff,
    loot: [
      { copper: 5000, chance: 1 },
      { itemId: 'hoarfrost_edge', chance: 0.035 },
      { itemId: 'emberforge_gauntlets', chance: 0.035 },
      { itemId: 'broodmother_carapace', chance: 0.035 },
      { itemId: 'bonelord_mantle', chance: 0.035 },
      { itemId: 'graskbreaker_girdle', chance: 0.035 },
      { itemId: 'voidscar_handwraps', chance: 0.035 },
      { itemId: 'stormscale_treads', chance: 0.035 },
      { itemId: 'abyssal_loop', chance: 0.035 },
      { itemId: 'pitlords_cleaver', chance: 0.035 },
      { itemId: 'pactbound_vestments', chance: 0.035 },

      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 0.5 },
    ],
    // These records also feed cast labels and the rank-kit metadata. The
    // encounter module owns their sequencing, movement lock, and phase gates.
    bigCast: {
      castId: 'rift_asmon_desk_slam',
      name: 'Desk Slam',
      castTime: 2.2,
      every: 8,
      radius: 8,
      min: 24,
      max: 36,
      school: 'physical',
    },
    summonAdds: { mobId: ROACHLING_ID, count: 2, atHpPct: [0.75, 0.35] },
    deathZoneCast: {
      castId: 'rift_asmon_filth',
      name: 'Mountain of Filth',
      castTime: 5,
      every: 20,
      radius: 7,
      school: 'nature',
      detonateText: 'The mountain of filth erupts!',
    },
    deathZoneStrike: {
      castId: 'rift_asmon_swarm',
      name: 'Royal Swarm',
      castTime: 5,
      every: 24,
      radius: 8,
      school: 'nature',
      detonateText: 'The royal swarm erupts!',
    },
    rankMechanics: ['bigCast', 'summonAdds', 'deathZoneCast', 'deathZoneStrike'],
  },
  [ROACHLING_ID]: {
    id: ROACHLING_ID,
    name: 'Royal Roachling',
    minLevel: 18,
    maxLevel: 23,
    family: 'spider',
    hpBase: 30,
    hpPerLevel: 11,
    dmgBase: 7,
    dmgPerLevel: 2,
    attackSpeed: 1.8,
    armorPerLevel: 10,
    moveSpeed: 7.5,
    aggroRadius: 12,
    loot: [],
    xpMult: 0,
    scale: 0.75,
    color: 0xffffff,
  },
  [GARBAGE_BEETLE_ID]: {
    id: GARBAGE_BEETLE_ID,
    name: 'Tribute Beetle',
    minLevel: 18,
    maxLevel: 23,
    family: 'spider',
    hpBase: 34,
    hpPerLevel: 12,
    dmgBase: 7,
    dmgPerLevel: 2,
    attackSpeed: 2.4,
    armorPerLevel: 12,
    moveSpeed: 6,
    aggroRadius: 12,
    loot: [],
    xpMult: 0,
    scale: 1.1,
    color: 0xffffff,
  },
};
