// The Demon Tower bestiary: eight wave demons plus the two bosses.
//
// These MUST be static entries in the merged MOBS table, because per-tick mob
// mechanics are read from MOBS[entity.templateId] (src/sim/mob/locomotion.ts).
// The tower's escalation comes from rift/tower_scaling.ts multiplying these
// baselines per floor, NEVER from spawning ad-hoc templates.
//
// The roster is ordered weakest to strongest (DEMON_TOWER_ROSTER in
// rift/tower_waves.ts slides a two-wide window up it as the raid climbs), so the
// stat lines below ascend in lockstep with that order and each tier adds one
// readable threat on top of the previous:
//
//   cinder whelp   fast, fragile, arrives in numbers
//   hellhound      pack rusher, bleeds on hit
//   pact reaver    cleaver, punishes stacking
//   brimstone zeal. brands its target so the rest of the wave hits harder
//   soulbinder     healer, must be focused or the wave never dies
//   iron defiler   armored wall, slows the clear
//   abyss knight   knockback + heavy hits, breaks formations
//   dread harbing. rot and fear, the summit's baseline threat
//
// Level band note (same rule as ../rift/mobs.ts): rift spawn levels come from
// rift/ranks.ts riftFloorLevel, so the bands here are metadata for
// item_level.buildSourceIndex and the deeds creditable-level analysis, not a
// spawn range. They match the rest of the rift content so the tower stays inside
// one itemisation envelope.
//
// Data-as-code: declarative tables only, no logic.

import type { LootEntry, MobTemplate } from '../../types';
import { RIFT_ESSENCE_ITEM_ID } from './items';

const MIN_LEVEL = 18;
const MAX_LEVEL = 23;

/** Wave-demon loot. The tower pays in Rift Essence rather than a per-demon rare:
 * a floor sends up to 14 at a time, so a rare roll per body would flood the
 * economy. The chase items ride the two bosses instead. */
const demonLoot = (copper: number): LootEntry[] => [
  { copper, chance: 1 },
  { itemId: RIFT_ESSENCE_ITEM_ID, chance: 0.04 },
];

const WAVE_DEMONS: Record<string, MobTemplate> = {
  tower_imp: {
    id: 'tower_imp',
    name: 'Cinder Whelp',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    hpBase: 30,
    hpPerLevel: 11,
    dmgBase: 7,
    dmgPerLevel: 1.8,
    attackSpeed: 1.6,
    armorPerLevel: 8,
    moveSpeed: 8,
    aggroRadius: 15,
    loot: demonLoot(70),
    scale: 1.32,
    color: 0xd94f2a,
  },
  tower_hellhound: {
    id: 'tower_hellhound',
    name: 'Hellhound',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    hpBase: 42,
    hpPerLevel: 15,
    dmgBase: 9,
    dmgPerLevel: 2.2,
    attackSpeed: 1.9,
    armorPerLevel: 12,
    moveSpeed: 8.6,
    aggroRadius: 16,
    loot: demonLoot(90),
    scale: 1.73,
    color: 0x8f2417,
    bleed: { chance: 0.3, perTick: 6, interval: 2, duration: 8, name: 'Rending Fangs' },
  },
  tower_pact_reaver: {
    id: 'tower_pact_reaver',
    name: 'Pact Reaver',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 58,
    hpPerLevel: 21,
    dmgBase: 11,
    dmgPerLevel: 2.6,
    attackSpeed: 2.3,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 14,
    loot: demonLoot(120),
    scale: 1.98,
    color: 0xb03a1e,
    // Punishes a stacked raid: spread or eat the sweep.
    cleave: { radius: 7, mult: 0.55, name: 'Reaving Sweep' },
  },
  tower_brimstone_zealot: {
    id: 'tower_brimstone_zealot',
    name: 'Brimstone Zealot',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 52,
    hpPerLevel: 19,
    dmgBase: 12,
    dmgPerLevel: 2.9,
    attackSpeed: 2.6,
    armorPerLevel: 14,
    moveSpeed: 6.6,
    aggroRadius: 22,
    loot: demonLoot(130),
    scale: 1.81,
    color: 0xe0742a,
    // Marks its target so the rest of the wave hits harder: the first demon that
    // makes the raid care which one it is standing next to.
    expose: { chance: 0.25, dmgIncrease: 0.15, duration: 8, name: 'Brand of Ruin' },
    smolder: { chance: 0.22, perTick: 8, interval: 2, duration: 8, name: 'Cinderburn' },
  },
  tower_soulbinder: {
    id: 'tower_soulbinder',
    name: 'Soulbinder',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 60,
    hpPerLevel: 22,
    dmgBase: 10,
    dmgPerLevel: 2.4,
    attackSpeed: 2.4,
    armorPerLevel: 16,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: demonLoot(150),
    scale: 1.9,
    color: 0x7d2ad9,
    // The wave will not die until this one does: the first real target-priority
    // demand the tower makes of a raid.
    mendAlly: { healMin: 55, healMax: 85, radius: 18, every: 6, name: 'Bind Soul' },
  },
  tower_iron_defiler: {
    id: 'tower_iron_defiler',
    name: 'Iron Defiler',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 96,
    hpPerLevel: 34,
    dmgBase: 13,
    dmgPerLevel: 3,
    attackSpeed: 3,
    armorPerLevel: 40,
    moveSpeed: 6.2,
    aggroRadius: 15,
    loot: demonLoot(180),
    scale: 2.39,
    color: 0x6b6f78,
    // A wall: heavily armored, and it hardens further mid-wave.
    stoneskin: { amount: 420, every: 14, duration: 6, name: 'Iron Rite' },
  },
  tower_abyss_knight: {
    id: 'tower_abyss_knight',
    name: 'Abyss Knight',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 110,
    hpPerLevel: 38,
    dmgBase: 16,
    dmgPerLevel: 3.6,
    attackSpeed: 2.8,
    armorPerLevel: 30,
    moveSpeed: 7.2,
    aggroRadius: 17,
    loot: demonLoot(220),
    scale: 2.56,
    color: 0x3b2a6b,
    cleave: { radius: 8, mult: 0.6, name: 'Abyssal Arc' },
    // Breaks a formation apart right when the arena is at its tightest.
    knockback: { chance: 0.22, distance: 6, name: 'Void Shove' },
  },
  tower_dread_harbinger: {
    id: 'tower_dread_harbinger',
    name: 'Dread Harbinger',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 124,
    hpPerLevel: 42,
    dmgBase: 18,
    dmgPerLevel: 4.1,
    attackSpeed: 2.7,
    armorPerLevel: 26,
    moveSpeed: 7,
    aggroRadius: 20,
    loot: demonLoot(260),
    scale: 2.64,
    color: 0x9b1f4d,
    soulrot: { chance: 0.3, perTick: 11, interval: 2, duration: 10, name: 'Withering Dread' },
    terrify: { every: 18, radius: 10, duration: 2, name: 'Toll of Dread' },
  },
  // ---- Second wave of the bestiary: the roster is 16 wide so the sliding
  // window (rift/tower_waves.ts) changes what you fight roughly every floor
  // instead of every other one.
  tower_gloom_bat: {
    id: 'tower_gloom_bat',
    name: 'Gloom Bat',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    hpBase: 24,
    hpPerLevel: 9,
    dmgBase: 6,
    dmgPerLevel: 1.5,
    attackSpeed: 1.4,
    armorPerLevel: 6,
    moveSpeed: 8.8,
    aggroRadius: 16,
    loot: demonLoot(60),
    scale: 1.24,
    color: 0x7b5bd6,
  },
  tower_cinder_crawler: {
    id: 'tower_cinder_crawler',
    name: 'Cinder Crawler',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    hpBase: 36,
    hpPerLevel: 13,
    dmgBase: 8,
    dmgPerLevel: 2,
    attackSpeed: 1.8,
    armorPerLevel: 14,
    moveSpeed: 8,
    aggroRadius: 14,
    loot: demonLoot(80),
    scale: 1.57,
    color: 0xd2691e,
    smolder: { chance: 0.28, perTick: 6, interval: 2, duration: 8, name: 'Ember Bite' },
  },
  tower_bone_acolyte: {
    id: 'tower_bone_acolyte',
    name: 'Bone Acolyte',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 50,
    hpPerLevel: 18,
    dmgBase: 10,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 14,
    moveSpeed: 7,
    aggroRadius: 16,
    loot: demonLoot(110),
    scale: 1.73,
    color: 0xcfc6a8,
    // Drains the tank's healing window: the first "watch the debuff" demon.
    healAbsorb: { chance: 0.22, amount: 120, duration: 8, name: 'Censer Rot' },
  },
  tower_shade_dancer: {
    id: 'tower_shade_dancer',
    name: 'Shade Dancer',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 54,
    hpPerLevel: 20,
    dmgBase: 13,
    dmgPerLevel: 3.1,
    attackSpeed: 1.7,
    armorPerLevel: 12,
    moveSpeed: 8.4,
    aggroRadius: 18,
    loot: demonLoot(140),
    scale: 1.81,
    color: 0x2f2a45,
    // Fast and bleeds: punishes ignoring the loose adds at the back.
    bleed: { chance: 0.35, perTick: 9, interval: 2, duration: 8, name: 'Twin Fangs' },
  },
  tower_flame_herald: {
    id: 'tower_flame_herald',
    name: 'Flame Herald',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 66,
    hpPerLevel: 24,
    dmgBase: 12,
    dmgPerLevel: 2.9,
    attackSpeed: 2.5,
    armorPerLevel: 18,
    moveSpeed: 7,
    aggroRadius: 18,
    loot: demonLoot(160),
    scale: 1.98,
    color: 0xff7a1a,
    // Buffs the pack around it, so it is a second priority target after the
    // Soulbinder: kill order starts to matter from here up.
    rally: { radius: 16, every: 16, ap: 40, duration: 8, name: 'Herald the Burning' },
  },
  tower_rot_hulk: {
    id: 'tower_rot_hulk',
    name: 'Rot Hulk',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 104,
    hpPerLevel: 36,
    dmgBase: 15,
    dmgPerLevel: 3.4,
    attackSpeed: 3.1,
    armorPerLevel: 24,
    moveSpeed: 6.4,
    aggroRadius: 15,
    loot: demonLoot(200),
    scale: 2.47,
    color: 0x6f8f4a,
    cleave: { radius: 7.5, mult: 0.55, name: 'Putrid Sweep' },
    // Bursts on death: the raid cannot simply melt it while stacked on it.
    deathThroes: { delay: 2, radius: 7, min: 18, max: 28, name: 'Burst Open', school: 'nature' },
  },
  tower_blood_matron: {
    id: 'tower_blood_matron',
    name: 'Blood Matron',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 96,
    hpPerLevel: 34,
    dmgBase: 17,
    dmgPerLevel: 3.9,
    attackSpeed: 2.4,
    armorPerLevel: 22,
    moveSpeed: 7.2,
    aggroRadius: 19,
    loot: demonLoot(230),
    scale: 2.31,
    color: 0x8e1230,
    // Heals itself off the raid: a damage race the healers feel.
    lifeleech: { healFrac: 0.35, chance: 0.4, name: 'Crimson Draught' },
    mortalStrike: { chance: 0.25, healReduction: 0.5, duration: 6, name: "Matron's Mark" },
  },
  tower_void_sentinel: {
    id: 'tower_void_sentinel',
    name: 'Void Sentinel',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    hpBase: 132,
    hpPerLevel: 44,
    dmgBase: 19,
    dmgPerLevel: 4.2,
    attackSpeed: 2.9,
    armorPerLevel: 42,
    moveSpeed: 6.8,
    aggroRadius: 18,
    loot: demonLoot(250),
    scale: 2.8,
    color: 0x4a3a7a,
    stoneskin: { amount: 520, every: 15, duration: 7, name: 'Sealed Form' },
    knockback: { chance: 0.24, distance: 7, name: 'Null Pulse' },
  },
};

const TOWER_BOSSES: Record<string, MobTemplate> = {
  // Floor 3. The tower's first real check: a support-heavy fight that punishes
  // a raid with no kill order.
  tower_boss_flesh_shaper: {
    id: 'tower_boss_flesh_shaper',
    name: 'Ghol the Flesh-Shaper',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 560,
    hpPerLevel: 48,
    dmgBase: 14,
    dmgPerLevel: 2.9,
    attackSpeed: 2.5,
    armorPerLevel: 24,
    moveSpeed: 6.8,
    aggroRadius: 19,
    loot: [
      { copper: 3000, chance: 1 },
      { itemId: 'pactbound_vestments', chance: 0.18 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
    ],
    scale: 3.96,
    color: 0x9a8f7a,
    summonAdds: { mobId: 'tower_gloom_bat', count: 4, atHpPct: [0.7, 0.4] },
    mendAlly: { healMin: 90, healMax: 140, radius: 20, every: 7, name: 'Graft Flesh' },
    aoeSlow: { radius: 11, mult: 0.6, duration: 5, every: 14, name: 'Sinew Snare' },
    rankMechanics: ['summonAdds', 'mendAlly', 'aoeSlow'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.4, hasteMult: 1.2 },
    yells: { engage: 'Hold still. This will be an improvement.', enrage: 'MORE CLAY!' },
  },
  // Floor 7. Pure pressure: a burning arena and a boss that never stops moving.
  tower_boss_ash_tyrant: {
    id: 'tower_boss_ash_tyrant',
    name: 'Cinderax, the Ash Tyrant',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 840,
    hpPerLevel: 70,
    dmgBase: 19,
    dmgPerLevel: 3.7,
    attackSpeed: 2.6,
    armorPerLevel: 32,
    moveSpeed: 7.2,
    aggroRadius: 21,
    loot: [
      { copper: 6000, chance: 1 },
      { itemId: 'pitlords_cleaver', chance: 0.3 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 0.8 },
    ],
    scale: 4.95,
    color: 0xff5a1e,
    bigCast: {
      castId: 'tower_ashfall',
      name: 'Ashfall',
      castTime: 2.8,
      every: 15,
      radius: 12,
      min: 30,
      max: 44,
      school: 'fire',
      yell: 'BURN WITH THE TOWER.',
    },
    aoePulse: {
      min: 18,
      max: 28,
      radius: 12,
      every: 9,
      name: 'Cinder Wake',
      school: 'fire',
      fx: 'nova',
    },
    stomp: { radius: 11, every: 13, duration: 1.5, min: 24, max: 34, name: 'Ember Quake' },
    charge: { minRange: 9, maxRange: 26, cooldown: 11, stunDuration: 1.2, name: 'Molten Rush' },
    rankMechanics: ['bigCast', 'aoePulse', 'stomp', 'charge'],
    enrage: { belowHpPct: 0.28, dmgMult: 1.5, hasteMult: 1.3 },
    yells: { engage: 'The ash remembers every climber.', enrage: 'ASH TAKES ALL!' },
  },
  // Floor 5. The gate: a raid that cannot handle him has no business climbing
  // higher, so he is the tower's honest difficulty check rather than its climax.
  tower_boss_gatekeeper: {
    id: 'tower_boss_gatekeeper',
    name: "Vaskar, the Gate's Warden",
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 720,
    hpPerLevel: 62,
    dmgBase: 17,
    dmgPerLevel: 3.4,
    attackSpeed: 2.6,
    armorPerLevel: 30,
    moveSpeed: 7,
    aggroRadius: 20,
    loot: [
      { copper: 4200, chance: 1 },
      { itemId: 'pactbound_vestments', chance: 0.25 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 0.6 },
    ],
    scale: 4.46,
    color: 0xc2431a,
    stomp: { radius: 11, every: 12, duration: 1.4, min: 20, max: 30, name: 'Warden the Gate' },
    aoePulse: {
      min: 15,
      max: 24,
      radius: 12,
      every: 10,
      name: 'Chainfire',
      school: 'fire',
      fx: 'nova',
    },
    summonAdds: { mobId: 'tower_imp', count: 4, atHpPct: [0.65, 0.35] },
    knockback: { chance: 0.2, distance: 7, name: 'Gate Slam' },
    rankMechanics: ['stomp', 'aoePulse', 'summonAdds', 'knockback'],
    enrage: { belowHpPct: 0.3, dmgMult: 1.45, hasteMult: 1.25 },
    yells: {
      engage: 'The tower does not open for the likes of you.',
      enrage: 'THEN CLIMB OVER MY CORPSE!',
    },
  },
  // Floor 10. The summit, and the hardest single encounter in the game: a
  // telegraphed lethal zone on top of the full pressure kit, at 10.6x health.
  tower_boss_demon_lord: {
    id: 'tower_boss_demon_lord',
    name: 'Malgrath, the Tower Unbound',
    minLevel: MIN_LEVEL,
    maxLevel: MAX_LEVEL,
    family: 'demon',
    elite: true,
    boss: true,
    ccImmune: true,
    slowImmune: true,
    hpBase: 980,
    hpPerLevel: 84,
    dmgBase: 21,
    dmgPerLevel: 4,
    attackSpeed: 2.8,
    armorPerLevel: 36,
    moveSpeed: 7,
    aggroRadius: 22,
    loot: [
      { copper: 9000, chance: 1 },
      { itemId: 'pitlords_cleaver', chance: 0.45 },
      { itemId: 'pactbound_vestments', chance: 0.25 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
      { itemId: RIFT_ESSENCE_ITEM_ID, chance: 1 },
    ],
    scale: 5.44,
    color: 0xff2d6a,
    bigCast: {
      castId: 'tower_unmaking',
      name: 'The Unmaking',
      castTime: 3.2,
      every: 16,
      radius: 13,
      min: 34,
      max: 50,
      school: 'shadow',
      yell: 'THE TOWER ENDS WITH YOU.',
    },
    // The lethal telegraph: dodgeable by construction, unforgiving if ignored.
    deathZoneCast: {
      castId: 'tower_rift_collapse',
      name: 'Rift Collapse',
      castTime: 2.4,
      every: 14,
      radius: 9,
      school: 'shadow',
      yell: 'The floor beneath you forgets it was ever there.',
      detonateText: 'Rift Collapse detonates!',
    },
    stomp: { radius: 12, every: 12, duration: 1.6, min: 26, max: 38, name: 'Sunder the Spire' },
    summonAdds: { mobId: 'tower_imp', count: 5, atHpPct: [0.75, 0.5, 0.25] },
    aoePulse: {
      min: 20,
      max: 32,
      radius: 13,
      every: 9,
      name: 'Unbound Nova',
      school: 'shadow',
      fx: 'nova',
    },
    rankMechanics: ['bigCast', 'deathZoneCast', 'stomp', 'summonAdds'],
    enrage: { belowHpPct: 0.25, dmgMult: 1.6, hasteMult: 1.35 },
    yells: {
      engage: 'Ten floors of the faithful died where you stand.',
      enrage: 'I AM THE TOWER!',
    },
  },
};

export const TOWER_MOBS: Record<string, MobTemplate> = {
  ...WAVE_DEMONS,
  ...TOWER_BOSSES,
};

/** Every Demon Tower wave-demon template id, in roster order. */
export const TOWER_WAVE_MOB_IDS = Object.keys(WAVE_DEMONS);
/** The two Demon Tower boss template ids. */
export const TOWER_BOSS_IDS = Object.keys(TOWER_BOSSES);
