// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with `npm run wiki:content`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys, and rich spec/mastery prose resolves
// live through src/ui/talent_i18n.ts. No balance numbers or instanced spoilers here.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideAbilityRef { id: string; name: string; }
export interface GuideClassSpec { id: string; name: string; role: GuideRole; signature: string; }

// Interactive 3D model data, mirrored from the renderer's VisualDef manifest. The Guide's
// standalone viewer builds the model from one GLB on demand; entities reference a model by
// visual key into GUIDE_MODELS and carry their own tint color.
export interface GuideModelAttach { url: string; bone: string; position?: [number, number, number]; rotationY?: number; gripRef?: string; }
export interface GuideModelWeaponFix { node: string; rotX?: number; rotY?: number; rotZ?: number; }
export interface GuideModelSpec {
  url: string;
  idle: string | null;
  height: number;
  yaw?: number;
  hover?: number;
  show?: string[];
  attach?: GuideModelAttach[];
  weaponFix?: GuideModelWeaponFix[];
  tintStrength?: number;
}

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideAbilityRef[];
  abilities: GuideAbilityRef[];
  model: string;
  tint?: string;
  /** Pre-rendered transparent still (public/guide-stills/), the default poster. */
  still?: string;
}

export interface GuideZoneInfo {
  id: string;
  name: string;
  min: number;
  max: number;
  biome: string;
  hub: string;
  pois: string[];
  welcome: string;
}

export interface GuideDungeon {
  id: string;
  isRaid: boolean;
  suggestedPlayers: number;
  min: number | null;
  max: number | null;
  name?: string;
}

export interface GuideWarlockPet { id: string; name: string; model: string; tint?: string; still?: string; }

export interface GuideCreature { name: string; min: number; max: number; rare: boolean; templateId: string; model: string; tint?: string; still?: string; }
export interface GuideFamily { family: string; creatures: GuideCreature[]; }

export interface GuideDelveKeeper { name: string; title: string; }
export interface GuideDelveCompanion { name: string; role: string; }
export interface GuideDelve {
  id: string;
  name: string;
  theme: string;
  minLevel: number;
  suggestedPlayers: number;
  keeper?: GuideDelveKeeper;
  companion?: GuideDelveCompanion;
  tiers: string[];
  affixes: string[];
}

export const GUIDE_CLASSES: GuideClassInfo[] = [
  {
    "id": "warrior",
    "color": "#c79c6e",
    "resource": "rage",
    "roles": [
      "tank",
      "dps"
    ],
    "specs": [
      {
        "id": "arms",
        "name": "Arms",
        "role": "dps",
        "signature": "mortal_strike"
      },
      {
        "id": "fury",
        "name": "Fury",
        "role": "dps",
        "signature": "bloodthirst"
      },
      {
        "id": "prot",
        "name": "Protection",
        "role": "tank",
        "signature": "shield_slam"
      }
    ],
    "signatureAbilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      }
    ],
    "abilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      },
      {
        "id": "hamstring",
        "name": "Hamstring"
      },
      {
        "id": "bloodrage",
        "name": "Bloodrage"
      },
      {
        "id": "overpower",
        "name": "Overpower"
      },
      {
        "id": "execute",
        "name": "Execute"
      },
      {
        "id": "slam",
        "name": "Slam"
      },
      {
        "id": "cleave",
        "name": "Cleave"
      },
      {
        "id": "defensive_stance",
        "name": "Defensive Stance"
      },
      {
        "id": "demoralizing_shout",
        "name": "Demoralizing Shout"
      },
      {
        "id": "sunder_armor",
        "name": "Sunder Armor"
      },
      {
        "id": "taunt",
        "name": "Taunt"
      }
    ],
    "model": "player_warrior",
    "still": "/guide-stills/player_warrior.webp"
  },
  {
    "id": "paladin",
    "color": "#f58cba",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "holy",
        "name": "Holy",
        "role": "healer",
        "signature": "flash_of_light"
      },
      {
        "id": "protection",
        "name": "Protection",
        "role": "tank",
        "signature": "righteous_fury"
      },
      {
        "id": "retribution",
        "name": "Retribution",
        "role": "dps",
        "signature": "judgement"
      }
    ],
    "signatureAbilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      }
    ],
    "abilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      },
      {
        "id": "hammer_of_justice",
        "name": "Hammer of Justice"
      },
      {
        "id": "lay_on_hands",
        "name": "Lay on Hands"
      },
      {
        "id": "flash_of_light",
        "name": "Flash of Light"
      },
      {
        "id": "exorcism",
        "name": "Exorcism"
      },
      {
        "id": "consecration",
        "name": "Consecration"
      },
      {
        "id": "righteous_fury",
        "name": "Righteous Fury"
      },
      {
        "id": "retribution_aura",
        "name": "Retribution Aura"
      }
    ],
    "model": "player_paladin",
    "still": "/guide-stills/player_paladin.webp"
  },
  {
    "id": "hunter",
    "color": "#abd473",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "beast_mastery",
        "name": "Beast Mastery",
        "role": "dps",
        "signature": "tame_beast"
      },
      {
        "id": "marksmanship",
        "name": "Marksmanship",
        "role": "dps",
        "signature": "aimed_shot"
      },
      {
        "id": "survival",
        "name": "Survival",
        "role": "dps",
        "signature": "wing_clip"
      }
    ],
    "signatureAbilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      }
    ],
    "abilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      },
      {
        "id": "wing_clip",
        "name": "Wing Clip"
      },
      {
        "id": "tame_beast",
        "name": "Tame Beast"
      },
      {
        "id": "dismiss_pet",
        "name": "Dismiss Pet"
      },
      {
        "id": "revive_pet",
        "name": "Revive Pet"
      },
      {
        "id": "aspect_of_the_monkey",
        "name": "Aspect of the Monkey"
      },
      {
        "id": "aspect_of_the_cheetah",
        "name": "Aspect of the Cheetah"
      },
      {
        "id": "aimed_shot",
        "name": "Aimed Shot"
      },
      {
        "id": "rapid_fire",
        "name": "Rapid Fire"
      },
      {
        "id": "volley",
        "name": "Volley"
      }
    ],
    "model": "player_hunter",
    "still": "/guide-stills/player_hunter.webp"
  },
  {
    "id": "rogue",
    "color": "#fff569",
    "resource": "energy",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "assassination",
        "name": "Assassination",
        "role": "dps",
        "signature": "eviscerate"
      },
      {
        "id": "combat",
        "name": "Combat",
        "role": "dps",
        "signature": "adrenaline_rush"
      },
      {
        "id": "subtlety",
        "name": "Subtlety",
        "role": "dps",
        "signature": "ambush"
      }
    ],
    "signatureAbilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      }
    ],
    "abilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      },
      {
        "id": "evasion",
        "name": "Evasion"
      },
      {
        "id": "sap",
        "name": "Sap"
      },
      {
        "id": "slice_and_dice",
        "name": "Slice and Dice"
      },
      {
        "id": "sprint",
        "name": "Sprint"
      },
      {
        "id": "crippling_poison",
        "name": "Crippling Poison"
      },
      {
        "id": "kidney_shot",
        "name": "Kidney Shot"
      },
      {
        "id": "expose_armor",
        "name": "Expose Armor"
      },
      {
        "id": "ambush",
        "name": "Ambush"
      },
      {
        "id": "rupture",
        "name": "Rupture"
      },
      {
        "id": "vanish",
        "name": "Vanish"
      },
      {
        "id": "instant_poison",
        "name": "Instant Poison"
      },
      {
        "id": "adrenaline_rush",
        "name": "Adrenaline Rush"
      },
      {
        "id": "deadly_poison",
        "name": "Deadly Poison"
      },
      {
        "id": "blind",
        "name": "Blind"
      },
      {
        "id": "stealth",
        "name": "Stealth"
      }
    ],
    "model": "player_rogue",
    "still": "/guide-stills/player_rogue.webp"
  },
  {
    "id": "priest",
    "color": "#fffff0",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "discipline",
        "name": "Discipline",
        "role": "healer",
        "signature": "power_word_shield"
      },
      {
        "id": "holy",
        "name": "Holy",
        "role": "healer",
        "signature": "flash_heal"
      },
      {
        "id": "shadow",
        "name": "Shadow",
        "role": "dps",
        "signature": "mind_flay"
      }
    ],
    "signatureAbilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      }
    ],
    "abilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      },
      {
        "id": "mind_blast",
        "name": "Mind Blast"
      },
      {
        "id": "heal",
        "name": "Heal"
      },
      {
        "id": "mind_flay",
        "name": "Mind Flay"
      },
      {
        "id": "flash_heal",
        "name": "Flash Heal"
      }
    ],
    "model": "player_priest",
    "tint": "#f0e9d6",
    "still": "/guide-stills/player_priest__f0e9d6.webp"
  },
  {
    "id": "shaman",
    "color": "#0070de",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "elemental",
        "name": "Elemental",
        "role": "dps",
        "signature": "lightning_bolt"
      },
      {
        "id": "enhancement",
        "name": "Enhancement",
        "role": "dps",
        "signature": "stormstrike"
      },
      {
        "id": "restoration",
        "name": "Restoration",
        "role": "healer",
        "signature": "healing_wave"
      }
    ],
    "signatureAbilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      }
    ],
    "abilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      },
      {
        "id": "flametongue_weapon",
        "name": "Flametongue Weapon"
      },
      {
        "id": "frost_shock",
        "name": "Frost Shock"
      },
      {
        "id": "frostbrand_weapon",
        "name": "Frostbrand Weapon"
      },
      {
        "id": "ghost_wolf",
        "name": "Ghost Wolf"
      },
      {
        "id": "stormstrike",
        "name": "Stormstrike"
      },
      {
        "id": "earthquake",
        "name": "Earthquake"
      }
    ],
    "model": "player_shaman",
    "tint": "#6f8fc9",
    "still": "/guide-stills/player_shaman__6f8fc9.webp"
  },
  {
    "id": "mage",
    "color": "#69ccf0",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "arcane",
        "name": "Arcane",
        "role": "dps",
        "signature": "arcane_missiles"
      },
      {
        "id": "fire",
        "name": "Fire",
        "role": "dps",
        "signature": "scorch"
      },
      {
        "id": "frost",
        "name": "Frost",
        "role": "dps",
        "signature": "ice_barrier"
      }
    ],
    "signatureAbilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      }
    ],
    "abilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      },
      {
        "id": "fire_blast",
        "name": "Fire Blast"
      },
      {
        "id": "arcane_missiles",
        "name": "Arcane Missiles"
      },
      {
        "id": "polymorph",
        "name": "Polymorph"
      },
      {
        "id": "frost_nova",
        "name": "Frost Nova"
      },
      {
        "id": "arcane_explosion",
        "name": "Arcane Explosion"
      },
      {
        "id": "scorch",
        "name": "Scorch"
      },
      {
        "id": "ice_barrier",
        "name": "Ice Barrier"
      },
      {
        "id": "pyroblast",
        "name": "Pyroblast"
      },
      {
        "id": "flamestrike",
        "name": "Flamestrike"
      }
    ],
    "model": "player_mage",
    "still": "/guide-stills/player_mage.webp"
  },
  {
    "id": "warlock",
    "color": "#9482c9",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "id": "affliction",
        "name": "Affliction",
        "role": "dps",
        "signature": "drain_life"
      },
      {
        "id": "demonology",
        "name": "Demonology",
        "role": "dps",
        "signature": "demon_skin"
      },
      {
        "id": "destruction",
        "name": "Destruction",
        "role": "dps",
        "signature": "shadowburn"
      }
    ],
    "signatureAbilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      }
    ],
    "abilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      },
      {
        "id": "summon_voidwalker",
        "name": "Summon Voidwalker"
      },
      {
        "id": "curse_of_agony",
        "name": "Curse of Agony"
      },
      {
        "id": "drain_life",
        "name": "Drain Life"
      },
      {
        "id": "fear",
        "name": "Fear"
      },
      {
        "id": "searing_pain",
        "name": "Searing Pain"
      },
      {
        "id": "shadowburn",
        "name": "Shadowburn"
      },
      {
        "id": "summon_succubus",
        "name": "Summon Succubus"
      },
      {
        "id": "summon_felhunter",
        "name": "Summon Felhunter"
      },
      {
        "id": "summon_felguard",
        "name": "Summon Felguard"
      },
      {
        "id": "summon_infernal",
        "name": "Summon Infernal"
      },
      {
        "id": "summon_doomguard",
        "name": "Summon Doomguard"
      },
      {
        "id": "rain_of_fire",
        "name": "Rain of Fire"
      }
    ],
    "model": "player_warlock",
    "tint": "#8d5fd3",
    "still": "/guide-stills/player_warlock__8d5fd3.webp"
  },
  {
    "id": "druid",
    "color": "#ff7d0a",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "id": "balance",
        "name": "Balance",
        "role": "dps",
        "signature": "starfire"
      },
      {
        "id": "feral",
        "name": "Feral",
        "role": "tank",
        "signature": "bear_form"
      },
      {
        "id": "restoration",
        "name": "Restoration",
        "role": "healer",
        "signature": "regrowth"
      }
    ],
    "signatureAbilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      }
    ],
    "abilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      },
      {
        "id": "entangling_roots",
        "name": "Entangling Roots"
      },
      {
        "id": "bear_form",
        "name": "Bear Form"
      },
      {
        "id": "bear_charge",
        "name": "Bear Charge"
      },
      {
        "id": "maul",
        "name": "Maul"
      },
      {
        "id": "growl",
        "name": "Growl"
      },
      {
        "id": "demoralizing_roar",
        "name": "Demoralizing Roar"
      },
      {
        "id": "cat_form",
        "name": "Wolf Form"
      },
      {
        "id": "prowl",
        "name": "Prowl"
      },
      {
        "id": "rake",
        "name": "Rake"
      },
      {
        "id": "claw",
        "name": "Claw"
      },
      {
        "id": "regrowth",
        "name": "Regrowth"
      },
      {
        "id": "ferocious_bite",
        "name": "Ferocious Bite"
      },
      {
        "id": "barkskin",
        "name": "Barkskin"
      },
      {
        "id": "swipe",
        "name": "Swipe"
      },
      {
        "id": "starfire",
        "name": "Starfire"
      },
      {
        "id": "travel_form",
        "name": "Travel Form"
      },
      {
        "id": "enrage",
        "name": "Enrage"
      },
      {
        "id": "bash",
        "name": "Bash"
      },
      {
        "id": "faerie_fire",
        "name": "Faerie Fire"
      },
      {
        "id": "hibernate",
        "name": "Hibernate"
      },
      {
        "id": "dash",
        "name": "Dash"
      },
      {
        "id": "pounce",
        "name": "Pounce"
      },
      {
        "id": "insect_swarm",
        "name": "Insect Swarm"
      },
      {
        "id": "tigers_fury",
        "name": "Tiger's Fury"
      },
      {
        "id": "rip",
        "name": "Rip"
      },
      {
        "id": "hurricane",
        "name": "Hurricane"
      }
    ],
    "model": "player_druid",
    "still": "/guide-stills/player_druid.webp"
  }
];

export const GUIDE_ZONES: GuideZoneInfo[] = [
  {
    "id": "eastbrook_vale",
    "name": "Eastbrook Vale",
    "min": 1,
    "max": 7,
    "biome": "vale",
    "hub": "Eastbrook",
    "pois": [
      "Eastbrook",
      "Wolf Run",
      "Boar Meadow",
      "Mirror Lake",
      "Webwood",
      "Copper Dig",
      "Bandit Camp",
      "Fallen Chapel",
      "Reliquary Hill",
      "Brightwood Glade"
    ],
    "welcome": "Find Marshal Redbrook in town — he has work for you."
  },
  {
    "id": "mirefen_marsh",
    "name": "Mirefen Marsh",
    "min": 6,
    "max": 13,
    "biome": "marsh",
    "hub": "Fenbridge",
    "pois": [
      "Fenbridge",
      "Prowler Reeds",
      "Deepfen Shallows",
      "Widow Thicket",
      "Drowned Chapel",
      "Troll Mounds",
      "Gravecaller Encampment",
      "The Sunken Bastion"
    ],
    "welcome": "Report to Warden Fenwick at the Fenbridge gate."
  },
  {
    "id": "thornpeak_heights",
    "name": "Thornpeak Heights",
    "min": 13,
    "max": 20,
    "biome": "peaks",
    "hub": "Highwatch",
    "pois": [
      "Highwatch",
      "Stalker Ridge",
      "Deeprock Burrows",
      "Ogre Foothills",
      "Drogmar's War-Camp",
      "Stormcrag",
      "The Glimmermere",
      "Wyrmcult Tents",
      "Revenant Fields",
      "Gravewyrm Sanctum"
    ],
    "welcome": "Captain Thessaly holds the wall at Highwatch — barely."
  },
  {
    "id": "ossara_domain",
    "name": "Ossara Domain",
    "min": 20,
    "max": 28,
    "biome": "desert",
    "hub": "Qesh Aram",
    "pois": [
      "Qesh Aram",
      "The Caravan Road",
      "Prowler Dunes",
      "Glasswind Flats",
      "Sunken Aqueduct",
      "Tombs of the Nameless",
      "Mirage Oasis",
      "Duststorm Rise",
      "Judges' Terrace",
      "Bonewind Barrens"
    ],
    "welcome": "Judge Saphira keeps the caravan road open from Qesh Aram, barely."
  },
  {
    "id": "veth_confederation",
    "name": "Veth Confederation",
    "min": 27,
    "max": 34,
    "biome": "shadowwood",
    "hub": "Nighthollow",
    "pois": [
      "Nighthollow",
      "Duskmane Run",
      "Palewidow Hollows",
      "Blackwater Quays",
      "The Whisper Market",
      "The Blackmere",
      "Wispwood",
      "The Silent Court",
      "Frostpine Terraces",
      "The Last Lodge"
    ],
    "welcome": "Veth is not a nation, it is an agreement, and Nighthollow keeps its ledger."
  },
  {
    "id": "kael_empire",
    "name": "Kael Empire",
    "min": 33,
    "max": 40,
    "biome": "highlands",
    "hub": "Kaelspire",
    "pois": [
      "Kaelspire",
      "The Tithe Road",
      "The Imperial Granaries",
      "Wolfsward Pines",
      "The Tithe House",
      "Silverbrook Millpond",
      "Ironhold Mine",
      "The Broken Legion Camp",
      "Frosthelm Ascent"
    ],
    "welcome": "Marshal Corvin keeps the Tithe Road open from Kaelspire; the Empire expects it kept."
  },
  {
    "id": "grey_hollows",
    "name": "Grey Hollows",
    "min": 28,
    "max": 45,
    "biome": "highlands",
    "hub": "The Underway Rest",
    "pois": [
      "The Underway Rest",
      "The Old South Road",
      "Sunken Mouths",
      "The Gnaw Warrens",
      "Shale Gallery",
      "Smugglers Spoil"
    ],
    "welcome": "Half of the Grey Hollows is underfoot, and none of it is empty."
  },
  {
    "id": "thornfen_border",
    "name": "Thornfen Border",
    "min": 30,
    "max": 46,
    "biome": "shadowwood",
    "hub": "Wardens Palisade",
    "pois": [
      "Wardens Palisade",
      "Creeper Hollows",
      "The Moving Wood",
      "Troll Fen",
      "Briarheart Thicket"
    ],
    "welcome": "The wardens mark the trees every night; by morning the marks have moved."
  },
  {
    "id": "ironpass_crossing",
    "name": "Ironpass Crossing",
    "min": 30,
    "max": 50,
    "biome": "peaks",
    "hub": "The Tollhouse",
    "pois": [
      "The Tollhouse",
      "The Banner Road",
      "Raider Bluffs",
      "The Ogre Toll",
      "Cragfall Slopes",
      "Wyvern Eyries"
    ],
    "welcome": "Every banner on the pass claims the road; the Tollhouse just charges them all."
  },
  {
    "id": "emberveil_marshes",
    "name": "Emberveil Marshes",
    "min": 32,
    "max": 48,
    "biome": "marsh",
    "hub": "Lanternfen Stilts",
    "pois": [
      "Lanternfen Stilts",
      "Bloatwater Shallows",
      "The Steaming Pools",
      "Silkstrand Mire",
      "The Fogwall"
    ],
    "welcome": "The fog over Emberveil has never lifted; bring your own light."
  },
  {
    "id": "pale_crossing",
    "name": "Pale Crossing",
    "min": 34,
    "max": 50,
    "biome": "vale",
    "hub": "Bridgewatch",
    "pois": [
      "Bridgewatch",
      "The Kneeling Stones",
      "The Pale Bridge",
      "Drowned Banks",
      "Gullwatch Rise"
    ],
    "welcome": "Every faction claims it built the Pale Bridge; the bridge has never agreed."
  },
  {
    "id": "the_breach",
    "name": "The Breach",
    "min": 45,
    "max": 60,
    "biome": "scorched",
    "hub": "Last Bastion",
    "pois": [
      "Last Bastion",
      "The Sundered Field",
      "The Ember Scar",
      "The Ashen Saps",
      "The Broken Siege Line",
      "Wreck of the Third Offensive",
      "The Shattered Vanguard",
      "The First Crater",
      "The Molten Gate",
      "Khorvax's Redoubt"
    ],
    "welcome": "No banner holds The Breach. The truce ends at the Last Bastion palisade; beyond it there is only the war."
  },
  {
    "id": "ashveil_wastes",
    "name": "Ashveil Wastes",
    "min": 35,
    "max": 45,
    "biome": "scorched",
    "hub": "Cinderrest",
    "pois": [
      "Cinderrest",
      "The Charred Furrows",
      "Bonewhite Tor",
      "The Smolder Line",
      "Ashfall Reach"
    ],
    "welcome": "These fields fed half a kingdom once. One battle burned them for years; Cinderrest is what grew back."
  },
  {
    "id": "saltbone_flats",
    "name": "Saltbone Flats",
    "min": 36,
    "max": 48,
    "biome": "salt",
    "hub": "Brinehollow",
    "pois": [
      "Brinehollow",
      "The Glare Flats",
      "The Great Ribcage",
      "Bonepicker Trails",
      "The Sunken Vertebrae"
    ],
    "welcome": "A white glare, colossal bones, and no two stories about them that agree. Brinehollow trades with all of them."
  },
  {
    "id": "duskwall_ruins",
    "name": "Duskwall Ruins",
    "min": 35,
    "max": 50,
    "biome": "scorched",
    "hub": "the Exile Market",
    "pois": [
      "The Exile Market",
      "The Broken Gate",
      "The Old Boulevard",
      "The Collapsed Quarter",
      "Old Duskwall Sewers",
      "The King's Midden"
    ],
    "welcome": "Duskwall died in the war thirty years ago. Everything picking through it now claims to be a scavenger."
  },
  {
    "id": "cindral_ridge",
    "name": "Cindral Ridge",
    "min": 38,
    "max": 52,
    "biome": "scorched",
    "hub": "Forgefall Camp",
    "pois": [
      "Forgefall Camp",
      "The Slag Steps",
      "The Abandoned Diggings",
      "Magmavein Gulch",
      "The Smeltheart Vent"
    ],
    "welcome": "The ridge is full of forge-metal, and the dwarves of Forgefall Camp have spent decades failing to hold it."
  },
  {
    "id": "redspire_pass",
    "name": "Redspire Pass",
    "min": 40,
    "max": 55,
    "biome": "scorched",
    "hub": "the Last Waymeet",
    "pois": [
      "The Last Waymeet",
      "The Broken Teeth",
      "Deserter Hollows",
      "The Silent Muster",
      "The Rim of the World"
    ],
    "welcome": "Past the Last Waymeet there is only red rock, the old deserters, and the rim of the known world."
  }
];

export const GUIDE_DUNGEONS: GuideDungeon[] = [
  {
    "id": "hollow_crypt",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 7,
    "max": 10,
    "name": "The Hollow Crypt"
  },
  {
    "id": "sunken_bastion",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 12,
    "max": 13,
    "name": "The Sunken Bastion"
  },
  {
    "id": "drowned_temple",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 16,
    "max": 18,
    "name": "The Drowned Temple"
  },
  {
    "id": "gravewyrm_sanctum",
    "isRaid": false,
    "suggestedPlayers": 5,
    "min": 19,
    "max": 20,
    "name": "Gravewyrm Sanctum"
  },
  {
    "id": "raid",
    "isRaid": true,
    "suggestedPlayers": 10,
    "min": 20,
    "max": 20
  }
];

export const GUIDE_WARLOCK_PETS: GuideWarlockPet[] = [
  {
    "id": "imp",
    "name": "Imp",
    "model": "mob_demon",
    "tint": "#ff7a2a",
    "still": "/guide-stills/mob_demon__ff7a2a.webp"
  },
  {
    "id": "voidwalker",
    "name": "Voidwalker",
    "model": "mob_demon",
    "tint": "#3a3a6e",
    "still": "/guide-stills/mob_demon__3a3a6e.webp"
  },
  {
    "id": "succubus",
    "name": "Succubus",
    "model": "mob_demon",
    "tint": "#c6469b",
    "still": "/guide-stills/mob_demon__c6469b.webp"
  },
  {
    "id": "felhunter",
    "name": "Felhunter",
    "model": "mob_demonalt",
    "tint": "#4a7d4a",
    "still": "/guide-stills/mob_demonalt__4a7d4a.webp"
  },
  {
    "id": "felguard",
    "name": "Felguard",
    "model": "mob_demonalt",
    "tint": "#6e5a2a",
    "still": "/guide-stills/mob_demonalt__6e5a2a.webp"
  },
  {
    "id": "infernal",
    "name": "Infernal",
    "model": "mob_demonalt",
    "tint": "#d24a2a",
    "still": "/guide-stills/mob_demonalt__d24a2a.webp"
  },
  {
    "id": "doomguard",
    "name": "Doomguard",
    "model": "mob_demonalt",
    "tint": "#7a3a8e",
    "still": "/guide-stills/mob_demonalt__7a3a8e.webp"
  }
];

export const GUIDE_FAMILIES: GuideFamily[] = [
  {
    "family": "beast",
    "creatures": [
      {
        "name": "Forest Wolf",
        "min": 1,
        "max": 2,
        "rare": false,
        "templateId": "forest_wolf",
        "model": "mob_wolf",
        "tint": "#7f8c8d",
        "still": "/guide-stills/mob_wolf__7f8c8d.webp"
      },
      {
        "name": "Wild Boar",
        "min": 2,
        "max": 3,
        "rare": false,
        "templateId": "wild_boar",
        "model": "mob_boar",
        "tint": "#935116",
        "still": "/guide-stills/mob_boar__935116.webp"
      },
      {
        "name": "Old Greyjaw",
        "min": 4,
        "max": 4,
        "rare": true,
        "templateId": "old_greyjaw",
        "model": "mob_wolf",
        "tint": "#566061",
        "still": "/guide-stills/mob_wolf__566061.webp"
      },
      {
        "name": "Mire Prowler",
        "min": 7,
        "max": 8,
        "rare": false,
        "templateId": "mire_prowler",
        "model": "mob_wolf",
        "tint": "#4d5656",
        "still": "/guide-stills/mob_wolf__4d5656.webp"
      },
      {
        "name": "Bog Bloat",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "bog_bloat",
        "model": "mob_murloc",
        "tint": "#6b8e23",
        "still": "/guide-stills/mob_murloc__6b8e23.webp"
      },
      {
        "name": "Ridge Stalker",
        "min": 13,
        "max": 14,
        "rare": false,
        "templateId": "ridge_stalker",
        "model": "mob_wolf",
        "tint": "#8c8270",
        "still": "/guide-stills/mob_wolf__8c8270.webp"
      },
      {
        "name": "Dune Prowler",
        "min": 20,
        "max": 22,
        "rare": false,
        "templateId": "dune_prowler",
        "model": "mob_raptor",
        "tint": "#c9a86a",
        "still": "/guide-stills/mob_raptor__c9a86a.webp"
      },
      {
        "name": "Mirage Stalker",
        "min": 23,
        "max": 25,
        "rare": false,
        "templateId": "mirage_stalker",
        "model": "mob_raptor",
        "tint": "#d8c9a3",
        "still": "/guide-stills/mob_raptor__d8c9a3.webp"
      },
      {
        "name": "Bonewind Ravager",
        "min": 26,
        "max": 28,
        "rare": false,
        "templateId": "bonewind_ravager",
        "model": "mob_bull",
        "tint": "#b99a66",
        "still": "/guide-stills/mob_bull__b99a66.webp"
      },
      {
        "name": "Duskmane Stalker",
        "min": 27,
        "max": 29,
        "rare": false,
        "templateId": "duskmane_stalker",
        "model": "mob_wolf",
        "tint": "#4a4a5e",
        "still": "/guide-stills/mob_wolf__4a4a5e.webp"
      },
      {
        "name": "Hollow Lurker",
        "min": 28,
        "max": 31,
        "rare": false,
        "templateId": "hollow_lurker",
        "model": "mob_wolf",
        "tint": "#4a4a58",
        "still": "/guide-stills/mob_wolf__4a4a58.webp"
      },
      {
        "name": "Rimeclaw Prowler",
        "min": 32,
        "max": 34,
        "rare": false,
        "templateId": "rimeclaw_prowler",
        "model": "mob_wolf",
        "tint": "#b9c8d2",
        "still": "/guide-stills/mob_wolf__b9c8d2.webp"
      },
      {
        "name": "Thorn-Warped Stag",
        "min": 33,
        "max": 36,
        "rare": false,
        "templateId": "thornwarped_stag",
        "model": "mob_stag",
        "tint": "#7a5f43",
        "still": "/guide-stills/mob_stag__7a5f43.webp"
      },
      {
        "name": "Wolfsward Packwolf",
        "min": 33,
        "max": 35,
        "rare": false,
        "templateId": "wolfsward_packwolf",
        "model": "mob_wolf",
        "tint": "#9aa3ad",
        "still": "/guide-stills/mob_wolf__9aa3ad.webp"
      },
      {
        "name": "Reagent-Fat Leech",
        "min": 35,
        "max": 38,
        "rare": false,
        "templateId": "emberveil_leech",
        "model": "mob_ooze",
        "tint": "#6a4b52",
        "still": "/guide-stills/mob_ooze__6a4b52.webp"
      },
      {
        "name": "Cinder Hound",
        "min": 36,
        "max": 38,
        "rare": false,
        "templateId": "cinder_hound",
        "model": "mob_wolf",
        "tint": "#8a4a2e",
        "still": "/guide-stills/mob_wolf__8a4a2e.webp"
      },
      {
        "name": "Frosthelm Icehowler",
        "min": 37,
        "max": 39,
        "rare": false,
        "templateId": "frosthelm_icehowler",
        "model": "mob_wolf",
        "tint": "#d7e4ec",
        "still": "/guide-stills/mob_wolf__d7e4ec.webp"
      },
      {
        "name": "Frosthelm Wendigo",
        "min": 38,
        "max": 40,
        "rare": false,
        "templateId": "frosthelm_wendigo",
        "model": "mob_yeti",
        "tint": "#cfe0e8",
        "still": "/guide-stills/mob_yeti__cfe0e8.webp"
      },
      {
        "name": "Warped Warhound",
        "min": 45,
        "max": 47,
        "rare": false,
        "templateId": "warped_warhound",
        "model": "mob_wolf",
        "tint": "#6e5a4a",
        "still": "/guide-stills/mob_wolf__6e5a4a.webp"
      },
      {
        "name": "Gutter Hound",
        "min": 46,
        "max": 49,
        "rare": false,
        "templateId": "gutter_hound",
        "model": "mob_wolf",
        "tint": "#6e5b43",
        "still": "/guide-stills/mob_wolf__6e5b43.webp"
      },
      {
        "name": "Spire Stalker",
        "min": 47,
        "max": 51,
        "rare": false,
        "templateId": "spire_stalker",
        "model": "mob_raptor",
        "tint": "#7d4f3a",
        "still": "/guide-stills/mob_raptor__7d4f3a.webp"
      }
    ]
  },
  {
    "family": "spider",
    "creatures": [
      {
        "name": "Webwood Lurker",
        "min": 2,
        "max": 4,
        "rare": false,
        "templateId": "webwood_spider",
        "model": "mob_spider",
        "tint": "#4a235a",
        "still": "/guide-stills/mob_spider__4a235a.webp"
      },
      {
        "name": "Mirefen Widow",
        "min": 8,
        "max": 10,
        "rare": false,
        "templateId": "mire_widow",
        "model": "mob_spider",
        "tint": "#283747",
        "still": "/guide-stills/mob_spider__283747.webp"
      },
      {
        "name": "Glasswind Scorpion",
        "min": 21,
        "max": 23,
        "rare": false,
        "templateId": "glasswind_scorpion",
        "model": "mob_crab",
        "tint": "#d9c48b",
        "still": "/guide-stills/mob_crab__d9c48b.webp"
      },
      {
        "name": "Palewidow Weaver",
        "min": 27,
        "max": 29,
        "rare": false,
        "templateId": "palewidow_weaver",
        "model": "mob_spider",
        "tint": "#d8d4e0",
        "still": "/guide-stills/mob_spider__d8d4e0.webp"
      },
      {
        "name": "Thornfen Creeper",
        "min": 30,
        "max": 33,
        "rare": false,
        "templateId": "thornfen_creeper",
        "model": "mob_spider",
        "tint": "#3f5a3a",
        "still": "/guide-stills/mob_spider__3f5a3a.webp"
      },
      {
        "name": "Brine Scuttler",
        "min": 38,
        "max": 41,
        "rare": false,
        "templateId": "brine_scuttler",
        "model": "mob_crab",
        "tint": "#bfd8d8",
        "still": "/guide-stills/mob_crab__bfd8d8.webp"
      },
      {
        "name": "Mire Strider",
        "min": 39,
        "max": 43,
        "rare": false,
        "templateId": "mire_strider",
        "model": "mob_crab",
        "tint": "#556655",
        "still": "/guide-stills/mob_crab__556655.webp"
      },
      {
        "name": "Sewer Broodspider",
        "min": 43,
        "max": 46,
        "rare": false,
        "templateId": "sewer_broodspider",
        "model": "mob_spider",
        "tint": "#4a5a3d",
        "still": "/guide-stills/mob_spider__4a5a3d.webp"
      }
    ]
  },
  {
    "family": "murloc",
    "creatures": [
      {
        "name": "Mudfin Skulker",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "mudfin_murloc",
        "model": "mob_murloc",
        "tint": "#52be80",
        "still": "/guide-stills/mob_murloc__52be80.webp"
      },
      {
        "name": "Deepfen Snapper",
        "min": 8,
        "max": 9,
        "rare": false,
        "templateId": "deepfen_murloc",
        "model": "mob_murloc",
        "tint": "#45b39d",
        "still": "/guide-stills/mob_murloc__45b39d.webp"
      },
      {
        "name": "Glimmermere Wader",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "glimmermere_wader",
        "model": "mob_murloc",
        "tint": "#8fb6c4",
        "still": "/guide-stills/mob_murloc__8fb6c4.webp"
      },
      {
        "name": "Blackriver Skulker",
        "min": 28,
        "max": 30,
        "rare": false,
        "templateId": "blackriver_skulker",
        "model": "mob_murloc",
        "tint": "#3d5a66",
        "still": "/guide-stills/mob_murloc__3d5a66.webp"
      },
      {
        "name": "Emberveil Bloat",
        "min": 32,
        "max": 35,
        "rare": false,
        "templateId": "emberveil_bloat",
        "model": "mob_ooze",
        "tint": "#86a05a",
        "still": "/guide-stills/mob_ooze__86a05a.webp"
      }
    ]
  },
  {
    "family": "kobold",
    "creatures": [
      {
        "name": "Tunnel Rat Digger",
        "min": 4,
        "max": 6,
        "rare": false,
        "templateId": "tunnel_rat",
        "model": "mob_kobold",
        "tint": "#9c640c",
        "still": "/guide-stills/mob_kobold__9c640c.webp"
      },
      {
        "name": "Deeprock Tunneler",
        "min": 14,
        "max": 15,
        "rare": false,
        "templateId": "deeprock_kobold",
        "model": "mob_kobold",
        "tint": "#9c7a3c",
        "still": "/guide-stills/mob_kobold__9c7a3c.webp"
      },
      {
        "name": "Ironhold Digger",
        "min": 34,
        "max": 36,
        "rare": false,
        "templateId": "ironhold_digger",
        "model": "mob_kobold",
        "tint": "#8a6b4a",
        "still": "/guide-stills/mob_kobold__8a6b4a.webp"
      },
      {
        "name": "Ironhold Geomancer",
        "min": 35,
        "max": 37,
        "rare": false,
        "templateId": "ironhold_geomancer",
        "model": "mob_kobold",
        "tint": "#9a7d52",
        "still": "/guide-stills/mob_kobold__9a7d52.webp"
      },
      {
        "name": "Pale Gnawer",
        "min": 35,
        "max": 39,
        "rare": false,
        "templateId": "pale_gnawer",
        "model": "mob_gnawer",
        "tint": "#cabfa8",
        "still": "/guide-stills/mob_gnawer__cabfa8.webp"
      },
      {
        "name": "Claim-Jumper Sapper",
        "min": 45,
        "max": 48,
        "rare": false,
        "templateId": "claimjumper_sapper",
        "model": "mob_kobold",
        "tint": "#8a6a3a",
        "still": "/guide-stills/mob_kobold__8a6a3a.webp"
      }
    ]
  },
  {
    "family": "humanoid",
    "creatures": [
      {
        "name": "Vale Bandit",
        "min": 3,
        "max": 5,
        "rare": false,
        "templateId": "vale_bandit",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Gravecaller Cultist",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_cultist",
        "model": "mob_dark_caster",
        "tint": "#6c3483",
        "still": "/guide-stills/mob_dark_caster__6c3483.webp"
      },
      {
        "name": "Gravecaller Mender",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_mender",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Gravecaller Summoner",
        "min": 11,
        "max": 12,
        "rare": false,
        "templateId": "gravecaller_summoner",
        "model": "mob_dark_caster",
        "tint": "#884ea0",
        "still": "/guide-stills/mob_dark_caster__884ea0.webp"
      },
      {
        "name": "Wyrmcult Zealot",
        "min": 17,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_zealot",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Wyrmcult Necromancer",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "wyrmcult_necromancer",
        "model": "mob_dark_caster",
        "tint": "#533566",
        "still": "/guide-stills/mob_dark_caster__533566.webp"
      },
      {
        "name": "Tombrobber Scavenger",
        "min": 22,
        "max": 24,
        "rare": false,
        "templateId": "tombrobber_scavenger",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Guildless Cutthroat",
        "min": 30,
        "max": 32,
        "rare": false,
        "templateId": "guildless_cutthroat",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Pass Raider",
        "min": 30,
        "max": 34,
        "rare": false,
        "templateId": "pass_raider",
        "model": "mob_bruiser",
        "tint": "#7d5b48",
        "still": "/guide-stills/mob_bruiser__7d5b48.webp"
      },
      {
        "name": "Underway Renegade",
        "min": 30,
        "max": 34,
        "rare": false,
        "templateId": "underway_renegade",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Bridge Cultist",
        "min": 34,
        "max": 37,
        "rare": false,
        "templateId": "bridge_cultist",
        "model": "mob_dark_caster",
        "tint": "#776688",
        "still": "/guide-stills/mob_dark_caster__776688.webp"
      },
      {
        "name": "Broken Legion Deserter",
        "min": 35,
        "max": 37,
        "rare": false,
        "templateId": "broken_legion_deserter",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Duskwall Scavenger",
        "min": 35,
        "max": 38,
        "rare": false,
        "templateId": "duskwall_scavenger",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Broken Legion Arbalist",
        "min": 36,
        "max": 38,
        "rare": false,
        "templateId": "broken_legion_arbalist",
        "model": "mob_arbalist",
        "tint": "#5c6470",
        "still": "/guide-stills/mob_arbalist__5c6470.webp"
      },
      {
        "name": "Veilstalker",
        "min": 38,
        "max": 40,
        "rare": false,
        "templateId": "veilstalker",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Bonepicker Renegade",
        "min": 41,
        "max": 44,
        "rare": false,
        "templateId": "bonepicker_renegade",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      },
      {
        "name": "Not-Quite-Man",
        "min": 51,
        "max": 54,
        "rare": false,
        "templateId": "not_quite_man",
        "model": "mob_tribal",
        "tint": "#9c8f7d",
        "still": "/guide-stills/mob_tribal__9c8f7d.webp"
      },
      {
        "name": "Breachsworn Deserter",
        "min": 54,
        "max": 56,
        "rare": false,
        "templateId": "breachsworn_deserter",
        "model": "mob_bandit",
        "tint": "#6b3a32",
        "still": "/guide-stills/mob_bandit__6b3a32.webp"
      }
    ]
  },
  {
    "family": "troll",
    "creatures": [
      {
        "name": "Mirefen Troll",
        "min": 10,
        "max": 12,
        "rare": false,
        "templateId": "fen_troll",
        "model": "mob_troll",
        "tint": "#229954",
        "still": "/guide-stills/mob_troll__229954.webp"
      },
      {
        "name": "Grubjaw the Glutton",
        "min": 12,
        "max": 12,
        "rare": true,
        "templateId": "grubjaw",
        "model": "mob_troll",
        "tint": "#145a32",
        "still": "/guide-stills/mob_troll__145a32.webp"
      },
      {
        "name": "Frostpine Headhunter",
        "min": 32,
        "max": 34,
        "rare": false,
        "templateId": "frostpine_headhunter",
        "model": "mob_troll",
        "tint": "#6e8a94",
        "still": "/guide-stills/mob_troll__6e8a94.webp"
      },
      {
        "name": "Thornfen Troll",
        "min": 37,
        "max": 41,
        "rare": false,
        "templateId": "thornfen_troll",
        "model": "mob_troll",
        "tint": "#5d7a4e",
        "still": "/guide-stills/mob_troll__5d7a4e.webp"
      }
    ]
  },
  {
    "family": "ogre",
    "creatures": [
      {
        "name": "Thornpeak Ogre",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "thornpeak_ogre",
        "model": "mob_ogre",
        "tint": "#9e7b53",
        "still": "/guide-stills/mob_ogre__9e7b53.webp"
      },
      {
        "name": "Crag Ogre Toller",
        "min": 36,
        "max": 40,
        "rare": false,
        "templateId": "crag_toller",
        "model": "mob_ogre",
        "tint": "#9c8b70",
        "still": "/guide-stills/mob_ogre__9c8b70.webp"
      },
      {
        "name": "Sellsword Ogre",
        "min": 37,
        "max": 39,
        "rare": false,
        "templateId": "sellsword_ogre",
        "model": "mob_ogre",
        "tint": "#b9975b",
        "still": "/guide-stills/mob_ogre__b9975b.webp"
      },
      {
        "name": "Slag Ogre",
        "min": 48,
        "max": 51,
        "rare": false,
        "templateId": "slag_ogre",
        "model": "mob_ogre",
        "tint": "#5f5a52",
        "still": "/guide-stills/mob_ogre__5f5a52.webp"
      },
      {
        "name": "Breach Scavenger Ogre",
        "min": 55,
        "max": 57,
        "rare": false,
        "templateId": "breach_scavenger_ogre",
        "model": "mob_ogre",
        "tint": "#8a7a5c",
        "still": "/guide-stills/mob_ogre__8a7a5c.webp"
      }
    ]
  },
  {
    "family": "undead",
    "creatures": [
      {
        "name": "Restless Bones",
        "min": 5,
        "max": 7,
        "rare": false,
        "templateId": "restless_bones",
        "model": "skel_minion",
        "tint": "#d5dbdb",
        "still": "/guide-stills/skel_minion__d5dbdb.webp"
      },
      {
        "name": "Drowned Dead",
        "min": 9,
        "max": 11,
        "rare": false,
        "templateId": "drowned_dead",
        "model": "skel_minion",
        "tint": "#7fb3d5",
        "still": "/guide-stills/skel_minion__7fb3d5.webp"
      },
      {
        "name": "Drowned Votary",
        "min": 15,
        "max": 16,
        "rare": false,
        "templateId": "drowned_votary",
        "model": "skel_minion",
        "tint": "#6c8f8a",
        "still": "/guide-stills/skel_minion__6c8f8a.webp"
      },
      {
        "name": "Boneclad Revenant",
        "min": 18,
        "max": 19,
        "rare": false,
        "templateId": "boneclad_revenant",
        "model": "skel_warrior",
        "tint": "#cacfd2",
        "still": "/guide-stills/skel_warrior__cacfd2.webp"
      },
      {
        "name": "Sandbound Shade",
        "min": 23,
        "max": 25,
        "rare": false,
        "templateId": "sandbound_shade",
        "model": "mob_ghost",
        "tint": "#d8cdb0",
        "still": "/guide-stills/mob_ghost__d8cdb0.webp"
      },
      {
        "name": "Forsaken Judge",
        "min": 26,
        "max": 28,
        "rare": false,
        "templateId": "forsaken_judge",
        "model": "skel_minion",
        "tint": "#bfae8e",
        "still": "/guide-stills/skel_minion__bfae8e.webp"
      },
      {
        "name": "Blackmere Drowned",
        "min": 29,
        "max": 31,
        "rare": false,
        "templateId": "blackmere_drowned",
        "model": "skel_minion",
        "tint": "#46605a",
        "still": "/guide-stills/skel_minion__46605a.webp"
      },
      {
        "name": "Hollow Revenant",
        "min": 31,
        "max": 33,
        "rare": false,
        "templateId": "hollow_revenant",
        "model": "mob_ghost",
        "tint": "#b8c4d0",
        "still": "/guide-stills/mob_ghost__b8c4d0.webp"
      },
      {
        "name": "Ash Ghoul",
        "min": 35,
        "max": 37,
        "rare": false,
        "templateId": "ash_ghoul",
        "model": "skel_rogue",
        "tint": "#9a9187",
        "still": "/guide-stills/skel_rogue__9a9187.webp"
      },
      {
        "name": "Gull-Picked Skeleton",
        "min": 38,
        "max": 41,
        "rare": false,
        "templateId": "gullpicked_skeleton",
        "model": "skel_minion",
        "tint": "#d6d0bd",
        "still": "/guide-stills/skel_minion__d6d0bd.webp"
      },
      {
        "name": "Rubble Haunt",
        "min": 39,
        "max": 42,
        "rare": false,
        "templateId": "rubble_haunt",
        "model": "skel_mage",
        "tint": "#8d8a93",
        "still": "/guide-stills/skel_mage__8d8a93.webp"
      },
      {
        "name": "Deserter Wraith",
        "min": 40,
        "max": 44,
        "rare": false,
        "templateId": "deserter_wraith",
        "model": "mob_ghost",
        "tint": "#8f9bb0",
        "still": "/guide-stills/mob_ghost__8f9bb0.webp"
      },
      {
        "name": "Riverbank Revenant",
        "min": 42,
        "max": 46,
        "rare": false,
        "templateId": "riverbank_revenant",
        "model": "skel_warrior",
        "tint": "#7c95a0",
        "still": "/guide-stills/skel_warrior__7c95a0.webp"
      },
      {
        "name": "Fog Wraith",
        "min": 44,
        "max": 48,
        "rare": false,
        "templateId": "fog_wraith",
        "model": "mob_ghost",
        "tint": "#b8c4c8",
        "still": "/guide-stills/mob_ghost__b8c4c8.webp"
      },
      {
        "name": "Salt Wraith",
        "min": 44,
        "max": 47,
        "rare": false,
        "templateId": "salt_wraith",
        "model": "mob_ghost",
        "tint": "#dfe8e6",
        "still": "/guide-stills/mob_ghost__dfe8e6.webp"
      },
      {
        "name": "Ember Revenant",
        "min": 48,
        "max": 50,
        "rare": false,
        "templateId": "ember_revenant",
        "model": "skel_warrior",
        "tint": "#d06a3c",
        "still": "/guide-stills/skel_warrior__d06a3c.webp"
      },
      {
        "name": "Ash Wraith",
        "min": 52,
        "max": 54,
        "rare": false,
        "templateId": "ash_wraith",
        "model": "mob_ghost",
        "tint": "#9a9aa8",
        "still": "/guide-stills/mob_ghost__9a9aa8.webp"
      }
    ]
  },
  {
    "family": "elemental",
    "creatures": [
      {
        "name": "Stormcrag Elemental",
        "min": 17,
        "max": 18,
        "rare": false,
        "templateId": "stormcrag_elemental",
        "model": "mob_elemental",
        "tint": "#5dade2",
        "still": "/guide-stills/mob_elemental__5dade2.webp"
      },
      {
        "name": "Shardlord Kazzix",
        "min": 18,
        "max": 18,
        "rare": true,
        "templateId": "shardlord_kazzix",
        "model": "mob_elemental",
        "tint": "#aed6f1",
        "still": "/guide-stills/mob_elemental__aed6f1.webp"
      },
      {
        "name": "Duststorm Elemental",
        "min": 24,
        "max": 26,
        "rare": false,
        "templateId": "duststorm_elemental",
        "model": "mob_elemental",
        "tint": "#cbb27a",
        "still": "/guide-stills/mob_elemental__cbb27a.webp"
      },
      {
        "name": "Feral Wisp",
        "min": 29,
        "max": 31,
        "rare": false,
        "templateId": "feral_wisp",
        "model": "mob_ghost",
        "tint": "#9fd4e8",
        "still": "/guide-stills/mob_ghost__9fd4e8.webp"
      },
      {
        "name": "Colossid Fragment",
        "min": 36,
        "max": 39,
        "rare": false,
        "templateId": "colossid_fragment",
        "model": "mob_elemental",
        "tint": "#e8e3d5",
        "still": "/guide-stills/mob_elemental__e8e3d5.webp"
      },
      {
        "name": "Granite Churn Elemental",
        "min": 36,
        "max": 38,
        "rare": false,
        "templateId": "granite_churn_elemental",
        "model": "mob_elemental",
        "tint": "#8d8d8d",
        "still": "/guide-stills/mob_elemental__8d8d8d.webp"
      },
      {
        "name": "Deep Shale Elemental",
        "min": 40,
        "max": 44,
        "rare": false,
        "templateId": "deep_shale_elemental",
        "model": "mob_elemental",
        "tint": "#5c6670",
        "still": "/guide-stills/mob_elemental__5c6670.webp"
      },
      {
        "name": "Ash Elemental",
        "min": 41,
        "max": 44,
        "rare": false,
        "templateId": "ash_elemental",
        "model": "mob_elemental",
        "tint": "#cf7a3a",
        "still": "/guide-stills/mob_elemental__cf7a3a.webp"
      },
      {
        "name": "Cragheart Elemental",
        "min": 41,
        "max": 45,
        "rare": false,
        "templateId": "ironpass_crag_elemental",
        "model": "mob_elemental",
        "tint": "#77706a",
        "still": "/guide-stills/mob_elemental__77706a.webp"
      },
      {
        "name": "Magma Serpent",
        "min": 41,
        "max": 45,
        "rare": false,
        "templateId": "magma_serpent",
        "model": "mob_dragonkin",
        "tint": "#d8542a",
        "still": "/guide-stills/mob_dragonkin__d8542a.webp"
      },
      {
        "name": "Briar Horror",
        "min": 42,
        "max": 46,
        "rare": false,
        "templateId": "briar_horror",
        "model": "mob_tribal",
        "tint": "#4c6b35",
        "still": "/guide-stills/mob_tribal__4c6b35.webp"
      },
      {
        "name": "Pale Watcher",
        "min": 46,
        "max": 50,
        "rare": false,
        "templateId": "pale_watcher",
        "model": "mob_ghost",
        "tint": "#dfe4e8",
        "still": "/guide-stills/mob_ghost__dfe4e8.webp"
      },
      {
        "name": "Magma Elemental",
        "min": 50,
        "max": 52,
        "rare": false,
        "templateId": "magma_elemental",
        "model": "mob_elemental",
        "tint": "#e0662e",
        "still": "/guide-stills/mob_elemental__e0662e.webp"
      }
    ]
  },
  {
    "family": "dragonkin",
    "creatures": [
      {
        "name": "Sethrael the Palecoil",
        "min": 16,
        "max": 16,
        "rare": true,
        "templateId": "sethrael_palecoil",
        "model": "mob_dragonkin",
        "tint": "#bcd2e6",
        "still": "/guide-stills/mob_dragonkin__bcd2e6.webp"
      },
      {
        "name": "Forgefall Salamander",
        "min": 38,
        "max": 41,
        "rare": false,
        "templateId": "forgefall_salamander",
        "model": "mob_dragonkin",
        "tint": "#c2622f",
        "still": "/guide-stills/mob_dragonkin__c2622f.webp"
      },
      {
        "name": "Ridge Shrieker",
        "min": 43,
        "max": 47,
        "rare": false,
        "templateId": "ridge_shrieker",
        "model": "mob_demon_flying",
        "tint": "#a5442f",
        "still": "/guide-stills/mob_demon_flying__a5442f.webp"
      },
      {
        "name": "Ridge Wyvern",
        "min": 46,
        "max": 50,
        "rare": false,
        "templateId": "ridge_wyvern",
        "model": "mob_dragonkin",
        "tint": "#8c4a3a",
        "still": "/guide-stills/mob_dragonkin__8c4a3a.webp"
      },
      {
        "name": "Ashwing Drake",
        "min": 58,
        "max": 60,
        "rare": false,
        "templateId": "ashwing_drake",
        "model": "mob_demon_flying",
        "tint": "#5c5250",
        "still": "/guide-stills/mob_demon_flying__5c5250.webp"
      }
    ]
  },
  {
    "family": "demon",
    "creatures": [
      {
        "name": "Breach Horror",
        "min": 46,
        "max": 48,
        "rare": false,
        "templateId": "breach_horror",
        "model": "mob_maw",
        "tint": "#8a3a3a",
        "still": "/guide-stills/mob_maw__8a3a3a.webp"
      }
    ]
  }
];

export const GUIDE_DELVES: GuideDelve[] = [
  {
    "id": "collapsed_reliquary",
    "name": "The Collapsed Reliquary",
    "theme": "crypt",
    "minLevel": 7,
    "suggestedPlayers": 2,
    "keeper": {
      "name": "Brother Halven",
      "title": "Reliquary Keeper"
    },
    "companion": {
      "name": "Acolyte Tessa",
      "role": "healer"
    },
    "tiers": [
      "Normal",
      "Heroic"
    ],
    "affixes": [
      "Restless Graves",
      "Bad Air",
      "Candleblind",
      "Grave Tax",
      "Unstable Roof",
      "Cult Remnants"
    ]
  }
];

export const GUIDE_MODELS: Record<string, GuideModelSpec> = {
  "player_warrior": {
    "url": "models/chars/players/knight.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Knight_Helmet",
      "Knight_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/sword_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_paladin": {
    "url": "models/chars/players/paladin.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_hunter": {
    "url": "models/chars/players/ranger.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/crossbow_1handed.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_rogue": {
    "url": "models/chars/players/rogue.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Rogue_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ]
  },
  "player_priest": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "player_shaman": {
    "url": "models/chars/players/barbarian.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Barbarian_BearHat"
    ],
    "attach": [
      {
        "url": "models/weapons/axe_1handed.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.4
  },
  "player_mage": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Cape"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "player_warlock": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [],
    "attach": [
      {
        "url": "models/weapons/wand.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/spellbook_open.glb",
        "bone": "handslot.l",
        "gripRef": "Spellbook_open"
      }
    ],
    "tintStrength": 0.45
  },
  "player_druid": {
    "url": "models/chars/players/druid.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ]
  },
  "mob_demon": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 1.8,
    "tintStrength": 0.5
  },
  "mob_demonalt": {
    "url": "models/creatures/demonalt.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.35
  },
  "mob_wolf": {
    "url": "models/creatures/wolf.glb",
    "idle": "Idle",
    "height": 1.6,
    "tintStrength": 0.35
  },
  "mob_boar": {
    "url": "models/creatures/wild_boar.glb",
    "idle": "Idle1",
    "height": 1.45,
    "tintStrength": 0.4
  },
  "mob_spider": {
    "url": "models/creatures/spider.glb",
    "idle": "Spider_Idle",
    "height": 1.4,
    "tintStrength": 0.35
  },
  "mob_murloc": {
    "url": "models/creatures/frog.glb",
    "idle": "Idle",
    "height": 1.7,
    "tintStrength": 0.45
  },
  "mob_kobold": {
    "url": "models/creatures/goblin.glb",
    "idle": "Idle",
    "height": 2.1,
    "tintStrength": 0.2
  },
  "mob_bandit": {
    "url": "models/chars/players/rogue_hooded.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.r"
      },
      {
        "url": "models/weapons/dagger.glb",
        "bone": "handslot.l"
      }
    ],
    "tintStrength": 0.3
  },
  "skel_minion": {
    "url": "models/chars/enemies/skeleton_minion.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_troll": {
    "url": "models/creatures/orc.glb",
    "idle": "Idle",
    "height": 2.4,
    "tintStrength": 0.12
  },
  "mob_dark_caster": {
    "url": "models/chars/players/mage.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Mage_Hat"
    ],
    "attach": [
      {
        "url": "models/weapons/staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.5
  },
  "mob_ogre": {
    "url": "models/creatures/giant.glb",
    "idle": "Idle",
    "height": 2.8,
    "tintStrength": 0.2
  },
  "mob_elemental": {
    "url": "models/creatures/golelingevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.2,
    "hover": 0.3,
    "tintStrength": 0.4
  },
  "skel_warrior": {
    "url": "models/chars/enemies/skeleton_warrior.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "mob_dragonkin": {
    "url": "models/creatures/dragonevolved.glb",
    "idle": "Flying_Idle",
    "height": 2.4,
    "hover": 0.25,
    "tintStrength": 0.2
  },
  "mob_raptor": {
    "url": "models/creatures/velociraptor.glb",
    "idle": "Velociraptor_Idle",
    "height": 1.7,
    "tintStrength": 0.35
  },
  "mob_crab": {
    "url": "models/creatures/crabenemy.glb",
    "idle": "Idle",
    "height": 1.5,
    "tintStrength": 0.35
  },
  "mob_ghost": {
    "url": "models/creatures/ghost.glb",
    "idle": "Flying_Idle",
    "height": 1.9,
    "hover": 0.35,
    "tintStrength": 0.35
  },
  "mob_bull": {
    "url": "models/creatures/bull.glb",
    "idle": "Idle",
    "height": 1.9,
    "tintStrength": 0.35
  },
  "mob_arbalist": {
    "url": "models/chars/players/ranger.glb",
    "idle": "Idle",
    "height": 2.6,
    "attach": [
      {
        "url": "models/weapons/crossbow_1handed.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.3
  },
  "mob_yeti": {
    "url": "models/creatures/yetialt.glb",
    "idle": "Idle",
    "height": 2.3,
    "tintStrength": 0.35
  },
  "mob_gnawer": {
    "url": "models/creatures/yeti.glb",
    "idle": "Idle",
    "height": 1.5,
    "tintStrength": 0.35
  },
  "mob_stag": {
    "url": "models/creatures/stag.glb",
    "idle": "Idle",
    "height": 1.9,
    "tintStrength": 0.35
  },
  "mob_tribal": {
    "url": "models/creatures/tribal.glb",
    "idle": "Flying_Idle",
    "height": 2,
    "hover": 0.25,
    "tintStrength": 0.35
  },
  "mob_bruiser": {
    "url": "models/chars/players/barbarian.glb",
    "idle": "Idle",
    "height": 2.6,
    "show": [
      "Barbarian_BearHat"
    ],
    "attach": [
      {
        "url": "models/weapons/axe_2handed.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.3
  },
  "mob_ooze": {
    "url": "models/creatures/glubevolved.glb",
    "idle": "Flying_Idle",
    "height": 1.5,
    "hover": 0.2,
    "tintStrength": 0.45
  },
  "mob_maw": {
    "url": "models/creatures/orcenemy.glb",
    "idle": "Idle",
    "height": 1.6,
    "tintStrength": 0.3
  },
  "mob_demon_flying": {
    "url": "models/creatures/demon.glb",
    "idle": "Flying_Idle",
    "height": 1.7,
    "hover": 0.35,
    "tintStrength": 0.25
  },
  "skel_rogue": {
    "url": "models/chars/enemies/skeleton_rogue.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "tintStrength": 0.25
  },
  "skel_mage": {
    "url": "models/chars/enemies/skeleton_mage.glb",
    "idle": "Idle_Combat",
    "height": 2.5,
    "attach": [
      {
        "url": "models/weapons/skeleton_staff.glb",
        "bone": "handslot.r"
      }
    ],
    "tintStrength": 0.25
  }
};
